CREATE USER BDOPER_CASE2 IDENTIFIED BY VALUES '99965E116DD5AB62';


CREATE USER RPE_CASE IDENTIFIED BY VALUES '64A1FE70F228D080';


CREATE USER SIPAT_CASE IDENTIFIED BY VALUES '57EE51DE94D3F5D1';


CREATE USER SISLIC_CASE IDENTIFIED BY VALUES '27088897D65FB618';


CREATE USER SRH_WEB_CASE IDENTIFIED BY VALUES '1A23AF3B569A8AE4';


CREATE USER SISDAT_CASE IDENTIFIED BY VALUES '44D2EA1372879BD1';


CREATE USER SISEG_CASE IDENTIFIED BY VALUES 'CCD250212BF92655';


CREATE USER SISELO_CASE IDENTIFIED BY VALUES 'C543153AF1BE27E4';


CREATE USER SISRH_CASE IDENTIFIED BY VALUES 'D3553B810E7C5DAF';


CREATE USER BDOPER_CASE IDENTIFIED BY VALUES '733BEC0B361085EC';


CREATE USER SISMAT_CASE IDENTIFIED BY VALUES '502026AD03CF6A4A';


CREATE USER SICOF_CASE IDENTIFIED BY VALUES '56D49A2D29BC7A77';


CREATE USER SISCOB_CASE IDENTIFIED BY VALUES 'EF39E1FC2D3E1D6A';


CREATE USER SISCAI_CASE IDENTIFIED BY VALUES '975C4F2B449B1639';


CREATE USER IFRCASE6I IDENTIFIED BY VALUES '9CD8280BC03529F4';


CREATE USER SMART_CASE IDENTIFIED BY VALUES 'CF026AF12A3E35C2';


GRANT CREATE SESSION TO BDOPER_CASE2;


GRANT CREATE SESSION TO RPE_CASE;


GRANT CREATE SESSION TO SIPAT_CASE;


GRANT CREATE SESSION TO SISLIC_CASE;


GRANT CREATE SESSION TO SRH_WEB_CASE;


GRANT CREATE SESSION TO SISDAT_CASE;


GRANT CREATE SESSION TO SISEG_CASE;


GRANT CREATE SESSION TO SISELO_CASE;


GRANT CREATE SESSION TO SISRH_CASE;


GRANT CREATE SESSION TO BDOPER_CASE;


GRANT CREATE SESSION TO SISMAT_CASE;


GRANT CREATE SESSION TO SICOF_CASE;


GRANT CREATE SESSION TO SISCOB_CASE;


GRANT CREATE SESSION TO SISCAI_CASE;


GRANT CREATE SESSION TO IFRCASE6I;


GRANT CREATE SESSION TO SMART_CASE;


GRANT RESOURCE, CONNECT TO IFRCASE6I;


CREATE ROLE CKR_IFRCASE6I;


CREATE ROLE CK_ORACLE_REPOS_OWNER;


GRANT CKR_IFRCASE6I, CK_ORACLE_REPOS_OWNER TO IFRCASE6I;


CREATE USER IFRAD IDENTIFIED BY VALUES '36AB4AF4148CE71E';


GRANT DBA, CKR_IFRCASE6I TO IFRAD;

create view v_parameter as select * from v$parameter;

grant select on v_parameter to ifrcase6i;

create public synonym v_parameter for sys.v_parameter;


GRANT CREATE VIEW TO IFRCASE6I;
GRANT CREATE TABLE TO IFRCASE6I;
GRANT CREATE SYNONYM TO IFRCASE6I;
GRANT CREATE SEQUENCE TO IFRCASE6I;
GRANT CREATE PROCEDURE TO IFRCASE6I;
GRANT DROP ANY SYNONYM TO IFRCASE6I;
GRANT SELECT ANY TABLE TO IFRCASE6I;
GRANT CREATE ANY SYNONYM TO IFRCASE6I;
GRANT DROP PUBLIC SYNONYM TO IFRCASE6I;
GRANT CREATE PUBLIC SYNONYM TO IFRCASE6I;


GRANT SELECT ON V_$PARAMETER TO IFRCASE6I;
GRANT SELECT ON V_$NLS_PARAMETERS TO IFRCASE6I;
GRANT SELECT ON DBA_ROLLBACK_SEGS TO IFRCASE6I;
GRANT SELECT ON DBA_SEGMENTS TO IFRCASE6I;
GRANT EXECUTE ON DBMS_LOCK TO IFRCASE6I;
GRANT EXECUTE ON DBMS_PIPE TO IFRCASE6I;


grant dba to ifrcase6i;

--full reconcile

revoke dba from ifrcase6i, ifrad;