--SET FEED ON
col HOST_NAME format a30
select INSTANCE_NUMBER,INSTANCE_NAME,HOST_NAME,TO_CHAR(STARTUP_TIME,'DD/MM/YYYY HH24:MI:SS') AS STARTUP_TIME,STATUS,PARALLEL,THREAD#, ARCHIVER
from v$instance;
show user;

