/***************************************************************************************
--Passo 1:
         Criação do database link com o servidor de recife.
         Aqui foi necessário a criação do usuário "IFRTECA" em Recife e também a criação
         das 3 tabelas fato e do Snapshot log dentro do schema desse usuário. Mas isso 
         ficará sobre responsabilidade da equipe da interproject quando for criado o 
         ambiente das outras regionais.
***************************************************************************************/

CREATE DATABASE LINK PORTAL.WORLD CONNECT TO IFRPORTAL IDENTIFIED BY xxxx USING 'INET2';

/***************************************************************************************
--Passo 2:
         Criação do SnapShot com o site Recife para as 3 tabelas fato.
***************************************************************************************/

CREATE SNAPSHOT AEROPORTO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AEROPORTO@PORTAL.WORLD;

CREATE SNAPSHOT AERO_AGEN
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AERO_AGEN@PORTAL.WORLD;

CREATE SNAPSHOT ITEM_GERAL
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.ITEM_GERAL@PORTAL.WORLD;

CREATE SNAPSHOT LINKS
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.LINKS@PORTAL.WORLD;

CREATE SNAPSHOT LINKS_GERAIS
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.LINKS_GERAIS@PORTAL.WORLD;

CREATE SNAPSHOT "LOG"
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid
as SELECT * FROM IFRPORTAL.LOG@PORTAL.WORLD;

CREATE SNAPSHOT LOGINUSER
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid
as SELECT * FROM IFRPORTAL.LOGINUSER@PORTAL.WORLD;

CREATE SNAPSHOT MOVIMENTO_AERO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.MOVIMENTO_AERO@PORTAL.WORLD;

CREATE SNAPSHOT MOVOPERA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.MOVOPERA@PORTAL.WORLD;

CREATE SNAPSHOT MYCLOBTAB
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid
as SELECT * FROM IFRPORTAL.MYCLOBTAB@PORTAL.WORLD;

CREATE SNAPSHOT NOTICIA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.NOTICIA@PORTAL.WORLD;

CREATE SNAPSHOT NOTICIA_ON
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.NOTICIA_ON@PORTAL.WORLD;

CREATE SNAPSHOT OBRA_PROJETO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.OBRA_PROJETO@PORTAL.WORLD;

CREATE SNAPSHOT OBRA_TECNICA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.OBRA_TECNICA@PORTAL.WORLD;

CREATE SNAPSHOT PARAMETRO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.PARAMETRO@PORTAL.WORLD;

CREATE SNAPSHOT PERFIL
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid
as SELECT * FROM IFRPORTAL.PERFIL@PORTAL.WORLD;

CREATE SNAPSHOT PROJETO_SOCIAL
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.PROJETO_SOCIAL@PORTAL.WORLD;

CREATE SNAPSHOT QUEMSOMOS
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.QUEMSOMOS@PORTAL.WORLD;

CREATE SNAPSHOT TESTE
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.TESTE@PORTAL.WORLD;

CREATE SNAPSHOT USUARIO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete  with rowid
as SELECT * FROM IFRPORTAL.USUARIO@PORTAL.WORLD;

CREATE SNAPSHOT USUARIO_FUNCAO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.USUARIO_FUNCAO@PORTAL.WORLD;

CREATE SNAPSHOT USUARIO_PERFIL
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete  with rowid
as SELECT * FROM IFRPORTAL.USUARIO_PERFIL@PORTAL.WORLD;

CREATE SNAPSHOT AERO_COMP
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AERO_COMP@PORTAL.WORLD;

CREATE SNAPSHOT AERO_PSOC
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AERO_PSOC@PORTAL.WORLD;

CREATE SNAPSHOT AGENDA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AGENDA@PORTAL.WORLD;

CREATE SNAPSHOT AREA_NEGOCIO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.AREA_NEGOCIO@PORTAL.WORLD;

CREATE SNAPSHOT ARTIGO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.ARTIGO@PORTAL.WORLD;

CREATE SNAPSHOT AUDIENCIAS
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.AUDIENCIAS@PORTAL.WORLD;

CREATE SNAPSHOT BLA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.BLA@PORTAL.WORLD;

CREATE SNAPSHOT COMPANHIA
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.COMPANHIA@PORTAL.WORLD;

CREATE SNAPSHOT CONTENT_AREAS
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.CONTENT_AREAS@PORTAL.WORLD;

CREATE SNAPSHOT DIVULGACAO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.DIVULGACAO@PORTAL.WORLD;

CREATE SNAPSHOT EVENTO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.EVENTO@PORTAL.WORLD;

CREATE SNAPSHOT FUNCAO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.FUNCAO@PORTAL.WORLD;

CREATE SNAPSHOT FUNCAO_PERFIL
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete with rowid 
as SELECT * FROM IFRPORTAL.FUNCAO_PERFIL@PORTAL.WORLD;

CREATE SNAPSHOT IMAGEM
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.IMAGEM@PORTAL.WORLD;

CREATE SNAPSHOT INCENTIVO
PCTFREE 15 PCTUSED 80
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
USING INDEX 
TABLESPACE TSD_PORTAL_INFRAERO
STORAGE  ( INITIAL 1M
	 NEXT 1M
	 MINEXTENTS 1 
	 MAXEXTENTS 100 
	 PCTINCREASE 0 )
refresh complete 
as SELECT * FROM IFRPORTAL.INCENTIVO@PORTAL.WORLD;


/***************************************************************************************
--Passo 3:
         Criação do grupo de refresh. Em recife está programado para replicar as 20:00, 
         todos os dias.
***************************************************************************************/

BEGIN
   DBMS_REFRESH.MAKE (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => '', 
      next_date => SYSDATE, 
      interval => 'sysdate + 30/1440',
      implicit_destroy => FALSE, 
      rollback_seg => '',
      push_deferred_rpc => TRUE, 
      refresh_after_errors => FALSE);
END;
/

/***************************************************************************************
--Passo 4:
         Adição do grupo de snapshots ao grupo de refresh.
***************************************************************************************/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AEROPORTO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AERO_AGEN',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.ITEM_GERAL',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.LINKS',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.LINKS_GERAIS',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.LOG',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.LOGINUSER',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.MOVIMENTO_AERO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.MOVOPERA',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.MYCLOBTAB',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.NOTICIA',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.NOTICIA_ON',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.OBRA_PROJETO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.OBRA_TECNICA',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.PARAMETRO',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.PERFIL',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.PROJETO_SOCIAL',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.QUEMSOMOS',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.TESTE',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.USUARIO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.USUARIO_FUNCAO',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.USUARIO_PERFIL',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AERO_COMP',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AERO_PSOC',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AGENDA',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AREA_NEGOCIO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.ARTIGO',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.AUDIENCIAS',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.BLA',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.COMPANHIA',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.CONTENT_AREAS',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.DIVULGACAO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.EVENTO',
      lax => TRUE);
END;
/
BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.FUNCAO',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.FUNCAO_PERFIL',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.IMAGEM',
      lax => TRUE);
END;
/

BEGIN
   DBMS_REFRESH.ADD (
      name => 'IFRPORTAL.PORTAL_REFRESH',
      list => 'IFRPORTAL.INCENTIVO',
      lax => TRUE);
END;
/


/*************************************************************************
--Passo 5:
	 Os comando abaixo forçam uma replicacão;
*************************************************************************/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRPORTAL.NOTICIA', '?' );
end;
/


--coisa do suporte oracle
exec dbms_mview.refresh('IFRPORTAL.NOTICIA','f');
