--SEBU 04

ALTER ROLLBACK SEGMENT RBS1 OFFLINE;
ALTER ROLLBACK SEGMENT RBS2 OFFLINE;
ALTER ROLLBACK SEGMENT RBS3 OFFLINE;
ALTER ROLLBACK SEGMENT RBS4 OFFLINE;
ALTER ROLLBACK SEGMENT RBS5 OFFLINE;
ALTER ROLLBACK SEGMENT RBS6 OFFLINE;
ALTER ROLLBACK SEGMENT RBS7 OFFLINE;
ALTER ROLLBACK SEGMENT RBS8 OFFLINE;
ALTER ROLLBACK SEGMENT RBS9 OFFLINE;
ALTER ROLLBACK SEGMENT RBS10 OFFLINE;
ALTER ROLLBACK SEGMENT RBS11 OFFLINE;
ALTER ROLLBACK SEGMENT RBS12 OFFLINE;
ALTER ROLLBACK SEGMENT RBS13 OFFLINE;
ALTER ROLLBACK SEGMENT RBS14 OFFLINE;
ALTER ROLLBACK SEGMENT RB_GRANDE1 OFFLINE;
ALTER ROLLBACK SEGMENT RBS_PUB_01 OFFLINE;

--SEBU05
ALTER ROLLBACK SEGMENT RBS15 OFFLINE;
ALTER ROLLBACK SEGMENT RBS16 OFFLINE;
ALTER ROLLBACK SEGMENT RBS17 OFFLINE;
ALTER ROLLBACK SEGMENT RBS18 OFFLINE;
ALTER ROLLBACK SEGMENT RBS19 OFFLINE;
ALTER ROLLBACK SEGMENT RBS20 OFFLINE;
ALTER ROLLBACK SEGMENT RBS21 OFFLINE;
ALTER ROLLBACK SEGMENT RBS22 OFFLINE;
ALTER ROLLBACK SEGMENT RBS23 OFFLINE;
ALTER ROLLBACK SEGMENT RBS24 OFFLINE;
ALTER ROLLBACK SEGMENT RBS25 OFFLINE;
ALTER ROLLBACK SEGMENT RBS26 OFFLINE;
ALTER ROLLBACK SEGMENT RBS27 OFFLINE;
ALTER ROLLBACK SEGMENT RBS28 OFFLINE;
ALTER ROLLBACK SEGMENT RB_GRANDE2 OFFLINE;
ALTER ROLLBACK SEGMENT RBS_PUB_02 OFFLINE;