
SPO D:\SCRIPT_VIEW.SQL
@SOS_CRIA_TUDO_VIEW.SQL
SPO OFF

SPO D:\SCRIPT_FUNC.SQL
@SOS_CRIA_TUDO_FUNC.SQL
SPO OFF

SPO D:\SCRIPT_PKG.SQL
@SOS_CRIA_TUDO_PKG.SQL
SPO OFF

SPO D:\SCRIPT_PKGB.SQL
@SOS_CRIA_TUDO_PKGB.SQL
SPO OFF

SPO D:\SCRIPT_PROC.SQL
@SOS_CRIA_TUDO_PROC.SQL
SPO OFF

SPO D:\SCRIPT_TRIG.SQL
@SOS_CRIA_TUDO_TRIG.SQL
SPO OFF
