COL USERNAME FORMAT A20
COL OSUSER FORMAT A20
col Program format A20
SELECT s.SID, s.SERIAL#, s.USERNAME, s.OSUSER, s.STATUS, s.SERVER, s.Program --,s.TERMINAL
FROM v$session s
WHERE s.USERNAME NOT IN (' ')
ORDER BY
	s.SERVER
,	s.OSUSER
,	s.USERNAME
/
