--IFRDBA2
grant references on IFRDBA2.AGENCIAINF to IFRSRH2;
grant references on IFRDBA2.CENTRO_CUSTO to IFRSRH2;
grant references on IFRDBA2.CONTA_CONTABIL to IFRSRH2;
grant references on IFRDBA2.DEPENDENCIAS to IFRSRH2;
grant references on IFRDBA2.MUNICIPIOS to IFRSRH2;
grant references on IFRDBA2.PAISES to IFRSRH2;
grant references on IFRDBA2.UNIDADES_FEDERACAO to IFRSRH2;
grant references on IFRDBA2.UNIDADES_ORGANIZACIONAIS to IFRSRH2;
grant references on IFRDBA2.SEG_SISTEMA to IFRSRH2;
grant references on IFRDBA2.SEG_USUARIO to IFRSRH2;

--IFRSRH2
grant references on IFRSRH2.AREAS_ATUACAO_CARGO to IFRHUMANUS;
grant references on IFRSRH2.AREAS_DE_ATUACAO to IFRHUMANUS;
grant references on IFRSRH2.ATIVIDADES_CARGOS to IFRHUMANUS;
grant references on IFRSRH2.ATIVIDADES_FUNCOES to IFRHUMANUS;
grant references on IFRSRH2.CADASTROS to IFRDBA2;
grant references on IFRSRH2.CADASTROS to SST;
grant references on IFRSRH2.CARGOS to IFRAGENDA;
