COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_CODIGO IS 'Codigo da dependencias_licitacoes'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_DATA_CRIACAO IS 'Data em que foi criada a dependencia'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_DATA_EXTINCAO IS 'Data em que foi extinta a dependencia'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_NOME IS 'Nome da dependencia'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_SIGLA IS 'Sigla da dependencia'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_UF_ENDERECO IS 'UF da dependecia'
/
COMMENT ON COLUMN DEPENDENCIAS_LICITACOES.DEP_DEP_CODIGO IS 'Codigo da dependencia'
/
