COMMENT ON COLUMN HISTORICO_PARTICIPANTE.ID IS 'Identificacao do historico_participante'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.ID_PARTICIPANTE IS 'Identificacao do participante'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.DT_ALTERACAO IS 'Data de alteracao do historico participante'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.OPERACAO IS 'Historico de inclusao e exclusao de participantes (empresa) em um licitacao'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.ID_USUARIO IS 'Identificacao do usuario'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.NOME_USUARIO IS 'Nome do usuario'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.EMAIL_USUARIO IS 'Email do usuario'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.CONTATO IS 'Contato com a empresa'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.FAX IS 'Fax da empresa'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.TELEFONE IS 'Telefone da empresa'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.EMAIL IS 'Email da empresa'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.ID_LICITACAO IS 'Identificacao da licitacao'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.RAZAO_SOCIAL_FORNECEDOR IS 'Nome do fornecedor'
/
COMMENT ON COLUMN HISTORICO_PARTICIPANTE.CNPJ_FORNECEDOR IS 'CNPJ do fornecedor'
/
