COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.ID IS 'Identificacao do log_atualiza_funcionario'
/
COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.ID_FUNCIONARIO IS 'Identificacao do funcionario'
/
COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.NOME_FUNCIONARIO IS 'Nome do funcionario'
/
COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.DESCRICAO_ERRO IS 'Descricao do erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.DATA_ERRO IS 'Data do erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_FUNCIONARIO.ACAO IS 'Acao tomada'
/
