CREATE OR REPLACE TRIGGER TRG_AUD_LOG_OCO_EMP
BEFORE INSERT
ON OCORRENCIAS_EMPREGADOS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
  --
  :NEW.oem_cod_usuario  := USER;
  --
END; --TRG_AUD_LOG_OCO_EMP
/

