alter table DOCUMENTOS_COBRANCA
add DOC_INTERFACE_PS_MES      Number(2)
/

alter table DOCUMENTOS_COBRANCA
add DOC_INTERFACE_PS_ANO      Number(2)
/

alter table DOCUMENTOS_COBRANCA
add DOC_INTERFACE_PS_SEQ        Number(10)
/


COMMENT ON COLUMN DOCUMENTOS_COBRANCA.DOC_INTERFACE_PS_MES IS 'NÚMERO DO MÊS de processamento do DOCUMENTO'
/

COMMENT ON COLUMN DOCUMENTOS_COBRANCA.DOC_INTERFACE_PS_ANO IS 'NÚMERO DO ANO de processamento do DOCUMENTO'
/

COMMENT ON COLUMN DOCUMENTOS_COBRANCA.DOC_INTERFACE_PS_SEQ IS 'NÚMERO DO SEQUENCIAL DO DOCUMENTO'
/

update DOCUMENTOS_COBRANCA
set DOC_INTERFACE_PS_MES = Null
, DOC_INTERFACE_PS_ANO = Null
/

commit;


alter table DOCUMENTOS_COBRANCA
modify DOC_INTERFACE_PS_MES      Number(2) null
/

alter table DOCUMENTOS_COBRANCA
modify DOC_INTERFACE_PS_ANO      Number(4) null
/

alter table DOCUMENTOS_COBRANCA
modify DOC_INTERFACE_PS_SEQ        Number(10) null
/

