CREATE TABLE RSTE_TARIFAS_EMBARQUE(
	ANO_RSTE			number(4)	
,	NUM_RSTE			number(6) 	
,	DEP_CODIGO			number(4)	
,	SERIE_SELO			varchar2(2)	not null
,	NUM_INICIAL			number(7)	not null
,	NUM_FINAL 			number(7)	not null
,	DAT_ENTREGA_SELO		varchar2(15)	not null
,	CIA_CD_CIA_AEREA		varchar2(3)	not null)
/
ALTER TABLE RSTE_TARIFAS_EMBARQUE
ADD CONSTRAINT RSTE_TARIFAS_EMBARQUE_PK PRIMARY KEY(ANO_RSTE, NUM_RSTE, DEP_CODIGO)
/

CREATE PUBLIC SYNONYM RSTE_TARIFAS_EMBARQUE 
       FOR IFRSELO.RSTE_TARIFAS_EMBARQUE
/
INSERT INTO TABELAS VALUES  ('SISELO', 'RSTE_TARIFAS_EMBARQUE', 'IFRSELO', 'TABELA')
/ 