CREATE OR REPLACE FUNCTION FUN_BUSCA_CEDIDO(IMAT NUMBER, ICODIGO NUMBER, STIPO CHAR) RETURN VARCHAR2 IS
  SNOME CADASTROS.EMP_NOME_ABREVIADO%TYPE;
BEGIN
     IF STIPO = 'S' THEN --SUPERINTENDENCIA
        SELECT EMP_NOME_ABREVIADO
	INTO SNOME
	FROM EMPREGADOS_SUBORDINADOS S
	WHERE EXISTS
		(SELECT DISTINCT (E.EMP_NUMERO_MATRICULA)
		 FROM CADASTROS E, OCORRENCIAS_EMPREGADOS O
		 WHERE  E.EMP_STATUS <> 2 AND
	 	       O.OEM_OFU_CODIGO IN (135, 136, 203, 249, 250, 251, 253, 254) AND
		       O.OEM_EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
		       E.EMP_QFU_FUN_CODIGO IS NULL AND
		       ((E.EMP_UOR_CODIGO_LOTACAO = E.EMP_UOR_CODIGO_FISICO)AND
		         (E.EMP_DEP_CODIGO_LOTACAO = E.EMP_DEP_CODIGO_FISICO)) AND
		       S.EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
		       E.EMP_NUMERO_MATRICULA = IMAT AND
	               EXISTS 
			       (SELECT DEP_CODIGO
				FROM DEPENDENCIAS
				WHERE DEP_DATA_EXTINCAO IS NULL AND
				      E.EMP_DEP_CODIGO_LOTACAO = DEP_CODIGO
				CONNECT BY PRIOR DEP_CODIGO = DEP_DEP_CODIGO
				START WITH DEP_CODIGO = ICODIGO));				 

      ELSIF STIPO = 'D' THEN -- DEPENDENCIA
	  SELECT EMP_NOME_ABREVIADO
	  INTO SNOME
	  FROM EMPREGADOS_SUBORDINADOS S
	  WHERE EXISTS
			(SELECT DISTINCT (E.EMP_NUMERO_MATRICULA)
			FROM CADASTROS E, OCORRENCIAS_EMPREGADOS O
			WHERE  E.EMP_STATUS <> 2 AND
			       O.OEM_OFU_CODIGO IN (135, 136, 203, 249, 250, 251, 253, 254) AND
			       O.OEM_EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
			       E.EMP_QFU_FUN_CODIGO IS NULL AND
			       ((E.EMP_UOR_CODIGO_LOTACAO = E.EMP_UOR_CODIGO_FISICO)AND
		                (E.EMP_DEP_CODIGO_LOTACAO = E.EMP_DEP_CODIGO_FISICO)) AND
			       S.EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
			       E.EMP_NUMERO_MATRICULA = IMAT AND
			       E.EMP_DEP_CODIGO_LOTACAO = ICODIGO);					           
	 
       ELSIF STIPO = 'L' THEN	--LOTACAO
	  SELECT EMP_NOME_ABREVIADO
	  INTO SNOME
	  FROM EMPREGADOS_SUBORDINADOS S
	  WHERE EXISTS
			(SELECT DISTINCT (E.EMP_NUMERO_MATRICULA)
			FROM CADASTROS E, OCORRENCIAS_EMPREGADOS O
			WHERE  E.EMP_STATUS <> 2 AND
			       O.OEM_OFU_CODIGO IN (135, 136, 203, 249, 250, 251, 253, 254) AND
			       O.OEM_EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
			       E.EMP_QFU_FUN_CODIGO IS NULL AND
			       ((E.EMP_UOR_CODIGO_LOTACAO = E.EMP_UOR_CODIGO_FISICO)AND
		                (E.EMP_DEP_CODIGO_LOTACAO = E.EMP_DEP_CODIGO_FISICO)) AND
			       S.EMP_NUMERO_MATRICULA = E.EMP_NUMERO_MATRICULA AND
			       E.EMP_NUMERO_MATRICULA = IMAT AND
			       EXISTS 
				       (SELECT UOR_CODIGO
					FROM UNIDADES_ORGANIZACIONAIS
					WHERE UOR_DATA_EXTINCAO IS NULL AND
					      (UOR_CODIGO = ICODIGO OR UOR_UOR_CODIGO = ICODIGO) AND
					      E.EMP_UOR_CODIGO_LOTACAO = UOR_CODIGO
					/*CONNECT BY PRIOR UOR_CODIGO = UOR_UOR_CODIGO
					START WITH UOR_CODIGO = ICODIGO*/));			       
       END IF;
       RETURN SNOME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;     	
END;
/