CREATE OR REPLACE FUNCTION FUN_BUSCA_SEM_FUNCAO(IMAT NUMBER, ICODIGO NUMBER, STIPO CHAR) RETURN VARCHAR2 IS
  SNOME CADASTROS.EMP_NOME_ABREVIADO%TYPE;
BEGIN
     IF STIPO = 'S' THEN --SUPERINTENDENCIA
        SELECT EMP_NOME_ABREVIADO
        INTO SNOME
        FROM EMPREGADOS_SUBORDINADOS S
        WHERE S.EMP_STATUS <> 2 AND 
              S.EMP_QLP_CAR_CODIGO IS NOT NULL AND
	      S.EMP_NUMERO_MATRICULA = IMAT AND
	      ((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
	       (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO)) AND
              NOT EXISTS
	        (SELECT C.FUN_CODIGO FROM CARGOS_CONFIANCA C
	         WHERE C.FUN_POSICAO_TRABALHO = 0 AND
	               S.EMP_QFU_FUN_CODIGO = C.FUN_CODIGO) AND
		       EXISTS 
			   (SELECT DEP_CODIGO
			    FROM DEPENDENCIAS
			    WHERE DEP_DATA_EXTINCAO IS NULL AND
				  S.EMP_DEP_CODIGO_LOTACAO = DEP_CODIGO
			    CONNECT BY PRIOR DEP_CODIGO = DEP_DEP_CODIGO
			    START WITH DEP_CODIGO = ICODIGO);		

      ELSIF STIPO = 'D' THEN -- DEPENDENCIA
	  SELECT EMP_NOME_ABREVIADO
          INTO SNOME
          FROM EMPREGADOS_SUBORDINADOS S
          WHERE S.EMP_STATUS <> 2 AND 
                S.EMP_QLP_CAR_CODIGO IS NOT NULL AND
	        S.EMP_NUMERO_MATRICULA = IMAT AND
		S.EMP_DEP_CODIGO_LOTACAO = ICODIGO AND
                ((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
		 (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO)) AND
                NOT EXISTS
	          (SELECT C.FUN_CODIGO FROM CARGOS_CONFIANCA C
	           WHERE C.FUN_POSICAO_TRABALHO = 0 AND
	               S.EMP_QFU_FUN_CODIGO = C.FUN_CODIGO);					           	 
      
      ELSIF STIPO = 'L' THEN	--LOTACAO
	  SELECT EMP_NOME_ABREVIADO
          INTO SNOME
          FROM EMPREGADOS_SUBORDINADOS S
          WHERE S.EMP_STATUS <> 2 AND 
              S.EMP_QLP_CAR_CODIGO IS NOT NULL AND
	      S.EMP_NUMERO_MATRICULA = IMAT AND
              ((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
	       (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO)) AND
              NOT EXISTS
	        (SELECT C.FUN_CODIGO FROM CARGOS_CONFIANCA C
	         WHERE C.FUN_POSICAO_TRABALHO = 0 AND
	               S.EMP_QFU_FUN_CODIGO = C.FUN_CODIGO) AND
		       EXISTS 
			       (SELECT UOR_CODIGO
				FROM UNIDADES_ORGANIZACIONAIS
				WHERE UOR_DATA_EXTINCAO IS NULL AND
				      (UOR_CODIGO = ICODIGO OR UOR_UOR_CODIGO = ICODIGO) AND
				      S.EMP_UOR_CODIGO_LOTACAO = UOR_CODIGO
				/*CONNECT BY PRIOR UOR_CODIGO = UOR_UOR_CODIGO
				START WITH UOR_CODIGO = ICODIGO*/);			
       END IF;
       RETURN SNOME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;     	
END;
/