grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_01;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_02;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_03;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_04;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_06;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_11;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_17;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_18;
grant SELECT, UPDATE, DELETE, INSERT on APROVADOR_VIAGEM_TIPO to SRH_CAD_99;
grant SELECT on APROVADOR_VIAGEM_TIPO to SRH_CONSULTA;


grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_01;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_02;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_03;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_04;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_06;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_11;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_17;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_18;
grant SELECT, UPDATE, DELETE, INSERT on  APROVADOR_VIAGEM to SRH_CAD_99;
grant SELECT on  APROVADOR_VIAGEM to SRH_CONSULTA;

grant EXECUTE on PK_VIAGENS to SRH_CAD_01;
grant EXECUTE on PK_VIAGENS to SRH_CAD_02;
grant EXECUTE on PK_VIAGENS to SRH_CAD_03;
grant EXECUTE on PK_VIAGENS to SRH_CAD_04;
grant EXECUTE on PK_VIAGENS to SRH_CAD_06;
grant EXECUTE on PK_VIAGENS to SRH_CAD_11;
grant EXECUTE on PK_VIAGENS to SRH_CAD_17;
grant EXECUTE on PK_VIAGENS to SRH_CAD_18;
grant EXECUTE on PK_VIAGENS to SRH_CAD_99;
grant EXECUTE on PK_VIAGENS to SRH_CONSULTA;

--******************************************************************************************

grant SELECT,DELETE,INSERT, UPDATE on DEPENDENTES_USU_PLANO_SAUDE to SRH_BEN_13;

grant SELECT,DELETE,INSERT, UPDATE on USUARIOS_PLANOS_SAUDE to SRH_BEN_13;
