SET SCAN OFF
CREATE OR REPLACE PACKAGE FUNCOES_ABSENTEISMO AS  
  TYPE TCADORG is RECORD (
         CODIGO  NUMBER,
         TOTAL NUMBER);
  TYPE TDADOS IS REF CURSOR RETURN TCADORG;
  TYPE TDEMONSTRATIVO is RECORD (
         CODIGO  NUMBER,
         TOTAL NUMBER,
         MATRICULA NUMBER,
         LOTACAO NUMBER,
         NOME VARCHAR2(50));
  TYPE TDEMO IS REF CURSOR RETURN TDEMONSTRATIVO;
  TYPE TABSENTEISMO is RECORD (
   	MATRICULA NUMBER, 
  	NOME VARCHAR2(50),  
    	LOTACAO NUMBER,      
	CODIGO  NUMBER,
	DATA DATE);        
  TYPE TABS IS REF CURSOR RETURN TABSENTEISMO;
  TYPE TEMPREGADO is RECORD (      
	CODIGO  NUMBER,
	DATA DATE);
  TYPE TEMP IS REF CURSOR RETURN TEMPREGADO; 
  TYPE TOCORRENCIA is RECORD (      
	MATRICULA  NUMBER,
        NOME VARCHAR2(50),
        LOTACAO NUMBER,
	DATA DATE);
  TYPE TOCOR IS REF CURSOR RETURN TOCORRENCIA;
 
  	PROCEDURE ABSENTEISMO_CONSOLIDADO(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2,SANO IN VARCHAR2);

	PROCEDURE ABSENTEISMO_NOMINAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2);

        PROCEDURE ABSENTEISMO_EMP(TAB IN OUT TEMP, SMES IN VARCHAR2, SANO IN VARCHAR2, SMES1 IN VARCHAR2, SANO1 IN VARCHAR2, IMATRICULA IN NUMBER);

  	PROCEDURE FREQUENCIA_CONSOLIDADA(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2,SANO IN VARCHAR2);
       
        PROCEDURE FREQUENCIA_NOMINAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2);

        PROCEDURE FREQUENCIA_EMP(TAB IN OUT TEMP, SMES IN VARCHAR2, SMES1 IN VARCHAR2, SANO1 IN VARCHAR2, SANO IN VARCHAR2, IMATRICULA IN NUMBER);

        PROCEDURE DEMONSTRATIVO_FALTAS(TAB IN OUT TDEMO , IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2,SANO IN VARCHAR2, SMES1 IN VARCHAR2, SANO1 IN VARCHAR2);

	PROCEDURE DEMONSTRATIVO_FALTAS_EMP (TAB IN OUT TDADOS, SMES IN VARCHAR2, SMES1 IN VARCHAR2, SANO IN VARCHAR2, SANO1 IN VARCHAR2 ,SMATRICULA IN VARCHAR2);

	PROCEDURE OCORRENCIA_TOTAL(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2);

        PROCEDURE OCORRENCIA_ANUAL(TAB IN OUT TOCOR, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2,  IOCR_CODIGO IN NUMBER);

        PROCEDURE OCORRENCIA_MENSAL(TAB IN OUT TOCOR, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2,  IOCR_CODIGO IN NUMBER);

        PROCEDURE HORA_EXTRA_COMP_ANUAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2);
        
        PROCEDURE HORA_EXTRA_COMP_MENSAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2);

        PROCEDURE HORA_EXTRA_PAG_ANUAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2);
        
        PROCEDURE HORA_EXTRA_PAG_MENSAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2);

END FUNCOES_ABSENTEISMO;
/
CREATE OR REPLACE PACKAGE BODY FUNCOES_ABSENTEISMO AS
  
/*Retorna o total por ocorrência da coordenadoria escolhida*/

  PROCEDURE ABSENTEISMO_CONSOLIDADO(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2) IS     
  BEGIN
     OPEN TAB FOR 
     SELECT CODIGO, COUNT(*) AS TOTAL FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       where C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     ) GROUP BY CODIGO;
  END;

  PROCEDURE ABSENTEISMO_NOMINAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2) IS     
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA , C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO,
       F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO,
       O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE ABSENTEISMO_EMP(TAB IN OUT TEMP, SMES IN VARCHAR2, SANO IN VARCHAR2,SMES1 IN VARCHAR2, SANO1 IN VARCHAR2, IMATRICULA IN NUMBER) IS
  BEGIN
     OPEN TAB FOR 
     SELECT CODIGO, DATA FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE F.OFE_EMP_NUMERO_MATRICULA = IMATRICULA
       AND F.OFE_OFU_CODIGO IN(46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) BETWEEN SMES AND SMES1
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) BETWEEN SANO AND SANO1
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM OCORRENCIAS_EMPREGADOS O
       WHERE O.OEM_EMP_NUMERO_MATRICULA = IMATRICULA
       AND O.OEM_OFU_CODIGO IN (46,49,32,29,23,24,224,225,226,227,228,229,230,231,232,13,50,60,48,47,124,51,75,35,151,162,34,61,28,156,54,25)
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) BETWEEN SMES AND SMES1
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) BETWEEN SANO AND SANO1
     )ORDER BY DATA;
  END;


  PROCEDURE FREQUENCIA_CONSOLIDADA(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2) IS
  BEGIN
     OPEN TAB FOR
     SELECT CODIGO, COUNT(*) AS TOTAL FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       where C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     ) GROUP BY CODIGO;
  END;

  PROCEDURE FREQUENCIA_NOMINAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2) IS
  BEGIN
     OPEN TAB FOR
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA  FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F
       WHERE F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO,
       O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND O.OEM_OFU_CODIGO IN (37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
       AND C.EMP_UOR_CODIGO_LOTACAO IN
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
     ) ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE FREQUENCIA_EMP(TAB IN OUT TEMP, SMES IN VARCHAR2, SMES1 IN VARCHAR2, SANO1 IN VARCHAR2, SANO IN VARCHAR2, IMATRICULA IN NUMBER) IS
  BEGIN
     OPEN TAB FOR
     SELECT CODIGO, DATA FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM OCORRENCIAS_FREQUENCIA_EMP F
       WHERE F.OFE_EMP_NUMERO_MATRICULA = IMATRICULA
       AND F.OFE_OFU_CODIGO IN(37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) BETWEEN SMES AND SMES1
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) BETWEEN SANO AND SANO1
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM OCORRENCIAS_EMPREGADOS O
       WHERE O.OEM_EMP_NUMERO_MATRICULA = IMATRICULA
       AND O.OEM_OFU_CODIGO IN (37,187,188,38,167,39,40,42,41,43,65,66,67)
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) BETWEEN SMES AND SMES1
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) BETWEEN SANO AND SANO1
     )ORDER BY DATA;
  END;

  PROCEDURE DEMONSTRATIVO_FALTAS(TAB IN OUT TDEMO , IUOR_CODIGO IN NUMBER, SMES IN VARCHAR2, SANO IN VARCHAR2, SMES1 IN VARCHAR2, SANO1 IN VARCHAR2) IS
  BEGIN
     OPEN TAB FOR
     SELECT CODIGO, COUNT(*) AS TOTAL , MATRICULA, LOTACAO, NOME FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO, c.emp_numero_matricula AS MATRICULA,c.emp_uor_codigo_lotacao as LOTACAO,c.emp_nome_abreviado NOME
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (49, 32, 50, 60, 48, 47, 23, 24, 224, 225, 226, 227, 228, 229, 230, 231, 232, 51, 75, 35, 34, 61)
       AND EXTRACT(MONTH FROM f.OFE_DATA_INICIO) between SMES and SMES1
       AND EXTRACT(YEAR FROM f.OFE_DATA_INICIO) between SANO and SANO1
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO, c.emp_numero_matricula AS MATRICULA,c.emp_uor_codigo_lotacao as LOTACAO,c.emp_nome_abreviado NOME
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (49, 32, 50, 60, 48, 47, 23, 24, 224, 225, 226, 227, 228, 229, 230, 231, 232, 51, 75, 35, 34, 61)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM o.OEM_DATA_INICIO) between SMES and SMES1
       AND EXTRACT(YEAR FROM o.OEM_DATA_INICIO) between SANO and SANO1
     ) GROUP BY CODIGO,MATRICULA,LOTACAO, NOME
     ORDER BY LOTACAO, NOME, CODIGO;
  END;

  PROCEDURE DEMONSTRATIVO_FALTAS_EMP (TAB IN OUT TDADOS, SMES IN VARCHAR2, SMES1 IN VARCHAR2, SANO IN VARCHAR2, SANO1 IN VARCHAR2 ,SMATRICULA IN VARCHAR2) IS
  BEGIN
     OPEN TAB FOR
     SELECT CODIGO, COUNT(*) AS TOTAL FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO
       FROM OCORRENCIAS_FREQUENCIA_EMP F
       WHERE F.OFE_EMP_NUMERO_MATRICULA = SMATRICULA
       AND F.OFE_OFU_CODIGO  IN (49, 32, 50, 60, 48, 47, 23, 24, 224, 225, 226, 227, 228, 229, 230, 231, 232, 51, 75, 35, 34, 61)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) between SMES  and SMES1
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) between SANO and SANO1
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO
       FROM OCORRENCIAS_EMPREGADOS O
       WHERE  O.OEM_EMP_NUMERO_MATRICULA = SMATRICULA
       AND O.OEM_OFU_CODIGO IN (49, 32, 50, 60, 48, 47, 23, 24, 224, 225, 226, 227, 228, 229, 230, 231, 232, 51, 75, 35, 34, 61)
       AND EXTRACT(MONTH FROM o.OEM_DATA_INICIO) between SMES and SMES1
       AND EXTRACT(YEAR FROM o.OEM_DATA_INICIO) between SANO and SANO1
     ) GROUP BY CODIGO;
  END;

  PROCEDURE OCORRENCIA_TOTAL(TAB IN OUT TDADOS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2) IS
  BEGIN
     OPEN TAB FOR
     SELECT CODIGO, COUNT(*) AS TOTAL FROM (
       SELECT F.OFE_OFU_CODIGO AS CODIGO
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (50,34,51)
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT O.OEM_OFU_CODIGO AS CODIGO
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (50,34,51)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     ) GROUP BY CODIGO;
  END;

  PROCEDURE OCORRENCIA_ANUAL(TAB IN OUT TOCOR, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2,  IOCR_CODIGO IN NUMBER) IS
  BEGIN
     OPEN TAB FOR
     SELECT MATRICULA, NOME, LOTACAO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  = IOCR_CODIGO
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO = IOCR_CODIGO
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE OCORRENCIA_MENSAL(TAB IN OUT TOCOR, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2, IOCR_CODIGO IN NUMBER) IS     
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  = IOCR_CODIGO
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO IN 
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO = IOCR_CODIGO       
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE HORA_EXTRA_COMP_ANUAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2) IS  
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME,        C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (44,45)
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       WHERE C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (44,45)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE HORA_EXTRA_COMP_MENSAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2) IS     
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME,C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (44,45)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       where C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO IN 
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (44,45)      
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE HORA_EXTRA_PAG_ANUAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2) IS  
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME,C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (152,179,180,19,20,76,154,181,182,153,183,184,77,78,87,155,185,186)
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       where C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (152,179,180,19,20,76,154,181,182,153,183,184,77,78,87,155,185,186)
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA 
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

  PROCEDURE HORA_EXTRA_PAG_MENSAL(TAB IN OUT TABS, IUOR_CODIGO IN NUMBER, SANO IN VARCHAR2, SMES IN VARCHAR2) IS     
  BEGIN
     OPEN TAB FOR 
     SELECT MATRICULA, NOME, LOTACAO, CODIGO, DATA FROM (
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME, C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, F.OFE_OFU_CODIGO AS CODIGO, F.OFE_DATA_INICIO AS DATA
       FROM CADASTROS C, OCORRENCIAS_FREQUENCIA_EMP F 
       WHERE C.EMP_UOR_CODIGO_LOTACAO in
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND F.OFE_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND C.EMP_STATUS <> '2'
       AND F.OFE_OFU_CODIGO  IN (152,179,180,19,20,76,154,181,182,153,183,184,77,78,87,155,185,186)
       AND EXTRACT(MONTH FROM F.OFE_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM F.OFE_DATA_INICIO) = SANO
       UNION ALL
       SELECT C.EMP_NUMERO_MATRICULA AS MATRICULA, C.EMP_NOME_ABREVIADO AS NOME,        C.EMP_UOR_CODIGO_LOTACAO AS LOTACAO, O.OEM_OFU_CODIGO AS CODIGO, O.OEM_DATA_INICIO AS DATA
       FROM CADASTROS C , OCORRENCIAS_EMPREGADOS O
       where C.EMP_STATUS <> '2'
       AND C.EMP_UOR_CODIGO_LOTACAO IN 
          (Select uor_codigo
           from unidades_organizacionais
           connect by prior uor_codigo = uor_uor_codigo
           start with uor_codigo = IUOR_CODIGO)
       AND O.OEM_OFU_CODIGO IN (152,179,180,19,20,76,154,181,182,153,183,184,77,78,87,155,185,186)      
       AND O.OEM_EMP_NUMERO_MATRICULA = C.EMP_NUMERO_MATRICULA
       AND EXTRACT(MONTH FROM O.OEM_DATA_INICIO) = SMES
       AND EXTRACT(YEAR FROM O.OEM_DATA_INICIO) = SANO
     )ORDER BY LOTACAO, NOME, DATA;
  END;

END FUNCOES_ABSENTEISMO;
/
SHOW ERROR