CREATE TABLE INTEGRACAO.TAB_TIPO_CONTRATO_U
  (
  CONTRACT_TYPE CHAR (4) NOT NULL,
  DESCP CHAR (40) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  USER_ID_CREATED CHAR (30) NOT NULL,
  DATE_CHANGED DATE NOT NULL,
  USER_ID_CHANGED CHAR (30) NOT NULL,
  INACTIVE_IND CHAR (1) NOT NULL,
  ACTIVE_DATE DATE NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.CONTRACT_TYPE IS 'TIPO DO CONTRATO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.DESCP IS 'DESCRICAO DO TIPO DO CONTRATO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.DATE_CREATED IS 'DATA DE CRIACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.USER_ID_CREATED IS 'USUARIO CRIADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.DATE_CHANGED IS 'DATA DE ALTERACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.USER_ID_CHANGED IS 'USUARIO ALTERADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.INACTIVE_IND IS 'FLAG DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.ACTIVE_DATE IS 'DATA DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_TIPO_CONTRATO_U.CHGSTAMP IS 'CONTROLE DE QTDE DE ALTERACOES DO REGISTRO'
/
