CREATE TABLE INTEGRACAO.TAB_SUBTIPO_CONTRATO_U
  (
  CONTRACT_TYPE CHAR (4) NOT NULL,
  CONTRACT_SUB_TYPE CHAR (4) NOT NULL,
  DESCP CHAR (4) NOT NULL,
  VALIDA_UFC9001 CHAR (1) NOT NULL,
  VALIDA_UFC9002 CHAR (1) NOT NULL,
  VALIDA_UFC9003 CHAR (1) NOT NULL,
  VALIDA_UFC9004 CHAR (1) NOT NULL,
  VALIDA_UFC9005 CHAR (1) NOT NULL,
  VALIDA_UFC9006 CHAR (1) NOT NULL,
  VALIDA_UFC9007 CHAR (1) NOT NULL,
  VALIDA_UFC9008 CHAR (1) NOT NULL,
  VALIDA_UFC9009 CHAR (1) NOT NULL,
  VALIDA_UFC9010 CHAR (1) NOT NULL,
  VALIDA_UFC9011 CHAR (1) NOT NULL,
  VALIDA_UFC9012 CHAR (1) NOT NULL,
  VALIDA_UFC9013 CHAR (1) NOT NULL,
  VALIDA_UFC9014 CHAR (1) NOT NULL,
  VALIDA_UFC9015 CHAR (1) NOT NULL,
  VALIDA_UFCVAL01 CHAR (1) NOT NULL,
  VALIDA_UFCVAL02 CHAR (1) NOT NULL,
  VALIDA_UFCVAL03 CHAR (1) NOT NULL,
  VALIDA_UFCVAL04 CHAR (1) NOT NULL,
  VALIDA_UFCVAL05 CHAR (1) NOT NULL,
  VALIDA_UFCVAL06 CHAR (1) NOT NULL,
  IND_GARANTIA_CAUCIONARIA CHAR (1) NOT NULL,
  PER_GARANTIA_FIXA FLOAT NOT NULL,
  IND_REFER_MOMENTO_0101 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0102 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0103 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0104 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0201 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0202 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0203 CHAR (1) NOT NULL,
  IND_REFER_MOMENTO_0204 CHAR (1) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  USER_ID_CREATED CHAR (30) NOT NULL,
  DATE_CHANGED DATE NOT NULL,
  USER_ID_CHANGED CHAR (30) NOT NULL,
  INACTIVE_IND CHAR (1) NOT NULL,
  ACTIVE_DATE DATE NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.CONTRACT_TYPE IS 'SIGLA DO TIPO DO CONTRATO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.CONTRACT_SUB_TYPE IS 'CODIGO DO SUBTIPO DO CONTRATO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.DESCP IS 'DESCRICAO DO SUBTIPO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9001 IS 'IDENTIFICACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9002 IS 'OBJETO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9003 IS 'DATAS E PRAZO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9004 IS 'CONTRATO/PARTICIPE'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9005 IS 'REPRESENTANTES'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9006 IS 'PUBLICACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9007 IS 'CAMPOS DE USUARIOS'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9008 IS 'TERMO ADITIVO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9009 IS 'ITEM IDENTIFICACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9010 IS 'PROJETO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9011 IS 'CLASSIFICACAO CONTABIL'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9012 IS 'CAMPOS DE USUARIOS'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9013 IS 'RESUMO DOS VALORES'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9014 IS 'CONFIGURACAO DO REAJUSTE'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFC9015 IS 'PROGRAMACAO FINANCEIRA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL01 IS 'OUTRAS VALIDACOES 1'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL02 IS 'OUTRAS VALIDACOES 2'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL03 IS 'OUTRAS VALIDACOES 3'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL04 IS 'OUTRAS VALIDACOES 4'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL05 IS 'OUTRAS VALIDACOES 5'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.VALIDA_UFCVAL06 IS 'OUTRAS VALIDACOES 6'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_GARANTIA_CAUCIONARIA IS 'GARANTIA CAUCIONARIA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.PER_GARANTIA_FIXA IS 'INDICE DE GARANTIA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0101 IS 'FLAG DE ATIVACAO FISCAL'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0102 IS 'FLAG DE APROVACAO DO GESTOR'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0103 IS 'FLAG DE APROVACAO AUDITORIA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0104 IS 'FLAG DE APROVACAO JURIDICA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0201 IS 'FLAG DE CERTIFICACAO SP DO FISCAL'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0202 IS 'FLAG DE APROVACAO SP GESTOR'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0203 IS 'FLAG DE APROVACAO SP CALCULOS FISCAIS'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.IND_REFER_MOMENTO_0204 IS 'FLAG DE APROVACAO SP CONTABILIDADE'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.DATE_CREATED IS 'DATA DE ALTERACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.USER_ID_CREATED IS 'USUARIO CRIADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.DATE_CHANGED IS 'DATA DE ALTERACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.USER_ID_CHANGED IS 'USUARIO ALTERADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.INACTIVE_IND IS 'FLAG DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.ACTIVE_DATE IS 'DATA DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_SUBTIPO_CONTRATO_U.CHGSTAMP IS 'CONTROLE DE QTDE DE ALTERACOES DO REGISTRO'
/
