INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('CARGA_TABELA_EO','Atualiza E.O. apartir tabela externa ','');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('PATH_DOCUMENTO','path anexar documento','');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('PATH_INTRFACE','Path Exportação Interface','G:\sgs\exec\rep20010808.txt');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('SITSNSTRO_D1','Negado','Negado');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('SITSNSTRO_E1','Encerrado','Encerrado');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('SNSTRO','Parâmetros de Sinistro','NUM_AVSSNT_LOCRSC=RF
NOM_AVSSNT_RSPNSV=C032702
NOM_AVSSNT_CNTATO=Ângela / Iara
');
INSERT INTO PARAMETROS_SGS(COD_PARAMT, DCR_PARAMT, VLR_PARAMT) VALUES ('SYSTEMINFO','Informacoes do Sistema','CODE=SGS
SYSVERSION=3.9.0.0
DTBVERSION=3.9
');
