CREATE OR REPLACE VIEW VIW_OCORRENCIAS_FREQ_EMP
              (
               OFE_EMP_NUMERO_MATRICULA,
               OFE_OFU_CODIGO,
               OFE_DATA_INICIO,
               OFE_DATA_INCLUSAO,
               OFE_DATA_TERMINO,
               OFE_TEXTO,
               OFE_DIPLOMA_LEGAL,
               OFE_DIPLOMA_LEGAL_TERMINO,
               OFE_OFE_EMP_NUMERO_MATRICULA,
               OFE_OFE_OFU_CODIGO,
               OFE_OFE_DATA_INICIO,
               OFE_DEP_CODIGO,
               OFE_MOV_PARAMETRO,
               OFE_TIPO_EXPEDIENTE,
               OFE_COD_HORARIO_EMPREGADO,
               OFE_TURNO_TRABALHO_EMPREGADO,
               OFE_UOR_CODIGO,
               COD_USUARIO
              )
AS
SELECT 
       OFE_EMP_NUMERO_MATRICULA,
       OFE_OFU_CODIGO,
       OFE_DATA_INICIO,
       OFE_DATA_INCLUSAO,
       OFE_DATA_TERMINO,
       OFE_TEXTO,
       OFE_DIPLOMA_LEGAL,
       OFE_DIPLOMA_LEGAL_TERMINO,
       OFE_OFE_EMP_NUMERO_MATRICULA,
       OFE_OFE_OFU_CODIGO,
       OFE_OFE_DATA_INICIO,
       OFE_DEP_CODIGO,
       OFE_MOV_PARAMETRO,
       OFE_TIPO_EXPEDIENTE,
       OFE_COD_HORARIO_EMPREGADO,
       OFE_TURNO_TRABALHO_EMPREGADO,
       OFE_UOR_CODIGO,
       COD_USUARIO
FROM OCORRENCIAS_FREQUENCIA_EMP
 UNION ALL
SELECT 
         OFE_EMP_NUMERO_MATRICULA,
         OFE_OFU_CODIGO,
         OFE_DATA_INICIO,
         OFE_DATA_INCLUSAO,
         OFE_DATA_TERMINO,
         OFE_TEXTO,
         OFE_DIPLOMA_LEGAL,
         OFE_DIPLOMA_LEGAL_TERMINO,
         OFE_OFE_EMP_NUMERO_MATRICULA,
         OFE_OFE_OFU_CODIGO,
         OFE_OFE_DATA_INICIO,
         OFE_DEP_CODIGO,
         OFE_MOV_PARAMETRO,
         OFE_TIPO_EXPEDIENTE,
         OFE_COD_HORARIO_EMPREGADO,
         OFE_TURNO_TRABALHO_EMPREGADO,
         OFE_UOR_CODIGO,
         COD_USUARIO
    FROM HST_OCORRENCIAS_FREQ_EMP 
  
/

