


CREATE OR REPLACE VIEW view_ativos (
   codigo_superintendecia,
   sigla_superintendecia,
   nome_superintendecia,
   codigo_dependencia,
   sigla_dependencia,
   nome_dependencia,
   codigo_uor,
   sigla_uor,
   descricao_uor,
   matricula,
   nome,
   nome_abreviado,
   numero_cpf,
   admissao,
   nascimento,
   categoria,
   padrao,
   centro_custos,
   codigo_cargo,
   sigla_cargo,
   nome_cargo,
   car_codigo_cbo,
   codigo_ocupacao,
   descricao_ocupacao,
   codigo_funcao,
   tipo_remuneracao,
   descricao_funcao,
   fun_codigo_cbo,
   codigo_escolaridade,
   escolaridade,
   anuenios_qtde,
   anuenios_percentual,
   numero_matricula_ant,
   numero_matricula_tasa,
   numero_matricula_arsa,
   numero_fre,
   indicador_sexo,
   indicador_estado_civil,
   nacionalidade,
   endereco_logradouro,
   endereco_numero_cep,
   ramal_residencia,
   endereco_bairro,
   endereco_fone,
   numero_celular,
   ddd_residencia,
   ddd_celular,
   jtr_codigo,
   aba_ban_codigo_cta_pgto,
   aba_codigo_conta_pgto,
   nu_conta_corrente_pagto,
   sfu_codigo,
   htd_dep_codigo,
   htd_htr_codigo,
   htd_sequencial,
   data_chegada_brasil,
   nu_registro_estrangeiro,
   in_classe_registro_estrang,
   data_registro_estrangeiro,
   cidade_nasc_estrangeiro,
   cidade_natural_estrang,
   ufe_sigla_estrangeiro,
   decreto_naturalizacao,
   data_validade_rne,
   numero_ctps_rne,
   nu_serie_ctps_rne,
   data_expedicao_ctps_rne,
   data_validade_ctps_rne,
   mun_codigo_natural,
   ufe_sigla_natural,
   mun_codigo_reside,
   ufe_sigla_residente,
   data_naturalizacao,
   numero_pis_pasep,
   data_pis_pasep,
   nu_carteira_identidade,
   sigla_orgao_emitente_ci,
   data_expedicao_ci,
   ufe_sigla_ci,
   nu_titulo_eleitor,
   nu_zona_titulo_eleitor,
   nu_secao_titulo_eleitor,
   ufe_sigla_tit_eleitor,
   nu_certificado_reservista,
   nu_categoria_cr,
   nu_regiao_militar_cr,
   tipo_cr,
   ano_emissao_cr,
   nu_livro_certidao_casam,
   nu_folha_certidao_casam,
   data_casamento,
   numero_carteira_trabalho,
   numero_serie_carteira_trab,
   dt_expedicao_carteira_trab,
   ufe_sigla_ctps,
   data_opcao_fgts,
   codigo_fgts,
   numero_conta_fgts,
   aba_ban_codigo_fgts,
   aba_codigo_fgts,
   nu_carteira_habilitacao,
   in_categoria_habilitacao,
   dt_validade_carteira_hab,
   nu_habilitacao_lancha,
   indicador_categoria_hab,
   dt_validade_habilit_lancha,
   nu_carteira_orgao_classe,
   ufe_sigla_reg_profis,
   pai_codigo,
   oex_codigo_cedido,
   oex_codigo_requisitado,
   qlp_hcl_uor_codigo,
   qlp_hcl_data_vigencia,
   qlp_car_codigo,
   qlp_car_codigo_nivel,
   nsa_in_nivel_escolaridade,
   qfu_hfl_uor_codigo,
   qfu_hfl_data_vigencia,
   qfu_fun_codigo_acumula,
   qfu_hfl_uor_cod_acum,
   qfu_hfl_data_vigen_acum,
   tipo_remuner_funcao_acumul,
   qfu_fun_codigo_substitui,
   qfu_hfl_uor_cod_subst,
   qfu_hfl_data_vigen_subst,
   tipo_remuner_funcao_subst,
   ocl_sigla,
   nu_matricula_casado,
   dep_codigo_pagto,
   indicador_primeiro_emprego,
   ano_primeiro_emprego,
   ufe_sigla_primeiro_emprego,
   status,
   codigo_rais,
   tipo_conta,
   classe_hab_tecnologica,
   numero_hab_tecnologica,
   data_hab_tecnologica,
   habilit_orgao_oper,
   data_capacitacao_fisica,
   indicador_depv,
   numero_depv,
   licenca_depv,
   situacao_militar,
   posto_graduacao_codigo,
   quadro_arma_esp_codigo,
   forca_armada_codigo,
   nome_pai,
   nome_mae,
   id_aposentadoria,
   dt_aposentadoria,
   dt_reserva_militar,
   plano_arsaprev,
   data_filiacao_arsaprev,
   data_cancelamento_arsaprev,
   contrib_sindical_anual,
   contrib_federativa,
   adianta_13,
   cor_raca,
   nome_guerra,
   endereco_eletronico_mail )
AS
select subor.dep_codigo codigo_Superintendecia,
       subor.dep_sigla Sigla_Superintendecia,
       subor.dep_nome Nome_Superintendecia,
       dep.dep_codigo codigo_Dependencia,
       dep.dep_sigla Sigla_Dependencia,
       dep.dep_nome Nome_Dependencia,
       emp_uor_codigo_lotacao codigo_UOR,
       uor_sigla Sigla_UOR,
       uor_nome Descricao_UOR,
       emp_numero_matricula Matricula,
       emp_nome Nome,
       emp_nome_abreviado,
       emp_numero_cpf,
       emp_data_admissao Admissao,
       emp_data_nascimento Nascimento,
       emp_nsa_codigo_padrao Categoria,
       emp_nsa_codigo_nivel Padrao,
       emp_ati_ct_custos Centro_Custos,
       car_codigo codigo_Cargo,
       car_sigla Sigla_Cargo,
       Car_nome Nome_Cargo,
       car_codigo_CBO,
       emp_qlp_car_occ_codigo codigo_Ocupacao,
       Occ_descricao Descricao_Ocupacao,
       emp_qfu_fun_codigo codigo_Funcao,
       emp_tipo_remuneracao_funcao Tipo,
       fun_nome Descricao_Funcao,
       fun_codigo_CBO,
       emp_eso_codigo,
       eso_nome Escolaridade,
       nvl(oem_valor,0) anuenios_qtde,
       nvl(oem_mov_parametro,0) anuenios_percentual,
       emp_numero_matricula_ant,
       emp_numero_matricula_tasa,
       emp_numero_matricula_arsa,
       emp_numero_fre,
       emp_indicador_sexo,
       emp_indicador_estado_civil,
       emp_nacionalidade,
       emp_endereco_logradouro,
       emp_endereco_numero_cep,
       emp_ramal_residencia,
       emp_endereco_bairro,
       emp_endereco_fone,
       emp_numero_celular,
       emp_ddd_residencia,
       emp_ddd_celular,
       emp_jtr_codigo,
       emp_aba_ban_codigo_cta_pgto,
       emp_aba_codigo_conta_pgto,
       emp_nu_conta_corrente_pagto,
       emp_sfu_codigo,
       emp_htd_dep_codigo,
       emp_htd_htr_codigo,
       emp_htd_sequencial,
       emp_data_chegada_brasil,
       emp_nu_registro_estrangeiro,
       emp_in_classe_registro_estrang,
       emp_data_registro_estrangeiro,
       emp_cidade_nasc_estrangeiro,
       emp_cidade_natural_estrang,
       emp_ufe_sigla_estrangeiro,
       emp_decreto_naturalizacao,
       emp_data_validade_rne,
       emp_numero_ctps_rne,
       emp_nu_serie_ctps_rne,
       emp_data_expedicao_ctps_rne,
       emp_data_validade_ctps_rne,
       emp_mun_codigo_natural,
       emp_ufe_sigla_natural,
       emp_mun_codigo_reside,
       emp_ufe_sigla_residente,
       emp_data_naturalizacao,
       emp_numero_pis_pasep,
       emp_data_pis_pasep,
       emp_nu_carteira_identidade,
       emp_sigla_orgao_emitente_ci,
       emp_data_expedicao_ci,
       emp_ufe_sigla_ci,
       emp_nu_titulo_eleitor,
       emp_nu_zona_titulo_eleitor,
       emp_nu_secao_titulo_eleitor,
       emp_ufe_sigla_tit_eleitor,
       emp_nu_certificado_reservista,
       emp_nu_categoria_cr,
       emp_nu_regiao_militar_cr,
       emp_tipo_cr,
       emp_ano_emissao_cr,
       emp_nu_livro_certidao_casam,
       emp_nu_folha_certidao_casam,
       emp_data_casamento,
       emp_numero_carteira_trabalho,
       emp_numero_serie_carteira_trab,
       emp_dt_expedicao_carteira_trab,
       emp_ufe_sigla_ctps,
       emp_data_opcao_fgts,
       emp_codigo_fgts,
       emp_numero_conta_fgts,
       emp_aba_ban_codigo_fgts,
       emp_aba_codigo_fgts,
       emp_nu_carteira_habilitacao,
       emp_in_categoria_habilitacao,
       emp_dt_validade_carteira_hab,
       emp_nu_habilitacao_lancha,
       emp_indicador_categoria_hab,
       emp_dt_validade_habilit_lancha,
       emp_nu_carteira_orgao_classe,
       emp_ufe_sigla_reg_profis,
       emp_pai_codigo,
       emp_oex_codigo_cedido,
       emp_oex_codigo_requisitado,
       emp_qlp_hcl_uor_codigo,
       emp_qlp_hcl_data_vigencia,
       emp_qlp_car_codigo,
       emp_qlp_car_codigo_nivel,
       emp_nsa_in_nivel_escolaridade,
       emp_qfu_hfl_uor_codigo,
       emp_qfu_hfl_data_vigencia,
       emp_qfu_fun_codigo_acumula,
       emp_qfu_hfl_uor_cod_acum,
       emp_qfu_hfl_data_vigen_acum,
       emp_tipo_remuner_funcao_acumul,
       emp_qfu_fun_codigo_substitui,
       emp_qfu_hfl_uor_cod_subst,
       emp_qfu_hfl_data_vigen_subst,
       emp_tipo_remuner_funcao_subst,
       emp_ocl_sigla,
       emp_emp_nu_matricula_casado,
       emp_dep_codigo_pagto,
       emp_indicador_primeiro_emprego,
       emp_ano_primeiro_emprego,
       emp_ufe_sigla_primeiro_emprego,
       emp_status,
       emp_codigo_rais,
       emp_tipo_conta,
       emp_classe_hab_tecnologica,
       emp_numero_hab_tecnologica,
       emp_data_hab_tecnologica,
       emp_habilit_orgao_oper,
       emp_data_capacitacao_fisica,
       emp_indicador_depv,
       emp_numero_depv,
       emp_licenca_depv,
       emp_situacao_militar,
       emp_posto_graduacao_codigo,
       emp_quadro_arma_esp_codigo,
       emp_forca_armada_codigo,
       emp_nome_pai,
       emp_nome_mae,
       emp_id_aposentadoria,
       emp_dt_aposentadoria,
       emp_dt_reserva_militar,
       emp_plano_arsaprev,
       emp_data_filiacao_arsaprev,
       emp_data_cancelamento_arsaprev,
       emp_contrib_sindical_anual,
       emp_contrib_federativa,
       emp_adianta_13,
       emp_cor_raca,
       emp_nome_guerra,
       emp_endereco_eletronico_mail
from cadastros,
     cargos,
     ocupacoes_cargo,
     dependencias dep,
     (select dep_codigo,
             dep_sigla,
             dep_nome
      from dependencias
      where dep_data_extincao is null
      connect by prior dep_codigo = dep_dep_codigo
      start with to_char(dep_codigo)  = '1') subor,
     unidades_organizacionais,
     funcoes,
     escolaridades,
     ocorrencias_empregados
where emp_status != 2
and   emp_qlp_car_codigo = car_codigo(+)
and   emp_qlp_car_codigo_nivel = car_codigo_nivel(+)
and   emp_qlp_car_occ_codigo = car_occ_codigo(+)
and   car_occ_codigo = occ_codigo(+)
and   ((emp_dep_codigo_lotacao = dep.dep_codigo
        and  dep.dep_dep_codigo = subor.dep_codigo)
      or
      (emp_dep_codigo_lotacao = 1
       and emp_dep_codigo_lotacao = dep.dep_codigo
       and dep.dep_codigo = subor.dep_codigo))
and   emp_uor_codigo_lotacao = uor_codigo(+)
and   emp_qfu_fun_codigo = fun_codigo(+)
and   emp_eso_codigo = eso_codigo(+)
and   emp_numero_matricula = oem_emp_numero_matricula(+)
and   oem_ofu_codigo(+) = 216
order by subor.dep_codigo,
         dep.dep_codigo,
         emp_nome
/

