-- View VIW_CAR_FUN_UOR_EPOCA_TREIN

CREATE OR REPLACE VIEW ifrhumanus.viw_car_fun_uor_epoca_trein (
   sequencial,
   matricula,
   CAR_SIGLA,
   OCC_DESCRICAO,
   FUN_CODIGO,
   FUN_DESCRICAO,
   UOR_CODIGO,
   UOR_SIGLA,
   UOR_NOME)
AS
select EVP_EVE_SEQ,EVPEMP_NUMERO_MATRICULA,
	   CAR_SIGLA,OCC_DESCRICAO,      --Cargo
       FUN_CODIGO,FUN_DESCRICAO,     --Função
	   UOR_CODIGO,UOR_SIGLA,UOR_NOME --UOR
FROM VIW_CARGO_EPOCA_TREIN,VIW_FUN_EPOCA_TREIN,VIW_UOR_EPOCA_TREIN,TRN_EVENTO_PARTICIP
WHERE TRN_EVENTO_PARTICIP.EVP_EVE_SEQ = VIW_CARGO_EPOCA_TREIN.SEQUENCIAL(+)
      AND TRN_EVENTO_PARTICIP.EVP_EVE_SEQ = VIW_FUN_EPOCA_TREIN.SEQUENCIAL(+)
	  AND TRN_EVENTO_PARTICIP.EVP_EVE_SEQ = VIW_UOR_EPOCA_TREIN.SEQUENCIAL(+)
	  AND TRN_EVENTO_PARTICIP.EVPEMP_NUMERO_MATRICULA = VIW_CARGO_EPOCA_TREIN.MATRICULA(+)
	  AND TRN_EVENTO_PARTICIP.EVPEMP_NUMERO_MATRICULA = VIW_FUN_EPOCA_TREIN.MATRICULA(+)
      AND TRN_EVENTO_PARTICIP.EVPEMP_NUMERO_MATRICULA = VIW_UOR_EPOCA_TREIN.MATRICULA(+)
/
-- Grants for View
GRANT SELECT ON ifrhumanus.viw_car_fun_uor_epoca_trein TO srh_trn_01
/
GRANT SELECT ON ifrhumanus.viw_car_fun_uor_epoca_trein TO srh_trn_02
/
GRANT SELECT ON ifrhumanus.viw_car_fun_uor_epoca_trein TO srh_trn_03
/
