DECLARE	@SIG_AEROPORTO	VARCHAR(4)
	  ,	@INTERVALO INT

SELECT	@SIG_AEROPORTO	= 'SBRF'
	  ,	@INTERVALO = -6

SELECT	TOP 100 *
  FROM	IEOP..IEOP_DESEMBARQUE
 WHERE  SIG_AEROPORTO = @SIG_AEROPORTO
   AND  DTH_NORMAL_POUSO > (CONVERT(VARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(VARCHAR(8), DATEADD(HOUR, @INTERVALO, GETDATE()), 108))
   AND  NUM_GRUPO_VOO_DESEMB = 1
 ORDER
	BY	DTH_EFETIVA_POUSO