--ORACLE
SELECT  EMP_NUMERO_MATRICULA
     ,  EMP_NOME
     ,  EMP_DATA_ADMISSAO
     ,  DEP_CODIGO
     ,  DEP_SIGLA
     ,  DEP_NOME
     ,  DECODE(DEP_SIGLA, 'SEDE', DEP_SIGLA, DEP_SIGLA || ' - ' || DEP_NOME) AS DEP_SIGLA_NOME
     ,  UOR_CODIGO
     ,  UOR_SIGLA
     ,  UOR_NOME
     ,  UOR_SIGLA || ' - ' || UOR_NOME AS UOR_SIGLA_NOME
FROM (
SELECT EGT.EGT_EMP_NUMERO_MATRICULA AS EMP_NUMERO_MATRICULA
     , (SELECT EMP_NOME FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = EGT_EMP_NUMERO_MATRICULA) EMP_NOME
     , (SELECT EMP_DATA_ADMISSAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = EGT_EMP_NUMERO_MATRICULA) EMP_DATA_ADMISSAO
     , egt_dep_codigo_fisico DEP_CODIGO
     , (SELECT HDE_SIGLA FROM HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico AND  (HDE_DATA_EXTINCAO IS NULL OR HDE_DATA_EXTINCAO IN (SELECT MAX(HDE_DATA_EXTINCAO) FROM HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico)) AND ROWNUM =1) AS DEP_SIGLA
     , (SELECT HDE_NOME FROM HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico AND  (HDE_DATA_EXTINCAO IS NULL OR HDE_DATA_EXTINCAO IN (SELECT MAX(HDE_DATA_EXTINCAO) FROM HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico)) AND ROWNUM =1) AS DEP_NOME
     , EGT_UOR_CODIGO UOR_CODIGO
     , (SELECT UOR_SIGLA FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EGT_UOR_CODIGO) AS UOR_SIGLA
     , (SELECT UOR_NOME FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EGT_UOR_CODIGO) AS UOR_NOME
  FROM EMPREGADOS_PAGAMENTOS EGT
 WHERE EGT_CRP_ANO_PAGAMENTO = 2010
   AND EGT_CRP_MES_PAGAMENTO = 12
   AND EGT_CRP_SEQUENCIAL = 1 )  TMP;
   --WHERE EMP_NUMERO_MATRICULA = 9504989
   
   
--select * from cadastros where emp_numero_matricula = 9504989


--SQL SERVER
SELECT  EMP_NUMERO_MATRICULA
     ,  EMP_NOME
     ,  EMP_DATA_ADMISSAO
     ,  DEP_CODIGO
     ,  DEP_SIGLA
     ,  DEP_NOME
     ,  CASE DEP_SIGLA
	       WHEN 'SEDE' THEN DEP_SIGLA
		   ELSE DEP_SIGLA + ' - ' + DEP_NOME
	    END AS DEP_SIGLA_NOME
     ,  UOR_CODIGO
     ,  UOR_SIGLA
     ,  UOR_NOME
     ,  UOR_SIGLA + ' - ' + UOR_NOME AS UOR_SIGLA_NOME
	 --INTO [EMPREGADOS_INFRAERO_2010]
FROM (
SELECT EGT.EGT_EMP_NUMERO_MATRICULA AS EMP_NUMERO_MATRICULA
     , (SELECT EMP_NOME FROM CORPORATIVO..IFRSRH.CADASTROS WHERE EMP_NUMERO_MATRICULA = EGT_EMP_NUMERO_MATRICULA) EMP_NOME
     , (SELECT EMP_DATA_ADMISSAO FROM CORPORATIVO..IFRSRH.CADASTROS WHERE EMP_NUMERO_MATRICULA = EGT_EMP_NUMERO_MATRICULA) EMP_DATA_ADMISSAO
     , egt_dep_codigo_fisico DEP_CODIGO
     , (SELECT TOP 1 HDE_SIGLA FROM CORPORATIVO..IFRDBA2.HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico AND  (HDE_DATA_EXTINCAO IS NULL OR HDE_DATA_EXTINCAO IN (SELECT MAX(HDE_DATA_EXTINCAO) FROM CORPORATIVO..IFRDBA2.HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico)) ORDER BY 1 ASC ) AS DEP_SIGLA
     , (SELECT TOP 1 HDE_NOME FROM CORPORATIVO..IFRDBA2.HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico AND  (HDE_DATA_EXTINCAO IS NULL OR HDE_DATA_EXTINCAO IN (SELECT MAX(HDE_DATA_EXTINCAO) FROM CORPORATIVO..IFRDBA2.HISTORICO_DEPENDENCIAS WHERE HDE_DEP_CODIGO = egt_dep_codigo_fisico)) ORDER BY 1 ASC ) AS DEP_NOME
     , EGT_UOR_CODIGO UOR_CODIGO
     , (SELECT UOR_SIGLA FROM CORPORATIVO..IFRDBA2.UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EGT_UOR_CODIGO) AS UOR_SIGLA
     , (SELECT UOR_NOME FROM CORPORATIVO..IFRDBA2.UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EGT_UOR_CODIGO) AS UOR_NOME
  FROM CORPORATIVO..IFRSRH.EMPREGADOS_PAGAMENTOS EGT
 WHERE EGT_CRP_ANO_PAGAMENTO = 2010
   AND EGT_CRP_MES_PAGAMENTO = 12
   AND EGT_CRP_SEQUENCIAL = 1 )  TMP