SELECT (SELECT TOP 1 UPPER(NME_CIA_AEREA) NOME_CIA_AEREA FROM  [dbo].[IEOP_DESEMBARQUE] WHERE UPPER(SIG_CIA_AEREA_IATA) =  T.SIGLA_CIA_AEREA) AS "NOME DA CIA AÉREA"
     , T.TOTAL * 2 AS "NUM DE POUSO/DECOLAGENS"
FROM (
		SELECT	DISTINCT UPPER(SIG_CIA_AEREA_IATA) SIGLA_CIA_AEREA --*
			 ,  COUNT(1) AS TOTAL
		  FROM	[dbo].[IEOP_DESEMBARQUE]
		 WHERE  SIG_AEROPORTO IN ('SBBE', 'SBCT', 'SBCY', 'SBEG', 'SBFZ', 'SBMO', 'SBPA', 'SBRF', 'SBRJ', 'SBGO', 'SBSP', 'SBSP')
		   AND  NUM_GRUPO_VOO_DESEMB = 1
		   AND  NUM_NATUREZA_VOO_DESEMB = 1
		   AND  NUM_CATEGORIA_VOO_DESEMB = 1
		   AND  NUM_CLASSE_VOO_DESEMB IN (1,3)
		   AND  NUM_CATEGORIA_VOO_DESEMB_VINCULADO IS NULL
		   --AND  UPPER(NME_CIA_AEREA) LIKE '%AEROMÉXICO CONNECT%'
		   --AND  SIG_CIA_AEREA_IATA = 'ARE'
		   AND  DTH_EFETIVA_POUSO > '20140101'
		   GROUP BY UPPER(SIG_CIA_AEREA_IATA)) AS T
   ORDER BY 2 DESC


/*

SELECT	DISTINCT UPPER(NME_CIA_AEREA) NOME_CIA_AEREA --*
     ,  COUNT(1) AS TOTAL
  FROM	[dbo].[IEOP_DESEMBARQUE]
 WHERE  SIG_AEROPORTO IN ('SBBE', 'SBCT', 'SBCY', 'SBEG', 'SBFZ', 'SBMO', 'SBPA', 'SBRF', 'SBRJ', 'SBGO', 'SBSP', 'SBSP')
   AND  NUM_GRUPO_VOO_DESEMB = 1
   AND  NUM_NATUREZA_VOO_DESEMB = 1
   AND  NUM_CATEGORIA_VOO_DESEMB = 1
   AND  NUM_CATEGORIA_VOO_DESEMB_VINCULADO IS NULL
   --AND  UPPER(NME_CIA_AEREA) LIKE '%AEROMÉXICO CONNECT%'
   --AND  SIG_CIA_AEREA_IATA = 'ARE'
   AND  DTH_EFETIVA_POUSO > '20140101'
   GROUP BY UPPER(NME_CIA_AEREA)
   ORDER BY 1



SELECT	TOP 100 *
  FROM	[dbo].[IEOP_DESEMBARQUE]
 WHERE  SIG_AEROPORTO IN ('SBBE', 'SBCT', 'SBCY', 'SBEG', 'SBFZ', 'SBMO', 'SBPA', 'SBRF', 'SBRJ', 'SBGO', 'SBSP', 'SBSP')
   /*AND  NUM_GRUPO_VOO_DESEMB = 1
   AND  NUM_NATUREZA_VOO_DESEMB = 1
   AND  NUM_CATEGORIA_VOO_DESEMB = 1
   AND  NUM_CATEGORIA_VOO_DESEMB_VINCULADO IS NULL*/
   AND  UPPER(NME_CIA_AEREA) LIKE '%MAP LINHAS AÉREAS%'
   --AND  SIG_CIA_AEREA_IATA = 'ARE'
   AND  DTH_EFETIVA_POUSO > '20140101'
   ORDER BY 1

*/