USE IEOP
GO

--   EXECUTE IEOP..PRC_MIGRA_RPE_SISO 'SBVT'

ALTER PROCEDURE PRC_MIGRA_RPE_SISO (@SIG_AEROPORTO varchar(4))
AS
DECLARE		@SQL VARCHAR(MAX)
	  ,		@DATA VARCHAR(30)


SELECT @DATA = CONVERT(VARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(VARCHAR(8), GETDATE(), 108)

SELECT @SQL = '
BEGIN TRY 
	INSERT INTO [' + @SIG_AEROPORTO + ' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RPE_DES]
	SELECT 	[SIG_AEROPORTO] AS SIGLA_AEROPORTO
		,	[NUM_VOO] AS NR_CHG_VOO
		,	[DTH_NORMAL_POUSO] AS DH_CHG_NRM
		,	[DTH_EFETIVA_POUSO] AS DH_CHG_EFE
		,	[COD_CIA_AEREA] AS CD_COM
		,	[SIG_CIA_AEREA_IATA] AS SG_COM_IAT_003
		,	[COD_MATRICULA_AERONAVE] AS NR_AEN
		,	[NUM_GRUPO_VOO_DESEMB] AS TP_CHG_GRU
		,	[NUM_NATUREZA_VOO_DESEMB] AS TP_CHG_NAT
		,	[NUM_CLASSE_VOO_DESEMB] AS TP_CHG
		,	[NUM_CATEGORIA_VOO_DESEMB] AS TP_CHG_CTG
		,	[NUM_CATEGORIA_VOO_DESEMB_VINCULADO] AS TP_CHG_CTG_VIN
		,	[SIG_EQUIPAMENTO] AS SG_EQP
		,	[QTD_PAX_DESEMB_DOM] AS QT_DEC_DES_DOM
		,	[QTD_PAX_DESEMB_INT] AS QT_DEC_DES_INT
		,	[QTD_BAG_DESEMB_DOM] AS QT_DEC_DES_BAG_DOM
		,	[QTD_BAG_DESEMB_INT] AS QT_DEC_DES_BAG_INT
		,	[QTD_CAR_DESEMB_DOM] AS QT_DEC_DES_CAR_DOM
		,	[QTD_CAR_DESEMB_INT] AS QT_DEC_DES_CAR_INT
		,	[QTD_COR_DESEMB_DOM] AS QT_DEC_DES_COR_DOM
		,	[QTD_COR_DESEMB_INT] AS QT_DEC_DES_COR_INT
		,	[QTD_BAG_TRANSITO_DOM] AS QT_DEC_TRA_BAG_DOM
		,	[QTD_BAG_TRANSITO_INT] AS QT_DEC_TRA_BAG_INT
		,	[QTD_CAR_TRANSITO_DOM] AS QT_DEC_TRA_CAR_DOM
		,	[QTD_CAR_TRANSITO_INT] AS QT_DEC_TRA_CAR_INT
		,	[QTD_COR_TRANSITO_DOM] AS QT_DEC_TRA_COR_DOM
		,	[QTD_COR_TRANSITO_INT] AS QT_DEC_TRA_COR_INT
		,	[QTD_CON_TRANSITO_DOM] AS QT_DEC_TRA_DOM_CX
		,	[QTD_CON_TRANSITO_INT] AS QT_DEC_TRA_INT_CX
		,	[COD_VOO_CHEGADA] AS CD_CHG
		,	[COD_DESEMB_VINCULADO] AS CD_CHG_VIN
		,	[NUM_BOX] AS NR_BOX
		,	[TIP_BOX] AS TP_BOX
		,	[SIG_AEROPORTO_PROCEDENCIA] AS SIGLA_AEROPORTO_PRO
		,	[FLG_TAXI_AEREO] AS FL_AEN_TAX
		,	[FLG_EQUIP_HELICOP] AS FL_EQP_HLC
		,	[COD_STATUS] AS CD_STA
		,	[NME_CIA_AEREA] AS NOME_CIA
		,	[NME_EQUIPAMENTO] AS NM_EQP
		,	[DSC_PISTA_POUSO] AS PIS_PO
		,	[DSC_PISTA_DECOLAGEM] AS PIS_DE
		,	[DTH_PRI_MOV] AS HR_MOV_PRI
		,	[DTH_ULT_MOV] AS HR_MOV_ULT
		,	[DTH_ATUALIZACAO] AS DTH_ATUALIZACAO
		,	[FLG_STATUS] AS FL_STATUS
		,	[FLG_ISENTO] AS FLAG_ISE
		,	[FLG_AVISTA] AS FLAG_AVISTA
		,	[DTH_PRI_ENT_MOV] AS HR_MOV_PRI_ENT
		,	[TIP_STATUS] AS TP_STA
		,	[COD_STATUS_ANT] AS CD_STA_ANT
		,	[COD_STATUS_POS] AS CD_STA_POS
		,	[NME_PONTE] AS NM_PON
		,	[NUM_ESTEIRA] AS NR_EST
		,	''' + @DATA + ''' AS DTH_MIGRACAO
		,	NULL AS FLG_MIGRADO
		,	NULL AS DTH_CARGA_SISO
	  FROM 	[IEOP].[dbo].[RPE_DESEMBARQUE] WITH (NOLOCK)
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 0
	   AND  DTH_MIGRACAO IS NULL;

	INSERT INTO [' + @SIG_AEROPORTO + ' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RPE_EMB]
	SELECT 	[SIG_AEROPORTO] AS SIGLA_AEROPORTO
		  ,	[NUM_VOO] AS NR_PAR_VOO
		  ,	[DTH_NORMAL_DECOLAGEM] AS DH_PAR_NRM
		  ,	[DTH_EFETIVA_DECOLAGEM] AS DH_PAR_EFE
		  ,	[COD_CIA_AEREA] AS CD_COM
		  ,	[SIG_CIA_AEREA_IATA] AS SG_COM_IAT_003
		  ,	[COD_MATRICULA_AERONAVE] AS NR_AEN
		  ,	[NUM_GRUPO_VOO_EMB] AS TP_PAR_GRU
		  ,	[NUM_NATUREZA_VOO_EMB] AS TP_PAR_NAT
		  ,	[NUM_CLASSE_VOO_EMB] AS TP_PAR
		  ,	[NUM_CATEGORIA_VOO_EMB] AS TP_PAR_CTG
		  ,	[NUM_CATEGORIA_VOO_EMB_VINCULADO] AS TP_PAR_CTG_VIN
		  ,	[SIG_EQUIPAMENTO] AS SG_EQP
		  ,	[QTD_TARIFA_PAGA_BILHETE_DOM_EMB] AS QT_DEP_TFB_DOM
		  ,	[QTD_TARIFA_PAGA_BILHETE_INT_EMB] AS QT_DEP_TFB_INT
		  ,	[QTD_TARIFA_PAGA_CHECKIN_DOM_EMB] AS QT_DEP_TFC_DOM
		  ,	[QTD_TARIFA_PAGA_CHECKIN_INT_EMB] AS QT_DEP_TFC_INT
		  ,	[QTD_ISENTA_COLO_EMB] AS QT_DEP_ISE_COL
		  ,	[QTD_ISENTA_TRANSITO_EMB] AS QT_DEP_ISE_TRA
		  ,	[QTD_ISENTA_CONEXAO_EMB_DOM] AS QT_DEP_ISE_CON_DOM
		  ,	[QTD_ISENTA_CONEXAO_EMB_INT] AS QT_DEP_ISE_CON_INT
		  ,	[QTD_ISENTA_OUTRAS_EMB] AS QT_DEP_ISE_OUT
		  ,	[QTD_BAG_EMB_DOM] AS QT_DEP_EMB_BAG_DOM
		  ,	[QTD_BAG_EMB_INT] AS QT_DEP_EMB_BAG_INT
		  ,	[QTD_CAR_EMB_DOM] AS QT_DEP_EMB_CAR_DOM
		  ,	[QTD_CAR_EMB_INT] AS QT_DEP_EMB_CAR_INT
		  ,	[QTD_COR_EMB_DOM] AS QT_DEP_EMB_COR_DOM
		  ,	[QTD_COR_EMB_INT] AS QT_DEP_EMB_COR_INT
		  ,	[QTD_TARIFA_PAG_BILHETE_EMB_DOM_ANT] AS QT_DEP_TFB_DOM_ANT
		  ,	[QTD_TARIFA_PAG_BILHETE_EMB_INT_ANT] AS QT_DEP_TFB_INT_ANT
		  ,	[QTD_TARIFA_PAG_CHECKIN_EMB_DOM_ANT] AS QT_DEP_TFC_DOM_ANT
		  ,	[QTD_TARIFA_PAG_CHECKIN_EMB_INT_ANT] AS QT_DEP_TFC_INT_ANT
		  ,	[COD_VOO_CHEGADA_ANT] AS CD_CHG_AEN_ANT
		  ,	[COD_EMB_VINCULADO] AS CD_PAR_VIN
		  ,	[NUM_BOX] AS NR_BOX
		  ,	[TIP_BOX] AS TP_BOX
		  ,	[SIG_AEROPORTO_DESTINO] AS SIGLA_AEROPORTO_DES
		  ,	[FLG_TAXI_AEREA] AS FL_AEN_TAX
		  ,	[FLG_EQUIP_HELICOP] AS FL_EQP_HLC
		  ,	[COD_STATUS] AS CD_STA
		  ,	[NME_CIA_AEREA] AS NOME_CIA
		  ,	[NME_EQUIPAMENTO] AS NM_EQP
		  ,	[DSC_PISTA_POUSO] AS PIS_PO
		  ,	[DSC_PISTA_DECOLAGEM] AS PIS_DE
		  ,	[DTH_PRI_MOV] AS HR_MOV_PRI
		  ,	[DTH_ULT_MOV] AS HR_MOV_ULT
		  ,	[DTH_ATUALIZACAO] AS DTH_ATUALIZACAO
		  ,	[FLG_STATUS] AS FL_STATUS
		  ,	[DTH_ULT_SAI_MOV] AS HR_MOV_ULT_SAI
		  ,	[TIP_STATUS] AS TP_STA
		  ,	[COD_STATUS_ANT] AS CD_STA_ANT
		  ,	[COD_STATUS_POS] AS CD_STA_POS
		  ,	[NME_PONTE] AS NM_PON
		  ,	[NUM_PORTAO] AS NR_POR
		  ,	[COD_VOO_PARTIDA] AS CD_PAR
		  ,	''' + @DATA + ''' AS DTH_MIGRACAO
		  ,	NULL AS FLG_MIGRADO
		  ,	NULL AS DTH_CARGA_SISO
	  FROM	IEOP.[dbo].[RPE_EMBARQUE] WITH (NOLOCK)
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 0
	   AND  DTH_MIGRACAO IS NULL;

	UPDATE	IEOP.[dbo].[RPE_DESEMBARQUE]
	   SET	FLG_MIGRADO = 1
		 ,  DTH_MIGRACAO = ''' + @DATA + '''
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 0
	   AND  DTH_MIGRACAO IS NULL;

	UPDATE	IEOP.[dbo].[RPE_EMBARQUE]
	   SET	FLG_MIGRADO = 1
		 ,  DTH_MIGRACAO = ''' + @DATA + '''
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 0
	   AND  DTH_MIGRACAO IS NULL;

END TRY

BEGIN CATCH
	DELETE
	  FROM	[' + @SIG_AEROPORTO + ' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RPE_DES]
	 WHERE  FLG_MIGRADO IS NULL
	   AND  DTH_CARGA_SISO IS NULL;

	DELETE
	  FROM	[' + @SIG_AEROPORTO + ' - INTEGRACAO].integracao.dbo.INTEGRACAO_IEOP_SISO_RPE_EMB
	 WHERE  FLG_MIGRADO IS NULL
	   AND  DTH_CARGA_SISO IS NULL;
 
	UPDATE	IEOP.[dbo].[RPE_DESEMBARQUE]
	   SET	FLG_MIGRADO = 0
		 ,  DTH_MIGRACAO = NULL
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 1
	   AND  DTH_MIGRACAO = ''' + @DATA + ''';

	UPDATE	IEOP.[dbo].[RPE_EMBARQUE]
	   SET	FLG_MIGRADO = 0
		 ,  DTH_MIGRACAO = NULL
	 WHERE  SIG_AEROPORTO = ''' + @SIG_AEROPORTO + '''
	   AND  FLG_MIGRADO = 1
	   AND  DTH_MIGRACAO = ''' + @DATA + ''';

END CATCH  
'
 EXECUTE (@SQL)
 --PRINT (@SQL)

 


/*

SELECT	*
--DELETE
  FROM	[SBJV - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RPE_DES]

SELECT	*
--DELETE
  FROM	[SBJV - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RPE_EMB]


SELECT	*
  FROM [IEOP].[dbo].[RPE_EMBARQUE]
 WHERE DTH_MIGRACAO IS NULL
   --AND SIG_AEROPORTO = 'SBRJ'

SELECT	*
  FROM [IEOP].[dbo].[RPE_DESEMBARQUE]
 WHERE DTH_MIGRACAO IS NULL
   --AND SIG_AEROPORTO = 'SBRJ'


UPDATE	IEOP.[dbo].[RPE_DESEMBARQUE]
   SET	FLG_MIGRADO = 0
     ,  DTH_MIGRACAO = NULL
 WHERE  SIG_AEROPORTO != 'SBRJ';

UPDATE	IEOP.[dbo].[RPE_EMBARQUE]
   SET	FLG_MIGRADO = 0
     ,  DTH_MIGRACAO = NULL
 WHERE  SIG_AEROPORTO != 'SBRJ';


 */