SET SERVEROUTPUT ON
DECLARE
	--CRIA CURSOR COM TODAS AS MATRICULAS COM STATUS 2(DESLIGADO).
	CURSOR C_MAT IS
	SELECT EMP_NUMERO_MATRICULA  
	FROM CADASTROS
	WHERE ROWNUM < 11;
	
BEGIN
FOR X IN C_MAT LOOP 
	DBMS_OUTPUT.PUT_LINE('ALTER USER I' || TRIM(TO_CHAR(X.EMP_NUMERO_MATRICULA, '0000000')) || ' ACCOUNT LOCK;');
END LOOP;
END;
/
