CREATE TABLE TESTE(
	CAMPO1 NUMBER(7)
,	CAMPO2 VARCHAR2(200)
,	CAMPO3 DATE
)
/

BEGIN
FOR X IN 1..1000000 LOOP 
	INSERT INTO TESTE VALUES(X,'KLJFDSÇFLDSÇFKÇLSDKFÇDSKÇLFSDÇLFÇLDSFLÇSDKÇFLDÇLLDFUIJHOTSDFMKVPLDKPFGSDKPO', TO_DATE('16/02/2005', 'DD/MM/YYYY'));
	COMMIT;
END LOOP;
END;
/
