CREATE TABLE IFRCORP.TB_LOG_IDM (
  ID_LOG_IDM NUMBER(8) NOT NULL,
  DT_LOG DATE NOT NULL,
  NO_PROCEDURE VARCHAR2(30) NOT NULL,
  DS_PROCEDURE VARCHAR2(3000) NOT NULL,
  NU_PROCEDURE_RESULTADO NUMBER(2) NULL,
  DS_PROCEDURE_RESULTADO VARCHAR2(500)
)

ALTER TABLE IFRCORP.TB_LOG_IDM ADD CONSTRAINT PK_TB_LOG_IDM PRIMARY KEY (ID_LOG_IDM)

CREATE PUBLIC SYNONYM TB_LOG_IDM FOR IFRCORP.TB_LOG_IDM;

CREATE SEQUENCE IFRCORP.SEQ_ID_LOG_IDM
INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  NOCACHE
/

CREATE PUBLIC SYNONYM SEQ_ID_LOG_IDM FOR IFRCORP.SEQ_ID_LOG_IDM;

CREATE OR REPLACE TRIGGER IFRCORP.TRG_SILI_I
 BEFORE
  INSERT
 ON IFRCORP.TB_LOG_IDM
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN SELECT SEQ_ID_LOG_IDM.NEXTVAL INTO :NEW.ID_LOG_IDM FROM DUAL; END;
/
