SET SERVEROUTPUT ON
DECLARE
	V_OK NUMBER;
BEGIN
	pck_usuario.PRC_VERIFICA_ROLES('DENIS', 'CONNECT', v_OK);
	DBMS_OUTPUT.PUT_LINE('Resultado: ' || TO_CHAR(V_OK));
END;
/


SET SERVEROUTPUT ON
DECLARE
	V_OK NUMBER;
BEGIN
	pck_usuario.PRC_VERIFICA_ROLES(0, 0, v_OK);
	DBMS_OUTPUT.PUT_LINE('Resultado: ' || TO_CHAR(V_OK));
END;
/
