ACCEPT USU CHAR PROMPT 'ENTRE COM O USUARIO: '

CREATE USER &USU IDENTIFIED BY INFRAERO;

GRANT CREATE SESSION TO &USU;

CREATE SYNONYM &USU..CAD_SISTEMA FOR SCA_OWNER.CAD_SISTEMA;
CREATE SYNONYM &USU..CAD_GRUPO FOR SCA_OWNER.CAD_GRUPO;
CREATE SYNONYM &USU..CAD_USUARIO FOR SCA_OWNER.CAD_USUARIO;
CREATE SYNONYM &USU..CAD_EMPRESA FOR SISA_OWNER.CAD_EMPRESA;
CREATE SYNONYM &USU..TAB_AREA FOR SISA_OWNER.TAB_AREA;
CREATE SYNONYM &USU..SEQ_EMPRESA FOR SISA_OWNER.SEQ_EMPRESA;
CREATE SYNONYM &USU..CAD_OCORRENCIA FOR SISA_OWNER.CAD_OCORRENCIA;
CREATE SYNONYM &USU..VIW_TABLE_NAME FOR SISA_OWNER.VIW_TABLE_NAME;
CREATE SYNONYM &USU.SEQ_STRUT_LOG FOR SISA_OWNER.SEQ_STRUT_LOG;
CREATE SYNONYM &USU..NEXTVAL_STRUT_LOG FOR SISA_OWNER.NEXTVAL_STRUT_LOG;
CREATE SYNONYM &USU..TAB_COLUMN_LOG FOR SISA_OWNER.TAB_COLUMN_LOG;
CREATE SYNONYM &USU..TAB_STRUT_LOG FOR SISA_OWNER.TAB_STRUT_LOG;
CREATE SYNONYM &USU..VIW_COLUMNS_TABLE FOR SISA_OWNER.VIW_COLUMNS_TABLE;
CREATE SYNONYM &USU..WRITEAPPEND_CLOB FOR  SISA_OWNER.WRITEAPPEND_CLOB;
CREATE SYNONYM &USU..WRITE_CLOB FOR SISA_OWNER.WRITE_CLOB;


GRANT RL_SCA_ADM,RL_SISA_ADM,RL_SISA1_ADM,RL_SISA2_ADM,RL_SISA3_ADM,RL_SCA_ADM_SA,
RL_SCA_PUBLIC,RL_SEDE_PUBLIC,RL_SISA123_ADM,RL_SISA_PUBLIC,RL_SISA1_PUBLIC,
RL_SISA2_PUBLIC,RL_SCA_PUBLIC_SA,RL_SISA123_PUBLIC,RL_SCA_ADM_DOMINIO TO &USU;