CREATE USER SYSAD IDENTIFIED BY VALUES '1CE61BCA266BAE09';

GRANT SELECT ON DBA_ROLES TO SYSAD;
GRANT SELECT ON DBA_OBJECTS TO SYSAD;
GRANT SELECT ON DBA_ROLE_PRIVS TO SYSAD;
GRANT SELECT ON DBA_SYNONYMS TO SYSAD;
GRANT SELECT ON DBA_TABLES TO SYSAD;
GRANT SELECT ON DBA_TAB_PRIVS TO SYSAD;
GRANT SELECT ON DBA_VIEWS TO SYSAD;
GRANT SELECT ON DBA_SOURCE TO SYSAD;
GRANT SELECT ON DBA_TRIGGERS TO SYSAD;
GRANT SELECT ON DBA_DEPENDENCIES TO SYSAD;
GRANT SELECT ON DBA_EXTENTS TO SYSAD;
GRANT SELECT ON DBA_TAB_COLUMNS TO SYSAD;
GRANT SELECT ON DBA_CONSTRAINTS TO SYSAD;

GRANT SELECT ANY SEQUENCE TO SYSAD;
GRANT EXECUTE ANY PROCEDURE TO SYSAD;
GRANT ALTER ANY PROCEDURE TO SYSAD;
GRANT CREATE ANY PROCEDURE TO SYSAD;

grant connect to sysad;


--*******************************************************************************
--PARA VISUALIZAR SOMENTE OS OBJETOS DO OWNER
--*******************************************************************************
GRANT SELECT ON DBA_OBJECTS_ENG TO eng_desenv;
GRANT SELECT ON DBA_SOURCE_ENG TO eng_desenv;
GRANT SELECT ON DBA_TRIGGERS_ENG TO eng_desenv;

REVOKE SELECT ON DBA_OBJECTS_ENG FROM eng_desenv;
REVOKE SELECT ON DBA_SOURCE_ENG FROM eng_desenv;
REVOKE SELECT ON DBA_TRIGGERS_ENG FROM eng_desenv;
