begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPRF_MOV_RECEBIMENTO', 'C' );
end;
/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPRF_MOV_FINANCEIRO', 'C' );
end;
/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPRF_MOV_ENTREGA', 'C' );
end;
/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPKP_MOV_RECEBIMENTO', 'C' );
end;
/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPKP_MOV_FINANCEIRO', 'C' );
end;
/

begin
DBMS_SNAPSHOT.REFRESH ( 'IFRTECA.TKPSANPKP_MOV_ENTREGA', 'C' );
end;
/
