Set Transaction Use Rollback  Segment Rb_Grande2
/
ALTER TABLE IFRMAXIMO.WORKORDER2 MOVE TABLESPACE TSD_SELO
/
ALTER INDEX SYSMAN.TEMP_MIGRACAO REBUILD TABLESPACE TSD_SELO ONLINE
/
Set Transaction Use Rollback  Segment Rb_Grande2
/
INSERT INTO WOHISTORICO
SELECT * FROM WORKORDER2
WHERE REPORTDATE < TO_DATE('01/01/2003', 'DD/MM/YYYY')
/
COMMIT;

SELECT COUNT(1) FROM WORKORDER2
WHERE REPORTDATE <= TO_DATE('01/01/2003', 'DD/MM/YYYY')
/

SELECT COUNT(1) FROM WORKORDER2
/
