
GRANT SELECT ON CARGOS TO SRH_BME;

GRANT SELECT ON FORMACOES_PROFISSIONAIS TO SRH_BME;

GRANT SELECT ON OCORRENCIAS_EMPREGADOS TO SRH_BME;

GRANT SELECT ON OCUPACOES_CARGO TO SRH_BME;

GRANT SELECT ON TRN_EVENTO TO SRH_BME;

GRANT SELECT ON TRN_EVENTO_PARTICIP TO SRH_BME;

GRANT SELECT ON UNIDADES_ORGANIZACIONAIS TO SRH_BME;

GRANT SELECT ON EMPREGADOS_FORMACOES TO SRH_BME;

GRANT SELECT ON CADASTROS TO SRH_BME;

GRANT SELECT ON OCORRENCIAS_FREQUENCIA_EMP TO SRH_BME;

GRANT SELECT ON TIPOS_OCORRENCIAS TO SRH_BME;

GRANT SELECT ON DEPENDENCIAS TO SRH_BME;

GRANT SELECT ON CARGOS_CONFIANCA TO SRH_BME;

GRANT SELECT ON TAB_QUALIFICACAO_ACADEMICA TO SRH_BME;

GRANT SELECT ON EMP_QUALIFICACAO_ACADEMICA TO SRH_BME;

GRANT SELECT ON PESSOAS_VINCULADAS TO SRH_BME;

GRANT SELECT ON TIPO_VINCULOS TO SRH_BME;

GRANT SELECT ON CATEGORIAS_FUNCOES_VALOR TO SRH_BME;

GRANT SELECT ON INDICES TO SRH_BME;

GRANT SELECT ON CONSTANTES_LEGAIS TO SRH_BME;

GRANT SELECT ON HISTORICO_NIVEIS_SALARIAIS TO SRH_BME;

GRANT SELECT ON SITUACOES_FUNCIONAIS TO SRH_BME;
