--incluir
grant rh_perfil_99 to I1190738;

grant SEG_GERAL to I1190738;

INSERT INTO ifrdba2.seg_usuario_sistema
(SU_ID_USUARIO,SS_CD_SISTEMA,SGU_CD_GRUPO,DS_USUARIO,ID_GERENTE_SISTEMA)
VALUES
('I1190738',10,11,NULL,'S')
/

INSERT INTO ifrdba2.seg_usuario_sistema
(SU_ID_USUARIO,SS_CD_SISTEMA,SGU_CD_GRUPO,DS_USUARIO,ID_GERENTE_SISTEMA)
VALUES
('I1190738',9,8,NULL,'S')
/

INSERT INTO ifrdba2.seg_usuario_sistema
(SU_ID_USUARIO,SS_CD_SISTEMA,SGU_CD_GRUPO,DS_USUARIO,ID_GERENTE_SISTEMA)
VALUES
('I1190738',5,4,NULL,'S')
/

INSERT INTO ifrdba2.seg_usuario_sistema
(SU_ID_USUARIO,SS_CD_SISTEMA,SGU_CD_GRUPO,DS_USUARIO,ID_GERENTE_SISTEMA)
VALUES
('I1190738',3,7,NULL,'S')
/


INSERT INTO ifrdba2.seg_usuario_sistema
(SU_ID_USUARIO,SS_CD_SISTEMA,SGU_CD_GRUPO,DS_USUARIO,ID_GERENTE_SISTEMA)
VALUES
('I1190738',11,1,NULL,'N')
/

INSERT INTO ifrdba2.seg_usuario_centro_custo
VALUES
('I1190738',3,20145,'S')
/
INSERT INTO ifrdba2.seg_usuario_centro_custo
VALUES
('I1190738',5,20145,'S')
/
INSERT INTO ifrdba2.seg_usuario_centro_custo
VALUES
('I1190738',9,20145,'S')
/
INSERT INTO ifrdba2.seg_usuario_centro_custo
VALUES
('I1190738',10,20145,'S')
/
INSERT INTO ifrdba2.seg_usuario_centro_custo
VALUES
('I1190738',11,20145,'S')
/

INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',1,'S',5,'S',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',2,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',3,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',4,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',5,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',6,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',7,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',8,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',9,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',10,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',11,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',12,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',13,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',14,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',15,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',16,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',17,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',18,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',19,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',20,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',21,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',22,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',23,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',24,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',25,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',26,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',27,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',28,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',29,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',30,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',31,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',32,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',33,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',34,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',35,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',36,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',37,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',38,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',39,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',40,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',41,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',42,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',43,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',44,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',45,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',46,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',47,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',48,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',49,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',50,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',51,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',52,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',53,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',54,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',55,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',56,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',57,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',58,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',59,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',60,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',61,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',62,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',63,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',64,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',65,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',66,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',67,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',68,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',69,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',70,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',71,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',72,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',73,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',74,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',75,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',76,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',77,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',78,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',79,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',80,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',81,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',82,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',83,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',84,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',85,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',86,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',87,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',88,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',89,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',90,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',91,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',92,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',93,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',94,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',95,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',96,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',97,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',98,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',99,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',100,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',101,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',102,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',103,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',104,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',105,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',106,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',107,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',108,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',109,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',110,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',111,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',112,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',113,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',114,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',115,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',116,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',117,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',118,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',119,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',120,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',121,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',122,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',123,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',124,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',125,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',126,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',127,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',128,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',129,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',130,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',131,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',132,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',133,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',134,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',135,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',136,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',137,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',138,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',139,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',140,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',141,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',142,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',143,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',144,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',145,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',146,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',147,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',148,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',149,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',150,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',151,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',152,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',153,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',154,'N',5,'N','QUINTA-FEIRA, 23 DE NOVEMBRO DE 2006','I9980851')
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',900,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',902,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',903,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',904,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',905,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',906,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',907,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',908,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',909,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',910,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',911,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',912,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',918,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',919,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',920,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',921,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',922,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',923,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',924,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',926,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',927,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',928,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',929,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',930,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',931,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',932,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',933,'N',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',934,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',935,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',936,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',937,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',938,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',939,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',940,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',941,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',942,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',943,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',944,'S',5,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',1,'N',10,'S',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',2,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',4,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',5,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',6,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',7,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',8,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',9,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',10,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',11,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',12,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',13,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',14,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',15,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',16,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',17,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',18,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',19,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',20,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',21,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',22,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',23,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',24,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',25,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',26,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',27,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',28,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',29,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',30,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',31,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',32,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',33,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',34,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',35,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',36,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',37,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',38,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',39,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',40,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',41,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',42,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',43,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',44,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',45,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',46,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',47,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',48,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',49,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',50,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',51,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',52,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',53,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',54,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',56,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',57,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',58,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',60,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',61,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',62,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',63,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',64,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',65,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',71,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',72,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',73,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',74,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',75,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',76,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',78,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',79,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',80,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',81,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',83,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',84,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',85,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',86,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',87,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',88,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',89,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',90,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',91,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',92,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',93,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',94,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',95,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',96,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',97,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',98,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',99,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',113,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',149,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',150,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',151,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',152,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',900,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',902,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',903,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',918,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',919,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',920,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',921,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',922,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',923,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',924,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',926,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',927,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',934,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',935,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',936,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',937,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',938,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',939,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',940,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',941,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',942,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',943,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',944,'N',10,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',1,'N',11,'S',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',2,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',4,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',5,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',6,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',7,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',8,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',9,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',10,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',11,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',12,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',13,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',14,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',15,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',16,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',17,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',18,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',19,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',20,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',21,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',22,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',23,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',24,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',25,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',26,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',27,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',28,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',29,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',30,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',31,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',32,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',33,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',34,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',35,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',36,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',37,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',38,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',39,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',40,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',41,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',42,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',43,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',44,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',45,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',46,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',47,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',48,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',49,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',50,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',51,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',52,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',53,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',54,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',56,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',57,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',58,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',60,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',61,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',62,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',63,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',64,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',65,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',71,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',72,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',73,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',74,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',75,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',76,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',78,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',79,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',80,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',81,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',83,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',84,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',85,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',86,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',87,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',88,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',89,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',90,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',91,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',92,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',93,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',94,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',95,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',96,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',97,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',98,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',99,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',113,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',117,'N',11,'N','QUINTA-FEIRA, 23 DE NOVEMBRO DE 2006','I9980851')
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',149,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',150,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',151,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',152,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',154,'N',11,'N','QUINTA-FEIRA, 23 DE NOVEMBRO DE 2006','I9980851')
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',901,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',902,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',903,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',918,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',919,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',920,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',921,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',922,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',923,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',924,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',926,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',927,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',934,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',935,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',936,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',937,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',938,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',939,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',940,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',941,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',942,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',943,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',944,'N',11,'N',NULL,NULL)
/
INSERT INTO ifrsrh.controle_usuario_dependencia
VALUES
('I1190738',1,'N',13,'S',NULL,NULL)
/


commit;

