Select 'ALTER ' || OBJECT_TYPE || ' ' || OWNER || '.' || OBJECT_NAME || ' COMPILE;' nl, 'SHOW ERROR'
FROM dba_objects
WHERE OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION', 'PACKAGE', 'TRIGGER', 'VIEW')
AND OWNER NOT IN ('SYS', 'SYSTEM', 'DISCOVERER')
and status = 'INVALID'
/

Select 'ALTER PACKAGE ' || OWNER || '.' || OBJECT_NAME || ' COMPILE BODY;' nl, 'SHOW ERROR'
FROM dba_objects
WHERE OBJECT_TYPE IN ('PACKAGE BODY')
AND OWNER NOT IN ('SYS', 'SYSTEM', 'DISCOVERER')
and status = 'INVALID'
/

/*
Select 'ALTER ' || OBJECT_TYPE || ' ' || OBJECT_NAME || ' COMPILE;'
FROM user_objects
WHERE OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION', 'PACKAGE', 'TRIGGER', 'VIEW')
and status = 'INVALID'
/

Select 'ALTER PACKAGE ' || OBJECT_NAME || ' COMPILE BODY;'
FROM user_objects
WHERE OBJECT_TYPE IN ('PACKAGE BODY')
and status = 'INVALID'
/

SELECT 'CREATE PUBLIC SYNONYM ' || TABLE_NAME || ' FOR ' || TABLE_OWNER || '.' || TABLE_NAME || ';'
FROM DBA_SYNONYMS
WHERE TABLE_OWNER = 'IFRCOE';

*/
