SELECT 'GRANT ' || PRIVILEGE || ' ON ' || TABLE_NAME || ' TO ' || DECODE(GRANTEE, 'IFRSRH2', 'IFRSRH', GRANTEE) || DECODE(GRANTABLE,'YES', ' WITH GRANT OPTION', ' ') ||';'
FROM DBA_TAB_PRIVS
WHERE OWNER = 'IFRDBA2'
/
