SQL> /

ALTER PROCEDURE IFRDBA2.PDC02_EQUIP_MOV COMPILE;                                                                        
ALTER PROCEDURE IFRDBA2.PDC03_EQUIP_MOV COMPILE;                                                                        
ALTER PROCEDURE IFRDBA2.PDC04_EVENTO_ATRASO COMPILE;                                                                    
ALTER PROCEDURE IFRDBA2.PRC_CONTA2 COMPILE;                                                                             
ALTER TRIGGER IFRDBA2.TRG_ASBP01 COMPILE;                                                                               
ALTER TRIGGER IFRDBA2.TRG_BDBP01 COMPILE;                                                                               
ALTER TRIGGER IFRDBA2.TRG_BP COMPILE;                                                                                   
ALTER TRIGGER IFRDBA2.TRG_IAT01 COMPILE;                                                                                
ALTER TRIGGER IFRDBA2.TRG_SMBP01 COMPILE;                                                                               
ALTER TRIGGER IFRDBA2.TRG_TBP01 COMPILE;                                                                                
ALTER TRIGGER IFRDBA2.TRG_VCBP01 COMPILE;                                                                               
ALTER PROCEDURE IFRDBA2.UP_INTDPB COMPILE;                                                                              
ALTER PROCEDURE IFRSGP.CPV_RT_BV_DEPV COMPILE;                                                                          
ALTER PROCEDURE IFRSRH.ALTERA_OCORRENCIAS COMPILE;                                                                      
ALTER PACKAGE IFRSRH.BENWEB02$STO COMPILE;                                                                              
ALTER PACKAGE IFRSRH.BENWEB05$ORE COMPILE;                                                                              
ALTER PACKAGE IFRSRH.BENWEB06$EMB COMPILE;                                                                              
ALTER PACKAGE IFRSRH.BENWEB07$ORV COMPILE;                                                                              
ALTER PACKAGE IFRSRH.BENWEB08$ORT COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB01$EMP COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB02$CADASTROS COMPILE;                                                                        
ALTER PACKAGE IFRSRH.CADWEB03$CAD COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB04$CADASTROS COMPILE;                                                                        
ALTER PACKAGE IFRSRH.CADWEB04$PENSIONISTAS COMPILE;                                                                     
ALTER PACKAGE IFRSRH.CADWEB06$ADM COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB07$FCO COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB07$PFE COMPILE;                                                                              
ALTER PACKAGE IFRSRH.CADWEB08$FERIAS_PROGRAMADAS COMPILE;                                                               
ALTER PACKAGE IFRSRH.CADWEB08$PFE COMPILE;                                                                              
ALTER PROCEDURE IFRSRH.FORMWEB01 COMPILE;                                                                               
ALTER PROCEDURE IFRSRH.FORMWEB02 COMPILE;                                                                               
ALTER PROCEDURE IFRSRH.FORMWEB03 COMPILE;                                                                               
ALTER PROCEDURE IFRSRH.FORMWEB04 COMPILE;                                                                               
ALTER PROCEDURE IFRSRH.FORMWEB05 COMPILE;                                                                               
ALTER PROCEDURE IFRSRH.FORMWEB07 COMPILE;                                                                               
ALTER TRIGGER IFRSRH.LOG_ATIVIDADES_CARGOS COMPILE;                                                                     
ALTER PROCEDURE IFRSRH.VALIDA_OCORRENCIAS COMPILE;                                                                      
ALTER PROCEDURE IFRSRH.VALIDA_OCORRENCIAS_AFASTAMENTO COMPILE;                                                          
ALTER PROCEDURE IFRSRH.VALIDA_OCORRENCIAS_FREQUENCIA COMPILE;                                                           
ALTER PROCEDURE IFR_DESENV.TESTADATA COMPILE;                                                                           
ALTER PROCEDURE IFR_DESENV.TESTADATATYA COMPILE;                                                                        
ALTER FUNCTION IFRVGA.FC_APLSEG_COD_SITUAC_SGS COMPILE;                                                                 
ALTER FUNCTION IFRVGA.FC_ESPCSG_COD_SITUAC_SGS COMPILE;                                                                 
ALTER FUNCTION IFRVGA.FC_OCRRNC_COD_SITUAC_SGS COMPILE;                                                                 
ALTER TRIGGER IFRMAXIMO2.LABTRANS_T COMPILE;                                                                            
ALTER TRIGGER IFRMAXIMO2.MATUSETRANS_T COMPILE;                                                                         

46 linhas selecionadas.

SQL> spo off
