SELECT * FROM EQUIPE_TI WHERE SELECT * FROM EQUIPE_TI WHERE NOM_EQUIPE_TI like 'TISI%'

SELECT * FROM ITEM_CONFIGURACAO

SELECT C.SEQ_CHAMADO, I.NOM_ITEM_CONFIGURACAO
FROM CHAMADO C
INNER JOIN ITEM_CONFIGURACAO I
ON (C.SEQ_ITEM_CONFIGURACAO = I.SEQ_ITEM_CONFIGURACAO)

-- Chamados abertos antes do ciclo e encerrados no ciclo ---

SELECT E.NOM_EQUIPE_TI,I.NOM_ITEM_CONFIGURACAO,COUNT(*)
FROM ATRIBUICAO_CHAMADO A 
INNER JOIN EQUIPE_TI E 
ON (A.SEQ_EQUIPE_TI = E.SEQ_EQUIPE_TI)
INNER JOIN CHAMADO C
ON (A.SEQ_CHAMADO = C.SEQ_CHAMADO)
LEFT OUTER JOIN ITEM_CONFIGURACAO I
ON (C.SEQ_ITEM_CONFIGURACAO = I.SEQ_ITEM_CONFIGURACAO)
WHERE NOM_EQUIPE_TI like 'TISI-1%' and
A.DTH_ATRIBUICAO < '19/03/2011' and
( A.DTH_ENCERRAMENTO_EFETIVO >= '19/03/2011')-- or A.DTH_ENCERRAMENTO_EFETIVO is null)
GROUP BY E.NOM_EQUIPE_TI,I.NOM_ITEM_CONFIGURACAO
ORDER BY E.NOM_EQUIPE_TI

-- Chamados abertos no ciclo e encerrados no ciclo ---
SELECT E.NOM_EQUIPE_TI,I.SIG_ITEM_CONFIGURACAO,COUNT(*)
FROM ATRIBUICAO_CHAMADO A 
INNER JOIN EQUIPE_TI E 
ON (A.SEQ_EQUIPE_TI = E.SEQ_EQUIPE_TI)
INNER JOIN CHAMADO C
ON (A.SEQ_CHAMADO = C.SEQ_CHAMADO)
LEFT OUTER JOIN ITEM_CONFIGURACAO I
ON (C.SEQ_ITEM_CONFIGURACAO = I.SEQ_ITEM_CONFIGURACAO)
WHERE NOM_EQUIPE_TI like 'TISI-1%' and
A.DTH_ATRIBUICAO >= '19/03/2011' --and
--A.DTH_ENCERRAMENTO_EFETIVO is not null
GROUP BY E.NOM_EQUIPE_TI,I.SIG_ITEM_CONFIGURACAO
ORDER BY E.NOM_EQUIPE_TI


-- Chamados abertos 
SELECT E.NOM_EQUIPE_TI,I.NOM_ITEM_CONFIGURACAO,COUNT(*)
FROM ATRIBUICAO_CHAMADO A 
INNER JOIN EQUIPE_TI E 
ON (A.SEQ_EQUIPE_TI = E.SEQ_EQUIPE_TI)
INNER JOIN CHAMADO C
ON (A.SEQ_CHAMADO = C.SEQ_CHAMADO)
LEFT OUTER JOIN ITEM_CONFIGURACAO I
ON (C.SEQ_ITEM_CONFIGURACAO = I.SEQ_ITEM_CONFIGURACAO)
WHERE NOM_EQUIPE_TI like 'TISI-1%' and
A.DTH_ENCERRAMENTO_EFETIVO is null 
and A.DTH_ATRIBUICAO < '22/04/2011'
GROUP BY E.NOM_EQUIPE_TI,I.NOM_ITEM_CONFIGURACAO
ORDER BY E.NOM_EQUIPE_TI
