USE [integracao]
GO

/****** Object:  Table [dbo].[INTEGRACAO_IEOP_SISO_RSO]    Script Date: 07/16/2014 10:50:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[INTEGRACAO_IEOP_SISO_RSO](
	[CD_RSO] [int] IDENTITY(1,1) NOT NULL,
	[MES_ANO] [int] NOT NULL,
	[SG_AER] [char](4) NOT NULL,
	[DH_GRAVAR] [smalldatetime] NOT NULL,
	[NM_PES] [nchar](40) NOT NULL,
	[DT_MIGRACAO] [smalldatetime] NULL,
	[FL_MIGRACAO] [nchar](1) NULL
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[INTEGRACAO_SISO_IEOP_RSO](
	[CD_RSO] [int] IDENTITY(1,1) NOT NULL,
	[MES_ANO] [smalldatetime] NOT NULL,
	[SG_AER] [char](4) NOT NULL,
	[CD_TIPO] [int] NOT NULL,
	[REGULAR_ORI_DOM] [int] NULL,
	[REGULAR_ORI_INT] [int] NULL,
	[REGULAR_DES_DOM] [int] NULL,
	[REGULAR_DES_INT] [int] NULL,
	[REGULAR_SOMA_DOM] [int] NULL,
	[REGULAR_SOMA_INT] [int] NULL,
	[REGULAR_TRANSI_DOM] [int] NULL,
	[REGULAR_TRANSI_INT] [int] NULL,
	[REGULAR_CNX_ORI_DOM] [int] NULL,
	[REGULAR_CNX_ORI_INT] [int] NULL,
	[REGULAR_CNX_DES_DOM] [int] NULL,
	[REGULAR_CNX_DES_INT] [int] NULL,
	[REGIONAL_ORI_DOM] [int] NULL,
	[REGIONAL_ORI_INT] [int] NULL,
	[REGIONAL_DES_DOM] [int] NULL,
	[REGIONAL_DES_INT] [int] NULL,
	[REGIONAL_SOMA_DOM] [int] NULL,
	[REGIONAL_SOMA_INT] [int] NULL,
	[REGIONAL_TRANSI_DOM] [int] NULL,
	[REGIONAL_TRANSI_INT] [int] NULL,
	[REGIONAL_CNX_ORI_DOM] [int] NULL,
	[REGIONAL_CNX_ORI_INT] [int] NULL,
	[REGIONAL_CNX_DES_DOM] [int] NULL,
	[REGIONAL_CNX_DES_INT] [int] NULL,
	[CHARTER_ORI_DOM] [int] NULL,
	[CHARTER_ORI_INT] [int] NULL,
	[CHARTER_DES_DOM] [int] NULL,
	[CHARTER_DES_INT] [int] NULL,
	[CHARTER_SOMA_DOM] [int] NULL,
	[CHARTER_SOMA_INT] [int] NULL,
	[CHARTER_TRANSI_DOM] [int] NULL,
	[CHARTER_TRANSI_INT] [int] NULL,
	[CHARTER_CNX_ORI_DOM] [int] NULL,
	[CHARTER_CNX_ORI_INT] [int] NULL,
	[CHARTER_CNX_DES_DOM] [int] NULL,
	[CHARTER_CNX_DES_INT] [int] NULL,
	[TAXI_ORI_DOM] [int] NULL,
	[TAXI_ORI_INT] [int] NULL,
	[TAXI_DES_DOM] [int] NULL,
	[TAXI_DES_INT] [int] NULL,
	[TAXI_SOMA_DOM] [int] NULL,
	[TAXI_SOMA_INT] [int] NULL,
	[TAXI_TRANSI_DOM] [int] NULL,
	[TAXI_TRANSI_INT] [int] NULL,
	[TAXI_CNX_ORI_DOM] [int] NULL,
	[TAXI_CNX_ORI_INT] [int] NULL,
	[TAXI_CNX_DES_DOM] [int] NULL,
	[TAXI_CNX_DES_INT] [int] NULL,
	[TRANS_ORI_DOM] [int] NULL,
	[TRANS_ORI_INT] [int] NULL,
	[TRANS_DES_DOM] [int] NULL,
	[TRANS_DES_INT] [int] NULL,
	[TRANS_SOMA_DOM] [int] NULL,
	[TRANS_SOMA_INT] [int] NULL,
	[OUTROS_ORI_DOM] [int] NULL,
	[OUTROS_ORI_INT] [int] NULL,
	[OUTROS_DES_DOM] [int] NULL,
	[OUTROS_DES_INT] [int] NULL,
	[OUTROS_SOMA_DOM] [int] NULL,
	[OUTROS_SOMA_INT] [int] NULL,
	[OUTROS_TRANSI_DOM] [int] NULL,
	[OUTROS_TRANSI_INT] [int] NULL,
	[OUTROS_CNX_ORI_DOM] [int] NULL,
	[OUTROS_CNX_ORI_INT] [int] NULL,
	[OUTROS_CNX_DES_DOM] [int] NULL,
	[OUTROS_CNX_DES_INT] [int] NULL,
	[SOMA_ORI_INT] [int] NULL,
	[SOMA_ORI_DOM] [int] NULL,
	[SOMA_DES_DOM] [int] NULL,
	[SOMA_DES_INT] [int] NULL,
	[SOMA_SOMA_DOM] [int] NULL,
	[SOMA_SOMA_INT] [int] NULL,
	[SOMA_TRANSI_DOM] [int] NULL,
	[SOMA_TRANSI_INT] [int] NULL,
	[SOMA_CNX_ORI_DOM] [int] NULL,
	[SOMA_CNX_ORI_INT] [int] NULL,
	[SOMA_CNX_DES_DOM] [int] NULL,
	[SOMA_CNX_DES_INT] [int] NULL,
	[MIL_ORI_INT] [int] NULL,
	[MIL_ORI_DOM] [int] NULL,
	[MIL_DES_DOM] [int] NULL,
	[MIL_DES_INT] [int] NULL,
	[MIL_SOMA_DOM] [int] NULL,
	[MIL_SOMA_INT] [int] NULL,
	[MIL_TRANSI_DOM] [int] NULL,
	[MIL_TRANSI_INT] [int] NULL,
	[HELIC_ORI_INT] [int] NULL,
	[HELIC_ORI_DOM] [int] NULL,
	[HELIC_DES_DOM] [int] NULL,
	[HELIC_DES_INT] [int] NULL,
	[HELIC_SOMA_DOM] [int] NULL,
	[HELIC_SOMA_INT] [int] NULL,
	[HELIC_TRANSI_DOM] [int] NULL,
	[HELIC_TRANSI_INT] [int] NULL,
	[CABO_ORI_REG] [int] NULL,
	[CABO_DES_REG] [int] NULL,
	[CABO_SOMA_REG] [int] NULL,
	[CABO_CNX_DES_REG] [int] NULL,
	[CABO_CNX_ORI_REG] [int] NULL,
	[CABO_ORI_NREG] [int] NULL,
	[CABO_DES_NREG] [int] NULL,
	[CABO_SOMA_NREG] [int] NULL,
	[CABO_CNX_DES_NREG] [int] NULL,
	[CABO_CNX_ORI_NREG] [int] NULL,
	[CARGA_ORI_REG_INT] [int] NULL,
	[CARGA_DES_REG_INT] [int] NULL,
	[CARGA_SOMA_REG_INT] [int] NULL,
	[CARGA_ORI_REG_DOM] [int] NULL,
	[CARGA_DES_REG_DOM] [int] NULL,
	[CARGA_SOMA_REG_DOM] [int] NULL,
	[CARGA_ORI_NREG_INT] [int] NULL,
	[CARGA_DES_NREG_INT] [int] NULL,
	[CARGA_SOMA_NREG_INT] [int] NULL,
	[CARGA_ORI_NREG_DOM] [int] NULL,
	[CARGA_DES_NREG_DOM] [int] NULL,
	[CARGA_SOMA_NREG_DOM] [int] NULL,
	[SOMA_ORI_TOT] [int] NULL,
	[SOMA_DES_TOT] [int] NULL,
	[SOMA_SOMA_TOT] [int] NULL,
	[SOMA_TRANSI_TOT] [int] NULL,
	[SOMA_CNX_ORI_TOT] [int] NULL,
	[SOMA_CNX_DES_TOT] [int] NULL,
	[DT_MIGRACAO] [smalldatetime] NULL,
	[FL_MIGRACAO] [nchar](1) NULL,
 CONSTRAINT [PK_INTEGRACAO_SISO_IEOP_RSO] PRIMARY KEY CLUSTERED 
(
	[MES_ANO] ASC,
	[CD_TIPO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


--MIGRAÇÃO
/*--S-SEBN111

INSERT INTO [dbo].[INTEGRACAO_IEOP_SISO_RSO]
SELECT [MES_ANO]
      ,[SG_AER]
      ,[DH_GRAVAR]
      ,[NM_PES]
      ,[DT_MIGRACAO]
      ,[FL_MIGRACAO]
  FROM	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] WITH (NOLOCK)


INSERT INTO [dbo].[INTEGRACAO_SISO_IEOP_RSO]
SELECT	    [MES_ANO]
		,	[SG_AER]
		,	[CD_TIPO]
		,	[REGULAR_ORI_DOM]
		,	[REGULAR_ORI_INT]
		,	[REGULAR_DES_DOM]
		,	[REGULAR_DES_INT]
		,	[REGULAR_SOMA_DOM]
		,	[REGULAR_SOMA_INT]
		,	[REGULAR_TRANSI_DOM]
		,	[REGULAR_TRANSI_INT]
		,	[REGULAR_CNX_ORI_DOM]
		,	[REGULAR_CNX_ORI_INT]
		,	[REGULAR_CNX_DES_DOM]
		,	[REGULAR_CNX_DES_INT]
		,	[REGIONAL_ORI_DOM]
		,	[REGIONAL_ORI_INT]
		,	[REGIONAL_DES_DOM]
		,	[REGIONAL_DES_INT]
		,	[REGIONAL_SOMA_DOM]
		,	[REGIONAL_SOMA_INT]
		,	[REGIONAL_TRANSI_DOM]
		,	[REGIONAL_TRANSI_INT]
		,	[REGIONAL_CNX_ORI_DOM]
		,	[REGIONAL_CNX_ORI_INT]
		,	[REGIONAL_CNX_DES_DOM]
		,	[REGIONAL_CNX_DES_INT]
		,	[CHARTER_ORI_DOM]
		,	[CHARTER_ORI_INT]
		,	[CHARTER_DES_DOM]
		,	[CHARTER_DES_INT]
		,	[CHARTER_SOMA_DOM]
		,	[CHARTER_SOMA_INT]
		,	[CHARTER_TRANSI_DOM]
		,	[CHARTER_TRANSI_INT]
		,	[CHARTER_CNX_ORI_DOM]
		,	[CHARTER_CNX_ORI_INT]
		,	[CHARTER_CNX_DES_DOM]
		,	[CHARTER_CNX_DES_INT]
		,	[TAXI_ORI_DOM]
		,	[TAXI_ORI_INT]
		,	[TAXI_DES_DOM]
		,	[TAXI_DES_INT]
		,	[TAXI_SOMA_DOM]
		,	[TAXI_SOMA_INT]
		,	[TAXI_TRANSI_DOM]
		,	[TAXI_TRANSI_INT]
		,	[TAXI_CNX_ORI_DOM]
		,	[TAXI_CNX_ORI_INT]
		,	[TAXI_CNX_DES_DOM]
		,	[TAXI_CNX_DES_INT]
		,	[TRANS_ORI_DOM]
		,	[TRANS_ORI_INT]
		,	[TRANS_DES_DOM]
		,	[TRANS_DES_INT]
		,	[TRANS_SOMA_DOM]
		,	[TRANS_SOMA_INT]
		,	[OUTROS_ORI_DOM]
		,	[OUTROS_ORI_INT]
		,	[OUTROS_DES_DOM]
		,	[OUTROS_DES_INT]
		,	[OUTROS_SOMA_DOM]
		,	[OUTROS_SOMA_INT]
		,	[OUTROS_TRANSI_DOM]
		,	[OUTROS_TRANSI_INT]
		,	[OUTROS_CNX_ORI_DOM]
		,	[OUTROS_CNX_ORI_INT]
		,	[OUTROS_CNX_DES_DOM]
		,	[OUTROS_CNX_DES_INT]
		,	[SOMA_ORI_INT]
		,	[SOMA_ORI_DOM]
		,	[SOMA_DES_DOM]
		,	[SOMA_DES_INT]
		,	[SOMA_SOMA_DOM]
		,	[SOMA_SOMA_INT]
		,	[SOMA_TRANSI_DOM]
		,	[SOMA_TRANSI_INT]
		,	[SOMA_CNX_ORI_DOM]
		,	[SOMA_CNX_ORI_INT]
		,	[SOMA_CNX_DES_DOM]
		,	[SOMA_CNX_DES_INT]
		,	[MIL_ORI_INT]
		,	[MIL_ORI_DOM]
		,	[MIL_DES_DOM]
		,	[MIL_DES_INT]
		,	[MIL_SOMA_DOM]
		,	[MIL_SOMA_INT]
		,	[MIL_TRANSI_DOM]
		,	[MIL_TRANSI_INT]
		,	[HELIC_ORI_INT]
		,	[HELIC_ORI_DOM]
		,	[HELIC_DES_DOM]
		,	[HELIC_DES_INT]
		,	[HELIC_SOMA_DOM]
		,	[HELIC_SOMA_INT]
		,	[HELIC_TRANSI_DOM]
		,	[HELIC_TRANSI_INT]
		,	[CABO_ORI_REG]
		,	[CABO_DES_REG]
		,	[CABO_SOMA_REG]
		,	[CABO_CNX_DES_REG]
		,	[CABO_CNX_ORI_REG]
		,	[CABO_ORI_NREG]
		,	[CABO_DES_NREG]
		,	[CABO_SOMA_NREG]
		,	[CABO_CNX_DES_NREG]
		,	[CABO_CNX_ORI_NREG]
		,	[CARGA_ORI_REG_INT]
		,	[CARGA_DES_REG_INT]
		,	[CARGA_SOMA_REG_INT]
		,	[CARGA_ORI_REG_DOM]
		,	[CARGA_DES_REG_DOM]
		,	[CARGA_SOMA_REG_DOM]
		,	[CARGA_ORI_NREG_INT]
		,	[CARGA_DES_NREG_INT]
		,	[CARGA_SOMA_NREG_INT]
		,	[CARGA_ORI_NREG_DOM]
		,	[CARGA_DES_NREG_DOM]
		,	[CARGA_SOMA_NREG_DOM]
		,	[SOMA_ORI_TOT]
		,	[SOMA_DES_TOT]
		,	[SOMA_SOMA_TOT]
		,	[SOMA_TRANSI_TOT]
		,	[SOMA_CNX_ORI_TOT]
		,	[SOMA_CNX_DES_TOT]
		,	[DT_MIGRACAO]
		,	[FL_MIGRACAO]
FROM	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO] WITH (NOLOCK)
*/

--ALTERAÇÃO BASE TESTES
/* --S-SEBN111
USE [integracao]
GO

UPDATE [dbo].[INTEGRACAO_IEOP_SISO_RSO]
   SET [DH_GRAVAR] = '20140716 11:00'
      ,[NM_PES] = 'DENIS TESTE'
      ,[DT_MIGRACAO] = NULL
      ,[FL_MIGRACAO] = NULL
 WHERE [MES_ANO] IN ('20140101', '20140201', '20140301', '20140401', '20140501', '20140601')


UPDATE [dbo].[INTEGRACAO_SISO_IEOP_RSO]
   SET [DT_MIGRACAO] = NULL
      ,[FL_MIGRACAO] = NULL
 WHERE [MES_ANO] IN ('20140101', '20140201', '20140301', '20140401', '20140501', '20140601')

GO


-CARGA BANCO DESENV
/* --DESENV
USE IEOP


TRUNCATE TABLE IEOP.dbo.INTEGRACAO_IEOP_SISO_RSO_CENTRAL 

INSERT INTO IEOP.dbo.INTEGRACAO_IEOP_SISO_RSO_CENTRAL 
SELECT	*
  FROM	[S-SEBN111].IEOP.dbo.INTEGRACAO_IEOP_SISO_RSO_CENTRAL SEDE WITH (NOLOCK)

TRUNCATE TABLE IEOP.dbo.INTEGRACAO_SISO_IEOP_RSO_CENTRAL 

INSERT INTO IEOP.dbo.INTEGRACAO_SISO_IEOP_RSO_CENTRAL 
SELECT	*
  FROM	[S-SEBN111].IEOP.dbo.INTEGRACAO_SISO_IEOP_RSO_CENTRAL SEDE WITH (NOLOCK)


UPDATE [IEOP].[dbo].[INTEGRACAO_IEOP_SISO_RSO_CENTRAL] SET [DT_PROG_MIGRACAO] = GETDATE() WHERE [MES_ANO] = '20141301' AND [SG_AER] = 'SBAR'


*/




*/