
DECLARE @MES_ANO VARCHAR(10)
      , @SG_AER VARCHAR(4)
	  , @CD_RSO INT
      ,	@DH_GRAVAR SMALLDATETIME
      ,	@NM_PES VARCHAR(40)
      , @FL_REPORCESSA TINYINT
	  , @MES_ANO_REP VARCHAR(10)

SELECT	@FL_REPORCESSA = 1
     ,  @MES_ANO = SEDE.MES_ANO
	 ,  @SG_AER = SEDE.SG_AER
	 ,  @NM_PES = SEDE.NM_PES
FROM	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL SEDE WITH (NOLOCK)
WHERE	SEDE.FL_MIGRACAO = 'R'
  AND   SEDE.DT_PROG_MIGRACAO <= GETDATE()
  AND   SEDE.SG_AER = 'SBAR';

IF (@FL_REPORCESSA = 1) BEGIN
	BEGIN TRY
		UPDATE [SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO]  
		   SET FL_MIGRACAO = 'R'
			 , DT_MIGRACAO = '20140716 09:21:54'
			 , NM_PES = @NM_PES
		 WHERE FL_MIGRACAO = 'S'
		   AND MES_ANO =  @MES_ANO

		UPDATE	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL
		   SET	DT_MIGRACAO = '20140716 09:21:54' 
			 ,	FL_MIGRACAO = 'C'
		WHERE	MES_ANO = @MES_ANO
		  AND   SG_AER = @SG_AER 
		  AND	FL_MIGRACAO = 'R'
    END TRY

	BEGIN CATCH
		PRINT 'REPROCESSAMENTO: ERRO AO ATUALIZAR STATUS -> AEROPORTO: SBAR'
	END CATCH
END;

SELECT	   @MES_ANO = SEDE.MES_ANO
		,  @SG_AER = SEDE.SG_AER
FROM	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL SEDE WITH (NOLOCK)
WHERE	SEDE.FL_MIGRACAO IS NULL
	AND   SEDE.DT_PROG_MIGRACAO <= GETDATE()
	AND   SEDE.SG_AER = 'SBAR';

IF (@MES_ANO = '20141301') BEGIN
   --APAGA OS MESES 01,02,03,04,05,06
   PRINT 'APAGA OS MESES 01,02,03,04,05,06' + CHAR(10) + CHAR(13)
   	DELETE
	FROM	IEOP..INTEGRACAO_SISO_IEOP_RSO_CENTRAL
	WHERE	MES_ANO IN ('20140101', '20140201', '20140301', '20140401','20140501','20140601')
	  AND   SG_AER = @SG_AER    

	SELECT @MES_ANO_REP = @MES_ANO
END 
ELSE IF (@MES_ANO = '20141401') BEGIN
	--APAGA OS MESES 01,02,03,04,05,06,07,08,09,10,11,12
	PRINT 'APAGA OS MESES 01,02,03,04,05,06,07,08,09,10,11,12' + CHAR(10) + CHAR(13)
	DELETE
	FROM	IEOP..INTEGRACAO_SISO_IEOP_RSO_CENTRAL
	WHERE	MES_ANO IN ('20140101', '20140201', '20140301', '20140401','20140501','20140601'
	                    '20140101', '20140201', '20140301', '20140401','20140501','20140601')
	  AND   SG_AER = @SG_AER    

	SELECT @MES_ANO_REP = @MES_ANO
	SELECT @MES_ANO_REP = @MES_ANO
END;

SET @MES_ANO = NULL;
SET @SG_AER = NULL;
SET @NM_PES = NULL;

--TRANSFORMAR EM CURSOR
DECLARE C_AEROP CURSOR FOR
SELECT	MES_ANO = AER.MES_ANO
     ,	SG_AER = LTRIM(RTRIM(AER.SG_AER))
FROM	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] AER WITH (NOLOCK)
    ,	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL SEDE WITH (NOLOCK)
WHERE	LTRIM(RTRIM(AER.SG_AER)) = SEDE.SG_AER COLLATE SQL_Latin1_General_CP1_CI_AI
  --AND   AER.MES_ANO = SEDE.MES_ANO ---LINHA COMENTADA ---RETIRAR
  AND   AER.FL_MIGRACAO IS NULL 
  AND   (SEDE.FL_MIGRACAO IS NULL OR SEDE.FL_MIGRACAO = 'R' OR SEDE.FL_MIGRACAO = 'C')
  AND   SEDE.DT_PROG_MIGRACAO <= GETDATE()
  AND   SEDE.SG_AER = 'SBAR' --LINHA ADICIONADA

--ABRE CURSOR DE AEROPORTOS E POSICIONA NA PRIMEIRA POSICAO
OPEN C_AEROP
FETCH NEXT FROM C_AEROP 
INTO @MES_ANO
,    @SG_AER

DECLARE @TXT VARCHAR(4000)

--CURSOR PARA RECUPERAR OS AEROPORTOS E CONSOLIDAR OS DADOS DE PASSAGEIROS.
WHILE @@FETCH_STATUS = 0
BEGIN

    SELECT  @TXT = 'O AEROPORTO ' + @SG_AER + ' PARA O MÊS: ' + CONVERT(VARCHAR(20), @MES_ANO) + CHAR(10) + CHAR(13)

	PRINT @TXT
		IF (@MES_ANO IS NOT NULL) BEGIN
			UPDATE  IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL 
			   SET  DT_MIGRACAO = NULL
				 ,  FL_MIGRACAO = NULL
			WHERE	MES_ANO = @MES_ANO
			  AND   SG_AER = @SG_AER 
			  AND	FL_MIGRACAO IS NOT NULL

			DELETE
			  FROM	IEOP..INTEGRACAO_SISO_IEOP_RSO_CENTRAL
			 WHERE	MES_ANO = @MES_ANO
			   AND  SG_AER = @SG_AER    
			   AND	FL_MIGRACAO IS NOT NULL

			BEGIN TRY

			INSERT INTO IEOP..INTEGRACAO_SISO_IEOP_RSO_CENTRAL
			SELECT	[CD_RSO] 
					,	CONVERT(VARCHAR(8), [MES_ANO], 112) MES_ANO
					,	[SG_AER]
					,	[CD_TIPO]
					,	[REGULAR_ORI_DOM]
					,	[REGULAR_ORI_INT]
					,	[REGULAR_DES_DOM]
					,	[REGULAR_DES_INT]
					,	[REGULAR_SOMA_DOM]
					,	[REGULAR_SOMA_INT]
					,	[REGULAR_TRANSI_DOM]
					,	[REGULAR_TRANSI_INT]
					,	[REGULAR_CNX_ORI_DOM]
					,	[REGULAR_CNX_ORI_INT]
					,	[REGULAR_CNX_DES_DOM]
					,	[REGULAR_CNX_DES_INT]
					,	[REGIONAL_ORI_DOM]
					,	[REGIONAL_ORI_INT]
					,	[REGIONAL_DES_DOM]
					,	[REGIONAL_DES_INT]
					,	[REGIONAL_SOMA_DOM]
					,	[REGIONAL_SOMA_INT]
					,	[REGIONAL_TRANSI_DOM]
					,	[REGIONAL_TRANSI_INT]
					,	[REGIONAL_CNX_ORI_DOM]
					,	[REGIONAL_CNX_ORI_INT]
					,	[REGIONAL_CNX_DES_DOM]
					,	[REGIONAL_CNX_DES_INT]
					,	[CHARTER_ORI_DOM]
					,	[CHARTER_ORI_INT]
					,	[CHARTER_DES_DOM]
					,	[CHARTER_DES_INT]
					,	[CHARTER_SOMA_DOM]
					,	[CHARTER_SOMA_INT]
					,	[CHARTER_TRANSI_DOM]
					,	[CHARTER_TRANSI_INT]
					,	[CHARTER_CNX_ORI_DOM]
					,	[CHARTER_CNX_ORI_INT]
					,	[CHARTER_CNX_DES_DOM]
					,	[CHARTER_CNX_DES_INT]
					,	[TAXI_ORI_DOM]
					,	[TAXI_ORI_INT]
					,	[TAXI_DES_DOM]
					,	[TAXI_DES_INT]
					,	[TAXI_SOMA_DOM]
					,	[TAXI_SOMA_INT]
					,	[TAXI_TRANSI_DOM]
					,	[TAXI_TRANSI_INT]
					,	[TAXI_CNX_ORI_DOM]
					,	[TAXI_CNX_ORI_INT]
					,	[TAXI_CNX_DES_DOM]
					,	[TAXI_CNX_DES_INT]
					,	[TRANS_ORI_DOM]
					,	[TRANS_ORI_INT]
					,	[TRANS_DES_DOM]
					,	[TRANS_DES_INT]
					,	[TRANS_SOMA_DOM]
					,	[TRANS_SOMA_INT]
					,	[OUTROS_ORI_DOM]
					,	[OUTROS_ORI_INT]
					,	[OUTROS_DES_DOM]
					,	[OUTROS_DES_INT]
					,	[OUTROS_SOMA_DOM]
					,	[OUTROS_SOMA_INT]
					,	[OUTROS_TRANSI_DOM]
					,	[OUTROS_TRANSI_INT]
					,	[OUTROS_CNX_ORI_DOM]
					,	[OUTROS_CNX_ORI_INT]
					,	[OUTROS_CNX_DES_DOM]
					,	[OUTROS_CNX_DES_INT]
					,	[SOMA_ORI_INT]
					,	[SOMA_ORI_DOM]
					,	[SOMA_DES_DOM]
					,	[SOMA_DES_INT]
					,	[SOMA_SOMA_DOM]
					,	[SOMA_SOMA_INT]
					,	[SOMA_TRANSI_DOM]
					,	[SOMA_TRANSI_INT]
					,	[SOMA_CNX_ORI_DOM]
					,	[SOMA_CNX_ORI_INT]
					,	[SOMA_CNX_DES_DOM]
					,	[SOMA_CNX_DES_INT]
					,	[MIL_ORI_INT]
					,	[MIL_ORI_DOM]
					,	[MIL_DES_DOM]
					,	[MIL_DES_INT]
					,	[MIL_SOMA_DOM]
					,	[MIL_SOMA_INT]
					,	[MIL_TRANSI_DOM]
					,	[MIL_TRANSI_INT]
					,	[HELIC_ORI_INT]
					,	[HELIC_ORI_DOM]
					,	[HELIC_DES_DOM]
					,	[HELIC_DES_INT]
					,	[HELIC_SOMA_DOM]
					,	[HELIC_SOMA_INT]
					,	[HELIC_TRANSI_DOM]
					,	[HELIC_TRANSI_INT]
					,	[CABO_ORI_REG]
					,	[CABO_DES_REG]
					,	[CABO_SOMA_REG]
					,	[CABO_CNX_DES_REG]
					,	[CABO_CNX_ORI_REG]
					,	[CABO_ORI_NREG]
					,	[CABO_DES_NREG]
					,	[CABO_SOMA_NREG]
					,	[CABO_CNX_DES_NREG]
					,	[CABO_CNX_ORI_NREG]
					,	[CARGA_ORI_REG_INT]
					,	[CARGA_DES_REG_INT]
					,	[CARGA_SOMA_REG_INT]
					,	[CARGA_ORI_REG_DOM]
					,	[CARGA_DES_REG_DOM]
					,	[CARGA_SOMA_REG_DOM]
					,	[CARGA_ORI_NREG_INT]
					,	[CARGA_DES_NREG_INT]
					,	[CARGA_SOMA_NREG_INT]
					,	[CARGA_ORI_NREG_DOM]
					,	[CARGA_DES_NREG_DOM]
					,	[CARGA_SOMA_NREG_DOM]
					,	[SOMA_ORI_TOT]
					,	[SOMA_DES_TOT]
					,	[SOMA_SOMA_TOT]
					,	[SOMA_TRANSI_TOT]
					,	[SOMA_CNX_ORI_TOT]
					,	[SOMA_CNX_DES_TOT]
					,	'20140716 09:21:54' 
					,	'N'
			FROM	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO] WITH (NOLOCK)
			WHERE	FL_MIGRACAO IS NULL 
			  AND   CONVERT(VARCHAR(8), [MES_ANO], 112) = @MES_ANO
			  AND   SG_AER = @SG_AER 

			UPDATE  [SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO]  
			   SET	FL_MIGRACAO = 'S'
				,	DT_MIGRACAO = '20140716 09:21:54'
			 WHERE	FL_MIGRACAO IS NULL
			   AND  CONVERT(VARCHAR(8), [MES_ANO], 112) = @MES_ANO
			   AND  SG_AER = @SG_AER 

			BEGIN TRY

				SELECT	@CD_RSO = [CD_RSO]
						,	@DH_GRAVAR = [DH_GRAVAR]
						,	@NM_PES = LTRIM(RTRIM([NM_PES]))
				 FROM	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] WITH (NOLOCK)
				WHERE	FL_MIGRACAO IS NULL
				  AND   CONVERT(VARCHAR(8), [MES_ANO], 112) = @MES_ANO
			      AND	SG_AER = @SG_AER 

				UPDATE	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL
				   SET	CD_RSO = @CD_RSO
					 ,	DH_GRAVAR = @DH_GRAVAR
					 ,  NM_PES = @NM_PES
					 ,  DT_MIGRACAO = '20140716 09:21:54' 
					 ,	FL_MIGRACAO = 'N'
				 WHERE	MES_ANO = @MES_ANO
				   AND  SG_AER = @SG_AER 
				   AND	FL_MIGRACAO IS NULL

				UPDATE	[SBAR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO]  
				   SET	FL_MIGRACAO = 'S'
					 ,	DT_MIGRACAO = '20140716 09:21:54'
				 WHERE	FL_MIGRACAO IS NULL
				   AND  CONVERT(VARCHAR(8), [MES_ANO], 112) = @MES_ANO
			       AND	SG_AER = @SG_AER 
				
				IF ( (@MES_ANO_REP = '20141301') OR (@MES_ANO_REP = '20141401') ) BEGIN
					UPDATE	IEOP..INTEGRACAO_IEOP_SISO_RSO_CENTRAL
					   SET	CD_RSO = @CD_RSO
						 ,	DH_GRAVAR = @DH_GRAVAR
						 ,  NM_PES = @NM_PES
						 ,  DT_MIGRACAO = '20140716 09:21:54' 
						 ,	FL_MIGRACAO = 'N'
					 WHERE	MES_ANO = @MES_ANO_REP
					   AND  SG_AER = @SG_AER 
					   AND	FL_MIGRACAO IS NULL
				END;
			END TRY

			BEGIN CATCH
				PRINT '2a CARGA: DADOS DE RESUMO DO RSO -> ERRO NO AEROPORTO: SBAR'
			END CATCH
		END TRY

		BEGIN CATCH
			PRINT '1a CARGA: DADOS COMPLETOS DO RSO -> ERRO NO AEROPORTO: SBAR'
		END CATCH
	END

	FETCH NEXT FROM C_AEROP 
	INTO @MES_ANO
	,    @SG_AER
END

CLOSE C_AEROP
DEALLOCATE C_AEROP	

