insert into ifrbanco.tabelas values ('BDCLIM','SEQCLASSE','IFRCLIM','SEQUENCE');                                       
insert into ifrbanco.tabelas values ('BDCLIM','SEQESTACAO','IFRCLIM','SEQUENCE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','SEQINSTRUMENTO','IFRCLIM','SEQUENCE');                                  
insert into ifrbanco.tabelas values ('BDCLIM','SEQLOGIMPORT','IFRCLIM','SEQUENCE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','SEQMEDICAOINV','IFRCLIM','SEQUENCE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','SEQMENSAGEM','IFRCLIM','SEQUENCE');                                     
insert into ifrbanco.tabelas values ('BDCLIM','SEQREGIONAL','IFRCLIM','SEQUENCE');                                     
insert into ifrbanco.tabelas values ('IFRBANCO','ANALYZ_TABELAS','IFRBANCO','TABLE');                                   
insert into ifrbanco.tabelas values ('IFRBANCO','TABELAS','IFRBANCO','TABLE');                                          
insert into ifrbanco.tabelas values ('BDCLIM','ATRIBUTO','IFRCLIM','TABLE');                                           
insert into ifrbanco.tabelas values ('BDCLIM','ATRIBUTO_CODIGO','IFRCLIM','TABLE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','ATRIBUTO_INFRAERO','IFRCLIM','TABLE');                                  
insert into ifrbanco.tabelas values ('BDCLIM','ATRIB_ESTACAO','IFRCLIM','TABLE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','BASE','IFRCLIM','TABLE');                                               
insert into ifrbanco.tabelas values ('BDCLIM','CATEGORIA','IFRCLIM','TABLE');                                          
insert into ifrbanco.tabelas values ('BDCLIM','CLASSE','IFRCLIM','TABLE');                                             
insert into ifrbanco.tabelas values ('BDCLIM','CLASSIFICACAO','IFRCLIM','TABLE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','COLABORADOR','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','CONSISTENCIA','IFRCLIM','TABLE');                                       
insert into ifrbanco.tabelas values ('BDCLIM','CONSIST_ESTACAO','IFRCLIM','TABLE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','CONV_UNIDADE','IFRCLIM','TABLE');                                       
insert into ifrbanco.tabelas values ('BDCLIM','CORR_ATRIB_EST','IFRCLIM','TABLE');                                     
insert into ifrbanco.tabelas values ('BDCLIM','ENTIDADE','IFRCLIM','TABLE');                                           
insert into ifrbanco.tabelas values ('BDCLIM','ESTACAO','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','ESTACAO_PISTA','IFRCLIM','TABLE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','ESTADO','IFRCLIM','TABLE');                                             
insert into ifrbanco.tabelas values ('BDCLIM','FUNCAO','IFRCLIM','TABLE');                                             
insert into ifrbanco.tabelas values ('BDCLIM','GRUPO_USUARIO','IFRCLIM','TABLE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','HABILITACAO','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','IMPORTA_INFOMET','IFRCLIM','TABLE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','INSTRUMENTO','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','LOG_ACESSO','IFRCLIM','TABLE');                                         
insert into ifrbanco.tabelas values ('BDCLIM','LOG_ERRO_IMPORT','IFRCLIM','TABLE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','LOG_ERRO_IMPORTA_INFOMET','IFRCLIM','TABLE');                           
insert into ifrbanco.tabelas values ('BDCLIM','LOG_IMPORTA_INFOMET','IFRCLIM','TABLE');                                
insert into ifrbanco.tabelas values ('BDCLIM','LOG_MENSAGEM','IFRCLIM','TABLE');                                       
insert into ifrbanco.tabelas values ('BDCLIM','MANUTENCAO','IFRCLIM','TABLE');                                         
insert into ifrbanco.tabelas values ('BDCLIM','MEDICAO','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','MEDICAO_ALT','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','MEDICAO_INV','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','MENSAGEM','IFRCLIM','TABLE');                                           
insert into ifrbanco.tabelas values ('BDCLIM','MENSAGEM_ESTACAO','IFRCLIM','TABLE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','MULTIANUAL','IFRCLIM','TABLE');                                         
insert into ifrbanco.tabelas values ('BDCLIM','MUNICIPIO','IFRCLIM','TABLE');                                          
insert into ifrbanco.tabelas values ('BDCLIM','PAIS','IFRCLIM','TABLE');                                               
insert into ifrbanco.tabelas values ('BDCLIM','PARAMETRO','IFRCLIM','TABLE');                                          
insert into ifrbanco.tabelas values ('BDCLIM','PARAM_GERAL','IFRCLIM','TABLE');                                        
insert into ifrbanco.tabelas values ('BDCLIM','REGIAO','IFRCLIM','TABLE');                                             
insert into ifrbanco.tabelas values ('BDCLIM','REGIONAL','IFRCLIM','TABLE');                                           
insert into ifrbanco.tabelas values ('BDCLIM','REPLICA','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','SECAO','IFRCLIM','TABLE');                                              
insert into ifrbanco.tabelas values ('BDCLIM','SERVIDOR','IFRCLIM','TABLE');                                           
insert into ifrbanco.tabelas values ('BDCLIM','TEMP_INF_MEDIAS2','IFRCLIM','TABLE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','TEMP_INF_MEDIAS3','IFRCLIM','TABLE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','TEMP_INF_MEDIAS4','IFRCLIM','TABLE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','TIPO_ERRO','IFRCLIM','TABLE');                                          
insert into ifrbanco.tabelas values ('BDCLIM','TIPO_INSTRUMENTO','IFRCLIM','TABLE');                                   
insert into ifrbanco.tabelas values ('BDCLIM','UNIDADE','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','UNIDADE_CLASSE','IFRCLIM','TABLE');                                     
insert into ifrbanco.tabelas values ('BDCLIM','UNIDADE_SECAO','IFRCLIM','TABLE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','VERSAO1','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','VERSAO2','IFRCLIM','TABLE');                                            
insert into ifrbanco.tabelas values ('BDCLIM','VW_GRAPH_VL_MEDICAO_AVG1','IFRCLIM','VIEW');                            
insert into ifrbanco.tabelas values ('BDCLIM','VW_GRAPH_VL_MEDICAO_AVG2','IFRCLIM','VIEW');                            
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_GERA_SYNOP','IFRCLIM','PACKAGE');                                
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_ATUALIZA_MEDICAO','IFRCLIM','PROCEDURE');                        
insert into ifrbanco.tabelas values ('BDCLIM','PRO_EXCLUI_DADOS_RRR','IFRCLIM','PROCEDURE');                           
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_GERAL','IFRCLIM','PACKAGE');                                     
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_CALCULA_MEDIAS','IFRCLIM','PROCEDURE');                          
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_EFETIVA_MEDICAO','IFRCLIM','PROCEDURE');                         
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_DELECAO_MEDIA','IFRCLIM','PROCEDURE');                           
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_MEDIA','IFRCLIM','PROCEDURE');                           
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_MAXIMA_HR','IFRCLIM','PROCEDURE');                       
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_MAXIMA','IFRCLIM','PROCEDURE');                          
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_MAXIMA_6HR','IFRCLIM','PROCEDURE');                      
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_MINIMA','IFRCLIM','PROCEDURE');                          
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_HORA','IFRCLIM','PROCEDURE');                            
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_HORAMAXIMA','IFRCLIM','PROCEDURE');                      
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_PORCENTAGEM','IFRCLIM','PROCEDURE');                     
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_FREQUENCIA','IFRCLIM','PROCEDURE');                      
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_TOTALHORAS','IFRCLIM','PROCEDURE');                      
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_GERACAO_TOTAL','IFRCLIM','PROCEDURE');                           
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_CALCULA_MEDIA_ATRIBUTO','IFRCLIM','PROCEDURE');                  
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_IMPORTA_HISTORICO','IFRCLIM','PROCEDURE');                       
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_MENU','IFRCLIM','PACKAGE');                                      
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_MENU','IFRCLIM','PROCEDURE');                                    
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_CALCULA_MEDIA_MULTIANO','IFRCLIM','PROCEDURE');                  
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_FORCA_MEDIAS','IFRCLIM','PROCEDURE');                            
insert into ifrbanco.tabelas values ('BDCLIM','UP_INF_DELECAO_MULTIANUAL','IFRCLIM','PROCEDURE');                      
insert into ifrbanco.tabelas values ('BDCLIM','DECIMAL_LAT','IFRCLIM','FUNCTION');                                     
insert into ifrbanco.tabelas values ('BDCLIM','DECIMAL_LONG','IFRCLIM','FUNCTION');                                    
insert into ifrbanco.tabelas values ('BDCLIM','FUN_INTEGRIDADE_FK','IFRCLIM','FUNCTION');                              
insert into ifrbanco.tabelas values ('BDCLIM','FUN_INTEGRIDADE','IFRCLIM','FUNCTION');                                 
insert into ifrbanco.tabelas values ('BDCLIM','FUN_VLD_PK','IFRCLIM','FUNCTION');                                      
insert into ifrbanco.tabelas values ('BDCLIM','LAT_DECIMAL','IFRCLIM','FUNCTION');                                     
insert into ifrbanco.tabelas values ('BDCLIM','RANDOM','IFRCLIM','FUNCTION');                                          
insert into ifrbanco.tabelas values ('BDCLIM','LONG_DECIMAL','IFRCLIM','FUNCTION');                                    
insert into ifrbanco.tabelas values ('BDCLIM','FUN_VLD_PK_UNICA','IFRCLIM','FUNCTION');                                
insert into ifrbanco.tabelas values ('BDCLIM','FUN_RETORNA_DESC_ATRIBUTO','IFRCLIM','FUNCTION');                       
insert into ifrbanco.tabelas values ('BDCLIM','FUN_REPLICATE','IFRCLIM','FUNCTION');                                   
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_PRESSAO','IFRCLIM','PACKAGE');                    
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_PREC','IFRCLIM','PACKAGE');                       
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_FORM_B','IFRCLIM','PACKAGE');                     
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_FORM_A','IFRCLIM','PACKAGE');                     
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_II_6B','IFRCLIM','PACKAGE');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_III','IFRCLIM','PACKAGE');                           
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_II','IFRCLIM','PACKAGE');                            
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_I','IFRCLIM','PACKAGE');                             
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_E','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_D','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_C','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_B','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_A','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_V','IFRCLIM','PACKAGE');                             
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_I_6B','IFRCLIM','PACKAGE');                          
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_VENTO','IFRCLIM','PACKAGE');                      
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_TEMP','IFRCLIM','PACKAGE');                       
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_TRG_CORRECAO','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_TRG_ATRIBUTO','IFRCLIM','PACKAGE');                              
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_02_DET','IFRCLIM','PACKAGE');                     
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_02','IFRCLIM','PACKAGE');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_01','IFRCLIM','PACKAGE');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_ROSA_DOS_VENTOS','IFRCLIM','PACKAGE');                           
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_MENSAGEM','IFRCLIM','PACKAGE');                                  
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_CLIMAT_ESTAT_MENSAL','IFRCLIM','PACKAGE');                       
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_D','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_C','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_B','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_A','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_V','IFRCLIM','PACKAGE BODY');                        
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_I_6B','IFRCLIM','PACKAGE BODY');                     
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_VENTO','IFRCLIM','PACKAGE BODY');                 
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_TEMP','IFRCLIM','PACKAGE BODY');                  
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_PRESSAO','IFRCLIM','PACKAGE BODY');               
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_PREC','IFRCLIM','PACKAGE BODY');                  
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_FORM_B','IFRCLIM','PACKAGE BODY');                
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_IV_FORM_A','IFRCLIM','PACKAGE BODY');                
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_II_6B','IFRCLIM','PACKAGE BODY');                    
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_III','IFRCLIM','PACKAGE BODY');                      
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_II','IFRCLIM','PACKAGE BODY');                       
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_FORMATO_I','IFRCLIM','PACKAGE BODY');                        
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_TRG_CORRECAO','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_TRG_ATRIBUTO','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_02_DET','IFRCLIM','PACKAGE BODY');                
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_02','IFRCLIM','PACKAGE BODY');                    
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_SUMARIO_MENSAL_01','IFRCLIM','PACKAGE BODY');                    
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_ROSA_DOS_VENTOS','IFRCLIM','PACKAGE BODY');                      
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_REL_MODELO_E','IFRCLIM','PACKAGE BODY');                         
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_GERAL','IFRCLIM','PACKAGE BODY');                                
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_MENSAGEM','IFRCLIM','PACKAGE BODY');                             
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_GERA_SYNOP','IFRCLIM','PACKAGE BODY');                           
insert into ifrbanco.tabelas values ('BDCLIM','PC_INF_CLIMAT_ESTAT_MENSAL','IFRCLIM','PACKAGE BODY');                  
