IFRDBA no BDSEDE122 >/

'GRANTSELECTON'||TABLE_NAME||'TORL_VAX_COBRA;'                                                                                                                                        
-------------------------------------------------------------                                                                                                                       
GRANT SELECT ON BANCO_AGENCIA_COBRA TO RL_VAX_COBRA;                                                                                                                                  
GRANT SELECT ON DEPENDENCIAS_COBRA TO RL_VAX_COBRA;                                                                                                                                   
GRANT SELECT ON DOC_FOLHA_COBRA TO RL_VAX_COBRA;                                                                                                                                      
GRANT SELECT ON REGIAO_SAL_MIN_COBRA TO RL_VAX_COBRA;                                                                                                                                 
GRANT SELECT ON PROVENTOS_DESCONTOS_COBRA TO RL_VAX_COBRA;                                                                                                                            
GRANT SELECT ON TAB_FUNCOES_COBRA TO RL_VAX_COBRA;                                                                                                                                    
GRANT SELECT ON TAB_IRRF_COBRA TO RL_VAX_COBRA;                                                                                                                                       
GRANT SELECT ON TAB_NIVEL_PADRAO_COBRA TO RL_VAX_COBRA;                                                                                                                               
GRANT SELECT ON TAB_LOTACOES_COBRA TO RL_VAX_COBRA;                                                                                                                                   
GRANT SELECT ON TAB_PROG_BENEFICIOS_COBRA TO RL_VAX_COBRA;                                                                                                                            
GRANT SELECT ON FCADASTRO TO RL_VAX_COBRA;                                                                                                                                            

11 linhas selecionadas.

IFRDBA no BDSEDE122 >SPO OFF
