DECLARE @SIG_AEROPORTO VARCHAR(4)
	  ,	@DATA VARCHAR(8)

SELECT	@DATA = CONVERT(VARCHAR(4), YEAR(DATEADD(MONTH,-1,GETDATE()))) + CONVERT(VARCHAR(2), MONTH(DATEADD(MONTH,-1,GETDATE()))) + '01'

DECLARE cursor_aeroportos CURSOR FOR 
SELECT	sig_aeroporto
  FROM	BIOGER..BIOGER_SERVERS_SISO WITH (NOLOCK)
 WHERE  sta_srv_primario = 1
   AND  sig_aeroporto NOT IN ('SBBR', 'SBGR', 'SBKP')
   AND  sig_aeroporto NOT IN ( SELECT	SG_AER COLLATE Latin1_General_CI_AI
								 FROM	[IEOP]..[INTEGRACAO_IEOP_SISO_RSO_CENTRAL] WITH (NOLOCK)
								WHERE	FL_MIGRACAO != 'R'
								  AND   MES_ANO = @DATA)
 ORDER
    BY	1

 OPEN cursor_aeroportos

FETCH NEXT FROM cursor_aeroportos
INTO @SIG_AEROPORTO

WHILE @@FETCH_STATUS = 0
BEGIN
	BEGIN TRY
		PRINT 'UPDATE [' + @SIG_AEROPORTO + ' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] SET DT_MIGRACAO = NULL, FL_MIGRACAO = NULL WHERE	MES_ANO = ''20131101'''
		PRINT 'UPDATE [' + @SIG_AEROPORTO + ' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO] SET DT_MIGRACAO = NULL, FL_MIGRACAO = NULL WHERE	MES_ANO = ''20131101'''
		PRINT 'EXEC IEOP..PRC_CARGA_RSO_AEROPORTOS ''' +  @SIG_AEROPORTO + ''''
	END TRY

	BEGIN CATCH
		PRINT 'ERRO NO AEROPORTO: ' + @SIG_AEROPORTO
	END CATCH

	FETCH NEXT FROM cursor_aeroportos
	INTO @SIG_AEROPORTO
END


CLOSE cursor_aeroportos;
DEALLOCATE cursor_aeroportos;

/*

DELETE   FROM [IEOP].[dbo].[INTEGRACAO_SISO_IEOP_RSO_CENTRAL]

DELETE   FROM [IEOP].[dbo].[INTEGRACAO_IEOP_SISO_RSO_CENTRAL]

UPDATE [SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO] SET FL_MIGRACAO = NULL 

UPDATE [SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] SET FL_MIGRACAO = NULL 

EXEC IEOP..PRC_CARGA_RSO_AEROPORTOS 'SBBG'

SELECT	*
  FROM	[SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_IEOP_RSO] WITH (NOLOCK)

SELECT	*
  FROM	[SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_IEOP_SISO_RSO] WITH (NOLOCK)


SELECT	*
  FROM	[IEOP]..[INTEGRACAO_SISO_IEOP_RSO_CENTRAL] WITH (NOLOCK)

SELECT	*
  FROM	[IEOP]..[INTEGRACAO_IEOP_SISO_RSO_CENTRAL] WITH (NOLOCK)

  */