DECLARE @SIG_AEROPORTO VARCHAR(4)

DECLARE cursor_aeroportos CURSOR FOR 
SELECT	sig_aeroporto
  FROM	BIOGER..BIOGER_SERVERS_SISO WITH (NOLOCK)
 WHERE  sta_srv_primario = 1
   AND  sig_aeroporto NOT IN ( SELECT	SG_AER COLLATE Latin1_General_CI_AI
								 FROM	[IEOP]..[INTEGRACAO_IEOP_SISO_RSO_CENTRAL] WITH (NOLOCK)
								WHERE	FL_MIGRACAO != 'R')
 ORDER
    BY	1

 OPEN cursor_aeroportos

FETCH NEXT FROM cursor_aeroportos
INTO @SIG_AEROPORTO

WHILE @@FETCH_STATUS = 0
BEGIN
	BEGIN TRY
		EXEC IEOP..PRC_CARGA_RSO_AEROPORTOS @SIG_AEROPORTO
	END TRY

	BEGIN CATCH
		PRINT 'ERRO NO AEROPORTO: ' + @SIG_AEROPORTO
	END CATCH

	FETCH NEXT FROM cursor_aeroportos
	INTO @SIG_AEROPORTO
END


CLOSE cursor_aeroportos;
DEALLOCATE cursor_aeroportos;
