set heading off
SET FEEDBACK OFF
set verify off

select 'Períodos Válidos' from dual;
select distinct( to_char(data_analyz,'DD/MM/YYYY'))
from analyz_tabelas
;

Accept dat1 PROMPT 'Informe data inicial (dd/mm/aaaa): ';

Accept dat2 PROMPT 'Informe data final   (dd/mm/aaaa): ';
spool c:\ronei\scripts\taxa_crescim.log

SELECT '#### Total GERAL no período &dat1 à &dat2' FROM DUAL;
SELECT to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2'
;

SELECT '#### Total de TABELAS CRIADAS no período &dat1 à &dat2' FROM DUAL;
SELECT to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A
WHERE 	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2' AND
        A.OWNER||A.TABELA NOT IN (SELECT D.OWNER||D.TABELA FROM ANALYZ_TABELAS D 
                                  WHERE D.OWNER=A.OWNER AND D.TABELA=A.TABELA AND
					to_char(D.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1');

SELECT '#### Total de TABELAS ELIMINADAS no período &dat1 à &dat2' FROM DUAL;
SELECT to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A
WHERE 	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
        A.OWNER||A.TABELA NOT IN (SELECT D.OWNER||D.TABELA FROM ANALYZ_TABELAS D 
                                  WHERE D.OWNER=A.OWNER AND D.TABELA=A.TABELA AND
					to_char(D.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2');


SELECT '#### Percentual de crescimento, no período &dat1 à &dat2' FROM DUAL;
SELECT to_char((((sum(A.NUM_REGS * A.TAMANHO_MEDIO_REGS) / sum(B.NUM_REGS * B.TAMANHO_MEDIO_REGS)) * 100) - 100),'99.99')||'%'
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2'
;

SELECT '#### Total POR OWNER, no período &dat1 à &dat2' FROM DUAL;
SELECT A.OWNER||' '||to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND 
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2'
GROUP BY A.OWNER;

SELECT '#### Total POR SISTEMA (cadastrado), no período &dat1 à &dat2' FROM DUAL;
SELECT C.APLICACAO||' '||to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B, TABELAS C
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND C.OWNER=B.OWNER AND C.TABELA=B.TABELA AND
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2'
GROUP BY C.APLICACAO;

SELECT '#### Total de Tabelas não cadastradas, no período &dat1 à &dat2' FROM DUAL;
SELECT A.OWNER||'.'||A.TABELA||' = '||to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND 
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2' AND
        A.OWNER||A.TABELA NOT IN (SELECT D.OWNER||D.TABELA FROM TABELAS D 
                                  WHERE D.OWNER=A.OWNER AND D.TABELA=A.TABELA)
GROUP BY A.OWNER,A.TABELA;

SELECT '#### Tabelas que CRESCERAM, no período &dat1 à &dat2' FROM DUAL;
SELECT C.TABELA||' '||to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B, TABELAS C
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND C.OWNER=B.OWNER AND C.TABELA=B.TABELA AND
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2' AND
	0 < ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)) 
GROUP BY C.OWNER,C.TABELA
ORDER BY (SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS))) DESC 
;

SELECT '#### Tabelas que DIMINUIRAM, no período &dat1 à &dat2' FROM DUAL;
SELECT C.TABELA||' '||to_char(SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)),'999,999,999,999')||' bytes' 
FROM ANALYZ_TABELAS A, ANALYZ_TABELAS B, TABELAS C
WHERE 	A.OWNER=B.OWNER AND A.TABELA=B.TABELA AND C.OWNER=B.OWNER AND C.TABELA=B.TABELA AND
	to_char(B.DATA_ANALYZ,'DD/MM/YYYY') = '&dat1' AND
	to_char(A.DATA_ANALYZ,'DD/MM/YYYY') = '&dat2' AND
	0 > ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS)) 
GROUP BY C.OWNER,C.TABELA
ORDER BY (SUM ((A.NUM_REGS * A.TAMANHO_MEDIO_REGS) - (B.NUM_REGS * B.TAMANHO_MEDIO_REGS))) 
;

spool off
 