create user IFRCASE6I identified by CASE6I
default tablespace tsd_case
temporary tablespace temp
/

alter user IFRCASE6I
quota unlimited on tsd_case
/

CREATE ROLE CK_ORACLE_REPOS_OWNER;

GRANT ALTER SESSION
, CREATE SESSION
, CREATE ANY TABLE
, CREATE ANY VIEW
, CREATE ANY SNAPSHOT
, CREATE ANY SYNONYM
, CREATE ANY PROCEDURE
, CREATE ANY SEQUENCE
, CREATE ANY TRIGGER
, CREATE ANY INDEX
, CREATE ANY TYPE
, CREATE ANY CLUSTER
, CREATE ROLE
, CREATE DATABASE LINK
, DROP ANY SYNONYM
, SELECT ANY SEQUENCE
  TO CK_ORACLE_REPOS_OWNER ;

GRANT EXECUTE ON standard TO CK_ORACLE_REPOS_OWNER;


GRANT SELECT ON V_$PARAMETER TO IFRCASE6I;                  
GRANT SELECT ON V_$NLS_PARAMETERS  TO IFRCASE6I;
GRANT SELECT ON DBA_ROLLBACK_SEGS TO IFRCASE6I;
GRANT SELECT ON DBA_SEGMENTS TO IFRCASE6I;
GRANT EXECUTE ON DBMS_LOCK TO IFRCASE6I;
GRANT EXECUTE ON DBMS_PIPE  TO IFRCASE6I;

GRANT  CONNECT                      
,RESOURCE                     
,CK_ORACLE_REPOS_OWNER        
,CREATE VIEW              
,CREATE TABLE             
,CREATE SYNONYM           
,CREATE SEQUENCE          
,CREATE PROCEDURE         
,DROP ANY SYNONYM         
,SELECT ANY TABLE         
,CREATE ANY SYNONYM       
,DROP PUBLIC SYNONYM      
,UNLIMITED TABLESPACE     
,CREATE PUBLIC SYNONYM    
 TO IFRCASE6I; 
