USE IEOP

DECLARE @DTH_INI VARCHAR(20)
	  ,	@DTH_FIM VARCHAR(20)
	  ,	@SIG_AEROPORTO VARCHAR(4)


SET	@DTH_INI = '20130805 00:00'
SET	@DTH_FIM = '20130806 00:00'
SET @SIG_AEROPORTO = 'SBBR'


 /*SELECT	COD_STATUS
 --     , COD_MOVIMENTO
	  ,	COUNT(1) AS TOTAL
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO]
 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
 GROUP
    BY	COD_STATUS
--      , COD_MOVIMENTO
 HAVING COUNT(1) < 3
 ORDER
    BY	COD_STATUS*/

SELECT	CD_STA
 --     , COD_MOVIMENTO
	  ,	COUNT(1) AS TOTAL
  FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
 WHERE	HR_MOV BETWEEN @DTH_INI AND @DTH_FIM
 GROUP
    BY	CD_STA
--      , COD_MOVIMENTO
 HAVING COUNT(1) < 3
 ORDER
    BY	CD_STA