USE IEOP

DECLARE @DTH_INI VARCHAR(20)
	  ,	@DTH_FIM VARCHAR(20)
	  ,	@SIG_AEROPORTO VARCHAR(4)


SET	@DTH_INI = '20130801 00:00'
SET	@DTH_FIM = '20130901 00:00'
SET @SIG_AEROPORTO = 'SBGL'


SELECT *
 --UPDATE [IEOP].[dbo].[IEOP_EMBARQUE_TEMP] SET FLG_MIGRADO = 22
  FROM	[IEOP].[dbo].[IEOP_EMBARQUE_TEMP]
 WHERE	[DTH_NORMAL_DECOLAGEM] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  TIP_STATUS =  3

SELECT *
 --UPDATE [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP] SET FLG_MIGRADO = 22
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP]
 WHERE	[DTH_NORMAL_POUSO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  TIP_STATUS =  3