/*
SELECT	--DISTINCT COD_STATUS
		COD_STATUS
	 ,	COUNT(1) TOTAL
  FROM	[dbo].[IEOP_DESEMBARQUE]
 WHERE	SIG_AEROPORTO = 'SBSP'
   AND  DTH_EFETIVA_POUSO >= '20130930'
   AND  DTH_EFETIVA_POUSO < '20131001'
 GROUP
    BY	COD_STATUS
HAVING	COUNT(1) > 1
*/

SELECT	COD_STATUS AS CD_STA, *
  FROM	[dbo].[IEOP_EMBARQUE]
 WHERE	SIG_AEROPORTO = 'SBGL'
   AND  DTH_EFETIVA_DECOLAGEM >= '20131002'
   AND  DTH_EFETIVA_DECOLAGEM <  '20131003'
 ORDER BY COD_STATUS

SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[dbo].[TMP_INTEGRACAO_IEOP_EMB_SBGL]
 WHERE	DH_PAR_EFE >= '20131002'
   AND  DH_PAR_EFE <  '20131003'
ORDER BY   CD_STA 

SELECT	COD_STATUS AS CD_STA, *
  FROM	[dbo].[IEOP_DESEMBARQUE]
 WHERE	SIG_AEROPORTO = 'SBGL'
   AND  DTH_EFETIVA_POUSO >= '20131003'
   AND  DTH_EFETIVA_POUSO <  '20131004'
 ORDER BY COD_STATUS

SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[dbo].[TMP_INTEGRACAO_IEOP_DES_SBGL]
 WHERE	DH_CHG_EFE >= '20131003'
   AND  DH_CHG_EFE <  '20131004'
ORDER BY   CD_STA 


/*
SELECT	COD_STATUS AS CD_STA, *
  FROM	[dbo].[IEOP_EMBARQUE_TEMP]
 WHERE	SIG_AEROPORTO = 'SBGL'
   AND  DTH_EFETIVA_DECOLAGEM >= '20131001'
   AND  DTH_EFETIVA_DECOLAGEM <  '20131002'
 ORDER BY COD_STATUS
*/



/*
SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[dbo].[TMP_INTEGRACAO_IEOP_EMB_SBSP]
 WHERE	CD_STA = 1000275

SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[dbo].[TMP_INTEGRACAO_IEOP_EMB_SBSP]
 WHERE	CD_STA = 1000275

SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[dbo].[TMP_INTEGRACAO_IEOP_EMB_SBSP]
 WHERE	CD_STA = 1000275
 */