USE IEOP

DECLARE @DTH_INI VARCHAR(20)
	  ,	@DTH_FIM VARCHAR(20)
	  ,	@SIG_AEROPORTO VARCHAR(4)


SET	@DTH_INI = '20131101 00:00'
SET	@DTH_FIM = '20131106 00:00'
SET @SIG_AEROPORTO = 'SBBR'


SELECT	COUNT(1) AS TOTAL_EMB --TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_EMBARQUE]
 WHERE	[DTH_EFETIVA_DECOLAGEM] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
 --ORDER 	BY	[DTH_EFETIVA_DECOLAGEM] DESC


SELECT	COUNT(1) AS TOTAL_DES --TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE]
 WHERE	[DTH_EFETIVA_POUSO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
 --ORDER BY	[DTH_EFETIVA_POUSO] DESC


SELECT	COUNT(1) AS TOTAL_MOV --TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO] WITH (NOLOCK)
 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
 --ORDER BY	[DTH_MOVIMENTO] DESC


 SELECT	COUNT(1) AS TOTAL_EMB_INTEGRA
  FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] WITH (NOLOCK)
 WHERE	DH_PAR_EFE BETWEEN @DTH_INI AND @DTH_FIM


SELECT	COUNT(1) AS TOTAL_DES_INTEGRA
  FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_DES_NEW] WITH (NOLOCK)
 WHERE	DH_CHG_EFE BETWEEN @DTH_INI AND @DTH_FIM


SELECT	COUNT(1) AS TOTAL_MOV_INTEGRA 
  FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
 WHERE	HR_MOV BETWEEN @DTH_INI AND @DTH_FIM

/*
 SELECT	DISTINCT COD_STATUS, COD_MOVIMENTO
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO]
 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  NOT EXISTS (
				SELECT	*
				  FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
				 WHERE	HR_MOV BETWEEN @DTH_INI AND @DTH_FIM
				 )


   SELECT	*
	 FROM	[SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
	WHERE	HR_MOV BETWEEN @DTH_INI AND @DTH_FIM
	  AND   NOT EXISTS (
						SELECT	*
						  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO]
						 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
						   AND	SIG_AEROPORTO = @SIG_AEROPORTO
						)



 SELECT	DISTINCT COD_STATUS, COD_MOVIMENTO
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO]
 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
   AND	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  NOT EXISTS (
				SELECT	*
				  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO] AS T1 WITH (NOLOCK)
					 ,  [SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
				 WHERE	T1.DTH_MOVIMENTO BETWEEN @DTH_INI AND @DTH_FIM
				   AND  HR_MOV BETWEEN @DTH_INI AND @DTH_FIM
				   AND	T1.SIG_AEROPORTO = @SIG_AEROPORTO
				   AND	T1.COD_STATUS = CD_STA
				 )


SELECT	*
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO] AS T1 WITH (NOLOCK)
     ,  [SBBR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] AS T2 WITH (NOLOCK)
 WHERE	T1.DTH_MOVIMENTO BETWEEN @DTH_INI AND @DTH_FIM
   AND  T2.HR_MOV BETWEEN @DTH_INI AND @DTH_FIM
   AND	T1.SIG_AEROPORTO = @SIG_AEROPORTO
   AND	T1.COD_STATUS = T2.CD_STA
   AND  T1.COD_MOVIMENTO = T2.CD_MOV


   */