SELECT * FROM [IEOP].[dbo].[IEOP_EMBARQUE_TEMP]
--update [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP] set flg_migrado =22 
WHERE	SIG_AEROPORTO IN ('SBSP', 'SBCY', 'SBGO', 'SBJR', 'SBLO', 'SBME', 'SBRF')
  AND	(DTH_NORMAL_DECOLAGEM >= '20130701' AND	DTH_NORMAL_DECOLAGEM < '20130801')
  AND   TIP_STATUS = 4

SELECT * FROM [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP]
--update [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP] set flg_migrado =22 
WHERE	SIG_AEROPORTO IN ('SBSP', 'SBCY', 'SBGO', 'SBJR', 'SBLO', 'SBME', 'SBRF')
  AND	(DTH_NORMAL_POUSO >= '20130701' AND	DTH_NORMAL_POUSO < '20130801')
  AND   TIP_STATUS = 4


SELECT MOV.* 
--update [IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] set flg_migrado =22 
 FROM   [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP] DES
    ,	[IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] MOV
WHERE	DES.SIG_AEROPORTO = MOV.SIG_AEROPORTO
  AND   DES.COD_STATUS = MOV.COD_STATUS
  AND   DES.SIG_AEROPORTO IN ('SBSP', 'SBCY', 'SBGO', 'SBJR', 'SBLO', 'SBME', 'SBRF')
  AND	(DES.DTH_NORMAL_POUSO >= '20130701' AND	DES.DTH_NORMAL_POUSO < '20130801')
  AND   DES.TIP_STATUS = 4

SELECT MOV.* 
--update [IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] set flg_migrado =22 
 FROM   [IEOP].[dbo].[IEOP_EMBARQUE_TEMP] DES
    ,	[IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] MOV
WHERE	DES.SIG_AEROPORTO = MOV.SIG_AEROPORTO
  AND   DES.COD_STATUS = MOV.COD_STATUS
  AND   DES.SIG_AEROPORTO IN ('SBSP', 'SBCY', 'SBGO', 'SBJR', 'SBLO', 'SBME', 'SBRF')
  AND	(DES.DTH_NORMAL_DECOLAGEM >= '20130701' AND	DES.DTH_NORMAL_DECOLAGEM < '20130801')
  AND   DES.TIP_STATUS = 4