DECLARE @SIG_AEROPORTO VARCHAR(8)
      ,	@COD_STATUS INT

SET		@SIG_AEROPORTO = 'SBBR'
SET		@COD_STATUS =  504726		 			  

PRINT 'EMBARQUE'
SELECT	*
  FROM	[IEOP].[dbo].[IEOP_EMBARQUE]
  --update [IEOP].[dbo].[IEOP_EMBARQUE_TEMP] set flg_migrado =22 WHERE	SIG_AEROPORTO = 'SBBR'  AND  COD_STATUS = 504726
 WHERE	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  COD_STATUS = @COD_STATUS 

PRINT 'DESEMBARQUE'
SELECT	*
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE]
    --update [IEOP].[dbo].[IEOP_DESEMBARQUE_TEMP] set flg_migrado =22 WHERE	SIG_AEROPORTO = 'SBBR'  AND  COD_STATUS = 504726
 WHERE	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  COD_STATUS = @COD_STATUS

/*
SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[IEOP].[dbo].[TMP_INTEGRACAO_IEOP_EMB_SBGL]
 WHERE	CD_STA = @COD_STATUS
  
SELECT	CD_STA AS COD_STATUS, *--DISTINCT CD_STA
  FROM	[IEOP].[dbo].[TMP_INTEGRACAO_IEOP_DES_SBGL]
 WHERE	CD_STA = @COD_STATUS
*/

PRINT 'MOVIMENTACAO'
SELECT	*
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO]
    --update [IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] set flg_migrado =2 WHERE	SIG_AEROPORTO = 'SBSP'  AND  COD_STATUS = 988147
 WHERE	SIG_AEROPORTO = @SIG_AEROPORTO
   AND  COD_STATUS = @COD_STATUS


/*
SELECT COUNT(1) 
  FROM [IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP]
   --UPDATE [IEOP].[dbo].[IEOP_MOVIMENTACAO_TEMP] SET FLG_MIGRADO = 2
 WHERE [DTH_MIGRACAO] BETWEEN '20130930' AND '20131001'


*/