USE IEOP

DECLARE @DTH_INI VARCHAR(10)
      ,	@DTH_FIM VARCHAR(10)

SET	@DTH_INI = '20131001'
SET @DTH_FIM = '20131010'

--DES
DROP TABLE TMP_INTEGRACAO_IEOP_DES_SBGL
 	
SELECT  
			 LTRIM(RTRIM(SIGLA_AEROPORTO)) SIGLA_AEROPORTO
			,LTRIM(RTRIM(NR_CHG_VOO)) NR_CHG_VOO
			,DH_CHG_NRM
			,DH_CHG_EFE
			,CD_COM
			,LTRIM(RTRIM(SG_COM_IAT_003)) SG_COM_IAT_003
			,LTRIM(RTRIM(NOME_CIA)) NOME_CIA
			,LTRIM(RTRIM(NR_AEN)) NR_AEN
			,TP_CHG_GRU
			,TP_CHG_NAT
			,TP_CHG
			,TP_CHG_CTG
			,TP_CHG_CTG_VIN
			,LTRIM(RTRIM(SG_EQP)) SG_EQP
			,LTRIM(RTRIM(NM_EQP)) NM_EQP
			,QT_DEC_DES_DOM, QT_DEC_DES_INT, QT_DEC_DES_BAG_DOM
			,QT_DEC_DES_BAG_INT, QT_DEC_DES_CAR_DOM, QT_DEC_DES_CAR_INT
			,QT_DEC_DES_COR_DOM, QT_DEC_DES_COR_INT, QT_DEC_TRA_BAG_DOM
			,QT_DEC_TRA_BAG_INT, QT_DEC_TRA_CAR_DOM, QT_DEC_TRA_CAR_INT
			,QT_DEC_TRA_COR_DOM, QT_DEC_TRA_COR_INT, QT_DEC_TRA_DOM_CX,QT_DEC_TRA_INT_CX
			,ISNULL(LTRIM(RTRIM(CD_CHG)),0) CD_CHG
			,LTRIM(RTRIM(CD_CHG_VIN)) CD_CHG_VIN
			,LTRIM(RTRIM(SIGLA_AEROPORTO_PRO)) SIGLA_AEROPORTO_PRO
			,LTRIM(RTRIM(NR_BOX)) NR_BOX
			,LTRIM(RTRIM(TP_BOX)) TP_BOX
			,LTRIM(RTRIM(NM_PON)) NM_PON
			,LTRIM(RTRIM(NR_EST)) NR_EST
			,LTRIM(RTRIM(PIS_PO)) PIS_PO
			,LTRIM(RTRIM(PIS_DE)) PIS_DE
			,CD_STA
			,CD_STA_ANT
			,CD_STA_POS
			,TP_STA
			,FL_STATUS
			,FLAG_ISE
			,FLAG_AVISTA
			,FL_AEN_TAX
			,FL_EQP_HLC
			,HR_MOV_PRI
			,HR_MOV_PRI_ENT
			,HR_MOV_ULT
			,DTH_ATUALIZACAO
			,0 QTD_ATUALIZACAO
			,1 FLG_MIGRADO
			,GETDATE() DTH_MIGRACAO		
			INTO IEOP..TMP_INTEGRACAO_IEOP_DES_SBGL	
		FROM [SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_DES_NEW] WITH (NOLOCK)
	   WHERE DH_CHG_EFE >= @DTH_INI
	     AND DH_CHG_EFE <  @DTH_FIM 


--EMB
DROP TABLE TMP_INTEGRACAO_IEOP_EMB_SBGL
 	
SELECT  
			 LTRIM(RTRIM(SIGLA_AEROPORTO)) SIGLA_AEROPORTO 
			,LTRIM(RTRIM(NR_PAR_VOO)) NR_PAR_VOO
			,DH_PAR_NRM
			,DH_PAR_EFE
			,CD_COM
			,LTRIM(RTRIM(SG_COM_IAT_003)) SG_COM_IAT_003
			,LTRIM(RTRIM(NOME_CIA)) NOME_CIA
			,LTRIM(RTRIM(NR_AEN)) NR_AEN
			,TP_PAR_GRU
			,TP_PAR_NAT
			,TP_PAR
			,TP_PAR_CTG
			,TP_PAR_CTG_VIN
			,LTRIM(RTRIM(SG_EQP)) SG_EQP
			,LTRIM(RTRIM(NM_EQP)) NM_EQP
			,QT_DEP_TFB_DOM,QT_DEP_TFB_INT,QT_DEP_TFC_DOM
			,QT_DEP_TFC_INT,QT_DEP_ISE_COL,QT_DEP_ISE_TRA
			,QT_DEP_ISE_CON_DOM,QT_DEP_ISE_CON_INT,QT_DEP_ISE_OUT
			,QT_DEP_EMB_BAG_DOM,QT_DEP_EMB_BAG_INT,QT_DEP_EMB_CAR_DOM
			,QT_DEP_EMB_CAR_INT,QT_DEP_EMB_COR_DOM,QT_DEP_EMB_COR_INT
			,QT_DEP_TFB_DOM_ANT,QT_DEP_TFB_INT_ANT,QT_DEP_TFC_DOM_ANT,QT_DEP_TFC_INT_ANT
			,LTRIM(RTRIM(CD_CHG_AEN_ANT)) CD_CHG_AEN_ANT
			,LTRIM(RTRIM(CD_PAR_VIN)) CD_PAR_VIN
			,LTRIM(RTRIM(SIGLA_AEROPORTO_DES)) SIGLA_AEROPORTO_DES
			,LTRIM(RTRIM(NR_BOX)) NR_BOX
			,LTRIM(RTRIM(TP_BOX)) TP_BOX
			,LTRIM(RTRIM(NM_PON)) NM_PON
			,LTRIM(RTRIM(NR_POR)) NR_POR
			,LTRIM(RTRIM(PIS_PO)) PIS_PO
			,LTRIM(RTRIM(PIS_DE)) PIS_DE
			,CD_STA
			,CD_STA_ANT
			,CD_STA_POS
			,TP_STA
			,FL_STATUS
			,FL_AEN_TAX
			,FL_EQP_HLC
			,HR_MOV_PRI
			,HR_MOV_ULT
			,HR_MOV_ULT_SAI
			,ISNULL(CD_PAR,0) CD_PAR
			,DTH_ATUALIZACAO
			,0 QTD_ATUALIZACAO
			,1 FLG_MIGRADO
			,GETDATE() DTH_MIGRACAO		
			INTO IEOP..TMP_INTEGRACAO_IEOP_EMB_SBGL		
		FROM [SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] WITH (NOLOCK)
	   WHERE DH_PAR_EFE >= @DTH_INI
	     AND DH_PAR_EFE <  @DTH_FIM

--MOV
DROP TABLE TMP_INTEGRACAO_IEOP_MOV_SBGL
 	
SELECT  
			 LTRIM(RTRIM(sigla_aeroporto)) sigla_aeroporto
			,CD_STA
			,CD_MOV
			,LTRIM(RTRIM(TIPO_MOV)) TIPO_MOV
			,HR_MOV
			,LTRIM(RTRIM(NR_BOX)) NR_BOX
			,TIPO_BOX
			,LTRIM(RTRIM(NR_TPS)) NR_TPS
			,DTH_ATUALIZACAO
			,0 QTD_ATUALIZACAO
			,1 FLG_MIGRADO
			,GETDATE() DTH_MIGRACAO		
			INTO IEOP..TMP_INTEGRACAO_IEOP_MOV_SBGL		
		FROM [SBGL - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] WITH (NOLOCK)
	   WHERE HR_MOV >= @DTH_INI
	     AND HR_MOV <  @DTH_FIM