DECLARE @DTH_INI VARCHAR(20)
	  ,	@DTH_FIM VARCHAR(20)

SET	@DTH_INI = '20131010 00:00'
SET	@DTH_FIM = '20131012 00:00'

SELECT	TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_EMBARQUE]
 WHERE	[DTH_EFETIVA_DECOLAGEM] BETWEEN @DTH_INI AND @DTH_FIM
 ORDER
	BY	[DTH_EFETIVA_DECOLAGEM] DESC


SELECT	TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE]
 WHERE	[DTH_EFETIVA_POUSO] BETWEEN @DTH_INI AND @DTH_FIM
 ORDER
	BY	[DTH_EFETIVA_POUSO] DESC


SELECT	TOP 100 COD_STATUS AS CD_STA, *
  FROM	[IEOP].[dbo].[IEOP_MOVIMENTACAO] WITH (NOLOCK)
 WHERE	[DTH_MOVIMENTO] BETWEEN @DTH_INI AND @DTH_FIM
 ORDER
	BY	[DTH_MOVIMENTO] DESC

/*
EXEC PRC_CARGA_DES_AEROPORTOS 'SBNT'
EXEC PRC_CARGA_EMB_AEROPORTOS 'SBNT'
EXEC PRC_CARGA_MOV_AEROPORTOS 'SBNT'
*/
