USE [IEOP]
GO

/****** Object:  View [dbo].[VIW_DADOS_IEOP_INDICADORES_DA]    Script Date: 08/05/2014 09:41:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VIW_DADOS_IEOP_INDICADORES_DA] AS 
SELECT	EMB.SIG_AEROPORTO
	 ,	EMB.MES_EMB AS MES
	 ,	EMB.ANO_EMB AS ANO
	 ,  SUM (SUM_PAX_DES + SUM_PAX_EMB) QTD_PAX
FROM  (
		SELECT	SIG_AEROPORTO
			 ,	MONTH(ISNULL([DTH_EFETIVA_POUSO], [DTH_NORMAL_POUSO])) MES_DES
			 ,	YEAR(ISNULL([DTH_EFETIVA_POUSO], [DTH_NORMAL_POUSO])) ANO_DES
			 ,	SUM([QTD_PAX_DESEMB_DOM] + [QTD_PAX_DESEMB_INT] + [QTD_CON_TRANSITO_DOM] + [QTD_CON_TRANSITO_INT]) SUM_PAX_DES
		  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE] WITH (NOLOCK)
		 WHERE  DTH_NORMAL_POUSO > '20130101'
		 GROUP
			BY	SIG_AEROPORTO
			 ,	MONTH(ISNULL([DTH_EFETIVA_POUSO], [DTH_NORMAL_POUSO]))
			 ,	YEAR(ISNULL([DTH_EFETIVA_POUSO], [DTH_NORMAL_POUSO])) 
		) DES ,
		(
		SELECT	[SIG_AEROPORTO]
			 ,	MONTH(ISNULL([DTH_EFETIVA_DECOLAGEM], [DTH_NORMAL_DECOLAGEM])) MES_EMB
			 ,	YEAR(ISNULL([DTH_EFETIVA_DECOLAGEM], [DTH_NORMAL_DECOLAGEM])) ANO_EMB
			 ,	SUM([QTD_TARIFA_PAGA_BILHETE_DOM_EMB] + [QTD_TARIFA_PAGA_BILHETE_INT_EMB] + 
			        [QTD_TARIFA_PAGA_CHECKIN_DOM_EMB] + [QTD_TARIFA_PAGA_CHECKIN_INT_EMB] + 
					[QTD_ISENTA_CONEXAO_EMB_DOM] + [QTD_ISENTA_CONEXAO_EMB_INT] + 
					[QTD_TARIFA_PAG_BILHETE_EMB_DOM_ANT] + [QTD_TARIFA_PAG_BILHETE_EMB_INT_ANT] + 
					[QTD_TARIFA_PAG_CHECKIN_EMB_DOM_ANT] + [QTD_TARIFA_PAG_CHECKIN_EMB_INT_ANT]) SUM_PAX_EMB
			 ,	SUM([QTD_BAG_EMB_DOM] + [QTD_BAG_EMB_INT]) SUM_BAG_EMB
		  FROM	[IEOP].[dbo].[IEOP_EMBARQUE] WITH (NOLOCK)
		 WHERE	[DTH_NORMAL_DECOLAGEM] > '20130101'
		 GROUP
			BY	[SIG_AEROPORTO]
			 ,	MONTH(ISNULL([DTH_EFETIVA_DECOLAGEM], [DTH_NORMAL_DECOLAGEM]))
			 ,	YEAR(ISNULL([DTH_EFETIVA_DECOLAGEM], [DTH_NORMAL_DECOLAGEM]))
		) AS EMB
 WHERE	EMB.SIG_AEROPORTO = DES.SIG_AEROPORTO
   AND	EMB.MES_EMB = DES.MES_DES
   AND	EMB.ANO_EMB = DES.ANO_DES
 GROUP
    BY	EMB.SIG_AEROPORTO
	 ,	EMB.MES_EMB
	 ,	EMB.ANO_EMB



GO


