USE [IFRCORP]
GO

/****** Object:  StoredProcedure [dbo].[PRC_CARGA_REVISADA]    Script Date: 24/02/2015 13:02:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[PRC_CARGA_REVISADA]
	
AS
BEGIN
-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
SET NOCOUNT ON;


--CARGA DE DADOS DA TABELA DEPENDENCIAS
BEGIN TRY
	BEGIN TRAN CARGA_DEPENDENCIAS
    
	DELETE FROM [dbo].[DEPENDENCIAS] 
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT [dbo].[DEPENDENCIAS] 
	(	   [DEP_CODIGO]
		  ,[DEP_TIPO]
		  ,[DEP_NOME]
		  ,[DEP_SIGLA]
		  ,[DEP_ENDERECO_LOGRADOURO]
		  ,[DEP_ENDERECO_BAIRRO]
		  ,[DEP_ENDERECO_MUNICIPIO]
		  ,[DEP_UFE_SIGLA]
		  ,[DEP_ENDERECO_CEP]
		  ,[DEP_NUMERO_TELEFONE_1]
		  ,[DEP_NUMERO_TELEFONE_2]
		  ,[DEP_NUMERO_FAX]
		  ,[DEP_NUMERO_CGC]
		  ,[DEP_ABA_BAN_CODIGO]
		  ,[DEP_ABA_CODIGO]
		  ,[DEP_DEP_CODIGO]
		  ,[DEP_CODIGO_UGD]
		  ,[DEP_RGE_CODIGO]
		  ,[CD_DEPENDENCIA_CHAVE]
		  ,[DEP_IN_CATEGORIA_AEROPORTO]
		  ,[DEP_DATA_CRIACAO]
		  ,[DEP_DS_DOCUMENTO_CRIACAO]
		  ,[DEP_DATA_EXTINCAO]
		  ,[DEP_DS_DOCUMENTO_EXTINCAO]
		  ,[DEP_MSG_CNTCHQUE]
		  ,[DEP_DEP_CODIGO_VINCULA_PGTO]
		  ,[DEP_MUN_CODIGO]
		  ,[DEP_GRUPOS_DEPENDENCIAS]
		  ,[IN_OPB_AUTOMATICA]
		  ,[DEP_SIGLA_ANTERIOR]
		  ,[DEP_IND_RECOLH_SAL_EDUCACAO]
		  ,[DEP_IND_ORCAMENTO]
		  ,[DEP_ADM_MATERIAL]
		  ,[DEP_COMAR]
		  ,[DEP_DENOMINACAO_COMPLETA]
		  ,[DEP_DENOMINACAO_ABREVIADA]
		  ,[DEP_ID_CENT_EMPRESA]
		  ,[DEP_IE]
		  ,[DEP_HORARIA_ADMINISTRATIVO]
		  ,[DEP_FUSO_HORARIO_BRASILIA]
		  ,[DEP_DT_ABSORCAO_INFRAERO]
		  ,[DEP_TEL_ACHADOS_PERDIDOS]
		  ,[DEP_TEL_BALCAO_INFORMACAO]
		  ,[DEP_TEL_COMUNICACAO_SOCIAL]
		  ,[DEP_NUMERO_TELEFONE_DDD])
	SELECT [DEP_CODIGO]
		  ,[DEP_TIPO]
		  ,[DEP_NOME]
		  ,[DEP_SIGLA]
		  ,[DEP_ENDERECO_LOGRADOURO]
		  ,[DEP_ENDERECO_BAIRRO]
		  ,[DEP_ENDERECO_MUNICIPIO]
		  ,[DEP_UFE_SIGLA]
		  ,[DEP_ENDERECO_CEP]
		  ,[DEP_NUMERO_TELEFONE_1]
		  ,[DEP_NUMERO_TELEFONE_2]
		  ,[DEP_NUMERO_FAX]
		  ,[DEP_NUMERO_CGC]
		  ,[DEP_ABA_BAN_CODIGO]
		  ,[DEP_ABA_CODIGO]
		  ,[DEP_DEP_CODIGO]
		  ,[DEP_CODIGO_UGD]
		  ,[DEP_RGE_CODIGO]
		  ,[CD_DEPENDENCIA_CHAVE]
		  ,[DEP_IN_CATEGORIA_AEROPORTO]
		  ,[DEP_DATA_CRIACAO]
		  ,[DEP_DS_DOCUMENTO_CRIACAO]
		  ,[DEP_DATA_EXTINCAO]
		  ,[DEP_DS_DOCUMENTO_EXTINCAO]
		  ,[DEP_MSG_CNTCHQUE]
		  ,[DEP_DEP_CODIGO_VINCULA_PGTO]
		  ,[DEP_MUN_CODIGO]
		  ,[DEP_GRUPOS_DEPENDENCIAS]
		  ,[IN_OPB_AUTOMATICA]
		  ,[DEP_SIGLA_ANTERIOR]
		  ,[DEP_IND_RECOLH_SAL_EDUCACAO]
		  ,[DEP_IND_ORCAMENTO]
		  ,[DEP_ADM_MATERIAL]
		  ,[DEP_COMAR]
		  ,[DEP_DENOMINACAO_COMPLETA]
		  ,[DEP_DENOMINACAO_ABREVIADA]
		  ,[DEP_ID_CENT_EMPRESA]
		  ,[DEP_IE]
		  ,[DEP_HORARIA_ADMINISTRATIVO]
		  ,[DEP_FUSO_HORARIO_BRASILIA]
		  ,[DEP_DT_ABSORCAO_INFRAERO]
		  ,[DEP_TEL_ACHADOS_PERDIDOS]
		  ,[DEP_TEL_BALCAO_INFORMACAO]
		  ,[DEP_TEL_COMUNICACAO_SOCIAL]
		  ,[DEP_NUMERO_TELEFONE_DDD] 
	from CORPORATIVO..IFRDBA2.DEPENDENCIAS
	
	COMMIT TRAN CARGA_DEPENDENCIAS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_DEPENDENCIAS
END CATCH

/*=====================================================================================*/


/*=====================================================================================*/

--CARGA DE DADOS DA TAB_AGE_EMPREGADO
BEGIN TRY
	BEGIN TRAN CARGA_TAB_AGE_EMPREGADOS
    -- EXCLUI OS DADOS DA TABELA TAB_AGE_EMPREGADO
	DELETE FROM [dbo].[TAB_AGE_EMPREGADOS] 
	--ACESSO A TABELA TAB_AGE_EMPREGADO DO OWNER IFRAGENDA
	INSERT [dbo].[TAB_AGE_EMPREGADOS] 
		(	MATRICULA, 
			CPF, 
			NOME, 
			NOME_ABREVIADO,
			NOME_GUERRA,
			I_T,
			DEPENDENCIA,
			LOTACAO,
			CARGO_FUNCAO,
			EMAIL,
			DDD,
			TELEFONE,
			VOIP,
			STATUS_EMPREGADO,
			MAT_GERAL,
			DT_OPERACAO )
		SELECT [MATRICULA]
      ,[CPF]
      ,[NOME]
      ,[NOME_ABREVIADO]
      ,[NOME_GUERRA]
      ,[I_T]
      ,[DEPENDENCIA]
      ,[LOTACAO]
      ,[CARGO_FUNCAO]
      ,[EMAIL]
      ,[DDD]
      ,[TELEFONE]
      ,[VOIP]
      ,[STATUS]
      ,[MAT_GERAL]
      ,[DT_OPERACAO]
	FROM CORPORATIVO..IFRAGENDA.TAB_AGE_EMPREGADOS
	COMMIT TRAN CARGA_TAB_AGE_EMPREGADOS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_TAB_AGE_EMPREGADOS
END CATCH

/*=====================================================================================*/

--CARGA DE DADOS DAS UNIDADES_ORGANIZACIONAIS
BEGIN TRY
	BEGIN TRAN CARGA_UNIDADES_ORGANIZACIONAIS
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[UNIDADES_ORGANIZACIONAIS] 
	--ACESSO A TABELA UNIDADES_ORGANIZACIONAIS DO OWNER IFRDBA2
	INSERT [dbo].[UNIDADES_ORGANIZACIONAIS]
	(	   [UOR_CODIGO]
		  ,[UOR_NOME]
		  ,[UOR_SIGLA]
		  ,[UOR_CODIGO_LOTACAO_ANTERIOR]
		  ,[UOR_DEP_CODIGO]
		  ,[UOR_UOR_CODIGO]
		  ,[UOR_SEQUENCIA_ESTRUTURA]
		  ,[UOR_DATA_CRIACAO]
		  ,[UOR_DS_DOCUMENTO_CRIACAO]
		  ,[UOR_DATA_EXTINCAO]
		  ,[UOR_DS_DOCUMENTO_EXTINCAO]
		  ,[UOR_DEP_CODIGO_VINCULA_PGTO]
		  ,[UOR_NOME_ABREVIADO]
		  ,[UOR_TIPO_UNIDAD_ORG]
		  ,[UOR_DEP_ADM_MATERIAL]
		  ,[UOR_ENDERECO_LOGRADOURO]
		  ,[UOR_ENDERECO_BAIRRO]
		  ,[UOR_ENDERECO_MUNICIPIO]
		  ,[UOR_UFE_SIGLA]
		  ,[UOR_CEP]
		  ,[UOR_NUMERO_FAX])

	SELECT [UOR_CODIGO]
		  ,[UOR_NOME]
		  ,[UOR_SIGLA]
		  ,[UOR_CODIGO_LOTACAO_ANTERIOR]
		  ,[UOR_DEP_CODIGO]
		  ,[UOR_UOR_CODIGO]
		  ,[UOR_SEQUENCIA_ESTRUTURA]
		  ,[UOR_DATA_CRIACAO]
		  ,[UOR_DS_DOCUMENTO_CRIACAO]
		  ,[UOR_DATA_EXTINCAO]
		  ,[UOR_DS_DOCUMENTO_EXTINCAO]
		  ,[UOR_DEP_CODIGO_VINCULA_PGTO]
		  ,[UOR_NOME_ABREVIADO]
		  ,[UOR_TIPO_UNIDAD_ORG]
		  ,[UOR_DEP_ADM_MATERIAL]
		  ,[UOR_ENDERECO_LOGRADOURO]
		  ,[UOR_ENDERECO_BAIRRO]
		  ,[UOR_ENDERECO_MUNICIPIO]
		  ,[UOR_UFE_SIGLA]
		  ,[UOR_CEP]
		  ,[UOR_NUMERO_FAX]
	FROM CORPORATIVO..IFRDBA2.UNIDADES_ORGANIZACIONAIS
	COMMIT TRAN CARGA_UNIDADES_ORGANIZACIONAIS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_UNIDADES_ORGANIZACIONAIS
END CATCH

/*=====================================================================================*/

--CARGA DE DADOS DOS GRUPOS_DEPENDENCIAS
BEGIN TRY
	BEGIN TRAN CARGA_GRUPOS_DEPENDENCIAS
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[GRUPOS_DEPENDENCIAS] 
	--ACESSO A TABELA GRUPOS_DEPENDENCIAS DO OWNER IFRSRH
	INSERT [dbo].[GRUPOS_DEPENDENCIAS] 
	(	[GDP_CODIGO],
		[GDP_DESCRICAO])
	SELECT [GDP_CODIGO],
		   [GDP_DESCRICAO]
	FROM CORPORATIVO..IFRSRH.GRUPOS_DEPENDENCIAS
	COMMIT TRAN CARGA_GRUPOS_DEPENDENCIAS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_GRUPOS_DEPENDENCIAS
END CATCH

/*=====================================================================================*/

--CARGA DE DADOS DOS MUNICIPIOS
BEGIN TRY
	BEGIN TRAN CARGA_MUNICIPIOS
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[MUNICIPIOS] 
	--ACESSO A TABELA MUNICIPIOS DO OWNER IFRBD2
	INSERT [dbo].[MUNICIPIOS] 
	(	[MUN_CODIGO],
		[MUN_DESCRICAO],
		[MUN_UFE_SIGLA])
	SELECT 	[MUN_CODIGO],
			[MUN_DESCRICAO],
			[MUN_UFE_SIGLA]
	FROM CORPORATIVO..IFRDBA2.MUNICIPIOS
	COMMIT TRAN CARGA_MUNICIPIOS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_MUNICIPIOS
END CATCH

/*=====================================================================================*/

--CARGA DE DADOS DE EMPREGADOS
BEGIN TRY
	BEGIN TRAN CARGA_EMPREGADOS_INFRAERO
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[EMPREGADOS_INFRAERO] 
	-- INSERE DADOS NA TABELA DE EMPREGADOS_INFRAERO
	INSERT INTO [dbo].[EMPREGADOS_INFRAERO]
	(	[EMP_NUMERO_MATRICULA],
		[EMP_NOME_ABREVIADO],
		[EMP_NOME],
		[EMP_INDICADOR_SEXO],
		[EMP_QLP_CAR_CODIGO],
		[CAR_SIGLA],
		[CAR_NOME],
		[EMP_QLP_CAR_OCC_CODIGO],
		[OCC_DESCRICAO],
		[EMP_QLP_CAR_CODIGO_NIVEL],
		[EMP_NSA_CODIGO_PADRAO],
		[EMP_NSA_CODIGO_NIVEL],
		[EMP_QFU_FUN_CODIGO],
		[FUN_DESCRICAO],
		[CFU_NOME],
		[EMP_DEP_CODIGO_LOTACAO],
		[DEP_SIGLA],
		[DEP_NOME],
		[EMP_DEP_CODIGO_FISICO],
		[EMP_UOR_CODIGO_LOTACAO],
		[UOR_SIGLA],
		[EMP_UOR_CODIGO_FISICO],
		[UOR_SIGLA_FISICA],
		[EMP_NU_CARTEIRA_IDENTIDADE],
		[EMP_SIGLA_ORGAO_EMITENTE_CI],
		[EMP_NUMERO_CPF],
		[EMP_NUMERO_CPF_NOTES],
		[EMP_ATI_CT_CUSTOS],
		[EMP_ABA_BAN_CODIGO_CTA_PGTO],
		[EMP_ABA_CODIGO_CONTA_PGTO],
		[EMP_NU_CONTA_CORRENTE_PAGTO],
		[EMP_TIPO_CONTA],
		[CFU_VLD_CODIGO],
		[EMP_ENDERECO_ELETRONICO_MAIL])
	SELECT
		[EMP_NUMERO_MATRICULA],
		[EMP_NOME_ABREVIADO],
		[EMP_NOME],
		[EMP_INDICADOR_SEXO],
		[EMP_QLP_CAR_CODIGO],
		[CAR_SIGLA],
		[CAR_NOME],
		[EMP_QLP_CAR_OCC_CODIGO],
		[OCC_DESCRICAO],
		[EMP_QLP_CAR_CODIGO_NIVEL],
		[EMP_NSA_CODIGO_PADRAO],
		[EMP_NSA_CODIGO_NIVEL],
		[EMP_QFU_FUN_CODIGO],
		[FUN_DESCRICAO],
		[CFU_NOME],
		[EMP_DEP_CODIGO_LOTACAO],
		[DEP_SIGLA],
		[DEP_NOME],
		[EMP_DEP_CODIGO_FISICO],
		[EMP_UOR_CODIGO_LOTACAO],
		[UOR_SIGLA],
		[EMP_UOR_CODIGO_FISICO],
		[UOR_SIGLA_FISICA],
		[EMP_NU_CARTEIRA_IDENTIDADE],
		[EMP_SIGLA_ORGAO_EMITENTE_CI],
		[EMP_NUMERO_CPF],
		[EMP_NUMERO_CPF_NOTES],
		[EMP_ATI_CT_CUSTOS],
		[EMP_ABA_BAN_CODIGO_CTA_PGTO],
		[EMP_ABA_CODIGO_CONTA_PGTO],
		[EMP_NU_CONTA_CORRENTE_PAGTO],
		[EMP_TIPO_CONTA],
		[CFU_VLD_CODIGO],
		[EMP_ENDERECO_ELETRONICO_MAIL]
   	FROM CORPORATIVO..IFRSRH.EMPREGADOS_INFRAERO
	COMMIT TRAN CARGA_EMPREGADOS_INFRAERO
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_EMPREGADOS_INFRAERO
END CATCH

/*=====================================================================================*/

-- CARGA AEROPORTO COM DADOS DO SMART STREAM
BEGIN TRY
	BEGIN TRAN CARGA_AEROPORTO_SS
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[AEROPORTO_SS] 
	INSERT [dbo].[AEROPORTO_SS] 
	(	   [sig_aeroporto]
		  ,[nom_aeroporto]
		  ,[cod_entidade]
		  ,[cod_regional]
		  ,[cod_aeroporto]
		  ,[dat_criacao]
		  ,[nom_usuario_criacao]
		  ,[dat_alteracao]
		  ,[nom_usuario_alteracao]
		  ,[flg_status]
		  ,[dat_ativacao]
		  ,[flg_stamp])
	SELECT [cd_aerop] 
		  ,[no_aerop] 
		  ,[recv_entity_id] 
		  ,[cd_regional] 
		  ,[cd_aerop_num]
		  ,[date_created] 
		  ,[user_id_created]
		  ,[date_changed]
		  ,[user_id_changed]
		  ,[inactive_ind]
		  ,[active_date]
		  ,[chgstamp] 
	  FROM SQLSSII.GEACutcx.dbo.cor_aeroporto_u
	COMMIT TRAN CARGA_AEROPORTO_SS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_AEROPORTO_SS
END CATCH


/*=====================================================================================*/

--CARGA DE DADOS DOS GRUPOS_DEPENDENCIAS
BEGIN TRY
	BEGIN TRAN CARGA_DADOS_EMPREGADOS
    -- EXCLUI OS DADOS DA TABELA
	DELETE FROM [dbo].[TAB_DADOS_EMPREGADOS] 
	--ACESSO A TABELA GRUPOS_DEPENDENCIAS DO OWNER IFRSRH
	INSERT [dbo].[TAB_DADOS_EMPREGADOS] 
	SELECT 
		  EMP_NUMERO_MATRICULA,
		  EMP_NOME,
		  EMP_NOME_ABREVIADO,
		  EMP_INDICADOR_SEXO,
		  EMP_QLP_HCL_UOR_CODIGO,
		  EMP_QLP_HCL_DATA_VIGENCIA,
		  EMP_QLP_CAR_CODIGO,
		  EMP_QLP_CAR_CODIGO_NIVEL,
		  EMP_QLP_CAR_OCC_CODIGO,
		  EMP_NSA_CODIGO_NIVEL,
		  EMP_NSA_CODIGO_PADRAO,
		  EMP_NSA_IN_NIVEL_ESCOLARIDADE,
		  EMP_QFU_FUN_CODIGO,
		  CAR.FUN_NOME AS NOME_FUNCAO,
		  EMP_QFU_HFL_UOR_CODIGO,
		  EMP_QFU_HFL_DATA_VIGENCIA,
		  EMP_TIPO_REMUNERACAO_FUNCAO,
		  EMP_QFU_FUN_CODIGO_ACUMULA,
		  EMP_QFU_HFL_UOR_COD_ACUM,
		  EMP_QFU_HFL_DATA_VIGEN_ACUM,
		  EMP_TIPO_REMUNER_FUNCAO_ACUMUL,
		  EMP_QFU_FUN_CODIGO_SUBSTITUI,
		  EMP_QFU_HFL_UOR_COD_SUBST,
		  EMP_QFU_HFL_DATA_VIGEN_SUBST,
		  EMP_TIPO_REMUNER_FUNCAO_SUBST,
		  EMP_DEP_CODIGO_LOTACAO,
		  EMP_DEP_CODIGO_PAGTO,
		  EMP_DEP_CODIGO_FISICO,
		  EMP_UOR_CODIGO_LOTACAO,
		  EMP_UOR_CODIGO_FISICO,
		  EMP_STATUS,
		  EMP_DATA_ADMISSAO,
		  EMP_ATI_CT_CUSTOS,
		  EMP_NOME_GUERRA,
		  EMP_ENDERECO_ELETRONICO_MAIL,
		  '(' + CONVERT(VARCHAR(5), EMP_DDD_CELULAR_CORP)  + ') ' + CONVERT(VARCHAR(15), EMP_NUMERO_CELULAR_CORP) AS NUM_CEL_CORPORATIVO,
		  '(' + CONVERT(VARCHAR(5), TEL.DDD)  + ') ' + CONVERT(VARCHAR(15), TEL.TELEFONE) AS NUM_TEL_CORPORATIVO
	FROM CORPORATIVO..IFRSRH.VIW_DADOS_EMPREGADOS EMP
	   LEFT OUTER JOIN CORPORATIVO..IFRSRH.CARGOS_CONFIANCA CAR ON EMP.EMP_QFU_FUN_CODIGO = CAR.FUN_CODIGO
	   LEFT OUTER JOIN CORPORATIVO..IFRAGENDA.CELULAR_CORPORATIVO CEL ON EMP.EMP_NUMERO_MATRICULA = CEL.EMP_MATRICULA
	   LEFT OUTER JOIN CORPORATIVO..IFRAGENDA.VIW_AGE_EMPREGADOS TEL ON EMP.EMP_NUMERO_MATRICULA = TEL.MATRICULA
   WHERE  CAR.FUN_DATA_EXTINCAO IS NULL 
     AND  TEL.I_T = 'I';
	COMMIT TRAN CARGA_DADOS_EMPREGADOS
END TRY
BEGIN CATCH
	ROLLBACK TRAN CARGA_DADOS_EMPREGADOS
END CATCH

/*=====================================================================================*/

/*=====================================================================================*/
--CARGA DE DADOS DA TABELA CIA_AEROPORTOS
BEGIN TRY
	BEGIN TRAN [CARGA_CIA_AEROPORTOS]
    
	DELETE FROM [dbo].[CIA_AEROPORTOS]
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT INTO [dbo].[CIA_AEROPORTOS]
	SELECT  A.COD_AEROPORTO,   -- CODIGO DO AEROPORTO
			NOM_AEROPORTO,	-- NOME DO AEROPORTO  
			SIG_ICAO,   -- SIGLA ICAO DO AEROPORTO
			SIG_IATA,   -- SIGLA IATA DO AEROPORTO
			DSC_DOC_DESIG,   -- DOCUMENTO DE DESIGNAÇÃO
			DAT_DOC_DESIG,   -- DATA DO DOCUMENTO DE DESIGNAÇÃO
			DSC_ORG_ADMIN,   -- ORGÃOS ADMINISTRATIVOS
			NOM_PROPRIET,   -- PROPRIETÁRIO DO AEROPORTO
			DSC_ORG_OFICIAIS,   -- ORGÃO OFICIAIS
			DSC_DOC_HOMOLOG,   -- DOCUMENTO DE HOMOLOGAÇÃO
			ARP_DAT_DOC_HOMOLOG,   -- DATA DO DOCUMENTO DE HOMOLOGAÇÃO
			HOR_FUNCION,   -- HORÁRIO DE FUNCIONAMENTO
			HOR_OPERAC,   -- HORÁRIO DE FUNCIONAMENTO OPERACIONAL  
			HOR_ADM,   -- HORÁRIO DE FUNCIONAMENTO DA ADMINISTRAÇÃO
			HOR_COMERC,   -- HORÁRIO DE FUNCIONAMENTO COMERCIAL
			TAM_TOT_AREA,   -- AREA TOTAL DO AEROPORTO
			TAM_AREA_CIVIL,   -- AREA CIVIL CONFORME ANEXO 14 OACI
			TAM_AREA_A_LEGALIZ,   -- AREA A LEGALIZAR
			TAM_AREA_MILITAR,   -- AREA MILITAR
			TAM_AREA_NAO_LEGALIZ,   -- AREA NÃO LEGALIZADA
			TAM_AREA_EM_REGULARIZ,   -- AREA EMREGULARIZAÇÃO
			TAM_AREA_LEGALIZ,   -- AREA LEGALIZADA
			TAM_AREA_REGULARIZ,   -- AREA REGULARIZADA
			TIP_REFER_PISTA_NUM_CLAS,   -- NUMERO DA CLASSE DE REFERÊNCIA DA PISTA
			TIP_REFER_PISTA_LETRA_CLAS,   -- LETRA DA CLASSE DE REFERÊNCIA DA PISTA
			DSC_CLAS_COM_AERON,   -- CLASSE DE COMUNICAÇÃO AERONÁUTICA
			DSC_DOC_CLAS_COM_AERON,   -- DOCUMENTO DA CLASSE DE COMUNICAÇÃO AERONÁUTICA
			DAT_CLAS_COM_AERON,   -- DATA DO DOCUMENTO DA CLASSE DE COMUNICAÇÃO AERONAUTIC
			TIP_CATEG_TARIF,   -- CATEGORIA TARIFARIA
			DSC_DOC_CATEG_TARIF,   -- DOCUMENTO DA CATEGORIA TARIFÁRIA
			DAT_CATEG_TARIF,   -- DATA DO DOCUMENTO DA CATEGORIA TARIFARIA
			DSC_PLAN_ZONEAM_RUIDO,   -- PLANO DE ZONEAMENTO DE RUIDO
			DSC_DOC_PLAN_ZONEAM_RUIDO,   -- DOCUMENTO DE PLANO DE ZONEAMENTO E RUIDO
			DSC_PLAN_ZONEAM_PROTEC,   -- PLANO DE ZONEMANTO DE PROTEÇÃO
			DSC_DOC_PLAN_ZONEAM_PROTEC,   -- DOCUMENTO DE PLANO  ZONEAMENTO DE PROTEÇÃO
			DSC_CATEG_CONT_INCED_DISP,   -- CATEGORIA CONTRA INCENDIO DISPONÍVEL
			DSC_DOC_CATEG_CONT_INCED_DISP,   -- DOCUMENTO DE CATEGORIA CONTRA INCENDIO DISPONÍVEL
			DSC_UTIL_AEROD,   -- UTILIZAÇÃO DO AERÓDROMO
			TIP_OPERACAO,   -- TIPO DE OPERAÇÕES
			DSC_DOC_TIP_OPERAC,   -- DOCUMENTO TIPO OPERACIONAL
			DSC_DIST_DIREC_AEROP_CID,   -- CATEGORIA CONTRA INCÊNDIO DISPONÍVEL
			DSC_TIP_MED_PERC,   -- TEMPO MÉDIO DE PERCURSO
			TIP_AV_DOM,   -- AVIAÇÃO DOMÉSTICA
			ARP_AV_INT,   -- AVIAÇÃO INTERNACIONAL
			TIP_AV_REGION,   -- AVIAÇÃO REGIONAL
			TIP_AV_GERAL,   -- AVIAÇÃO GERAL
			TIP_AV_MILITAR,   -- AVIAÇÃO MILITAR
			DSC_PONTO_REF,   -- PONTO DE REFERÊNCIA
			DSC_ALTITUDE,   -- ALTITUDE DO AEROPORTO
			QTD_FUNC_EFET_ADM,   --	QUANTIDADE DE FUNCIONÁRIOS EFETIVOS DA ÁREA ADMINISTRATIVA
			QTD_FUNC_EFET_OPER,   --	QUANTIDADE DE FUNCIONÁRIOS EFETIVOS DA ÁREA DE OPERAÇÃO
			QTD_FUNC_EFET_MANUT,   --	QUANTIDADE DE FUNCIONÁRIOS EFETIVOS DA ÁREA DE MANUTENÇÃO
			QTD_FUNC_PREST_SERV,   --	QUANTIDADE DE FUNCIONÁRIOS PRESTADORES DE SERVIÇOS
			QTD_FUNC_CRED_CIAS_AER,   --	QUANTIDADE DE FUNCIONÁRIOS CREDENCIADOS DAS CIAS. AÉREAS
			QTD_FUNC_CRED_COMERC,   --	QUANTIDADE DE FUNCIONÁRIOS CREDENCIADOS DA ÁREA COMERCIAL
			QTD_FUNC_CRED_OUT,   --	QUANTIDADE DE FUNCIONÁRIOS CREDENCIADOS OUTROS
			TAM_COMP_VIAS_ACESSO_DEM_ED,   -- COMPRIMENTO DAS VIAS DE ACESSO AS DEMAIS EDIFICAÇÕES
			TAM_LARG_VIAS_ACESSO_DEM_ED,   -- LARGURA DA VIA DE ACESSO DAS DEMAIS  EDIFICAÇÕES
			DSC_OBS_SISTEM_VIARIO,   -- OBSERVAÇÕES RELATIVAS AO  SISTEMA VIÁRIO
			QTD_PONTES_EMB,   -- QUANTIDADE DE PONTES DE EMBARQUE
			QTD_PAVIMENTOS,   -- QUANTIDADE DE PAVIMENTOS
			TAM_AREA_PONTES_EMB,   -- AREA DE PONTES DE EMBARQUE
			TAM_AREA_PAVIMENTOS,   -- AREA DE PAVIMENTOS
			QTD_NIVEIS_OPER,   -- QUANTIDADE DE NÍVEIS OPERACIONAIS
			TAM_AREA_NIVEIS_OPER,   -- AREA NIVEIS OPERACIONAIS
			QTD_PISO_TECNICO,   -- QUANTIDADE DE PISO TÉCNICO
			TAM_AREA_PISO_TECNICO,   -- AREA DO PISO TECNICO
			QTD_PISO_OPER_DESEMB,   -- UANTIDADE DE PISO OPERACIONAL NO DESEMBARQUE
			TAM_AREA_PISO_OPER_DESEMB,   -- AREA DO PISO OPERACIONAL DE DESEMBARQUE
			QTD_PISO_OPER_EMB,   -- QUANTIDADE DE PISO OPERACIONAL NO EMBARQUE
			TAM_AREA_PISO_OPER_EMB,   -- AREA DO PISO OPERCIONAL DE EMBARQUE
			QTD_PISO_TERR_PANOR,   -- QUANTIDADE DE PISO TERRAÇO PANORÂMICO
			TAM_AREA_PISO_TERR_PANOR,   -- AREA DO PISO DE TERRAÇO PANORÂMICO
			QTD_TOT_AREA_CONST,   -- AREA TOTAL CONTRUIDA
			QTD_MONIT_SAG_DESEMB,   -- QUANTIDADE DE MONITOR DE PLASMA NO SAGUÃO DE DESEMBARQUE
			QTD_MONIT_SL_DESEMB_DOM,   -- QUANTIDADE  DE MONITOR DE PLASMA NA SALA DE DESEMBARQUE DOMÉSTICO
			QTD_MONIT_SL_DESEMB_INT,   -- QUANTIDADE  DE MONITOR DE PLASMA NA SALA DE DESEMBARQUE INTERNACIONAL
			QTD_MONIT_SAG_EMB,   -- QUANTIDADE DE MONITOR DE PLASMA NO SAGUÃO DE EMBARQUE
			QTD_MONIT_SL_EMB_DOM,   -- QUANTIDADE DE MONITOR DE PLASMA NA SALA DE EMBARQUE DOMÉSTICO
			QTD_MONIT_SL_EMB_INT,   -- QUANTIDADE DE MONITOR DE PLASMA NA SALA DE EMBARQUE INTERNACIONAL
			QTD_MONIT_EMB_REV_DOMINT,   -- QUANTIDADE DE MONITOR PLASMA NO SAGUÃO DE EMBARQUE REVERSÍVEL DOMÉSTICO INTERNACIONAL
			QTD_MONIT_TERR_PANOM,   -- QUANTIDADE DE MONITOR NO TERRAÇO PANORÂMICO
			FLG_SINAL_VERT_PORT_EMB,   -- SINAL VERTICAL DE PORTÃO DE EMBARQUE
			FLG_SINAL_VERT_EMB_DOMINT,   -- SINAL VERTICAL DE EMBARQUE DOMÉSTICO INTERNACIONAL
			FLG_SINAL_VERT_DESEMB_DOMINT,   --	SINAL VERTICAL DE DESEMBARQUE DOMÉSTICO E INTERNACIONAL
			FLG_SINAL_VERT_INDIC_CIAS_AER,   --	SINAL VERTICAL DE CIAS AÉREAS
			FLG_SINAL_VERT_ESTACION,   -- SINAL VERTICAL DE ESTACIONAMENTO
			FLG_SINAL_VERT_EMB_DESEMB,   --	SINAL VERTICAL DE EMBARQUE E DESEMBARQUE
			FLG_SINAL_VERT_RESTAUT,   -- SINAL VERTICAL DE RESTAURANTES
			FLG_SINAL_VERT_LANCHONETE,   -- SINAL VERTICAL DE LANCHONETE
			FLG_SINAL_VERT_CAMBIO,   -- SINAL VERTICAL DE CAMBIO
			FLG_SINAL_VERT_FARMACIA,   --	SINAL VERTICAL DE FARMÁCIA
			FLG_SINAL_VERT_BALC_INF,   --	SINAL VERTICAL DO BALCÃO DE INFORMAÇÕES
			FLG_SINAL_VERT_SERV_PUBLICO,   --	SINAL VERTICAL DE SERVIÇO PÚBLICO
			FLG_SINAL_VERT_CORREIOS,   -- SINAL VERTICAL DE CORREIOS
			FLG_SINAL_VERT_TELEFONES,   -- SINAL VERTICAL DE TELEFONES
			FLG_SINAL_VERT_ACH_PERD,   --	SINAL VERTICAL DE ACHADOS E PERDIDOS
			FLG_SINAL_VERT_GUARD_VOL,   --	SINAL VERTICAL DE GUARDA VOLUME
			FLG_SINAL_VERT_SANIT_FEM,   --	SINAL VERTICAL DE SANITARIO FEMININO
			FLG_SINAL_VERT_SANIT_MASC,   --	SINAL VERTICAL DE SANITARIO MASCULINO
			FLG_SINAL_VERT_INF_DEFICIENT,   -- SINAL VERTICAL DE INFORMAÇÕES A DEFICIENTES
			FLG_SINAL_VERT_PROIB_FUMAR,   --	SINAL VERTICAL DE PROIBIDO  FUMAR
			FLG_SINAL_VERT_ACESS_REST,   --	SIANL VERTICAL DE ACESSO AO RESTAURANTE
			FLG_SINAL_VERT_ENT_PROIB,   --	SINAL VERTICAL DE ENTRADA PROIBIDA
			VOL_CARR_BAG_DESEMB_DOM_QTD,   --	QUANTIDADE DE CARROSSEL DE BAGAGEM DE DESEMBARQUE DOMÉSTICO
			VOL_CARR_BAG_DESEMB_DOM_DIAM,   --	DIAMETRO DA AREA DE CARROSSEL DE BAGAGENS DESEMBARQUE DOMÉSTICO
			VOL_CARR_BAG_DESEMB_INTER_QTD,   -- QUANTIDADE DE CARROSSEL DE BAGAGEM DE DESEMBARQUE INTERNACIONAL
			VOL_CARR_BAG_DESEMB_INTER_DIAM,   -- DIAMETRO DA AREA DE CARROSSEL DE BAGAGENS DESEMBARQUE INTERNACIONAL
			TAM_AREA_TRIAG_MAN_EMB_DOM,   -- AREA DE TRIAGEM E MANUSEIO DE BAGAGENS NO EMBARQUE DOMÉSTICO
			TAM_AREA_TRIAG_MAN_EMB_INT,   -- AREA DE TRIAGEM E MANUSEIO DE BAGAGENS NO EMBARQUE INTERNACIONAL
			TAM_AREA_TRIAG_MAN_DESEMB_DOM,   --	AREA DE TRIAGEM E MANUSEIO DE BAGAGENS NO DESEMBARQUE DOMÉSTICO
			TAM_AREA_TRIAG_MAN_DESEMB_INT,   --	AREA DE TRIAGEM E MANUSEIO DE BAGAGENS NO DESEMBARQUE INTERNACIONAL
			ARP_PONT_EMB_FIXA_QTD,   --	QUANTIDADE DE PONTE DE EMBARQUE FIXA
			ARP_PONT_EMB_MOV_QTD,   -- QUANTIDADE DE PONTE DE EMBARQUE MOVEL
			TAM_AREA_ARM_CARG_IMP,   -- AREA DE CARGAS DE IMPORTAÇÃO
			TAM_AREA_ARM_CARG_EXP,   -- AREA DE CARGA  ESPECIAL EXPLOSIVA
			TAM_AREA_ARM_PERDIM,   -- AREA DE CARGA DE PERDIMENTO
			TAM_AREA_ARM_CARG_ESP_PEREC,   -- AREA DE ARMAZENAGEM DE CARGAS ESPECIAIS PERECIVEIS
			TAM_AREA_ARM_CARG_ESP_VIVA,   -- AREA DE CARGA ESPECIAL VIVA
			TAM_AREA_ARM_CARG_ESP_REST,   -- AREA DE ARMAZENAGEM DE CARGA ESPECIAL RESTRITA
			TAM_AREA_DEP_CARG_PERIG_RADIO,   -- AREA DE DEPOSITO DE CARGAS RADIOATIVAS PERIGOSAS
			TAM_AREA_DEP_CARG_PERIG_EXPL,   -- AREA DE DEPOSITO DE CARGAS EXPLOSIVAS PERIGOSAS
			TAM_AREA_DEP_CARG_PERIG_ION,   -- AERA DE DEPOSITO DE CARGAS IONIZANTES PERIGOSAS
			TAM_AREA_MOV_RECEB_DIVERSOS,   -- AREA DE RECEBIMENTO DIVERSOS
			TAM_AREA_MOV_ENTREGA,   -- AREA DE MOVIMENTAÇÃO E ENTREGA
			TAM_AREA_ESC_ADM_RECEIT_INFRA,   -- AREA DO ESCRITORIO DA RECEITA FEDERAL
			TAM_AREA_REC_FEDERAL,   -- AREA DA RECEITA FEDERAL
			TAM_AREA_ESC_ANVISA,   -- AREA DO ESCRITORIA DA ANVISA
			TAM_AREA_DOCAS,   -- AREA DE DOCAS
			TAM_AREA_CARGA_TRANS,   -- AREA DE TRANSPORTE DE CARGAS
			TAM_AREA_CIRC,   -- AREA CIRCULAÇÃO
			FLG_ABAST,   -- TIPO DE ABASTECIMENTO
			DSC_OUTROS_TP_ABAST,   -- DESCRIÇÃO DE OUTROS TIPOS DE ABASTECIMENTOS
			TAM_CORREIOS_AREA_EDIF,   -- AREA EDIFICADA DOS CORREIOS
			TAM_CORREIOS_AREA_ESTC_VEIC,   -- AREA DO ESTACIONAMENTO DE VEICULOS DOS CORREIOS
			TAM_CORREIOS_AREA_LOTE,   -- AREA DO LOTE DOS CORREIOS
			FLG_CLIM_SAGUAO_REFRIG,   -- CLIMATIZAÇÃO DO SAGUÃO REFRIGERAÇÃO
			ARP_CLIM_SAGUAO_CALFEF,   -- CLIMATIZAÇÃO DO SAGUÃO CALEFAÇÃO
			FLG_CLIM_SAGUAO_VENT_MEC,   -- 	CLIMATIZAÇÃO DO SAGUÃO VENTILAÇÃO MECÂNICA
			FLG_CLIM_SLEMB_REFRIG,   -- CLIMATIZAÇÃO DA SALA DE EMBARQUE REFRIGERAÇÃO
			FLG_CLIM_SLEMB_CALEF,   -- CLIMATIZAÇÃO DA SALA DE EMBARQUE CALEFAÇÃO
			FLG_CLIM_SLEMB_VENT_MEC,   -- CLIMATIZAÇÃO DA SALA DE EMBARQUE VENTILAÇÃO MECANICA
			FLG_CLIM_SLDESEMB_REFRIG,   -- CLIMATIZAÇÃO DA SALA DE DESEMBARQUE REFRIGERAÇÃO
			FLG_CLIM_SLDESEMB_CALEF,   -- CLIMATIZAÇÃO DA SALA DE DESEMBARQUE CALEFAÇÃO
			FLG_CLIM_SLDESEMB_VENT_MEC,   -- CLIMATIZAÇÃO DA SALA DE DESEMBARQUE VENTILAÇÃO MECÂNICA
			QTD_ELEVADORES_PUB,   -- QUANTIDADE DE ELEVADORES PÚBLICOS
			QTD_ELEVADORES_SERV,   -- QUANTIDADE DE ELEVADORES DE SERVIÇO
			QTD_ESCAD_ROLANTES,   -- QUANTIDADE DE ESCADAS ROLANTES
			QTD_PORT_AUTOM,   -- QUANTIDADE DE PORTAS AUTMÁTICAS
			QTD_TRANSP_BAG_PADRAO,   -- QUANTIDADE DE TRANSPORTADOR DE BAGAGEM PADRÃO
			QTD_TRANSP_BAG_FORA_PADRAO,   -- QUANTIDADE DE TRANSPORTADOR DE BAGAGEM FORA PADRÃO
			QTD_CARRINHOS_BEBE,   -- QUANTIDADE DE CAIXA PARA PRIMEIROS SOCORROS
			QTD_BEBED_PAD,   -- QUANTIDADE DE BEBEDOUROS PADRÃO
			QTD_BEBED_DEF,   -- QUANTIDADE DE BEBEDOUROS PARA DEFICIENTES
			QTD_TEL_PADRAO,   -- TELEFONES PADRÕES
			QTD_TEL_DEF_LOCOM,   -- TELEFONES PARA DEFICIENTES DE LOCOMOÇÃO
			QTD_TEL_DEF_VISUAL,   -- TELEFONES PARA DEFICIENTES VISUAIS
			QTD_TEL_DEF_AUDIT,   -- TELEFONE PARA DEFICIENTES AUDITIVOS
			QTD_RAMPA_ACESSO_PNE,   -- QUANTIDADE DE RAMPAS DE ACESSO PARA DEFICIENTES
			QTD_CAD_RODAS_PNE,   -- QUANTIDADE DE CADEIRA DE RODAS PARA DEFICIENTES
			QTD_SIST_ELEV_EMBDESEMB,   -- QUANTIDADE DE SISTEMA ELEVATÓRIO EMBARQUE E DESEMBARQUE
			FLG_PESS_ATEND_MED,   -- TIPO DE PESSOAL PARA ATENDIMENTO MÉDICO
			TAM_AREA_ATEND_MED,   -- AREA DO POSTO DE ATENDIMENTO MÉDICO
			NOM_EMP_RESP_ATEND_MED,   -- EMPRESA RESPONSÁVEL PELO ATENDIMENTO MÉDICO
			QTD_UTI_MOVEL,   -- QUANTIDADE DE UTI MÓVEL
			TAM_AREA_UTI_MOVEL,   -- AREA DE UTI MOVEL
			QTD_INSTRUM_MEDICO,   -- QUANTIDADE DE INSTRUMENTOS MÉDICOS
			TAM_AREA_INSTRUM_MEDICO,   -- AREA DE INSTRUMENTOS MÉDICOS
			QTD_SL_PEQ_CIRURG,   -- QUANTIDADE DE SALAS PARA PEQUENAS CIRURGIAS
			TAM_AREA_SL_PEQ_CIRURG,   -- AREA DA SALA DE PEQUENAS CIRURGIAS
			QTD_SL_CURATIVOS,   -- QUANTIDADE DE SALA DE CURATIVOS
			TAM_AREA_SL_CURATIVOS,   -- AREA DA SALA DE CURATIVOS
			QTD_ENFERMARIA,   -- QUANTIDADE DE EMFERMARIA
			TAM_AREA_ENFERMARIA,   -- AREA DE EMFERMARIA
			QTD_CX_PRIM_SOCORR,   -- QUANTIDADE DE ELEVADORES PÚBLICOS
			TAM_AREA_CX_PRIM_SOCORR,   -- AREA DE CAIXA DE PRIMEIROS SOCORROS
			TAM_AREA_REM_EMERG_MED,   -- AREA DE REMOÇÃO DE EMERGÊNCIA MÉDICA
			QTD_AMBUL_COMUM,   -- QUANTIDADE DE AMBULÂNCIA COMUM
			QTD_AMBUL_UTI,   -- QUANTIDADE DE AMBULÂNCIA UTI
			FLG_INDIC_DIR_VENTO_CONV,   -- INDICADOR DE DIREÇÃO DO VENTO CONVENCIONAL
			FLG_INDIC_DIR_VENTO_ILUM,   -- INDICADOR DE DIREÇÃO DO VENTO ILUMINADO
			FLG_LANTERN_SINAL_TORRE,   -- LANTERNA DE SINALIZAÇÃO DE TORRE
			FLG_BALIZ_BORDO_PISTA_NAO_PAV,   -- BALIZAMENTO DE PORTO DE PISTA NÃO PAVIMENTADO
			FLG_BALIZ_BORDO_ZONA_PARADA,   -- BALIZAMENTO DE ZONA DE PARADA
			FLG_BALIZ_BORDO_PTAXI_NAO_PAV,   -- BALIZAMENTO DE PORTO DE TAXI NÃO PAVIMENTADO
			FLG_SERV_LIMPEZA_PISTA,   -- POSSUI SERVIÇO DE LIMPEZA DE PISTA
			NOM_EMP_RESP_SERV_LIMPEZA,   -- EMPRESA RESPONSÁVEL PELO SERVIÇO DE LIMPEZA
			QTD_CARRO_LIMPA_PISTA,   -- QUANTIDADE DE CARRO LIMPA PISTA
			QTD_ROCADEIRA,   -- POSSUI ROÇADEIRA
			QTD_VARREDOURA,   -- POSSUI VARRDOURA
			QTD_REABAST_AGUA_POTAVEL,   -- REABASTECIMENTO DE ÁGUA POTÁVEL
			QTD_ENERG_PATIO_MANOBRAS,   -- FONTES DE ENERGIA NO PATIO DE MANOBRAS
			QTD_REABAST_AR_REFRIG,   -- REABASTECIMENTO DE AR REFRIGERADO
			QTD_POS_DOT_SIST_OTICO_ATRAC,   -- POSIÇÕES DOTADAS DE SISTEMA OTICO DE ATRAÇÃO
			ARP_POS_DOT_SIST_ELET_MEC_ATRA,   -- POSIÇÕES DOTADAS DE SISTEMA ELETRO MECANICO DE ATRAÇÃO
			FLG_SNLZH_PAT_POS_ESTACION,   -- SINALIZAÇÃO DE POSICIONAMENTO DE ESTAÇÃO
			FLG_SNLZH_PAT_AREA_SERV,   -- SINALIZAÇÃO DE LOCALIZAÇÃO DE AREA DE SERVIÇO
			FLG_SNLZH_PAT_VIAS_SERV,   -- SINALIZAÇÃO DE VIAS DE SERVIÇO
			FLG_ARRUAM_INT_VIAS_SERV_ACESS,   -- AREA DE ARRUAMENTO INTERNO DE VIAS DE SERVICO DE ACESSO
			DSC_DIM_ARRUAM_INT_VIAS_ACESS,   -- DIMENSÃO DO ARRUAMENTO DE ACESSO DAS VIAS DE SERVIÇO
			FLG_ARRUAM_INT_ACESS_INTERN,   -- AREA DE ARRUAMENTO INTRNO DE ACESSO INTERNACIONAL
			DSC_DIM_ARRUAM_INT_ACESS_INT,   -- DIMENSÃO DO ARRUAMENTO DE ACESSO INTERNO
			DSC_RAMPA_ACESSO_PNE_RESP,   -- RESPONSÁVEL PELA RAMPA DE ACESSO PARA DEFICIENTES
			DSC_CAD_RODAS_PNE_RESP,   -- RESPONSÁVEL PELAS CADEIRAS DE RODAS
			DSC_SIST_ELEV_EMBDESEMB_RESP,   -- RESPONSÁVEL PELO SISTEMA ELEVATÓRIO DE EMBARQUE E DESEMBARQUE
			DSC_HISTORICO,	-- DESCRICAO DO HISTORICO DO AEROPORTO
			TIP_CERTIFICACAO,   -- TIPO DE CERTIFICACAO DA ANAC
			DSC_DOC_TIP_CERTIFICACAO,  -- DESCRICAO DO DOCUMENTO DO TIPO DA CERTIFICACAO
			(QTD_BALC_CHECK_AUT_DOM_INT + QTD_BALC_CHECK_AUT_TRANSF + QTD_BALC_CHECK_AUT_MEIO_FIO + QTD_BALC_CHECK_NAO_AUT_DOM + QTD_BALC_CHECK_NAO_AUT_INT) as QTD_TOTAL_BALC_CHECK_IN, -- QUANTIDADE TOTAL DE CHECK-INS NO AEROPORTO
			(TAM_CHECK_AUT_DOM_INT + TAM_CHECK_AUT_TRANSF + TAM_CHECK_AUT_MEIO_FIO + TAM_CHECK_NAO_AUT_DOM + TAM_CHECK_NAO_AUT_INT) as TAM_TOTAL_BALC_CHECK_IN, -- TAMANHO TOTAL DE CHECK-INS NO AEROPORTO
			QTD_CHECK_BALANC_DOM_INT, -- QUANTIDADE TOTAL DE BALANÇAS DE CHECK-INS NO AEROPORTO
			QTD_CHECK_BALANC_DOM_INT_CAPAC -- CAPACIDADE TOTAL(EM KG) DAS BALANÇAS DE CHECK-INS NO AEROPORTO
  FROM		CORPORATIVO..IFRCIA.CAD_AEROPORTOS A 
			LEFT OUTER JOIN	CORPORATIVO..IFRCIA.CAD_CHECK_IN C ON A.COD_AEROPORTO = C.COD_AEROPORTO;
	
	COMMIT TRAN [CARGA_CIA_AEROPORTOS]
END TRY
BEGIN CATCH
	ROLLBACK TRAN [CARGA_CIA_AEROPORTOS]
END CATCH


/*=====================================================================================*/

/*=====================================================================================*/

--CARGA DE DADOS DA TABELA CIA_PARQUE_ABASTECIMENTO
BEGIN TRY
	BEGIN TRAN [CARGA_CIA_PARQUE_ABASTECIMENTO]
    
	DELETE FROM [dbo].[CIA_PARQUE_ABASTECIMENTO]
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT INTO [dbo].[CIA_PARQUE_ABASTECIMENTO]
	SELECT 	ABS.COD_EMP_ABAST, -- CODIGO DA EMPRESA DE ABASTECIMENTO
			EMP.DSC_EMP_ABAST, -- NOME DA EMPRESA DE ABASTECIMENTO
			ABS.COD_AEROPORTO, -- CODIGO DO AEROPORTO
			ABS.TIP_COMBUSTIVEL_ABAST, -- TIPO DE COMBUSTIVEL
			ABS.VOL_TANCAGEM_ABAST, -- ABASTECIMENTO E TANCAGEM DA EMPRESA
			ABS.TAM_AREA_LOTE_ABAST -- LOTE DA AREA DE ABASTECIMENTO DA EMPRESA
	 FROM 	CORPORATIVO..IFRCIA.CAD_PARQUE_ABASTECIMENTO ABS
		, 	CORPORATIVO..IFRCIA.TAB_EMP_ABASTECIMENTO EMP
	WHERE 	ABS.COD_EMP_ABAST = EMP.COD_EMP_ABAST

	COMMIT TRAN [CARGA_CIA_PARQUE_ABASTECIMENTO]
END TRY
BEGIN CATCH
	ROLLBACK TRAN [CARGA_CIA_PARQUE_ABASTECIMENTO]
END CATCH


/*=====================================================================================*/

/*=====================================================================================*/

--CARGA DE DADOS DA TABELA CIA_CABEC_PISTA_POUSO_DEC
BEGIN TRY
	BEGIN TRAN [CARGA_CIA_CABEC_PISTA_POUSO_DEC]
    
	DELETE FROM [dbo].[CIA_CABEC_PISTA_POUSO_DEC]
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT INTO [dbo].[CIA_CABEC_PISTA_POUSO_DEC]
	SELECT 	COD_AEROPORTO, -- CODIGO DO AEROPORTO
			DSC_IDENTI_CABEC_PISTA, -- IDENTIFICAÇÃO DA CABECEIRA
			TAM_DIMENS_STOPWAY, -- DIMENSÃO DA STOPWAY
			QTD_NAT_PISO_STOPWAY, -- NATUREZA DO PISO DA STOPWAY
			TAM_DIMENS_CLEARWAY, -- DIMESÃO DA CLEARWAY
			DSC_DIMENS_FAIXA_PISTA, -- DIMENSÃO DA FAIXA DE PISTA
			TAM_DIST_EIXOPIST_BORDAPAT, -- DISTANCIA  DO EIXO DA PISTA E BORDA DO PÁTIO
			DSC_DIMENS_STOPWAY_FONTE, -- FONTE DA DIMENSÃO DA STOPWAY
			DSC_NAT_PISO_STOPWAY_FONTE, -- FONTE DA NATUREZA DO PISO DA STOPWAY
			DSC_DIMENS_CLEARWAY_FONTE, -- FONTE DA DIMENSÃO DA CLEARWAY
			DSC_DIMENS_FX_PISTA_FONTE, -- FONTE DA DIMENSÃO DE FAIXA DE PISTA
			DSC_DIST_EIXO_BORDA_FONTE, -- FONTE DA DISTANCIA DO EIXO E BORDA
			TAM_TORA, -- TORA DA CABCEIRA
			TAM_ASDA, -- DISTANCIA DECLARADA ASDA
			TAM_TODA, -- TODA DA CABECEIRA
			TAM_LDA, -- LDA CA CABECEIRA
			DSC_TORA_FONTE, -- FONTE DA DISTANCIA DECLARADA TORA
			DSC_ASDA_FONTE, -- FONTE DA DISTANCIA ASDA
			DSC_TODA_FONTE, -- FONTE DA DISTANCIA DECLARADA TODA
			DSC_LDA_FONTE, -- FONTE LDA
			TAM_AREA_GIRO_RAIO, -- RAIO DA ÁREA DE GIRO DA CABECEIRA
			DSC_AREA_GIRO_OBS, -- OBSERVAÇÃO DA AREA DE GIRO DA CABECEIRA
			TAM_DIST_CABECEIRA, -- DISTANCIA DA CABECEIRA
			TAM_DIST_CABEC_RAIO, -- DISTANCIA DA CABECEIRA E O RAIO
			FLG_VFR, -- VFR DA CABECEIRA
			FLG_IFR, -- IFR DA CABECEIRA
			FLG_CATEG_IFR_PREC, -- CATEGORIA IFR DE PRECISÃO
			CABEC.COD_NAT_PISO, -- CÓDIGO DA NATUREZA DO PISO
			DESC_NAT.DSC_NAT_PISO -- DESC. DA NATUREZA DO PISO
	 FROM 	CORPORATIVO..IFRCIA.CAD_CABEC_PISTA_POUSO_DEC CABEC
		, 	CORPORATIVO..IFRCIA.TAB_NAT_PISO DESC_NAT
	WHERE 	CABEC.COD_NAT_PISO = DESC_NAT.COD_NAT_PISO

	COMMIT TRAN [CARGA_CIA_CABEC_PISTA_POUSO_DEC]
END TRY
BEGIN CATCH
	ROLLBACK TRAN [CARGA_CIA_CABEC_PISTA_POUSO_DEC]
END CATCH


/*=====================================================================================*/

/*=====================================================================================*/

--CARGA DE DADOS DA TABELA CIA_PISTAS_POUSO_DEC
BEGIN TRY
	BEGIN TRAN [CARGA_CIA_PISTAS_POUSO_DEC]
    
	DELETE FROM [dbo].[CIA_PISTAS_POUSO_DEC]
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT INTO [dbo].[CIA_PISTAS_POUSO_DEC]
	SELECT 	COD_AEROPORTO, -- CODIGO DO AEROPORTO
			COD_PISTA_IDENT,  -- IDENTIFICAÇÃO DA PISTA
			TAM_COMPRIMENTO_PISTA,  -- COMPRIMENTO DA PISTA
			TAM_LARGURA_PISTA,  -- LARGURA DA PISTA
			TIP_PISO_PISTA,  -- TIPO DO PISO
			DSC_RESIST_PISTA,  -- RESISTÊNCIA DA PISTA
			TAM_ACOST_LARGURA,  -- LARGURA DO ACOSTAMENTO
			TAM_ACOST_NAT_PISO,  -- NATUREZA DO PISO DO ACOSTAMENTO
			PISTA.COD_NAT_PISO,  -- CÓDIGO DA NATUREZA DO PISO
			DESC_NAT.DSC_NAT_PISO  -- DESC. DA NATUREZA DO PISO
	 FROM 	CORPORATIVO..IFRCIA.CAD_PISTAS_POUSO_DEC PISTA
		, 	CORPORATIVO..IFRCIA.TAB_NAT_PISO DESC_NAT
	WHERE  	PISTA.COD_NAT_PISO = DESC_NAT.COD_NAT_PISO

	COMMIT TRAN [CARGA_CIA_PISTAS_POUSO_DEC]
END TRY
BEGIN CATCH
	ROLLBACK TRAN [CARGA_CIA_PISTAS_POUSO_DEC]
END CATCH

/*=====================================================================================*/

/*=====================================================================================*/


/*=====================================================================================*/

/*=====================================================================================*/

--CARGA DE DADOS DA TABELA SISC_CATEGORIA_SEGURANCA_AEROPORTO
BEGIN TRY
	BEGIN TRAN [CARGA_NPCR]
    
	DELETE FROM [dbo].[SISC_CATEGORIA_SEGURANCA_AEROPORTO]
	--ACESSO A TABELA DEPENDENCIAS DO OWNER IFRDBA2
	INSERT INTO [dbo].[SISC_CATEGORIA_SEGURANCA_AEROPORTO]
		SELECT	DEP.DEP_SIGLA , --SIGLA DO AEROPORTO
				SIG_CLASSE_AERODROMO as CLASSE_AERODROMO, --CLASSE DE SEGURANÇA DO AEROPORTO
				COD_CATEGORIA_REQUERIDA as CATEGORIA_REQUERIDA, --CATEGORIA REQUERIDA DE SEGURANÇA DO AEROPORTO
				COD_CATEGORIA_EXISTENTE as CATEGORIA_EXISTENTE --CATEGORIA EXISTENTE DE SEGURANÇA DO AEROPORTO
		  FROM	CORPORATIVO..IFRSISC.CAD_AERODROMO_SALVAMENTO S,
				CORPORATIVO..IFRSISC.TAB_CLASSE_AERODROMO C,
				CORPORATIVO..IFRDBA2.DEPENDENCIAS DEP
		 WHERE	C.SEQ_CLASSE_AERODROMO = S.SEQ_CLASSE_AERODROMO
		   AND	S.SEQ_AERODROMO_SALVAMENTO = DEP.DEP_CODIGO

	COMMIT TRAN [CARGA_NPCR]
END TRY
BEGIN CATCH
	ROLLBACK TRAN [CARGA_NPCR]
END CATCH

/*=====================================================================================*/

/*=====================================================================================*/

END




GO

