USE [IFRCORP]
GO

/****** Object:  Table [dbo].[CIA_AEROPORTOS]    Script Date: 24/02/2015 13:02:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_AEROPORTOS](
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[NOM_AEROPORTO] [varchar](30) NULL,
	[SIG_ICAO] [varchar](4) NULL,
	[SIG_IATA] [varchar](4) NULL,
	[DSC_DOC_DESIG] [varchar](30) NULL,
	[DAT_DOC_DESIG] [datetime2](7) NULL,
	[DSC_ORG_ADMIN] [varchar](30) NULL,
	[NOM_PROPRIET] [varchar](30) NULL,
	[DSC_ORG_OFICIAIS] [varchar](800) NULL,
	[DSC_DOC_HOMOLOG] [varchar](50) NULL,
	[ARP_DAT_DOC_HOMOLOG] [datetime2](7) NULL,
	[HOR_FUNCION] [varchar](40) NULL,
	[HOR_OPERAC] [varchar](40) NULL,
	[HOR_ADM] [varchar](40) NULL,
	[HOR_COMERC] [varchar](40) NULL,
	[TAM_TOT_AREA] [numeric](15, 2) NULL,
	[TAM_AREA_CIVIL] [numeric](15, 2) NULL,
	[TAM_AREA_A_LEGALIZ] [numeric](15, 2) NULL,
	[TAM_AREA_MILITAR] [numeric](15, 2) NULL,
	[TAM_AREA_NAO_LEGALIZ] [numeric](15, 2) NULL,
	[TAM_AREA_EM_REGULARIZ] [numeric](15, 2) NULL,
	[TAM_AREA_LEGALIZ] [numeric](15, 2) NULL,
	[TAM_AREA_REGULARIZ] [numeric](15, 2) NULL,
	[TIP_REFER_PISTA_NUM_CLAS] [varchar](2) NULL,
	[TIP_REFER_PISTA_LETRA_CLAS] [varchar](2) NULL,
	[DSC_CLAS_COM_AERON] [varchar](2) NULL,
	[DSC_DOC_CLAS_COM_AERON] [varchar](30) NULL,
	[DAT_CLAS_COM_AERON] [varchar](30) NULL,
	[TIP_CATEG_TARIF] [varchar](2) NULL,
	[DSC_DOC_CATEG_TARIF] [varchar](30) NULL,
	[DAT_CATEG_TARIF] [varchar](30) NULL,
	[DSC_PLAN_ZONEAM_RUIDO] [varchar](50) NULL,
	[DSC_DOC_PLAN_ZONEAM_RUIDO] [varchar](60) NULL,
	[DSC_PLAN_ZONEAM_PROTEC] [varchar](60) NULL,
	[DSC_DOC_PLAN_ZONEAM_PROTEC] [varchar](60) NULL,
	[DSC_CATEG_CONT_INCED_DISP] [varchar](2) NULL,
	[DSC_DOC_CATEG_CONT_INCED_DISP] [varchar](60) NULL,
	[DSC_UTIL_AEROD] [numeric](2, 0) NULL,
	[TIP_OPERACAO] [numeric](2, 0) NULL,
	[DSC_DOC_TIP_OPERAC] [varchar](60) NULL,
	[DSC_DIST_DIREC_AEROP_CID] [varchar](150) NULL,
	[DSC_TIP_MED_PERC] [varchar](100) NULL,
	[TIP_AV_DOM] [varchar](1) NULL,
	[ARP_AV_INT] [varchar](1) NULL,
	[TIP_AV_REGION] [varchar](1) NULL,
	[TIP_AV_GERAL] [varchar](1) NULL,
	[TIP_AV_MILITAR] [varchar](1) NULL,
	[DSC_PONTO_REF] [varchar](25) NULL,
	[DSC_ALTITUDE] [varchar](15) NULL,
	[QTD_FUNC_EFET_ADM] [numeric](8, 0) NULL,
	[QTD_FUNC_EFET_OPER] [numeric](8, 0) NULL,
	[QTD_FUNC_EFET_MANUT] [numeric](8, 0) NULL,
	[QTD_FUNC_PREST_SERV] [numeric](8, 0) NULL,
	[QTD_FUNC_CRED_CIAS_AER] [numeric](8, 0) NULL,
	[QTD_FUNC_CRED_COMERC] [numeric](8, 0) NULL,
	[QTD_FUNC_CRED_OUT] [numeric](8, 0) NULL,
	[TAM_COMP_VIAS_ACESSO_DEM_ED] [numeric](15, 2) NULL,
	[TAM_LARG_VIAS_ACESSO_DEM_ED] [numeric](15, 2) NULL,
	[DSC_OBS_SISTEM_VIARIO] [varchar](250) NULL,
	[QTD_PONTES_EMB] [numeric](2, 0) NULL,
	[QTD_PAVIMENTOS] [numeric](2, 0) NULL,
	[TAM_AREA_PONTES_EMB] [numeric](15, 2) NULL,
	[TAM_AREA_PAVIMENTOS] [numeric](15, 2) NULL,
	[QTD_NIVEIS_OPER] [numeric](5, 0) NULL,
	[TAM_AREA_NIVEIS_OPER] [numeric](15, 2) NULL,
	[QTD_PISO_TECNICO] [numeric](2, 0) NULL,
	[TAM_AREA_PISO_TECNICO] [numeric](15, 2) NULL,
	[QTD_PISO_OPER_DESEMB] [numeric](2, 0) NULL,
	[TAM_AREA_PISO_OPER_DESEMB] [numeric](15, 2) NULL,
	[QTD_PISO_OPER_EMB] [numeric](2, 0) NULL,
	[TAM_AREA_PISO_OPER_EMB] [numeric](15, 2) NULL,
	[QTD_PISO_TERR_PANOR] [numeric](2, 0) NULL,
	[TAM_AREA_PISO_TERR_PANOR] [numeric](15, 2) NULL,
	[QTD_TOT_AREA_CONST] [numeric](17, 2) NULL,
	[QTD_MONIT_SAG_DESEMB] [numeric](4, 0) NULL,
	[QTD_MONIT_SL_DESEMB_DOM] [numeric](4, 0) NULL,
	[QTD_MONIT_SL_DESEMB_INT] [numeric](4, 0) NULL,
	[QTD_MONIT_SAG_EMB] [numeric](4, 0) NULL,
	[QTD_MONIT_SL_EMB_DOM] [numeric](4, 0) NULL,
	[QTD_MONIT_SL_EMB_INT] [numeric](4, 0) NULL,
	[QTD_MONIT_EMB_REV_DOMINT] [numeric](4, 0) NULL,
	[QTD_MONIT_TERR_PANOM] [numeric](4, 0) NULL,
	[FLG_SINAL_VERT_PORT_EMB] [varchar](1) NULL,
	[FLG_SINAL_VERT_EMB_DOMINT] [varchar](1) NULL,
	[FLG_SINAL_VERT_DESEMB_DOMINT] [varchar](1) NULL,
	[FLG_SINAL_VERT_INDIC_CIAS_AER] [varchar](1) NULL,
	[FLG_SINAL_VERT_ESTACION] [varchar](1) NULL,
	[FLG_SINAL_VERT_EMB_DESEMB] [varchar](1) NULL,
	[FLG_SINAL_VERT_RESTAUT] [varchar](1) NULL,
	[FLG_SINAL_VERT_LANCHONETE] [varchar](1) NULL,
	[FLG_SINAL_VERT_CAMBIO] [varchar](1) NULL,
	[FLG_SINAL_VERT_FARMACIA] [varchar](1) NULL,
	[FLG_SINAL_VERT_BALC_INF] [varchar](1) NULL,
	[FLG_SINAL_VERT_SERV_PUBLICO] [varchar](1) NULL,
	[FLG_SINAL_VERT_CORREIOS] [varchar](1) NULL,
	[FLG_SINAL_VERT_TELEFONES] [varchar](1) NULL,
	[FLG_SINAL_VERT_ACH_PERD] [varchar](1) NULL,
	[FLG_SINAL_VERT_GUARD_VOL] [varchar](1) NULL,
	[FLG_SINAL_VERT_SANIT_FEM] [varchar](1) NULL,
	[FLG_SINAL_VERT_SANIT_MASC] [varchar](1) NULL,
	[FLG_SINAL_VERT_INF_DEFICIENT] [varchar](1) NULL,
	[FLG_SINAL_VERT_PROIB_FUMAR] [varchar](1) NULL,
	[FLG_SINAL_VERT_ACESS_REST] [varchar](1) NULL,
	[FLG_SINAL_VERT_ENT_PROIB] [varchar](1) NULL,
	[VOL_CARR_BAG_DESEMB_DOM_QTD] [numeric](2, 0) NULL,
	[VOL_CARR_BAG_DESEMB_DOM_DIAM] [numeric](5, 2) NULL,
	[VOL_CARR_BAG_DESEMB_INTER_QTD] [numeric](2, 0) NULL,
	[VOL_CARR_BAG_DESEMB_INTER_DIAM] [numeric](5, 2) NULL,
	[TAM_AREA_TRIAG_MAN_EMB_DOM] [numeric](10, 2) NULL,
	[TAM_AREA_TRIAG_MAN_EMB_INT] [numeric](10, 2) NULL,
	[TAM_AREA_TRIAG_MAN_DESEMB_DOM] [numeric](10, 2) NULL,
	[TAM_AREA_TRIAG_MAN_DESEMB_INT] [numeric](10, 2) NULL,
	[ARP_PONT_EMB_FIXA_QTD] [numeric](2, 0) NULL,
	[ARP_PONT_EMB_MOV_QTD] [numeric](2, 0) NULL,
	[TAM_AREA_ARM_CARG_IMP] [numeric](15, 2) NULL,
	[TAM_AREA_ARM_CARG_EXP] [numeric](15, 2) NULL,
	[TAM_AREA_ARM_PERDIM] [numeric](15, 2) NULL,
	[TAM_AREA_ARM_CARG_ESP_PEREC] [numeric](15, 2) NULL,
	[TAM_AREA_ARM_CARG_ESP_VIVA] [numeric](15, 2) NULL,
	[TAM_AREA_ARM_CARG_ESP_REST] [numeric](15, 2) NULL,
	[TAM_AREA_DEP_CARG_PERIG_RADIO] [numeric](15, 2) NULL,
	[TAM_AREA_DEP_CARG_PERIG_EXPL] [numeric](15, 2) NULL,
	[TAM_AREA_DEP_CARG_PERIG_ION] [numeric](15, 2) NULL,
	[TAM_AREA_MOV_RECEB_DIVERSOS] [numeric](15, 2) NULL,
	[TAM_AREA_MOV_ENTREGA] [numeric](15, 2) NULL,
	[TAM_AREA_ESC_ADM_RECEIT_INFRA] [numeric](15, 2) NULL,
	[TAM_AREA_REC_FEDERAL] [numeric](15, 2) NULL,
	[TAM_AREA_ESC_ANVISA] [numeric](15, 2) NULL,
	[TAM_AREA_DOCAS] [numeric](15, 2) NULL,
	[TAM_AREA_CARGA_TRANS] [numeric](15, 2) NULL,
	[TAM_AREA_CIRC] [numeric](15, 2) NULL,
	[FLG_ABAST] [varchar](1) NULL,
	[DSC_OUTROS_TP_ABAST] [varchar](100) NULL,
	[TAM_CORREIOS_AREA_EDIF] [numeric](10, 2) NULL,
	[TAM_CORREIOS_AREA_ESTC_VEIC] [numeric](10, 2) NULL,
	[TAM_CORREIOS_AREA_LOTE] [numeric](10, 2) NULL,
	[FLG_CLIM_SAGUAO_REFRIG] [varchar](1) NULL,
	[ARP_CLIM_SAGUAO_CALFEF] [varchar](1) NULL,
	[FLG_CLIM_SAGUAO_VENT_MEC] [varchar](1) NULL,
	[FLG_CLIM_SLEMB_REFRIG] [varchar](1) NULL,
	[FLG_CLIM_SLEMB_CALEF] [varchar](1) NULL,
	[FLG_CLIM_SLEMB_VENT_MEC] [varchar](1) NULL,
	[FLG_CLIM_SLDESEMB_REFRIG] [varchar](1) NULL,
	[FLG_CLIM_SLDESEMB_CALEF] [varchar](1) NULL,
	[FLG_CLIM_SLDESEMB_VENT_MEC] [varchar](1) NULL,
	[QTD_ELEVADORES_PUB] [numeric](3, 0) NULL,
	[QTD_ELEVADORES_SERV] [numeric](3, 0) NULL,
	[QTD_ESCAD_ROLANTES] [numeric](3, 0) NULL,
	[QTD_PORT_AUTOM] [numeric](3, 0) NULL,
	[QTD_TRANSP_BAG_PADRAO] [numeric](8, 0) NULL,
	[QTD_TRANSP_BAG_FORA_PADRAO] [numeric](8, 0) NULL,
	[QTD_CARRINHOS_BEBE] [numeric](8, 0) NULL,
	[QTD_BEBED_PAD] [numeric](3, 0) NULL,
	[QTD_BEBED_DEF] [numeric](3, 0) NULL,
	[QTD_TEL_PADRAO] [numeric](4, 0) NULL,
	[QTD_TEL_DEF_LOCOM] [numeric](3, 0) NULL,
	[QTD_TEL_DEF_VISUAL] [numeric](3, 0) NULL,
	[QTD_TEL_DEF_AUDIT] [numeric](3, 0) NULL,
	[QTD_RAMPA_ACESSO_PNE] [numeric](3, 0) NULL,
	[QTD_CAD_RODAS_PNE] [numeric](3, 0) NULL,
	[QTD_SIST_ELEV_EMBDESEMB] [numeric](3, 0) NULL,
	[FLG_PESS_ATEND_MED] [varchar](1) NULL,
	[TAM_AREA_ATEND_MED] [numeric](10, 2) NULL,
	[NOM_EMP_RESP_ATEND_MED] [varchar](100) NULL,
	[QTD_UTI_MOVEL] [numeric](2, 0) NULL,
	[TAM_AREA_UTI_MOVEL] [numeric](10, 2) NULL,
	[QTD_INSTRUM_MEDICO] [numeric](2, 0) NULL,
	[TAM_AREA_INSTRUM_MEDICO] [numeric](10, 2) NULL,
	[QTD_SL_PEQ_CIRURG] [numeric](2, 0) NULL,
	[TAM_AREA_SL_PEQ_CIRURG] [numeric](10, 2) NULL,
	[QTD_SL_CURATIVOS] [numeric](2, 0) NULL,
	[TAM_AREA_SL_CURATIVOS] [numeric](10, 2) NULL,
	[QTD_ENFERMARIA] [numeric](2, 0) NULL,
	[TAM_AREA_ENFERMARIA] [numeric](10, 2) NULL,
	[QTD_CX_PRIM_SOCORR] [numeric](2, 0) NULL,
	[TAM_AREA_CX_PRIM_SOCORR] [numeric](10, 2) NULL,
	[TAM_AREA_REM_EMERG_MED] [numeric](10, 2) NULL,
	[QTD_AMBUL_COMUM] [numeric](2, 0) NULL,
	[QTD_AMBUL_UTI] [numeric](2, 0) NULL,
	[FLG_INDIC_DIR_VENTO_CONV] [varchar](1) NULL,
	[FLG_INDIC_DIR_VENTO_ILUM] [varchar](1) NULL,
	[FLG_LANTERN_SINAL_TORRE] [varchar](1) NULL,
	[FLG_BALIZ_BORDO_PISTA_NAO_PAV] [varchar](1) NULL,
	[FLG_BALIZ_BORDO_ZONA_PARADA] [varchar](1) NULL,
	[FLG_BALIZ_BORDO_PTAXI_NAO_PAV] [varchar](1) NULL,
	[FLG_SERV_LIMPEZA_PISTA] [varchar](1) NULL,
	[NOM_EMP_RESP_SERV_LIMPEZA] [varchar](30) NULL,
	[QTD_CARRO_LIMPA_PISTA] [numeric](2, 0) NULL,
	[QTD_ROCADEIRA] [numeric](2, 0) NULL,
	[QTD_VARREDOURA] [numeric](2, 0) NULL,
	[QTD_REABAST_AGUA_POTAVEL] [numeric](2, 0) NULL,
	[QTD_ENERG_PATIO_MANOBRAS] [numeric](2, 0) NULL,
	[QTD_REABAST_AR_REFRIG] [numeric](2, 0) NULL,
	[QTD_POS_DOT_SIST_OTICO_ATRAC] [numeric](2, 0) NULL,
	[ARP_POS_DOT_SIST_ELET_MEC_ATRA] [numeric](2, 0) NULL,
	[FLG_SNLZH_PAT_POS_ESTACION] [varchar](1) NULL,
	[FLG_SNLZH_PAT_AREA_SERV] [varchar](1) NULL,
	[FLG_SNLZH_PAT_VIAS_SERV] [varchar](1) NULL,
	[FLG_ARRUAM_INT_VIAS_SERV_ACESS] [varchar](1) NULL,
	[DSC_DIM_ARRUAM_INT_VIAS_ACESS] [varchar](15) NULL,
	[FLG_ARRUAM_INT_ACESS_INTERN] [varchar](1) NULL,
	[DSC_DIM_ARRUAM_INT_ACESS_INT] [varchar](15) NULL,
	[DSC_RAMPA_ACESSO_PNE_RESP] [varchar](30) NULL,
	[DSC_CAD_RODAS_PNE_RESP] [varchar](30) NULL,
	[DSC_SIST_ELEV_EMBDESEMB_RESP] [varchar](30) NULL,
	[DSC_HISTORICO] [text] NULL,
	[TIP_CERTIFICACAO] [numeric](2, 0) NULL,
	[DSC_DOC_TIP_CERTIFICACAO] [varchar](60) NULL,
	[QTD_TOTAL_BALC_CHECK_IN] [int] NULL,
	[TAM_TOTAL_BALC_CHECK_IN] [int] NULL,
	[QTD_CHECK_BALANC_DOM_INT] [int] NULL,
	[QTD_CHECK_BALANC_DOM_INT_CAPAC] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_CABEC_PISTA_POUSO_DEC]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_CABEC_PISTA_POUSO_DEC](
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[DSC_IDENTI_CABEC_PISTA] [varchar](3) NOT NULL,
	[TAM_DIMENS_STOPWAY] [numeric](12, 2) NULL,
	[QTD_NAT_PISO_STOPWAY] [numeric](2, 0) NULL,
	[TAM_DIMENS_CLEARWAY] [numeric](12, 2) NULL,
	[DSC_DIMENS_FAIXA_PISTA] [varchar](15) NULL,
	[TAM_DIST_EIXOPIST_BORDAPAT] [numeric](5, 2) NULL,
	[DSC_DIMENS_STOPWAY_FONTE] [varchar](20) NULL,
	[DSC_NAT_PISO_STOPWAY_FONTE] [varchar](20) NULL,
	[DSC_DIMENS_CLEARWAY_FONTE] [varchar](20) NULL,
	[DSC_DIMENS_FX_PISTA_FONTE] [varchar](20) NULL,
	[DSC_DIST_EIXO_BORDA_FONTE] [varchar](20) NULL,
	[TAM_TORA] [numeric](7, 2) NULL,
	[TAM_ASDA] [numeric](7, 2) NULL,
	[TAM_TODA] [numeric](7, 2) NULL,
	[TAM_LDA] [numeric](7, 2) NULL,
	[DSC_TORA_FONTE] [varchar](20) NULL,
	[DSC_ASDA_FONTE] [varchar](20) NULL,
	[DSC_TODA_FONTE] [varchar](20) NULL,
	[DSC_LDA_FONTE] [varchar](20) NULL,
	[TAM_AREA_GIRO_RAIO] [numeric](5, 2) NULL,
	[DSC_AREA_GIRO_OBS] [varchar](250) NULL,
	[TAM_DIST_CABECEIRA] [numeric](5, 2) NULL,
	[TAM_DIST_CABEC_RAIO] [numeric](5, 2) NULL,
	[FLG_VFR] [varchar](1) NULL,
	[FLG_IFR] [varchar](1) NULL,
	[FLG_CATEG_IFR_PREC] [varchar](1) NULL,
	[COD_NAT_PISO] [numeric](2, 0) NOT NULL,
	[DSC_NAT_PISO] [varchar](40) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_PARQUE_ABASTECIMENTO]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_PARQUE_ABASTECIMENTO](
	[COD_EMP_ABAST] [numeric](7, 0) NOT NULL,
	[DSC_EMP_ABAST] [varchar](40) NULL,
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[TIP_COMBUSTIVEL_ABAST] [varchar](1) NOT NULL,
	[VOL_TANCAGEM_ABAST] [numeric](17, 2) NULL,
	[TAM_AREA_LOTE_ABAST] [numeric](15, 2) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_PATIOS]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_PATIOS](
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[DSC_DESIG_PATIO] [varchar](8) NOT NULL,
	[DSC_LOCALIZACAO_PATIO] [varchar](30) NULL,
	[DSC_PROFUND_PATIO] [varchar](30) NULL,
	[DSC_AREA] [varchar](15) NULL,
	[DSC_PCN] [varchar](15) NULL,
	[DSC_NAT_PISO] [varchar](40) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_PISTAS_POUSO_DEC]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_PISTAS_POUSO_DEC](
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[COD_PISTA_IDENT] [varchar](5) NOT NULL,
	[TAM_COMPRIMENTO_PISTA] [numeric](10, 2) NULL,
	[TAM_LARGURA_PISTA] [numeric](10, 2) NULL,
	[TIP_PISO_PISTA] [numeric](2, 0) NULL,
	[DSC_RESIST_PISTA] [varchar](20) NULL,
	[TAM_ACOST_LARGURA] [numeric](10, 2) NULL,
	[TAM_ACOST_NAT_PISO] [numeric](10, 2) NULL,
	[COD_NAT_PISO] [int] NULL,
	[DSC_NAT_PISO] [varchar](40) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_PISTAS_TAXI]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_PISTAS_TAXI](
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[DSC_IDENT_PISTA_TAX] [varchar](10) NOT NULL,
	[TAM_LARG_PISTA_TAX] [numeric](10, 2) NULL,
	[TAM_COMP_PISTA_TAX] [numeric](10, 2) NULL,
	[TAM_ACOSTAM_LARG] [numeric](5, 2) NULL,
	[QTD_ACOSTAM_NAT_PISO] [numeric](2, 0) NULL,
	[DSC_ANG_REL_PISTA_POUSO] [varchar](3) NULL,
	[DSC_RESIST_PAVIM] [varchar](10) NULL,
	[FLG_PISTA_ALTERN] [varchar](1) NULL,
	[DSC_DIST_REL_CABEC] [varchar](40) NULL,
	[DSC_NAT_PISO] [varchar](40) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[CIA_TRANSP_PASSAGEIROS]    Script Date: 24/02/2015 13:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIA_TRANSP_PASSAGEIROS](
	[COD_VEICULO] [numeric](5, 0) NOT NULL,
	[COD_AEROPORTO] [numeric](4, 0) NOT NULL,
	[DESC_TIPO_VEIC] [varchar](30) NULL,
	[QTD_VEIC] [numeric](3, 0) NULL,
	[NOM_EMP_RESP] [varchar](30) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

