--Conectar com IFRTECA
--

--
-- TAB_TKP_CLT  (Table) 
--
CREATE TABLE IFRTECA.TAB_TKP_CLT
(
  COD_CLT            NUMBER                     NOT NULL,
  NOM_CLT            VARCHAR2(30)          NOT NULL,
  NOM_RGNAL_CLT      VARCHAR2(30)          NOT NULL,
  COD_SENHA_CLT      VARCHAR2(30)          NOT NULL,
  NOM_DBLINK_CRRNTA  VARCHAR2(30)              NULL
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 128k next 128k pctincrease 0)
/


--
-- TKP_FAVORITOS  (Table) 
--
CREATE TABLE IFRTECA.TKP_FAVORITOS
(
  US_CODIGO  CHAR(10)                      NOT NULL,
  ID_MENU    NUMBER                             NOT NULL
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 128k next 128k pctincrease 0)
/


--
-- TKP_GRUPOS  (Table) 
--
CREATE TABLE IFRTECA.TKP_GRUPOS
(
  COD_GRUPO   CHAR(1)                          NULL,
  DESC_GRUPO  VARCHAR2(40)                     NULL
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 128k next 128k pctincrease 0)
/


--
-- TKP_LOG_ACESSO  (Table) 
--
CREATE TABLE IFRTECA.TKP_LOG_ACESSO
(
  US_CODIGO   CHAR(10)                         NULL,
  DT_ACESSO   DATE                                  NULL,
  END_ACESSO  VARCHAR2(512)                    NULL
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 10M next 10M pctincrease 0)
/


--
-- TKP_MENU  (Table) 
--
CREATE TABLE IFRTECA.TKP_MENU
(
  ID_MENU               INTEGER                     NULL,
  PAG_MENU              VARCHAR2(60)           NULL,
  DESC_MENU             VARCHAR2(80)           NULL,
  GRUPO_MENU            VARCHAR2(40)           NULL,
  ORDER_GRUPO           INTEGER                     NULL,
  ORDER_PAGINA          INTEGER                     NULL,
  COD_ITEM_OBRIGATORIO  NUMBER(1)                   NULL,
  COD_GRUPO             CHAR(1)                NULL
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 128k next 128k pctincrease 0)
/


--
-- TKP_PERMISSAO_MENU  (Table) 
--
CREATE TABLE IFRTECA.TKP_PERMISSAO_MENU
( AER_COD    CHAR(3) not null, 
  US_CODIGO  CHAR(10) not null,
  ID_MENU    NUMBER   not null
)
TABLESPACE &&TSD_TECASIG
STORAGE (initial 512k next 512k pctincrease 0)
/




--
-- TAB_TKP_CLT  (Synonym) 
--
CREATE PUBLIC SYNONYM TAB_TKP_CLT FOR IFRTECA.TAB_TKP_CLT
/


--
-- TKP_FAVORITOS  (Synonym) 
--
CREATE PUBLIC SYNONYM TKP_FAVORITOS FOR IFRTECA.TKP_FAVORITOS
/


--
-- TKP_GRUPOS  (Synonym) 
--
CREATE PUBLIC SYNONYM TKP_GRUPOS FOR IFRTECA.TKP_GRUPOS
/


--
-- TKP_LOG_ACESSO  (Synonym) 
--
CREATE PUBLIC SYNONYM TKP_LOG_ACESSO FOR IFRTECA.TKP_LOG_ACESSO
/


--
-- TKP_MENU  (Synonym) 
--
CREATE PUBLIC SYNONYM TKP_MENU FOR IFRTECA.TKP_MENU
/


--
-- TKP_PERMISSAO_MENU  (Synonym) 
--
CREATE PUBLIC SYNONYM TKP_PERMISSAO_MENU FOR IFRTECA.TKP_PERMISSAO_MENU
/




-- 
-- Non Foreign Key Constraints for Table TAB_TKP_CLT 
-- 
ALTER TABLE IFRTECA.TAB_TKP_CLT ADD ( 
  CONSTRAINT TAB_TKP_CLT_PK PRIMARY KEY (COD_CLT)
    USING INDEX 
    TABLESPACE &&TSI_TECASIG
    STORAGE (initial 128k next 128k pctincrease 0))
/

-- 
-- Non Foreign Key Constraints for Table TKP_GRUPOS 
-- 
ALTER TABLE IFRTECA.TKP_GRUPOS ADD (
  CONSTRAINT TKP_GRUPOS_PK PRIMARY KEY (COD_GRUPO)
    USING INDEX 
    TABLESPACE &&TSI_TECASIG
    STORAGE (initial 128k next 128k pctincrease 0))
/

ALTER TABLE IFRTECA.TKP_FAVORITOS ADD (
  CONSTRAINT TKP_FAVORITOS_PK PRIMARY KEY (US_CODIGO,ID_MENU)
    USING INDEX 
    TABLESPACE &&TSI_TECASIG
    STORAGE (initial 128k next 128k pctincrease 0))
/

ALTER TABLE IFRTECA.TKP_MENU ADD  ( 
  CONSTRAINT TKP_MENU_PK PRIMARY KEY (ID_MENU)
    USING INDEX 
    TABLESPACE &&TSI_TECASIG
    STORAGE (initial 128k next 128k pctincrease 0) ) ;

ALTER TABLE IFRTECA.TKP_PERMISSAO_MENU ADD  ( 
  CONSTRAINT TKP_PERMISSAO_MENU_PK PRIMARY KEY (ID_MENU, US_CODIGO, AER_COD) 
    USING INDEX 
    TABLESPACE &&TSI_TECASIG
    STORAGE (initial 128k next 128k pctincrease 0)) ;

-- ADICONA O GRUPO
ALTER TABLE TKP_USER
    MODIFY (US_GRUPO CHAR(1) NULL);

ALTER TABLE TKP_TECAS ADD (COD_CLT NUMBER);

-- CRIACAO DO CAMPO PARA ARMAZENAR O SALT DAS SENHAS
ALTER TABLE TKP_USER
       ADD US_SALT VARCHAR(10);

ALTER TABLE TKP_USER
       ADD TIP_USU_CRRNTA VARCHAR2(1);

-- AUMENTO DO TAMANHO DA SENHA PARA COMPORTAR CRIPTOGRAFIA
ALTER TABLE TKP_USER
     MODIFY US_SENHA VARCHAR2(40);

-- PARA EXPIRACAO DA NOTICIA
ALTER TABLE TKP_NOTICIA
       ADD (NOT_DATA_INICIO DATE);

ALTER TABLE TKP_NOTICIA
       ADD (NOT_DATA_FIM DATE);




-- RELACIONAMENTO ENTRE MENU RAPIDO/FAVORITOS E OS MENUS DISPONIVEIS
ALTER TABLE TKP_FAVORITOS
        ADD (CONSTRAINT FAVORITOS_MENU_FK FOREIGN KEY (ID_MENU) REFERENCES TKP_MENU (ID_MENU));

ALTER TABLE TKP_PERMISSAO_MENU
        ADD (CONSTRAINT PERMISSAO_MENU_FK FOREIGN KEY (ID_MENU) REFERENCES TKP_MENU (ID_MENU));

ALTER TABLE TKP_PERMISSAO_MENU
        ADD (CONSTRAINT USER_MENU_FK FOREIGN KEY (AER_COD,US_CODIGO) REFERENCES TKP_USER (AER_COD,US_CODIGO));

-- RELACIONAMENTO ENTRE OS USUARIOS E SEU GRUPO
ALTER TABLE TKP_USER
        ADD (CONSTRAINT USER_GRUPO_FK FOREIGN KEY (US_GRUPO) REFERENCES TKP_GRUPOS (COD_GRUPO));

-- RELACIONAMENTO ENTRE OS USUARIOS E SEU GRUPO
ALTER TABLE TKP_MENU
        ADD (CONSTRAINT GRUPO_MENU_FK FOREIGN KEY (COD_GRUPO) REFERENCES TKP_GRUPOS (COD_GRUPO));




GRANT DELETE, INSERT, SELECT, UPDATE ON  IFRTECA.TAB_TKP_CLT TO ROLE_DCLC
/

GRANT DELETE, INSERT, SELECT, UPDATE ON  IFRTECA.TKP_FAVORITOS TO ROLE_DCLC
/

GRANT DELETE, INSERT, SELECT, UPDATE ON  IFRTECA.TKP_GRUPOS TO ROLE_DCLC
/

GRANT INSERT, SELECT ON  IFRTECA.TKP_LOG_ACESSO TO ROLE_DCLC
/

GRANT SELECT ON  IFRTECA.TKP_MENU TO ROLE_DCLC
/

GRANT DELETE, INSERT, SELECT, UPDATE ON  IFRTECA.TKP_PERMISSAO_MENU TO ROLE_DCLC
/



COMMENT ON TABLE TKP_LOG_ACSSO IS 'Armazena os log´s de acesso às páginas. do TECASIG.';
COMMENT ON COLUMN TKP_LOG_ACSSO.DAT_ACESSO IS 'Data do acesso à página.';
COMMENT ON COLUMN TKP_LOG_ACSSO.END_ACESSO IS 'endereço de acesso à página.';
COMMENT ON COLUMN TKP_MENU.COD_ITEM_OBRIGATORIO IS 'Informa se o item é de preenchimento obrigatório ou não.';




