--Conectar como IFRTECA
--
GRANT SELECT, REFERENCES ON IFRTECA.TKP_LOG_DCLC       TO CORRENTISTA;
GRANT SELECT, REFERENCES ON IFRTECA.TKP_PERMISSAO_MENU TO CORRENTISTA;
GRANT SELECT, REFERENCES ON IFRTECA.TKP_TECAS          TO CORRENTISTA;
GRANT SELECT, REFERENCES ON IFRTECA.TKP_USER           TO CORRENTISTA;


