--Rodar com a conta correntista
--

GRANT DELETE ON CAD_CRRNTA TO CORRENTISTA_ADM;
GRANT INSERT ON CAD_CRRNTA TO CORRENTISTA_ADM;
GRANT SELECT ON CAD_CRRNTA TO CORRENTISTA_ADM;
GRANT UPDATE ON CAD_CRRNTA TO CORRENTISTA_ADM;
GRANT DELETE ON CAD_DPCHTE TO CORRENTISTA_ADM;
GRANT INSERT ON CAD_DPCHTE TO CORRENTISTA_ADM;
GRANT SELECT ON CAD_DPCHTE TO CORRENTISTA_ADM;
GRANT UPDATE ON CAD_DPCHTE TO CORRENTISTA_ADM;
GRANT DELETE ON CAD_REPRE TO CORRENTISTA_ADM;
GRANT INSERT ON CAD_REPRE TO CORRENTISTA_ADM;
GRANT SELECT ON CAD_REPRE TO CORRENTISTA_ADM;
GRANT UPDATE ON CAD_REPRE TO CORRENTISTA_ADM;
GRANT DELETE ON CAD_TERMO_CRRNTA TO CORRENTISTA_ADM;
GRANT INSERT ON CAD_TERMO_CRRNTA TO CORRENTISTA_ADM;
GRANT SELECT ON CAD_TERMO_CRRNTA TO CORRENTISTA_ADM;
GRANT UPDATE ON CAD_TERMO_CRRNTA TO CORRENTISTA_ADM;
GRANT DELETE ON HIS_MOVTC_TERMO TO CORRENTISTA_ADM;
GRANT INSERT ON HIS_MOVTC_TERMO TO CORRENTISTA_ADM;
GRANT SELECT ON HIS_MOVTC_TERMO TO CORRENTISTA_ADM;
GRANT UPDATE ON HIS_MOVTC_TERMO TO CORRENTISTA_ADM;
GRANT DELETE ON MOVTC_FNCRO_TERMO TO CORRENTISTA_ADM;
GRANT INSERT ON MOVTC_FNCRO_TERMO TO CORRENTISTA_ADM;
GRANT SELECT ON MOVTC_FNCRO_TERMO TO CORRENTISTA_ADM;
GRANT UPDATE ON MOVTC_FNCRO_TERMO TO CORRENTISTA_ADM;
GRANT SELECT ON SEQ_CAD_CRRNTA TO CORRENTISTA_ADM;
GRANT SELECT ON SEQ_CAD_DPCHTE TO ROLE_DCLC;
GRANT SELECT ON SEQ_CAD_REPRE TO ROLE_DCLC;
GRANT SELECT ON SEQ_CAD_TERMO_CRRNTA TO CORRENTISTA_ADM;
GRANT DELETE ON SOLTC_TERMO TO CORRENTISTA_ADM;
GRANT INSERT ON SOLTC_TERMO TO CORRENTISTA_ADM;
GRANT SELECT ON SOLTC_TERMO TO CORRENTISTA_ADM;
GRANT UPDATE ON SOLTC_TERMO TO CORRENTISTA_ADM;
GRANT DELETE ON TERMO_AER TO CORRENTISTA_ADM;
GRANT INSERT ON TERMO_AER TO CORRENTISTA_ADM;
GRANT SELECT ON TERMO_AER TO CORRENTISTA_ADM;
GRANT UPDATE ON TERMO_AER TO CORRENTISTA_ADM;
GRANT DELETE ON TERMO_MODLDE TO CORRENTISTA_ADM;
GRANT INSERT ON TERMO_MODLDE TO CORRENTISTA_ADM;
GRANT SELECT ON TERMO_MODLDE TO CORRENTISTA_ADM;
GRANT UPDATE ON TERMO_MODLDE TO CORRENTISTA_ADM;


GRANT DELETE ON TAB_MOTVO_APRV TO CORRENTISTA_ADM;
GRANT INSERT ON TAB_MOTVO_APRV TO CORRENTISTA_ADM;
GRANT SELECT ON TAB_MOTVO_APRV TO CORRENTISTA_ADM;
GRANT UPDATE ON TAB_MOTVO_APRV TO CORRENTISTA_ADM;

