SQL> /

'ALTERUSER'||INDEX_NAME||'REBUILDONLINETSI_PORTALBR;'                                                                   
----------------------------------------------------------------------                                                  
ALTER USER CDCS_AREAS_PK REBUILD ONLINE TSI_PORTALBR;                                                                   
ALTER USER CDCS_ATTACH_TYPES_PK REBUILD ONLINE TSI_PORTALBR;                                                            
ALTER USER CDCS_ATTRIBUTES_PK REBUILD ONLINE TSI_PORTALBR;                                                              
ALTER USER CDCS_ATTRIBUTE_VALUES_PK REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER CDCS_AUTHORS_PK REBUILD ONLINE TSI_PORTALBR;                                                                 
ALTER USER CDCS_CATEGORIES_PK REBUILD ONLINE TSI_PORTALBR;                                                              
ALTER USER CDCS_CONTENTS_EXP_DATE_IX REBUILD ONLINE TSI_PORTALBR;                                                       
ALTER USER CDCS_CONTENTS_PK REBUILD ONLINE TSI_PORTALBR;                                                                
ALTER USER CDCS_CONTENTS_PUBLISH_DATE_IX REBUILD ONLINE TSI_PORTALBR;                                                   
ALTER USER CDCS_CONTENT_AREAS_PK REBUILD ONLINE TSI_PORTALBR;                                                           
ALTER USER CDCS_CONTENT_ATTACHS_PK REBUILD ONLINE TSI_PORTALBR;                                                         
ALTER USER CDCS_CONTENT_ATTRIBS_PK REBUILD ONLINE TSI_PORTALBR;                                                         
ALTER USER CDCS_CONTENT_AUTHORS_PK REBUILD ONLINE TSI_PORTALBR;                                                         
ALTER USER CDCS_CONTENT_CATEGORIES_PK REBUILD ONLINE TSI_PORTALBR;                                                      
ALTER USER CDCS_CONTENT_LINKS_PK REBUILD ONLINE TSI_PORTALBR;                                                           
ALTER USER CDCS_CONTENT_REGIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                         
ALTER USER CDCS_CONTENT_SUBJECTS_PK REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER CDCS_CONTENT_TARGETS_PK REBUILD ONLINE TSI_PORTALBR;                                                         
ALTER USER CDCS_CONTENT_TRANSLATIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                    
ALTER USER CDCS_CONTENT_TYPES_ATTRIBS_PK REBUILD ONLINE TSI_PORTALBR;                                                   
ALTER USER CDCS_CONTENT_TYPES_PK REBUILD ONLINE TSI_PORTALBR;                                                           
ALTER USER CDCS_CONTENT_TYPE_AUTHORS_PK REBUILD ONLINE TSI_PORTALBR;                                                    
ALTER USER CDCS_LANGUAGES_PK REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER CDCS_LINKS_PK REBUILD ONLINE TSI_PORTALBR;                                                                   
ALTER USER CDCS_MEDIA_CATEGORIES_PK REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER CDCS_MEDIA_PK REBUILD ONLINE TSI_PORTALBR;                                                                   
ALTER USER CDCS_MEDIA_TYPES_PK REBUILD ONLINE TSI_PORTALBR;                                                             
ALTER USER CDCS_REGIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                                 
ALTER USER CDCS_RELATED_CONTENTS_PK REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER CDCS_RELATED_KEYS_PK REBUILD ONLINE TSI_PORTALBR;                                                            
ALTER USER CDCS_RELATED_MEDIA_PK REBUILD ONLINE TSI_PORTALBR;                                                           
ALTER USER CDCS_RELATION_TYPES_PK REBUILD ONLINE TSI_PORTALBR;                                                          
ALTER USER CDCS_RMK_PK REBUILD ONLINE TSI_PORTALBR;                                                                     
ALTER USER CDCS_ROLES_PK REBUILD ONLINE TSI_PORTALBR;                                                                   
ALTER USER CDCS_SECTIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                                
ALTER USER CDCS_SECTION_CONTENTS_PK REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER CDCS_SECTION_CONTENT_TYPES_PK REBUILD ONLINE TSI_PORTALBR;                                                   
ALTER USER CDCS_SITES_PK REBUILD ONLINE TSI_PORTALBR;                                                                   
ALTER USER CDCS_SUBJECTS_PK REBUILD ONLINE TSI_PORTALBR;                                                                
ALTER USER CDCS_TARGETS_PK REBUILD ONLINE TSI_PORTALBR;                                                                 
ALTER USER CDCS_TEMPLATES_PK REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER CONTENTS_INTRO_IX REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER CONTENTS_SUBTITLE_IX REBUILD ONLINE TSI_PORTALBR;                                                            
ALTER USER CONTENTS_TEXT_IX REBUILD ONLINE TSI_PORTALBR;                                                                
ALTER USER CONTENTS_TEXT_PK REBUILD ONLINE TSI_PORTALBR;                                                                
ALTER USER CONTENTS_TITLE_IX REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER DR$CONTENTS_INTRO_IX$X REBUILD ONLINE TSI_PORTALBR;                                                          
ALTER USER DR$CONTENTS_SUBTITLE_IX$X REBUILD ONLINE TSI_PORTALBR;                                                       
ALTER USER DR$CONTENTS_TEXT_IX$X REBUILD ONLINE TSI_PORTALBR;                                                           
ALTER USER DR$CONTENTS_TITLE_IX$X REBUILD ONLINE TSI_PORTALBR;                                                          
ALTER USER MODULES_PK REBUILD ONLINE TSI_PORTALBR;                                                                      
ALTER USER PERMISSIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                                  
ALTER USER PROFILES_PK REBUILD ONLINE TSI_PORTALBR;                                                                     
ALTER USER PROGRAMS_PK REBUILD ONLINE TSI_PORTALBR;                                                                     
ALTER USER SITES_PK REBUILD ONLINE TSI_PORTALBR;                                                                        
ALTER USER SYS_IL0000025948C00002$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000025971C00006$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000025976C00002$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000025983C00006$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000025988C00002$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000025995C00006$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000026000C00002$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000026010C00006$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IL0000026015C00002$$ REBUILD ONLINE TSI_PORTALBR;                                                        
ALTER USER SYS_IOT_TOP_25974 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_25979 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_25986 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_25991 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_25998 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_26003 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_26013 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER SYS_IOT_TOP_26018 REBUILD ONLINE TSI_PORTALBR;                                                               
ALTER USER USERS_CATEGORIES_PK REBUILD ONLINE TSI_PORTALBR;                                                             
ALTER USER USERS_PK REBUILD ONLINE TSI_PORTALBR;                                                                        
ALTER USER USER_REGIONS_PK REBUILD ONLINE TSI_PORTALBR;                                                                 

75 linhas selecionadas.

SQL> SPO OFF
