DROP INDEX IX_NOME_AERO_AEROPORTO
/
CREATE INDEX IX_NOME_AERO_AEROPORTO ON AEROPORTO (NOME_AERO )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_SIGL_REGI_AEROPORTO
/
CREATE INDEX IX_SIGL_REGI_AEROPORTO ON AEROPORTO (SIGL_REGI )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_NOME_EVEN_AGENDA
/
CREATE INDEX IX_NOME_EVEN_AGENDA ON AGENDA (NOME_EVEN )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_MATE_ARTI_ARTIGO
/
CREATE INDEX IX_MATE_ARTI_ARTIGO ON ARTIGO (MATE_ARTI )  INDEXTYPE IS  CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_ARTI_ARTIGO
/
CREATE INDEX IX_TITU_ARTI_ARTIGO ON ARTIGO (TITU_ARTI )  INDEXTYPE IS  CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_DIVU_DIVULGACAO
/
CREATE INDEX IX_TITU_DIVU_DIVULGACAO ON DIVULGACAO (TITU_DIVU )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_MATE_DIVU_DIVULGACAO
/
CREATE INDEX IX_MATE_DIVU_DIVULGACAO ON DIVULGACAO (MATE_DIVU )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_INCE_INCENTIVO
/
CREATE INDEX IX_TITU_INCE_INCENTIVO ON INCENTIVO (TITU_INCE )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_MATE_NOTI_NOTICIA
/
CREATE INDEX IX_MATE_NOTI_NOTICIA ON NOTICIA (MATE_NOTI )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_NOTI_NOTICIA
/
CREATE INDEX IX_TITU_NOTI_NOTICIA ON NOTICIA (TITU_NOTI )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_NOTI_NOTICIA_ON
/
CREATE INDEX IX_TITU_NOTI_NOTICIA_ON ON NOTICIA_ON (TITU_NOTI )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_MATE_NOTI_NOTICIA_ON
/
CREATE INDEX IX_MATE_NOTI_NOTICIA_ON ON NOTICIA_ON (MATE_NOTI )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_NOME_OBRA_OBRA
/
CREATE INDEX IX_NOME_OBRA_OBRA ON OBRA_PROJETO (NOME_OBRA )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_NAME_PARAMETRO
/
CREATE INDEX IX_NAME_PARAMETRO ON PARAMETRO (NAME )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_TITU_PSOC_PS
/
CREATE INDEX IX_TITU_PSOC_PS ON PROJETO_SOCIAL (TITU_PSOC )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX IX_SIGL_AERO_AEROPORTO
/
CREATE INDEX IX_SIGL_AERO_AEROPORTO ON AEROPORTO (SIGL_AERO )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_nome_quem_quemsomos
/
CREATE INDEX ix_nome_quem_quemsomos ON QUEMSOMOS (nome_quem )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_carg_quem_quemsomos
/
CREATE INDEX ix_carg_quem_quemsomos ON QUEMSOMOS (carg_quem )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_nome_func_funcao
/
CREATE INDEX ix_nome_func_funcao ON FUNCAO (nome_func )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_nome_perf_perfil
/
CREATE INDEX ix_nome_perf_perfil ON PERFIL (nome_perf )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_nome_user_usuario
/
CREATE INDEX ix_nome_user_usuario ON USUARIO (nome_user )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_area_cont_linksgerais
/
CREATE INDEX ix_area_cont_linksgerais ON LINKS_GERAIS (area_cont )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_text_link_links
/
CREATE INDEX ix_text_link_links ON LINKS (text_link )  INDEXTYPE IS CTXSYS.CONTEXT
/

DROP INDEX ix_nome_gera_linksgerais
/
CREATE INDEX ix_nome_gera_linksgerais ON LINKS_GERAIS (titu_gera )  INDEXTYPE IS CTXSYS.CONTEXT
/

