exec sp_attach_db @dbname = 'DBSctlg', 
	@filename1 = 'X:\MSSQL\DatS\DBSctlg.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSctlg.ldf'
go
exec sp_attach_db @dbname = 'DBSwact' , 
	@filename1 = 'V:\MSSQL\DatS\DBSwact.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSwact.ldf'
go
exec sp_attach_db @dbname = 'DBSCOMMON' , 
	@filename1 = 'X:\MSSQL\DatS\DBSCOMMON.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSCOMMON.ldf'
go
exec sp_attach_db @dbname = 'DBSosst' , 
	@filename1 = 'X:\MSSQL\DatS\DBSosst.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSosst.ldf'
go
exec sp_attach_db @dbname = 'DBSosxp' , 
	@filename1 = 'X:\MSSQL\DatS\DBSosxp.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSosxp.ldf'
go
exec sp_attach_db @dbname = 'DBSpscb' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpscb.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpscb.ldf'
go
exec sp_attach_db @dbname = 'DBSpiqd' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpiqd.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpiqd.ldf'
go
exec sp_attach_db @dbname = 'DBSarpc' , 
	@filename1 = 'X:\MSSQL\DatS\DBSarpc.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSarpc.ldf'
go
exec sp_attach_db @dbname = 'DBScfrm' , 
	@filename1 = 'X:\MSSQL\DatS\DBScfrm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScfrm.ldf'
go
exec sp_attach_db @dbname = 'DBSwsam' , 
	@filename1 = 'X:\MSSQL\DatS\DBSwsam.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSwsam.ldf'
go
exec sp_attach_db @dbname = 'DBSdemo' , 
	@filename1 = 'X:\MSSQL\DatS\DBSdemo.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSdemo.ldf'
go
exec sp_attach_db @dbname = 'DBSeuro' , 
	@filename1 = 'X:\MSSQL\DatS\DBSeuro.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSeuro.ldf'
go
exec sp_attach_db @dbname = 'DBSpurg' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpurg.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpurg.ldf'
go
exec sp_attach_db @dbname = 'DBScand' , 
	@filename1 = 'X:\MSSQL\DatS\DBScand.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScand.ldf'
go
exec sp_attach_db @dbname = 'DBSbank' , 
	@filename1 = 'X:\MSSQL\DatS\DBSbank.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSbank.ldf'
go
exec sp_attach_db @dbname = 'DBScmre' , 
	@filename1 = 'X:\MSSQL\DatS\DBScmre.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScmre.ldf'
go
exec sp_attach_db @dbname = 'DBSentp' , 
	@filename1 = 'X:\MSSQL\DatS\DBSentp.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSentp.ldf'
go
exec sp_attach_db @dbname = 'DBSpclh' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpclh.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpclh.ldf'
go
exec sp_attach_db @dbname = 'DBSvend' , 
	@filename1 = 'X:\MSSQL\DatS\DBSvend.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSvend.ldf'
go
exec sp_attach_db @dbname = 'DBSvmst' , 
	@filename1 = 'X:\MSSQL\DatS\DBSvmst.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSvmst.ldf'
go
exec sp_attach_db @dbname = 'DBSvpur' , 
	@filename1 = 'X:\MSSQL\DatS\DBSvpur.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSvpur.ldf'
go
exec sp_attach_db @dbname = 'DBSdbis' , 
	@filename1 = 'X:\MSSQL\DatS\DBSdbis.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSdbis.ldf'
go
exec sp_attach_db @dbname = 'DBSglep' , 
	@filename1 = 'K:\MSSQL\DatS\DBSglep.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSglep.ldf'
go
exec sp_attach_db @dbname = 'DBSjepc' , 
	@filename1 = 'K:\MSSQL\DatS\DBSjepc.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSjepc.ldf'
go
exec sp_attach_db @dbname = 'DBSfast' , 
	@filename1 = 'S:\MSSQL\DatS\DBSfast.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSfast.ldf'
go
exec sp_attach_db @dbname = 'DBSfwrk' , 
	@filename1 = 'S:\MSSQL\DatS\DBSfwrk.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSfwrk.ldf'
go
exec sp_attach_db @dbname = 'DBScons' , 
	@filename1 = 'U:\MSSql\DATS\DBScons.mdf', 
	@filename2 = 'U:\MSSql\DATA\DBScons.ldf'
go
exec sp_attach_db @dbname = 'DBSallc' , 
	@filename1 = 'U:\MSSQL\DatS\DBSallc.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSallc.ldf'
go
exec sp_attach_db @dbname = 'DBSbdgt' , 
	@filename1 = 'X:\MSSQL\DatS\DBSbdgt.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSbdgt.ldf'
go
exec sp_attach_db @dbname = 'DBSprqt' , 
	@filename1 = 'J:\MSSQL\DatS\DBSprqt.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSprqt.ldf'
go
exec sp_attach_db @dbname = 'DBSpymt' , 
	@filename1 = 'J:\MSSQL\DatS\DBSpymt.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpymt.ldf'
go
exec sp_attach_db @dbname = 'DBSbill' , 
	@filename1 = 'X:\MSSql\DATS\DBSbill.mdf', 
	@filename2 = 'X:\MSSql\DATA\DBSbill.ldf'
go
exec sp_attach_db @dbname = 'DBScred' , 
	@filename1 = 'X:\MSSQL\DatS\DBScred.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScred.ldf'
go
exec sp_attach_db @dbname = 'DBSuomm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSuomm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSuomm.ldf'
go
exec sp_attach_db @dbname = 'DBSpjcm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpjcm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpjcm.ldf'
go
exec sp_attach_db @dbname = 'DBSproj' , 
	@filename1 = 'X:\MSSQL\DatS\DBSproj.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSproj.ldf'
go
exec sp_attach_db @dbname = 'DBSpjal' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpjal.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpjal.ldf'
go
exec sp_attach_db @dbname = 'DBSpwrk' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpwrk.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpwrk.ldf'
go
exec sp_attach_db @dbname = 'DBScntl' , 
	@filename1 = 'X:\MSSQL\DatS\DBScntl.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScntl.ldf'
go
exec sp_attach_db @dbname = 'DBSdclm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSdclm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSdclm.ldf'
go
exec sp_attach_db @dbname = 'DBShist' , 
	@filename1 = 'X:\MSSQL\DatS\DBShist.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBShist.ldf'
go
exec sp_attach_db @dbname = 'DBSotpm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSotpm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSotpm.ldf'
go
exec sp_attach_db @dbname = 'DBSplmm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSplmm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSplmm.ldf'
go
exec sp_attach_db @dbname = 'DBSrsmm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSrsmm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSrsmm.ldf'
go
exec sp_attach_db @dbname = 'DBSudef' , 
	@filename1 = 'X:\MSSQL\DatS\DBSudef.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSudef.ldf'
go
exec sp_attach_db @dbname = 'DBSpmam' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpmam.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpmam.ldf'
go
exec sp_attach_db @dbname = 'DBSpplm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpplm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpplm.ldf'
go
exec sp_attach_db @dbname = 'DBSropm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSropm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSropm.ldf'
go
exec sp_attach_db @dbname = 'DBSmabl' , 
	@filename1 = 'X:\MSSQL\DatS\DBSmabl.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSmabl.ldf'
go
exec sp_attach_db @dbname = 'DBSpuen' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpuen.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpuen.ldf'
go
exec sp_attach_db @dbname = 'DBSpcde' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpcde.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpcde.ldf'
go
exec sp_attach_db @dbname = 'DBSreqm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSreqm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSreqm.ldf'
go
exec sp_attach_db @dbname = 'DBSpoan' , 
	@filename1 = 'X:\MSSQL\DatS\DBSpoan.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSpoan.ldf'
go
exec sp_attach_db @dbname = 'DBScost' , 
	@filename1 = 'X:\MSSQL\DatS\DBScost.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBScost.ldf'
go
exec sp_attach_db @dbname = 'DBSiplm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSiplm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSiplm.ldf'
go
exec sp_attach_db @dbname = 'DBSrcth' , 
	@filename1 = 'X:\MSSQL\DatS\DBSrcth.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSrcth.ldf'
go
exec sp_attach_db @dbname = 'DBSstrm' , 
	@filename1 = 'X:\MSSQL\DatS\DBSstrm.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSstrm.ldf'
go
exec sp_attach_db @dbname = 'DBSfund' , 
	@filename1 = 'X:\MSSQL\DatS\DBSfund.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSfund.ldf'
go
exec sp_attach_db @dbname = 'DBSrrcv' , 
	@filename1 = 'U:\MSSQL\DatS\DBSrrcv.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSrrcv.ldf'
go
exec sp_attach_db @dbname = 'BASEMF' , 
	@filename1 = 'X:\MSSQL\DatS\BASEMF.mdf', 
	@filename2 = 'R:\MSSQL\Logs\BASEMF.ldf', 
	@filename3 = 'X:\MSSQL\DatU\BASEMF_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\BASEMF_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACbank' , 
	@filename1 = 'X:\MSSQL\DatS\GEACbank.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACbank.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACbank_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACbank_idx1.idf'
go
exec sp_attach_db @dbname = 'DISTRIBUCION' , 
	@filename1 = 'X:\MSSQL\DatS\DISTRIBUCION.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DISTRIBUCION.ldf', 
	@filename3 = 'X:\MSSQL\DatU\DISTRIBUCION_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\DISTRIBUCION_idx1.idf'
go
exec sp_attach_db @dbname = 'IFRCORP' , 
	@filename1 = 'X:\MSSQL\DatS\IFRCORP.mdf', 
	@filename2 = 'R:\MSSQL\Logs\IFRCORP_log.ldf'
go
exec sp_attach_db @dbname = 'INFRAgco' , 
	@filename1 = 'U:\MSSQL\DATS\INFRAgco.mdf', 
	@filename2 = 'R:\MSSQL\logs\INFRAgco.ldf', 
	@filename3 = 'M:\MSSQL\DatU\INFRAgco_dat1.ddf', 
	@filename4 = 'U:\MSSQL\Idxs\INFRAgco_idx1.idf', 
	@filename5 = 'M:\MSSQL\DatU\INFRAgco_dat2.ddf', 
	@filename6 = 'M:\MSSQL\DATS\INFRAgco_dat3_Data.NDF'
go
exec sp_attach_db @dbname = 'GEACpdm' , 
	@filename1 = 'u:\MSSQL\DatS\GEACpdm_Data.MDF', 
	@filename2 = 'r:\MSSQL\Logs\GEACpdm_Log.LDF'
go
exec sp_attach_db @dbname = 'GEACcompras' , 
	@filename1 = 'u:\MSSQL\DatS\GEACcompras_Data.MDF', 
	@filename2 = 'r:\MSSQL\Logs\GEACcompras_Log.LDF'
go
exec sp_attach_db @dbname = 'GEACucox' , 
	@filename1 = 'V:\MSSQL\DatS\GEACucox.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACucox.ldf', 
	@filename3 = 'V:\MSSQL\DatU\GEACucox_dat1.ddf', 
	@filename4 = 'V:\MSSQL\Idxs\GEACucox_idx1.idf'
go
exec sp_attach_db @dbname = 'GCC' , 
	@filename1 = 'X:\MSSQL\DatS\GCC_dats.mdf', 
	@filename2 = 'R:\MSSQL\logs\GCC_log.ldf', 
	@filename3 = 'X:\MSSQL\Datu\GCC_dat1.mdf', 
	@filename4 = 'X:\MSSQL\idxs\GCC_idx1.mdf'
go
exec sp_attach_db @dbname = 'INFSUCOTAP' , 
	@filename1 = 'P:\MSSQL\DatS\INFSUCOTAP.mdf', 
	@filename2 = 'R:\MSSQL\Logs\INFSUCOTAP.ldf', 
	@filename3 = 'P:\MSSQL\DatU\INFSUCOTAP_dat1.ddf', 
	@filename4 = 'P:\MSSQL\Idxs\INFSUCOTAP_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACufcx' , 
	@filename1 = 'V:\MSSQL\DatS\GEACufcx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACufcx.ldf', 
	@filename3 = 'V:\MSSQL\DatU\GEACufcx_dat1.ddf', 
	@filename4 = 'V:\MSSQL\Idxs\GEACufcx_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACfast' , 
	@filename1 = 'S:\MSSQL\DatS\GEACfast.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACfast.ldf', 
	@filename3 = 'S:\MSSQL\DatU\GEACfast_dat1.ddf', 
	@filename4 = 'S:\MSSQL\Idxs\GEACfast_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACbl' , 
	@filename1 = 'X:\MSSQL\DatS\GEACbl.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACbl.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACbl_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACbl_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACcf' , 
	@filename1 = 'X:\MSSQL\DatS\GEACcf.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACcf.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACcf_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACcf_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACCOMMON' , 
	@filename1 = 'X:\MSSQL\DatS\GEACCOMMON.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACCOMMON.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACCOMMON_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACCOMMON_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACcust' , 
	@filename1 = 'X:\MSSQL\DatS\GEACcust.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACcust.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACcust_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACcust_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACret' , 
	@filename1 = 'X:\MSSQL\DatS\GEACret.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACret.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACret_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACret_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACremote' , 
	@filename1 = 'X:\MSSQL\DatS\GEACremote.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACremote.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACremote_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACremote_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACproj' , 
	@filename1 = 'X:\MSSQL\DatS\GEACproj.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACproj.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACproj_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACproj_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACpdxx' , 
	@filename1 = 'X:\MSSQL\DatS\GEACpdxx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACpdxx.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACpdxx_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACpdxx_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACreconb' , 
	@filename1 = 'X:\MSSQL\DatS\GEACreconb.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACreconb.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACreconb_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACreconb_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACif' , 
	@filename1 = 'X:\MSSQL\DatS\GEACif.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACif.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACif_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACif_idx1.idf'
go
exec sp_attach_db @dbname = 'GEAChp' , 
	@filename1 = 'X:\MSSQL\DatS\GEAChp.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEAChp.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEAChp_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEAChp_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACmf' , 
	@filename1 = 'X:\MSSQL\DatS\GEACmf.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACmf.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACmf_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACmf_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACursx' , 
	@filename1 = 'X:\MSSQL\DatS\GEACursx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACursx.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACursx_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACursx_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACcfxx' , 
	@filename1 = 'X:\MSSQL\DatS\GEACcfxx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACcfxx.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACcfxx_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACcfxx_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACorca' , 
	@filename1 = 'X:\MSSQL\DatS\GEACorca.MDF', 
	@filename2 = 'R:\MSSQL\Logs\GEACorca.LDF', 
	@filename3 = 'X:\MSSQL\datu\GEACorca_dat1.ddf', 
	@filename4 = 'X:\MSSQL\idxs\GEACorca_idx1.idf'
go
exec sp_attach_db @dbname = 'INFRArete' , 
	@filename1 = 'X:\MSSQL\DatS\INFRArete.mdf', 
	@filename2 = 'R:\MSSQL\Logs\INFRArete.ldf', 
	@filename3 = 'X:\MSSQL\DatU\INFRArete_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\INFRArete_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACweb' , 
	@filename1 = 'X:\MSSQL\DatS\GEACweb.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACweb.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACweb_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACweb_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACvend' , 
	@filename1 = 'X:\MSSQL\DatS\GEACvend.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACvend.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACvend_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACvend_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACuafi' , 
	@filename1 = 'X:\MSSQL\DatS\GEACuafi.MDF', 
	@filename2 = 'R:\MSSQL\Logs\GEACuafi.LDF', 
	@filename3 = 'X:\MSSQL\DatU\GEACuafi_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACuafi_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACteca' , 
	@filename1 = 'V:\MSSQL\Dats\GEACteca_Data.MDF', 
	@filename2 = 'R:\MSSQL\Logs\GEACteca_Log.LDF'
go
exec sp_attach_db @dbname = 'GEACrrcv' , 
	@filename1 = 'K:\MSSQL\DatS\GEACrrcv.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACrrcv.ldf', 
	@filename3 = 'K:\MSSQL\DatU\GEACrrcv_dat1.ddf', 
	@filename4 = 'K:\MSSQL\Idxs\GEACrrcv_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACutcx' , 
	@filename1 = 'X:\MSSQL\DatS\GEACutcx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACutcx.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACutcx_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACutcx_idx1.idf'
go
exec sp_attach_db @dbname = 'SUMMrpt' , 
	@filename1 = 'U:\MSSQL\DatS\SUMMrpt.mdf', 
	@filename2 = 'R:\MSSQL\Logs\SUMMrpt.ldf', 
	@filename3 = 'U:\MSSQL\DatU\SUMMrpt_dat1.ddf', 
	@filename4 = 'U:\MSSQL\Idxs\SUMMrpt_idx1.idf'
go
exec sp_attach_db @dbname = 'HIST' , 
	@filename1 = 'X:\MSSQL\DatS\HIST.mdf', 
	@filename2 = 'R:\MSSQL\Logs\HIST.ldf', 
	@filename3 = 'X:\MSSQL\DatU\HIST_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\HIST_idx1.idf'
go
exec sp_attach_db @dbname = 'HP' , 
	@filename1 = 'X:\MSSQL\DatS\HP.mdf', 
	@filename2 = 'R:\MSSQL\Logs\HP.ldf', 
	@filename3 = 'X:\MSSQL\DatU\HP_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\HP_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACtexx' , 
	@filename1 = 'X:\MSSQL\DatS\GEACtexx.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACtexx.ldf', 
	@filename3 = 'X:\MSSQL\DatU\GEACtexx_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\GEACtexx_idx1.idf'
go
exec sp_attach_db @dbname = 'INFRAERO' , 
	@filename1 = 'U:\MSSQL\DatS\INFRAERO.mdf', 
	@filename2 = 'R:\MSSQL\Logs\INFRAERO.ldf', 
	@filename3 = 'U:\MSSQL\DatU\INFRAERO_dat1.ddf', 
	@filename4 = 'U:\MSSQL\Idxs\INFRAERO_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACrpt' , 
	@filename1 = 'K:\MSSQL\DatS\GEACrpt.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACrpt.ldf', 
	@filename3 = 'K:\MSSQL\DatU\GEACrpt_dat1.ddf', 
	@filename4 = 'K:\MSSQL\Idxs\GEACrpt_idx1.idf'
go
exec sp_attach_db @dbname = 'VALIDA' , 
	@filename1 = 'X:\MSSQL\DatS\VALIDA.mdf', 
	@filename2 = 'R:\MSSQL\Logs\VALIDA.ldf', 
	@filename3 = 'X:\MSSQL\DatU\VALIDA_dat1.ddf', 
	@filename4 = 'X:\MSSQL\Idxs\VALIDA_idx1.idf'
go
exec sp_attach_db @dbname = 'DBSueve' , 
	@filename1 = 'U:\MSSQL\DatS\DBSueve.mdf', 
	@filename2 = 'R:\MSSQL\Logs\DBSueve.ldf', 
	@filename3 = 'U:\MSSQL\DatU\DBSueve_dat1.ddf', 
	@filename4 = 'U:\MSSQL\Idxs\DBSueve_idx1.idf'
go
exec sp_attach_db @dbname = 'INFRAledger' , 
	@filename1 = 'U:\MSSQL\DatS\INFRAledger.mdf', 
	@filename2 = 'R:\MSSQL\LOGS\INFRAledger_log.ldf'
go
exec sp_attach_db @dbname = 'GEACap' , 
	@filename1 = 'J:\MSSQL\DatS\GEACap.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACap.ldf', 
	@filename3 = 'J:\MSSQL\DatU\GEACap_dat1.ddf', 
	@filename4 = 'J:\MSSQL\Idxs\GEACap_idx1.idf'
go
exec sp_attach_db @dbname = 'GEACupax' , 
	@filename1 = 'P:\MSSQL\DatS\GEACupax.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACupax.ldf', 
	@filename3 = 'P:\MSSQL\DatU\GEACupax_dat1.ddf', 
	@filename4 = 'P:\MSSQL\Idxs\GEACupax_idx1.idf', 
	@filename5 = 'O:\MSSQL\Idxs\GEACupax_idx2.ndf', 
	@filename6 = 'M:\MSSQL\Datu\GEACupax_dat2.ndf', 
	@filename7 = 'N:\MSSQL\DATU\GEACupax_dat3.ndf'
go
exec sp_attach_db @dbname = 'GEACutax' , 
	@filename1 = 'V:\MSSQL\DatS\GEACutax.mdf', 
	@filename2 = 'R:\MSSQL\Logs\GEACutax.ldf', 
	@filename3 = 'V:\MSSQL\DatU\GEACutax_dat1.ddf', 
	@filename4 = 'V:\MSSQL\Idxs\GEACutax_idx1.idf', 
	@filename5 = 'J:\MSSQL\DatU\GEACutax_dat2.ddf'
go
exec sp_attach_db @dbname = 'DFWEB' , 
	@filename1 = 'Y:\MSQLServer\MSSQL.1\MSSQL\DATA\DFWEB.mdf', 
	@filename2 = 'Y:\MSQLServer\MSSQL.1\MSSQL\DATA\DFWEB_log.ldf'
go
exec sp_attach_db @dbname = 'sqlnexus' , 
	@filename1 = 'Y:\MSQLServer\MSSQL.1\MSSQL\DATA\sqlnexus.mdf', 
	@filename2 = 'Y:\MSQLServer\MSSQL.1\MSSQL\DATA\sqlnexus_log.LDF'
go
