use bdo
/*
Script criado para realizar alteracoes na base do BDO .
- Adicionado campo CD_AER nas tabelas
- Tratados valores incorretos antes de criar as FKs
- Incluidas FKs identificadas
- Alterados indexes clustered para as pks


Teste na base:
SBGL - 18/12/12 - OK
SBRJ - 18/12/12 - OK

*/


DECLARE @STRSQL VARCHAR(1000);
DECLARE @STARTTIME DATETIME;
DECLARE @ENDTIME DATETIME;
DECLARE @STRERROR VARCHAR(1000);
DECLARE @CD_AER_PSI VARCHAR(3);
DECLARE @VAL_CDBOX VARCHAR(10);
DECLARE @ID	INT;

/* Criar a tabela temporaria TMPCMD'; */
/*Criar tabela temporaria para registar os comandos e resultado de execucoes */
IF EXISTS(SELECT NAME FROM SYS.TABLES WHERE NAME='TMPCMD')
	DROP TABLE TMPCMD


	CREATE TABLE TMPCMD(
	ID INT IDENTITY(1,1) NOT NULL,
	COMMAND VARCHAR(2000),
	TIME_EXEC DATETIME,
	MSGERRO VARCHAR(1000) NULL
	); 

	
	
/*
ALTERAR DEFAULT PARA CAMPO CD_AER E ADICONAR CAMPO CD_AER E DEFAULT NAS TABELAS QUE NAO TEEM.
*/

SET @CD_AER_PSI = (SELECT convert(varchar(3),CD_AER) FROM T_PSI)



/*
CRIAR TODOS RELACIONAMENTOS
*/
PRINT '';
PRINT 'LISTANDO RELACIONAMENTOS MAPEADOS';

	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aan ADD CONSTRAINT FK_T_AAN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aan ADD CONSTRAINT FK_T_AAN_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_abo ADD CONSTRAINT FK_T_ABO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ach ADD CONSTRAINT FK_T_ACH_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ach ADD CONSTRAINT FK_T_ACH_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aen ADD CONSTRAINT FK_T_AEN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aen ADD CONSTRAINT FK_T_AEN_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aen ADD CONSTRAINT FK_T_AEN_T_EQP FOREIGN KEY (cd_eqp) REFERENCES dbo.t_eqp(cd_eqp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aer ADD CONSTRAINT FK_T_AER_T_CID FOREIGN KEY (cd_cid) REFERENCES dbo.t_cid(cd_cid)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aer_fec ADD CONSTRAINT FK_T_AER_FEC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aet ADD CONSTRAINT FK_T_AET_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aho ADD CONSTRAINT FK_T_AHO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aho ADD CONSTRAINT FK_T_AHO_T_HOT001 FOREIGN KEY (cd_hot) REFERENCES dbo.t_hot001(cd_hot)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_anu ADD CONSTRAINT FK_T_ANU_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_apa ADD CONSTRAINT FK_T_APA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_apa ADD CONSTRAINT FK_T_APA_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ase ADD CONSTRAINT FK_T_ASE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ase ADD CONSTRAINT FK_T_ASE_T_AAN FOREIGN KEY (cd_aan) REFERENCES dbo.t_aan(cd_aan)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ase ADD CONSTRAINT FK_T_ASE_T_FIDS_SET FOREIGN KEY (cd_set) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ata ADD CONSTRAINT FK_T_ATA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ata ADD CONSTRAINT FK_T_ATA_T_AAN FOREIGN KEY (cd_aan) REFERENCES dbo.t_aan(cd_aan)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ata ADD CONSTRAINT FK_T_ATA_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aus ADD CONSTRAINT FK_T_AUS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_aus ADD CONSTRAINT FK_T_AUS_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bcl ADD CONSTRAINT FK_T_BCL_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bcl ADD CONSTRAINT FK_T_BCL_T_BCP FOREIGN KEY (cd_bcp) REFERENCES dbo.t_bcp(cd_bcp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bcl ADD CONSTRAINT FK_T_BCL_T_BCP_CD_BCP_LIM FOREIGN KEY (cd_bcp_lim) REFERENCES dbo.t_bcp(cd_bcp) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bco ADD CONSTRAINT FK_T_BCO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bco ADD CONSTRAINT FK_T_BCO_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bco ADD CONSTRAINT FK_T_BCO_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bcp ADD CONSTRAINT FK_T_BCP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bcp ADD CONSTRAINT FK_T_BCP_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_beq ADD CONSTRAINT FK_T_BEQ_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_beq ADD CONSTRAINT FK_T_BEQ_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_beq ADD CONSTRAINT FK_T_BEQ_T_EQP FOREIGN KEY (cd_eqp) REFERENCES dbo.t_eqp(cd_eqp) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bin ADD CONSTRAINT FK_T_BIN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_bin ADD CONSTRAINT FK_T_BIN_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box ADD CONSTRAINT FK_T_BOX_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box ADD CONSTRAINT FK_T_BOX_T_EST FOREIGN KEY (cd_est) REFERENCES dbo.t_est(cd_est)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box ADD CONSTRAINT FK_T_BOX_T_PON FOREIGN KEY (cd_pon) REFERENCES dbo.t_pon(cd_pon)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box ADD CONSTRAINT FK_T_BOX_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box ADD CONSTRAINT FK_T_BOX_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_BOX_CD_BOX_DIR FOREIGN KEY (cd_box_dir) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_BOX_CD_BOX_ESQ FOREIGN KEY (cd_box_esq) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_BOX_FRENT FOREIGN KEY (cd_box_frent) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_box_adj ADD CONSTRAINT FK_T_BOX_ADJ_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_MSG FOREIGN KEY (cd_msg) REFERENCES dbo.t_msg(cd_msg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_PRA FOREIGN KEY (cd_pra) REFERENCES dbo.t_pra(cd_pra)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_PSS FOREIGN KEY (cd_pss) REFERENCES dbo.t_pss(cd_pss)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cha ADD CONSTRAINT FK_T_CHA_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_AEN_CD_AEN_CHG FOREIGN KEY (cd_aen_chg) REFERENCES dbo.t_aen(cd_aen)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_EQP_CD_EQP_CHG FOREIGN KEY (cd_eqp_chg) REFERENCES dbo.t_eqp(cd_eqp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_CHG_CD_CHG_VIN FOREIGN KEY (cd_chg_vin) REFERENCES dbo.t_chg(cd_chg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chg ADD CONSTRAINT FK_T_CHG_T_FIDS_SET_CD_SET_CHG FOREIGN KEY (cd_set_chg) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chgant ADD CONSTRAINT FK_T_CHGANT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chgant ADD CONSTRAINT FK_T_CHGANT_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chk ADD CONSTRAINT FK_T_CHK_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chk ADD CONSTRAINT FK_T_CHK_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_chk ADD CONSTRAINT FK_T_CHK_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cid ADD CONSTRAINT FK_T_CID_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cid ADD CONSTRAINT FK_T_CID_T_HOR FOREIGN KEY (cd_hor) REFERENCES dbo.t_hor(cd_hor)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cid ADD CONSTRAINT FK_T_CID_T_PAI FOREIGN KEY (cd_pai) REFERENCES dbo.t_pai(cd_pai) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ckv001 ADD CONSTRAINT FK_T_CKV001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ckv001 ADD CONSTRAINT FK_T_CKV001_T_CHK FOREIGN KEY (cd_chk) REFERENCES dbo.t_chk(cd_chk)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ckv001 ADD CONSTRAINT FK_T_CKV001_T_CLS FOREIGN KEY (cd_cls) REFERENCES dbo.t_cls(cd_cls)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ckv001 ADD CONSTRAINT FK_T_CKV001_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_cls ADD CONSTRAINT FK_T_CLS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_com ADD CONSTRAINT FK_T_COM_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_com ADD CONSTRAINT FK_T_COM_T_COM_T_COM_MAT FOREIGN KEY (cd_com_mat) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_com ADD CONSTRAINT FK_T_COM_T_FIDS_SET_CD_SET_COM FOREIGN KEY (cd_set_com) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_com ADD CONSTRAINT FK_T_COM_T_FIDS_TPS_CD_TPS_COM FOREIGN KEY (cd_tps_com) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dec ADD CONSTRAINT FK_T_DEC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dec ADD CONSTRAINT FK_T_DEC_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dec ADD CONSTRAINT FK_T_DEC_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dec ADD CONSTRAINT FK_T_DEC_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dep ADD CONSTRAINT FK_T_DEP_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dep ADD CONSTRAINT FK_T_DEP_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dep ADD CONSTRAINT FK_T_DEP_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dep ADD CONSTRAINT FK_T_DEP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_cor ADD CONSTRAINT FK_T_DGA_COR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_DGA_PSI FOREIGN KEY (cd_dga) REFERENCES dbo.t_dga_psi(cd_dga) ON DELETE CASCADE ON UPDATE NO ACTION');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_AEN FOREIGN KEY (cd_aen) REFERENCES dbo.t_aen(cd_aen)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_EQP FOREIGN KEY (cd_eqp) REFERENCES dbo.t_eqp(cd_eqp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_obj ADD CONSTRAINT FK_T_DGA_OBJ_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_psi ADD CONSTRAINT FK_T_DGA_PSI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_psi ADD CONSTRAINT FK_T_DGA_PSI_T_PES FOREIGN KEY (cd_pes) REFERENCES dbo.t_pes(cd_pes)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_dga_psi ADD CONSTRAINT FK_T_DGA_PSI_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ecc001 ADD CONSTRAINT FK_T_ECC001_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ecc001 ADD CONSTRAINT FK_T_ECC001_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ecp001 ADD CONSTRAINT FK_T_ECP001_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ecp001 ADD CONSTRAINT FK_T_ECP001_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_emb ADD CONSTRAINT FK_T_EMB_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_emb ADD CONSTRAINT FK_T_EMB_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_eqp ADD CONSTRAINT FK_T_EQP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_er_rpe ADD CONSTRAINT FK_T_ER_RPE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_err ADD CONSTRAINT FK_T_ERR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_est ADD CONSTRAINT FK_T_EST_T_SAL FOREIGN KEY (cd_sal) REFERENCES dbo.t_sal(cd_sal)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_est ADD CONSTRAINT FK_T_EST_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_esv001 ADD CONSTRAINT FK_T_ESV001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_esv001 ADD CONSTRAINT FK_T_ESV001_T_EST FOREIGN KEY (cd_est) REFERENCES dbo.t_est(cd_est)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_esv001 ADD CONSTRAINT FK_T_ESV001_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fai ADD CONSTRAINT FK_T_FAI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_cst ADD CONSTRAINT FK_T_FIDS_CST_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgi ADD CONSTRAINT FK_T_FIDS_DGI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgi ADD CONSTRAINT FK_T_FIDS_DGI_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgi ADD CONSTRAINT FK_T_FIDS_DGI_T_FIDS_DGT FOREIGN KEY (cd_dgt) REFERENCES dbo.t_fids_dgt(cd_dgt) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgt ADD CONSTRAINT FK_T_FIDS_DGT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgt ADD CONSTRAINT FK_T_FIDS_DGT_T_FIDS_SCR FOREIGN KEY (cd_scr) REFERENCES dbo.t_fids_scr(cd_scr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgt ADD CONSTRAINT FK_T_FIDS_DGT_T_FIDS_CST FOREIGN KEY (cd_cst) REFERENCES dbo.t_fids_cst(cd_cst)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgt ADD CONSTRAINT FK_T_FIDS_DGT_T_FIDS_SCR_002 FOREIGN KEY (cd_scr_off) REFERENCES dbo.t_fids_scr(cd_scr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgu ADD CONSTRAINT FK_T_FIDS_DGU_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgu ADD CONSTRAINT FK_T_FIDS_DGU_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgu ADD CONSTRAINT FK_T_FIDS_DGU_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dgu ADD CONSTRAINT FK_T_FIDS_DGU_T_FIDS_DGT FOREIGN KEY (cd_dgt) REFERENCES dbo.t_fids_dgt(cd_dgt) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dis ADD CONSTRAINT FK_T_FIDS_DIS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dis ADD CONSTRAINT FK_T_FIDS_DIS_T_FIDS_DGT FOREIGN KEY (cd_dgt) REFERENCES dbo.t_fids_dgt(cd_dgt)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dis ADD CONSTRAINT FK_T_FIDS_DIS_T_FIDS_DST FOREIGN KEY (cd_dst) REFERENCES dbo.t_fids_dst(cd_dst)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dis ADD CONSTRAINT FK_T_FIDS_DIS_T_FIDS_SET FOREIGN KEY (cd_set) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dst ADD CONSTRAINT FK_T_FIDS_DST_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_dst ADD CONSTRAINT FK_T_FIDS_DST_T_FIDS_DST FOREIGN KEY (cd_dst_pri) REFERENCES dbo.t_fids_dst(cd_dst)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_fld ADD CONSTRAINT FK_T_FIDS_FLD_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isc ADD CONSTRAINT FK_T_FIDS_ISC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isc ADD CONSTRAINT FK_T_FIDS_ISC_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isc ADD CONSTRAINT FK_T_FIDS_ISC_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ise ADD CONSTRAINT FK_T_FIDS_ISE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ise ADD CONSTRAINT FK_T_FIDS_ISE_T_EMB FOREIGN KEY (cd_emb) REFERENCES dbo.t_emb(cd_emb)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ise ADD CONSTRAINT FK_T_FIDS_ISE_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isf ADD CONSTRAINT FK_T_FIDS_ISF_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isf ADD CONSTRAINT FK_T_FIDS_ISF_T_FIDS_FLD FOREIGN KEY (cd_fld) REFERENCES dbo.t_fids_fld(cd_fld)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isg ADD CONSTRAINT FK_T_FIDS_ISG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isg ADD CONSTRAINT FK_T_FIDS_ISG_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isn ADD CONSTRAINT FK_T_FIDS_ISN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isn ADD CONSTRAINT FK_T_FIDS_ISN_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isp ADD CONSTRAINT FK_T_FIDS_ISP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isp ADD CONSTRAINT FK_T_FIDS_ISP_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isp ADD CONSTRAINT FK_T_FIDS_ISP_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isr ADD CONSTRAINT FK_T_FIDS_ISR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isr ADD CONSTRAINT FK_T_FIDS_ISR_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_iss ADD CONSTRAINT FK_T_FIDS_ISS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_iss ADD CONSTRAINT FK_T_FIDS_ISS_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_iss ADD CONSTRAINT FK_T_FIDS_ISS_T_FIDS_SET FOREIGN KEY (cd_set) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ist ADD CONSTRAINT FK_T_FIDS_IST_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ist ADD CONSTRAINT FK_T_FIDS_IST_T_CHK FOREIGN KEY (cd_chk) REFERENCES dbo.t_chk(cd_chk)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ist ADD CONSTRAINT FK_T_FIDS_IST_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ist ADD CONSTRAINT FK_T_FIDS_IST_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_ist ADD CONSTRAINT FK_T_FIDS_IST_T_EST FOREIGN KEY (cd_est) REFERENCES dbo.t_est(cd_est)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isv ADD CONSTRAINT FK_T_FIDS_ISV_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_isv ADD CONSTRAINT FK_T_FIDS_ISV_T_FIDS_IST FOREIGN KEY (cd_ist) REFERENCES dbo.t_fids_ist(cd_ist) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_obj ADD CONSTRAINT FK_T_FIDS_OBJ_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_obj ADD CONSTRAINT FK_T_FIDS_OBJ_T_FIDS_SCR FOREIGN KEY (cd_scr) REFERENCES dbo.t_fids_scr(cd_scr) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pal ADD CONSTRAINT FK_T_FIDS_PAL_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pal ADD CONSTRAINT FK_T_FIDS_PAL_T_FIDS_ROL FOREIGN KEY (cd_rol) REFERENCES dbo.t_fids_rol(cd_rol)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pob ADD CONSTRAINT FK_T_FIDS_POB_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pob ADD CONSTRAINT FK_T_FIDS_POB_T_FIDS_PRO FOREIGN KEY (cd_pro) REFERENCES dbo.t_fids_pro(cd_pro)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pob ADD CONSTRAINT FK_T_FIDS_POB_T_FIDS_OBJ FOREIGN KEY (cd_obj) REFERENCES dbo.t_fids_obj(cd_obj) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_prc ADD CONSTRAINT FK_T_FIDS_PRC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_prc ADD CONSTRAINT FK_T_FIDS_PRC_T_FIDS_PRO FOREIGN KEY (cd_pro) REFERENCES dbo.t_fids_pro(cd_pro)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_pro ADD CONSTRAINT FK_T_FIDS_PRO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_rol ADD CONSTRAINT FK_T_FIDS_ROL_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_scr ADD CONSTRAINT FK_T_FIDS_SCR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_set ADD CONSTRAINT FK_T_FIDS_SET_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_set ADD CONSTRAINT FK_T_FIDS_SET_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_tps ADD CONSTRAINT FK_T_FIDS_TPS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_web ADD CONSTRAINT FK_T_FIDS_WEB_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_web ADD CONSTRAINT FK_T_FIDS_WEB_T_FIDS_DGT FOREIGN KEY (cd_dgt) REFERENCES dbo.t_fids_dgt(cd_dgt) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_fids_web ADD CONSTRAINT FK_T_FIDS_WEB_T_FIDS_SCR FOREIGN KEY (cd_scr) REFERENCES dbo.t_fids_scr(cd_scr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_gru ADD CONSTRAINT FK_T_GRU_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_gru ADD CONSTRAINT FK_T_GRU_T_MOD FOREIGN KEY (cd_mod) REFERENCES dbo.t_mod(cd_mod) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_han ADD CONSTRAINT FK_T_HAN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbv ADD CONSTRAINT FK_T_HBV_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbv ADD CONSTRAINT FK_T_HBV_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box) ON DELETE CASCADE');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbv ADD CONSTRAINT FK_T_HBV_T_HBX001 FOREIGN KEY (cd_hbx,nr_hbx_seq) REFERENCES dbo.t_hbx001(cd_hbx,nr_hbx_seq) ON DELETE CASCADE');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_EQP FOREIGN KEY (sg_eqp) REFERENCES dbo.t_eqp(sg_eqp)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_HET_CD_HET_CHG FOREIGN KEY (cd_hot_chg,cd_hve_chg,cd_hfr_chg,cd_het_chg) REFERENCES dbo.t_het(cd_hot,cd_hve,cd_hfr,cd_het) ON DELETE NO ACTION');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_HET_CD_HET_PAR FOREIGN KEY (cd_hot_par,cd_hve_par,cd_hfr_par,cd_het_par) REFERENCES dbo.t_het(cd_hot,cd_hve,cd_hfr,cd_het) ON DELETE CASCADE');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_EQP_CD_EQP_CHG FOREIGN KEY (cd_eqp_chg) REFERENCES dbo.t_eqp(cd_eqp)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_EQP_CD_EQP_PAR FOREIGN KEY (cd_eqp_par) REFERENCES dbo.t_eqp(cd_eqp)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_COM_CD_COM_CHG FOREIGN KEY (cd_com_chg) REFERENCES dbo.t_com(cd_com)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hbx001 ADD CONSTRAINT FK_T_HBX001_T_COM_CD_COM_PAR FOREIGN KEY (cd_com_par) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hch ADD CONSTRAINT FK_T_HCH_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hch ADD CONSTRAINT FK_T_HCH_T_CHK FOREIGN KEY (cd_chk) REFERENCES dbo.t_chk(cd_chk)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hch ADD CONSTRAINT FK_T_HCH_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hch ADD CONSTRAINT FK_T_HCH_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hck ADD CONSTRAINT FK_T_HCK_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hck ADD CONSTRAINT FK_T_HCK_T_CHK FOREIGN KEY (cd_chk) REFERENCES dbo.t_chk(cd_chk)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hck ADD CONSTRAINT FK_T_HCK_T_CLS FOREIGN KEY (cd_cls) REFERENCES dbo.t_cls(cd_cls)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hck ADD CONSTRAINT FK_T_HCK_T_HFR FOREIGN KEY (cd_hot,cd_hve,cd_hfr) REFERENCES dbo.t_hfr(cd_hot,cd_hve,cd_hfr) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hes ADD CONSTRAINT FK_T_HES_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hes ADD CONSTRAINT FK_T_HES_T_EST FOREIGN KEY (cd_est) REFERENCES dbo.t_est(cd_est)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hes ADD CONSTRAINT FK_T_HES_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hes ADD CONSTRAINT FK_T_HES_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_HFR FOREIGN KEY (cd_hot,cd_hve,cd_hfr) REFERENCES dbo.t_hfr(cd_hot,cd_hve,cd_hfr) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_AER_SG_AER_DES FOREIGN KEY (sg_aer_des) REFERENCES dbo.t_aer(sg_aer_ica) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_AER_SG_AER_ORI FOREIGN KEY (sg_aer_ori) REFERENCES dbo.t_aer(sg_aer_ica)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_EQP_SG_EQP FOREIGN KEY (sg_eqp) REFERENCES dbo.t_eqp(sg_eqp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_HOT001_CD_HOT FOREIGN KEY (cd_hot_aen_ant) REFERENCES dbo.t_hot001(cd_hot)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_het ADD CONSTRAINT FK_T_HET_T_HOT001_CD_HOT_VIN FOREIGN KEY (cd_hot_vin) REFERENCES dbo.t_hot001(cd_hot)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hfr ADD CONSTRAINT FK_T_HFR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hfr ADD CONSTRAINT FK_T_HFR_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hfr ADD CONSTRAINT FK_T_HFR_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hfr ADD CONSTRAINT FK_T_HFR_T_EST FOREIGN KEY (cd_est) REFERENCES dbo.t_est(cd_est)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hfr ADD CONSTRAINT FK_T_HFR_T_HVE FOREIGN KEY (cd_hot,cd_hve) REFERENCES dbo.t_hve(cd_hot,cd_hve) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hif ADD CONSTRAINT FK_T_HIF_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hif ADD CONSTRAINT FK_T_HIF_T_INF FOREIGN KEY (cd_inf) REFERENCES dbo.t_inf(cd_inf) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hoc ADD CONSTRAINT FK_T_HOC_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hoc ADD CONSTRAINT FK_T_HOC_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hoc ADD CONSTRAINT FK_T_HOC_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hoc ADD CONSTRAINT FK_T_HOC_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hoc ADD CONSTRAINT FK_T_HOC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hop ADD CONSTRAINT FK_T_HOP_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hop ADD CONSTRAINT FK_T_HOP_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hop ADD CONSTRAINT FK_T_HOP_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hop ADD CONSTRAINT FK_T_HOP_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hop ADD CONSTRAINT FK_T_HOP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hor ADD CONSTRAINT FK_T_HOR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot ADD CONSTRAINT FK_T_HOT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot001 ADD CONSTRAINT FK_T_HOT001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot001 ADD CONSTRAINT FK_T_HOT001_T_FIDS_SET_001 FOREIGN KEY (cd_set_hot) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot001 ADD CONSTRAINT FK_T_HOT001_T_FIDS_SET_002 FOREIGN KEY (cd_set_hot_par) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot001 ADD CONSTRAINT FK_T_HOT001_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hot001 ADD CONSTRAINT FK_T_HOT001_T_FIDS_TPS_003 FOREIGN KEY (cd_tps_par) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hotran ADD CONSTRAINT FK_T_HOTRAN_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hpo ADD CONSTRAINT FK_T_HPO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hpo ADD CONSTRAINT FK_T_HPO_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hpo ADD CONSTRAINT FK_T_HPO_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hpo ADD CONSTRAINT FK_T_HPO_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hrc ADD CONSTRAINT FK_T_HRC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hrv ADD CONSTRAINT FK_T_HRV_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsc ADD CONSTRAINT FK_T_HSC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsc ADD CONSTRAINT FK_T_HSC_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsc ADD CONSTRAINT FK_T_HSC_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsc ADD CONSTRAINT FK_T_HSC_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsc ADD CONSTRAINT FK_T_HSC_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsp ADD CONSTRAINT FK_T_HSP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsp ADD CONSTRAINT FK_T_HSP_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsp ADD CONSTRAINT FK_T_HSP_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsp ADD CONSTRAINT FK_T_HSP_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hsp ADD CONSTRAINT FK_T_HSP_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hte ADD CONSTRAINT FK_T_HTE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hte ADD CONSTRAINT FK_T_HTE_T_TFE FOREIGN KEY (cd_tfe) REFERENCES dbo.t_tfe(cd_tfe) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hve ADD CONSTRAINT FK_T_HVE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_hve ADD CONSTRAINT FK_T_HVE_T_HOT001 FOREIGN KEY (cd_hot) REFERENCES dbo.t_hot001(cd_hot) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_idi ADD CONSTRAINT FK_T_IDI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ift ADD CONSTRAINT FK_T_IFT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ift ADD CONSTRAINT FK_T_IFT_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ift ADD CONSTRAINT FK_T_IFT_T_PES_CD_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_pes(cd_pes) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_inf ADD CONSTRAINT FK_T_INF_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ino ADD CONSTRAINT FK_T_INO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_log ADD CONSTRAINT FK_T_LOG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_log ADD CONSTRAINT FK_T_LOG_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_log ADD CONSTRAINT FK_T_LOG_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mai ADD CONSTRAINT FK_T_MAI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_PIS FOREIGN KEY (cd_pis) REFERENCES dbo.t_pis(cd_pis)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mch ADD CONSTRAINT FK_T_MCH_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mensagens ADD CONSTRAINT FK_T_MENSAGENS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mensagens ADD CONSTRAINT FK_T_MENSAGENS_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mng ADD CONSTRAINT FK_T_MNG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mng ADD CONSTRAINT FK_T_MNG_T_GRU FOREIGN KEY (cd_gru) REFERENCES dbo.t_gru(cd_gru) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mng ADD CONSTRAINT FK_T_MNG_T_MNU FOREIGN KEY (cd_mnu) REFERENCES dbo.t_mnu(cd_mnu) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mnu ADD CONSTRAINT FK_T_MNU_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mnu ADD CONSTRAINT FK_T_MNU_T_MOD FOREIGN KEY (cd_mod) REFERENCES dbo.t_mod(cd_mod)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mnu ADD CONSTRAINT FK_T_MNU_T_MNU_CD_MNU_PAI FOREIGN KEY (cd_mnu_pai) REFERENCES dbo.t_mnu(cd_mnu)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mod ADD CONSTRAINT FK_T_MOD_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mov ADD CONSTRAINT FK_T_MOV_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mov ADD CONSTRAINT FK_T_MOV_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mov ADD CONSTRAINT FK_T_MOV_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_mpa ADD CONSTRAINT FK_T_MPA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_msg ADD CONSTRAINT FK_T_MSG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_msg ADD CONSTRAINT FK_T_MSG_T_IDI FOREIGN KEY (cd_idi) REFERENCES dbo.t_idi(cd_idi)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_msg ADD CONSTRAINT FK_T_MSG_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_msg ADD CONSTRAINT FK_T_MSG_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_nro ADD CONSTRAINT FK_T_NRO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_obs ADD CONSTRAINT FK_T_OBS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_oni ADD CONSTRAINT FK_T_ONI_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_oni ADD CONSTRAINT FK_T_ONI_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pai ADD CONSTRAINT FK_T_PAI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_POR FOREIGN KEY (cd_por) REFERENCES dbo.t_por(cd_por)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_CHG_CD_CHG_ANT FOREIGN KEY (cd_chg_ant) REFERENCES dbo.t_chg(cd_chg)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_PAR_CD_PAR_VIN FOREIGN KEY (cd_par_vin) REFERENCES dbo.t_par(cd_par)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_FIDS_SET_CD_SET_PAR FOREIGN KEY (cd_set_par) REFERENCES dbo.t_fids_set(cd_set)');
INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_par ADD CONSTRAINT FK_T_PAR_T_CHG_CD_CHG_AEN_ANT FOREIGN KEY (cd_chg_aen_ant) REFERENCES dbo.t_chg(cd_chg) ON DELETE SET NULL');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_per ADD CONSTRAINT FK_T_PER_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_per ADD CONSTRAINT FK_T_PER_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pes ADD CONSTRAINT FK_T_PES_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pex ADD CONSTRAINT FK_T_PEX_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pex ADD CONSTRAINT FK_T_PEX_T_REX FOREIGN KEY (cd_rex) REFERENCES dbo.t_rex(cd_rex) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pis ADD CONSTRAINT FK_T_PIS_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pon ADD CONSTRAINT FK_T_PON_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pon ADD CONSTRAINT FK_T_PON_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_por ADD CONSTRAINT FK_T_POR_T_EMB FOREIGN KEY (cd_emb) REFERENCES dbo.t_emb(cd_emb)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_por ADD CONSTRAINT FK_T_POR_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pra ADD CONSTRAINT FK_T_PRA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pra ADD CONSTRAINT FK_T_PRA_T_IDI FOREIGN KEY (cd_idi) REFERENCES dbo.t_idi(cd_idi)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pra ADD CONSTRAINT FK_T_PRA_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pra ADD CONSTRAINT FK_T_PRA_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_CHG FOREIGN KEY (cd_chg) REFERENCES dbo.t_chg(cd_chg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_IDI FOREIGN KEY (cd_idi) REFERENCES dbo.t_idi(cd_idi) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_IFT FOREIGN KEY (cd_ift) REFERENCES dbo.t_ift(cd_ift) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_PRA FOREIGN KEY (cd_pra) REFERENCES dbo.t_pra(cd_pra) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pralog ADD CONSTRAINT FK_T_PRALOG_T_TPA FOREIGN KEY (cd_tpa) REFERENCES dbo.t_tpa(cd_tpa) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prd ADD CONSTRAINT FK_T_PRD_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prd ADD CONSTRAINT FK_T_PRD_T_BOX FOREIGN KEY (cd_box) REFERENCES dbo.t_box(cd_box)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prd ADD CONSTRAINT FK_T_PRD_T_AEN FOREIGN KEY (cd_aen) REFERENCES dbo.t_aen(cd_aen)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prd ADD CONSTRAINT FK_T_PRD_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prd ADD CONSTRAINT FK_T_PRD_T_EQP FOREIGN KEY (cd_eqp) REFERENCES dbo.t_eqp(cd_eqp)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prg ADD CONSTRAINT FK_T_PRG_T_ANU FOREIGN KEY (cd_anu) REFERENCES dbo.t_anu(cd_anu)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prg ADD CONSTRAINT FK_T_PRG_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prg ADD CONSTRAINT FK_T_PRG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prp ADD CONSTRAINT FK_T_PRP_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prp ADD CONSTRAINT FK_T_PRP_T_HRC FOREIGN KEY (cd_hrc) REFERENCES dbo.t_hrc(cd_hrc)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prp ADD CONSTRAINT FK_T_PRP_T_PRG FOREIGN KEY (cd_prg) REFERENCES dbo.t_prg(cd_prg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prp ADD CONSTRAINT FK_T_PRP_T_TEL FOREIGN KEY (cd_tel) REFERENCES dbo.t_tel(cd_tel)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_prr ADD CONSTRAINT FK_T_PRR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_ANU FOREIGN KEY (cd_anu) REFERENCES dbo.t_anu(cd_anu)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer) ON DELETE NO ACTION ON UPDATE NO ACTION');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_CHG_001 FOREIGN KEY (cd_sit_chg_001) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_CHG_002 FOREIGN KEY (cd_sit_chg_002) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_CHG_CON FOREIGN KEY (cd_sit_chg_con) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_PAR_001 FOREIGN KEY (cd_sit_par_001) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_PAR_002 FOREIGN KEY (cd_sit_par_002) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_psi ADD CONSTRAINT FK_T_PSI_T_SIT_CD_SIT_PAR_CON FOREIGN KEY (cd_sit_par_con) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pss ADD CONSTRAINT FK_T_PSS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_pss ADD CONSTRAINT FK_T_PSS_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_red WITH NOCHECK ADD CONSTRAINT FK_T_RED_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_red WITH NOCHECK ADD CONSTRAINT FK_T_RED_T_AER_SG_AER_ICA FOREIGN KEY (sg_aer_ica) REFERENCES dbo.t_aer(sg_aer_ica)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_rep001 ADD CONSTRAINT FK_T_REP001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_rex ADD CONSTRAINT FK_T_REX_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_rex ADD CONSTRAINT FK_T_REX_T_HRC FOREIGN KEY (cd_hrc) REFERENCES dbo.t_hrc(cd_hrc)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_rex ADD CONSTRAINT FK_T_REX_T_PRG FOREIGN KEY (cd_prg) REFERENCES dbo.t_prg(cd_prg) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_rex ADD CONSTRAINT FK_T_REX_T_TEL FOREIGN KEY (cd_tel) REFERENCES dbo.t_tel(cd_tel)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sal ADD CONSTRAINT FK_T_SAL_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sal ADD CONSTRAINT FK_T_SAL_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sca ADD CONSTRAINT FK_T_SCA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sca ADD CONSTRAINT FK_T_SCA_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sca ADD CONSTRAINT FK_T_SCA_T_SIT_CD_SIT_ANT FOREIGN KEY (cd_sit_ant) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_att ADD CONSTRAINT FK_T_SIRP_ATT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_log ADD CONSTRAINT FK_T_SIRP_LOG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_see ADD CONSTRAINT FK_T_SIRP_SEE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_see ADD CONSTRAINT FK_T_SIRP_SEE_T_FIDS_SET FOREIGN KEY (cd_set) REFERENCES dbo.t_fids_set(cd_set)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_see ADD CONSTRAINT FK_T_SIRP_SEE_T_FIDS_TPS FOREIGN KEY (cd_tps) REFERENCES dbo.t_fids_tps(cd_tps)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_siglas ADD CONSTRAINT FK_T_SIRP_SIGLAS_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sirp_sol ADD CONSTRAINT FK_T_SIRP_SOL_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_siso_bio ADD CONSTRAINT FK_T_SISO_BIO_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_siso_bio ADD CONSTRAINT FK_T_SISO_BIO_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sit ADD CONSTRAINT FK_T_SIT_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sit ADD CONSTRAINT FK_T_SIT_T_SIT_CD_SIT_ANTERIOR FOREIGN KEY (cd_sit_anterior) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ssu ADD CONSTRAINT FK_T_SSU_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ssu ADD CONSTRAINT FK_T_SSU_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ssu ADD CONSTRAINT FK_T_SSU_T_SIT_CD_SIT_SSU FOREIGN KEY (cd_sit_suc) REFERENCES dbo.t_sit(cd_sit)  ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_T_AEN FOREIGN KEY (cd_aen) REFERENCES dbo.t_aen(cd_aen)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tel ADD CONSTRAINT FK_T_TEL_T_AER FOREIGN KEY (cd_aer) REFERENCES dbo.t_aer(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	--INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_DEP FOREIGN KEY (cd_dep) REFERENCES dbo.t_dep(cd_dep) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_HTE FOREIGN KEY (cd_hte) REFERENCES dbo.t_hte(cd_hte)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_PAR FOREIGN KEY (cd_par) REFERENCES dbo.t_par(cd_par)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfb001 ADD CONSTRAINT FK_T_TFB001_T_STA FOREIGN KEY (cd_sta) REFERENCES dbo.t_sta(cd_sta)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfe ADD CONSTRAINT FK_T_TFE_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tfe ADD CONSTRAINT FK_T_TFE_T_INF FOREIGN KEY (cd_inf) REFERENCES dbo.t_inf(cd_inf)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tpa ADD CONSTRAINT FK_T_TPA_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tsi ADD CONSTRAINT FK_T_TSI_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tsi ADD CONSTRAINT FK_T_TSI_T_SIT FOREIGN KEY (cd_sit) REFERENCES dbo.t_sit(cd_sit) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_tsi ADD CONSTRAINT FK_T_TSI_T_TEL FOREIGN KEY (cd_tel) REFERENCES dbo.t_tel(cd_tel)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usg ADD CONSTRAINT FK_T_USG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usg ADD CONSTRAINT FK_T_USG_T_GRU FOREIGN KEY (cd_gru) REFERENCES dbo.t_gru(cd_gru) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usg ADD CONSTRAINT FK_T_USG_T_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usr ADD CONSTRAINT FK_T_USR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usr ADD CONSTRAINT FK_T_USR_T_COM FOREIGN KEY (cd_com) REFERENCES dbo.t_com(cd_com)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_usr ADD CONSTRAINT FK_T_USR_T_PES_CD_USR FOREIGN KEY (cd_usr) REFERENCES dbo.t_pes(cd_pes)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_ver ADD CONSTRAINT FK_T_VER_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_CD_PIS_CD_PIS_PO FOREIGN KEY (cd_pis_po) REFERENCES t_pis(cd_pis)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_CD_PIS_CD_PIS_DE FOREIGN KEY (cd_pis_de) REFERENCES t_pis(cd_pis)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE dbo.t_sta ADD CONSTRAINT FK_T_STA_CD_USR_CD_USR_VERIF FOREIGN KEY (cd_usr_verif) REFERENCES t_usr(cd_usr)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_RST ADD CONSTRAINT FK_T_RST_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_AIXS_EXEC ADD CONSTRAINT FK_T_AIXS_EXEC_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_CHG ADD CONSTRAINT FK_T_DGA_CHG_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_ECC001 ADD CONSTRAINT FK_T_DGA_ECC001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_ECP001 ADD CONSTRAINT FK_T_DGA_ECP001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_ESV001 ADD CONSTRAINT FK_T_DGA_ESV001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_PAR ADD CONSTRAINT FK_T_DGA_PAR_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE T_DGA_HBX001 ADD CONSTRAINT FK_T_DGA_HBX001_T_PSI FOREIGN KEY (cd_aer) REFERENCES dbo.t_psi(cd_aer)');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_SSAT_ATT]  ADD  CONSTRAINT [FK_T_SSAT_ATT_ASS] FOREIGN KEY([SG_ASS]) REFERENCES [dbo].[T_SSAT_ASS] ([SG_ASS])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_SSAT_ATT]  ADD  CONSTRAINT [FK_T_SSAT_ATT_MOT] FOREIGN KEY([SG_MOT]) REFERENCES [dbo].[T_SSAT_MOT] ([SG_MOT])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_SSAT_ATT]  ADD  CONSTRAINT [FK_T_SSAT_ATT_SOL] FOREIGN KEY([SG_SOL]) REFERENCES [dbo].[T_SSAT_SOL] ([SG_SOL])');

/*** Objetos novos  ***/

	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_AIXS_TAFS]  ADD  CONSTRAINT [FK_T_AIXS_TAFS_T_PSI] FOREIGN KEY([CD_AER]) REFERENCES [dbo].[T_PSI] ([CD_AER])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_CKV001]  ADD  CONSTRAINT [FK_T_CKV001_T_CHK] FOREIGN KEY([CD_CHK]) REFERENCES [dbo].[T_CHK] ([CD_CHK])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DECAUX]  ADD  CONSTRAINT [FK_T_DECAUX_T_CHG] FOREIGN KEY([CD_CHG]) REFERENCES [dbo].[T_CHG] ([CD_CHG]) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DECAUX]  ADD  CONSTRAINT [FK_T_DECAUX_T_COM] FOREIGN KEY([CD_COM]) REFERENCES [dbo].[T_COM] ([CD_COM])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DECAUX]  ADD  CONSTRAINT [FK_T_DECAUX_T_PSI] FOREIGN KEY([CD_AER]) REFERENCES [dbo].[T_PSI] ([CD_AER])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DECAUX]  ADD  CONSTRAINT [FK_T_DECAUX_T_STA] FOREIGN KEY([CD_STA]) REFERENCES [dbo].[T_STA] ([CD_STA])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DEPAUX]  ADD  CONSTRAINT [FK_T_DEPAUX_T_COM] FOREIGN KEY([CD_COM]) REFERENCES [dbo].[T_COM] ([CD_COM])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DEPAUX]  ADD  CONSTRAINT [FK_T_DEPAUX_T_PAR] FOREIGN KEY([CD_PAR]) REFERENCES [dbo].[T_PAR] ([CD_PAR]) ON DELETE CASCADE');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DEPAUX]  ADD  CONSTRAINT [FK_T_DEPAUX_T_PSI] FOREIGN KEY([CD_AER]) REFERENCES [dbo].[T_PSI] ([CD_AER])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_DEPAUX]  ADD  CONSTRAINT [FK_T_DEPAUX_T_STA] FOREIGN KEY([CD_STA]) REFERENCES [dbo].[T_STA] ([CD_STA])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_FIDS_IST]  ADD  CONSTRAINT [FK_T_FIDS_IST_T_CHK] FOREIGN KEY([CD_CHK]) REFERENCES [dbo].[T_CHK] ([CD_CHK])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_HCH]  ADD  CONSTRAINT [FK_T_HCH_T_CHK] FOREIGN KEY([CD_CHK]) REFERENCES [dbo].[T_CHK] ([CD_CHK])');
	INSERT INTO TMPCMD (COMMAND) VALUES ('ALTER TABLE [dbo].[T_HCK]  ADD  CONSTRAINT [FK_T_HCK_T_CHK] FOREIGN KEY([CD_CHK]) REFERENCES [dbo].[T_CHK] ([CD_CHK])');



DECLARE CURSQL CURSOR FOR
SELECT ID,COMMAND
FROM TMPCMD
ORDER BY ID

OPEN CURSQL;

FETCH NEXT FROM CURSQL INTO @ID,@STRSQL;
WHILE @@FETCH_STATUS=0
BEGIN 
	SET @STRERROR=NULL;
	SET @STARTTIME=GETDATE();
	BEGIN TRY
		EXECUTE (@STRSQL);
    END TRY
    BEGIN CATCH
		 SET @STRERROR = ERROR_NUMBER()
    END CATCH;
    SET @ENDTIME=GETDATE();
		UPDATE TMPCMD 
			SET TIME_EXEC=@ENDTIME-@STARTTIME, MSGERRO=@STRERROR
			WHERE TMPCMD.ID=@ID

    FETCH NEXT FROM CURSQL INTO @ID,@STRSQL;

    --WAITFOR DELAY '00:00:30';
END;

CLOSE CURSQL;
DEALLOCATE CURSQL;
