WITH ANIVER_TIDD1 AS (
SELECT  EMP_NOME, TO_CHAR(EMP_DATA_NASCIMENTO, 'DD/MM') DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'DD') DIA_DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'MM') MES_DATA_ANIVERSARIO
  FROM  CADASTROS
 WHERE  emp_uor_codigo_fisico_agenda = 9218 AND EMP_STATUS <> 2
 UNION
 SELECT  EMP_NOME, TO_CHAR(EMP_DATA_NASCIMENTO, 'DD/MM') DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'DD') DIA_DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'MM') MES_DATA_ANIVERSARIO
  FROM  CADASTROS
 WHERE  EMP_NOME LIKE 'JUNIA MARIA%'
  UNION ALL
 SELECT  EMP_NOME, TO_CHAR(EMP_DATA_NASCIMENTO, 'DD/MM') DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'DD') DIA_DATA_ANIVERSARIO
  , TO_CHAR(EMP_DATA_NASCIMENTO, 'MM') MES_DATA_ANIVERSARIO
  FROM  CADASTROS
 WHERE  EMP_NOME LIKE 'MARCIEL%')
 
 SELECT * FROM ANIVER_TIDD1 ORDER BY 4, 3
 
