SELECT	A.SIGLA_AEROPORTO
,		A.MES
,		A.ANO
,		SUM(A.QTD_EMB_BILHETE_CHECKIN +   
			A.QTD_EMB_COLO + A.QTD_EMB_ISENTO + 
			A.QTD_EMB_TRANSITO +  
			A.QTD_EMB_CONEXAO + 
			A.QTD_DES) AS QTD_PASSAGEIRO 
FROM	VIW_CONSOLIDADO_PASSAGEIRO A 
WHERE	A.MES IN (1,2,3,4,5,6,7,8,9,10,11,12)
AND		A.ANO IN (2007) 
GROUP BY 
		A.SIGLA_AEROPORTO
,		A.MES
,		A.ANO 
ORDER BY 
		A.SIGLA_AEROPORTO
,		A.ANO
,		A.MES

/*
SELECT	COUNT(1)
FROM	dbo.BIOGER_RPE_DES
WHERE	SIGLA_AEROPORTO = 'SBBH'
AND		YEAR(DATA_HORA_EFETIVA_POUSO) = 2007

DELETE
FROM	dbo.BIOGER_RPE_DES
WHERE	SIGLA_AEROPORTO = 'SBBH'
AND		YEAR(DATA_HORA_EFETIVA_POUSO) = 2007

DELETE
FROM	dbo.BIOGER_RPE_EMB
WHERE	SIGLA_AEROPORTO = 'SBBH'
AND		YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = 2007

DELETE
FROM	dbo.BIOGER_RPE_MOV
WHERE	SIGLA_AEROPORTO = 'SBBH'
AND		YEAR(DATA_HORA_MOV) = 2007


SELECT	MONTH( DATA_HORA_EFETIVA_POUSO), COUNT(1)
FROM	dbo.BIOGER_RPE_DES
WHERE	YEAR(DATA_HORA_EFETIVA_POUSO) = 2008
AND		FLG_MIGRADO = 2
GROUP BY MONTH( DATA_HORA_EFETIVA_POUSO)
ORDER BY 1



INSERT INTO dbo.BIOGER_RPE_DES
SELECT * FROM dbo.BIOGER_RPE_DES_MIG

INSERT INTO dbo.BIOGER_RPE_EMB
SELECT * FROM dbo.BIOGER_RPE_EMB_MIG

INSERT INTO dbo.BIOGER_RPE_MOV
SELECT * FROM dbo.BIOGER_RPE_MOV_MIG


TRUNCATE TABLE BIOGER_RPE_DES_MIG

TRUNCATE TABLE BIOGER_RPE_EMB_MIG

TRUNCATE TABLE BIOGER_RPE_MOV_MIG


*/
