INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,11111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,11111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,11111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,11111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,11111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12210);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12212);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12213);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12214);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12215);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,12216);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,13210);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,13211);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,13212);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,14110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14210);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14211);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14220);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14221);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14230);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14231);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14232);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14233);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14234);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,14510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,15310);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,15313);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(901,16041);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,16111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,16111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,16111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,16111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,16111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,16312);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,16313);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,16314);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,16315);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20111);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20112);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20112);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20112);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20112);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20112);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20114);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20114);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20114);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20114);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20114);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20115);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20115);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20115);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20115);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20115);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20116);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20117);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20118);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20118);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20118);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20118);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20118);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20121);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20122);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20123);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20124);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20125);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20126);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20127);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20128);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20129);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20130);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20131);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20131);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20131);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20131);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20131);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20132);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20145);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20146);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20155);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20155);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20155);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20155);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20155);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20164);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20169);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20169);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20169);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20169);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20169);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20171);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20171);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20171);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20171);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20171);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20172);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20172);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20172);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20172);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20172);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20173);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20173);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20173);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20173);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20175);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20410);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20411);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20412);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20510);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20511);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20512);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(154,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(157,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(160,20513);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(156,30110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(158,30110);
INSERT INTO INCIDENCIA_CENTRO_CUSTO_DEP (DEP_CD_DEPENDENCIA,CC_CD_CENTRO_CUSTO)
VALUES(159,30110);
