USE IFRSIVNET

SELECT      DISTINCT ISNULL(RTRIM(LTRIM(CIA.NOM_CIA)),'') AS NOM_CIA,
      ISNULL(RTRIM(LTRIM(CIA.SIG_CIA_AEREA)),'') AS SIG_CIA_AEREA,
      AERO.COD_ICAO
FROM TAB_CIA_AEREA CIA
      INNER JOIN HST_VOO_OPERACAO  VOO ON (VOO.SEQ_CIA = CIA.SEQ_CIA)
      INNER JOIN HST_VOO_OPERACAO_STATUS HS ON VOO.SEQ_HST_VOO_OPERACAO = HS.SEQ_HST_VOO_OPERACAO
      INNER JOIN TAB_AEROPORTO  AERO  ON (AERO.SEQ_AEROPORTO = VOO.SEQ_AEROPORTO_ENVIA_ARQUIVO)
WHERE
      CIA.SIG_CIA_AEREA <> 'GOL'
      AND HS.DAT_INSERCAO > GETDATE()-2

/*

EXEC dbo.PRC_MOVIMENTO_VOOS


SELECT	COUNT(1)
  FROM	dbo.HST_VOO_OPERACAO_STATUS
 WHERE  DAT_PREV > '20120101'
 
sp_who2 active

dbcc inputbuffer (135)

kill 99

*/
