--DES


--EMB
	select
		ISNULL(LTRIM(RTRIM(SIGLA_AEROPORTO)), 0),
		ISNULL(LTRIM(RTRIM(NR_PAR_VOO)), 0),
		CONVERT(VARCHAR(8), DH_PAR_NRM, 112),
		CD_COM,
		CD_STA,
		COUNT(1)
	from [SBGR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] NEW
	left join IEOP.dbo.IEOP_MERGE_CONTROLE MC on(NEW.SIGLA_AEROPORTO  COLLATE Latin1_General_CI_AI = MC.SIG_AEROPORTO)
	WHERE (NEW.DTH_ATUALIZACAO >= MC.DTH_ATUALIZACAO or MC.DTH_ATUALIZACAO is null)
		and MC.TIP_CARGA = 'EMB'
		AND CD_STA NOT IN (783032, 770466)
    GROUP BY
	    ISNULL(LTRIM(RTRIM(SIGLA_AEROPORTO)), 0),
		ISNULL(LTRIM(RTRIM(NR_PAR_VOO)), 0),
		CONVERT(VARCHAR(8), DH_PAR_NRM, 112),
		CD_COM,
		CD_STA
	HAVING COUNT(1) > 1
			
			
--MOV
select
	ISNULL(LTRIM(RTRIM(SIGLA_AEROPORTO)), 0),
	CD_MOV,
	CD_STA,
	CONVERT(VARCHAR(8), HR_MOV, 112),	
	COUNT(1)
from [SBGR - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_MOV_NEW] NEW
	left join IEOP.dbo.IEOP_MERGE_CONTROLE MC on(NEW.SIGLA_AEROPORTO  COLLATE Latin1_General_CI_AI = MC.SIG_AEROPORTO)
WHERE (NEW.DTH_ATUALIZACAO >= MC.DTH_ATUALIZACAO or MC.DTH_ATUALIZACAO is null)
		and MC.TIP_CARGA = 'MOV'
GROUP BY
	ISNULL(LTRIM(RTRIM(SIGLA_AEROPORTO)), 0),
	CD_MOV,
	CD_STA,
	CONVERT(VARCHAR(8), HR_MOV, 112)
HAVING	COUNT(1) > 1
