--CREATE OR REPLACE VIEW IFRSRH.VIW_ACONSULTA AS
SELECT  MOV_EMP_NUMERO_MATRICULA AS MATRICULA
     ,  (SELECT EMP_NOME FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) NOME
     ,  (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) COD_DEPENDENCIA
     ,  (SELECT DEP_NOME FROM DEPENDENCIAS WHERE DEP_CODIGO = (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA)) NOM_DEPENDENCIA
     ,  MOV_MES_REFERENCIA AS MES_REFERENCIA
     ,  MOV_ANO_REFERENCIA AS ANO_REFERENCIA
     ,  MOV_RUB_CODIGO AS COD_RUBRICA
     ,  (SELECT RUB_DENOMINACAO FROM RUBRICAS WHERE RUB_CODIGO = MOV_RUB_CODIGO) AS NOM_RUBRICA
     ,  MOV_VALOR AS VALOR_DESCONTADO
  FROM  MOVIMENTACAO
 WHERE  MOV_ANO_REFERENCIA >= 2007
   AND  MOV_ANO_REFERENCIA < 2012
   AND  MOV_RUB_CODIGO = 5135
UNION ALL
SELECT  MOV_EMP_NUMERO_MATRICULA AS MATRICULA
     ,  (SELECT EMP_NOME FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) NOME
     ,  (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) COD_DEPENDENCIA
     ,  (SELECT DEP_NOME FROM DEPENDENCIAS WHERE DEP_CODIGO = (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA)) NOM_DEPENDENCIA
     ,  MOV_MES_REFERENCIA AS MES_REFERENCIA
     ,  MOV_ANO_REFERENCIA AS ANO_REFERENCIA
     ,  MOV_RUB_CODIGO AS COD_RUBRICA
     ,  (SELECT RUB_DENOMINACAO FROM RUBRICAS WHERE RUB_CODIGO = MOV_RUB_CODIGO) AS NOM_RUBRICA
     ,  MOV_VALOR AS VALOR_DESCONTADO
  FROM  MOVIMENTACAO
 WHERE  MOV_ANO_REFERENCIA >= 2007
   AND  MOV_ANO_REFERENCIA < 2012
   AND  MOV_RUB_CODIGO = 5130 
UNION ALL
SELECT  MOV_EMP_NUMERO_MATRICULA AS MATRICULA
     ,  (SELECT EMP_NOME FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) NOME
     ,  (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA) COD_DEPENDENCIA
     ,  (SELECT DEP_NOME FROM DEPENDENCIAS WHERE DEP_CODIGO = (SELECT EMP_DEP_CODIGO_LOTACAO FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = MOV_EMP_NUMERO_MATRICULA)) NOM_DEPENDENCIA
     ,  MOV_MES_REFERENCIA AS MES_REFERENCIA
     ,  MOV_ANO_REFERENCIA AS ANO_REFERENCIA
     ,  MOV_RUB_CODIGO AS COD_RUBRICA
     ,  (SELECT RUB_DENOMINACAO FROM RUBRICAS WHERE RUB_CODIGO = MOV_RUB_CODIGO) AS NOM_RUBRICA
     ,  MOV_VALOR AS VALOR_DESCONTADO
  FROM  MOVIMENTACAO
 WHERE  MOV_ANO_REFERENCIA >= 2007
   AND  MOV_ANO_REFERENCIA < 2012
   AND  MOV_RUB_CODIGO = 5140 
--SELECT * FROM RUBRICAS WHERE RUB_DENOMINACAO LIKE '%SINDICAL%'
