WITH TESTE AS (SELECT  DEP_CODIGO 
FROM    DEPENDENCIAS
WHERE   DEP_SIGLA IN ('SEDE', 'SRCO')
UNION
SELECT  DEP_CODIGO 
FROM    DEPENDENCIAS
WHERE   DEP_DEP_CODIGO = 156
  AND   DEP_DATA_EXTINCAO IS NULL)

SELECT  (SELECT DEP_SIGLA FROM DEPENDENCIAS WHERE DEP_CODIGO = EMP_DEP_CODIGO_LOTACAO) AS DEPENDENCIA
     ,  COUNT(1) AS TOTAL
  FROM  CADASTROS
 WHERE  EMP_STATUS != 2
   AND  EMP_DEP_CODIGO_LOTACAO IN (
        SELECT DEP_CODIGO FROM TESTE
)
GROUP BY EMP_DEP_CODIGO_LOTACAO

