SELECT  (SELECT UOR_SIGLA FROM UOR WHERE  UOR_CODIGO = CADASTROS.EMP_UOR_CODIGO_LOTACAO AND UOR_DATA_EXTINCAO IS NULL AND UOR_DEP_CODIGO = 1) LOTACAO
     ,  COUNT(1) TOTAL
  FROM  CADASTROS
 WHERE  EMP_STATUS = 1
   AND  EMP_DEP_CODIGO_LOTACAO = 1
   AND  EMP_UOR_CODIGO_LOTACAO IN (SELECT UOR_CODIGO FROM UOR WHERE UOR_SIGLA LIKE '%TI%' AND UOR_DATA_EXTINCAO IS NULL AND UOR_DEP_CODIGO = 1)
 GROUP
    BY  CADASTROS.EMP_UOR_CODIGO_LOTACAO
  
/*  
 SELECT *
  FROM  CADASTROS
 WHERE  EMP_STATUS = 1
   AND  EMP_DEP_CODIGO_LOTACAO = 1
   AND  EMP_UOR_CODIGO_LOTACAO IN (SELECT UOR_CODIGO FROM UOR WHERE UOR_SIGLA LIKE '%TISI-3%' AND UOR_DATA_EXTINCAO IS NULL AND UOR_DEP_CODIGO = 1)

*/
   
   
--SELECT * FROM UOR WHERE UOR_SIGLA LIKE '%TI%' AND UOR_DATA_EXTINCAO IS NULL AND UOR_DEP_CODIGO = 1