SELECT		O.*      
	 /*,      E.COD_STATUS 
	 ,		E.[COD_VOO_CHEGADA_ANT]
     ,		E.[COD_EMB_VINCULADO]
     ,		E.[SIG_AEROPORTO_DESTINO]
     ,		E.[DTH_NORMAL_DECOLAGEM]
     ,		E.[DTH_EFETIVA_DECOLAGEM]
	 ,		E.[NUM_VOO]*/
FROM (
SELECT		D.[SIG_AEROPORTO]
      ,		D.[NUM_VOO]
      ,		D.[DTH_NORMAL_POUSO]
      ,		D.[DTH_EFETIVA_POUSO]
      ,		D.[COD_CIA_AEREA]
      ,		D.[SIG_CIA_AEREA_IATA]
      ,		D.[NME_CIA_AEREA]
      ,		D.[COD_MATRICULA_AERONAVE]
      ,		D.[SIG_EQUIPAMENTO]
      ,		D.[NME_EQUIPAMENTO]
      ,		D.[COD_VOO_CHEGADA]
      ,		D.[COD_DESEMB_VINCULADO]
      ,		D.[SIG_AEROPORTO_PROCEDENCIA]
      ,		D.[NUM_BOX]
      ,		D.[TIP_BOX]
      ,		D.[DSC_PISTA_POUSO]
      ,		D.[DSC_PISTA_DECOLAGEM]
      ,     M.[COD_MOVIMENTO]
      ,     M.[TIP_MOVIMENTO]
      ,     M.[DTH_MOVIMENTO]
      ,     M.[NUM_BOX] NUM_BOX_MOV
      ,     M.[TIP_BOX] TIP_BOX_MOV
      ,     M.[NUM_TPS]
      ,     D.COD_STATUS COD_STATUS_DES
      ,		M.COD_STATUS COD_STATUS_MOV
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE] D
		INNER JOIN [IEOP].[dbo].[IEOP_MOVIMENTACAO] M ON
		(M.COD_STATUS = D.COD_STATUS AND
		 M.SIG_AEROPORTO = D.SIG_AEROPORTO)
 WHERE	 D.COD_STATUS = 172594 --172582 --172570
   AND  (D.DTH_NORMAL_POUSO > '20110801' OR D.DTH_NORMAL_POUSO IS NULL)
   AND  (M.DTH_MOVIMENTO > '20110801' OR M.DTH_MOVIMENTO IS NULL)
) O 
  /*LEFT JOIN [IEOP].[dbo].[IEOP_EMBARQUE] E ON 
       (E.COD_STATUS = O.COD_STATUS_DES AND
	    E.SIG_AEROPORTO = O.SIG_AEROPORTO)
 WHERE	(E.DTH_NORMAL_DECOLAGEM > '20110801' OR E.DTH_NORMAL_DECOLAGEM IS NULL) */
 ORDER BY
        O.[COD_MOVIMENTO]
        
        
/*
SELECT		D.[SIG_AEROPORTO]
      ,		D.[NUM_VOO]
      ,		D.[DTH_NORMAL_POUSO]
      ,		D.[DTH_EFETIVA_POUSO]
      --,		E.[DTH_NORMAL_DECOLAGEM]
      --,		E.[DTH_EFETIVA_DECOLAGEM]
	  --,		E.[NUM_VOO]
      ,		D.[COD_CIA_AEREA]
      ,		D.[SIG_CIA_AEREA_IATA]
      ,		D.[NME_CIA_AEREA]
      ,		D.[COD_MATRICULA_AERONAVE]
      ,		D.[SIG_EQUIPAMENTO]
      ,		D.[NME_EQUIPAMENTO]
      ,		D.[COD_VOO_CHEGADA]
      ,		D.[COD_DESEMB_VINCULADO]
      ,		D.[SIG_AEROPORTO_PROCEDENCIA]
      ,		D.[NUM_BOX]
      ,		D.[TIP_BOX]
      ,		D.[DSC_PISTA_POUSO]
      ,		D.[DSC_PISTA_DECOLAGEM]
      --,		E.[COD_VOO_CHEGADA_ANT]
      --,		E.[COD_EMB_VINCULADO]
      --,		E.[SIG_AEROPORTO_DESTINO]
      ,     M.[COD_MOVIMENTO]
      ,     M.[TIP_MOVIMENTO]
      ,     M.[DTH_MOVIMENTO]
      ,     M.[NUM_BOX]
      ,     M.[TIP_BOX]
      ,     M.[NUM_TPS]
      ,     D.COD_STATUS
      ,     E.COD_STATUS
      ,		M.COD_STATUS
  FROM	[IEOP].[dbo].[IEOP_DESEMBARQUE] D
		INNER JOIN [IEOP].[dbo].[IEOP_MOVIMENTACAO] M ON
		(M.COD_STATUS = D.COD_STATUS AND
		 M.SIG_AEROPORTO = D.SIG_AEROPORTO)
		 LEFT OUTER JOIN [IEOP].[dbo].[IEOP_EMBARQUE] E ON 
        (E.COD_STATUS = M.COD_STATUS AND
		 E.SIG_AEROPORTO = M.SIG_AEROPORTO)
 WHERE	 D.COD_STATUS = 172594 --172595 --172570
   AND  (D.DTH_NORMAL_POUSO > '20110801' OR D.DTH_NORMAL_POUSO IS NULL)
   AND  (E.DTH_NORMAL_DECOLAGEM > '20110801' OR E.DTH_NORMAL_DECOLAGEM IS NULL)
   AND  (M.DTH_MOVIMENTO > '20110801' OR M.DTH_MOVIMENTO IS NULL)
 ORDER BY
        M.[COD_MOVIMENTO]
        

SELECT	*
  FROM [IEOP].[dbo].[IEOP_DESEMBARQUE]
 WHERE COD_STATUS = 172594
   AND DTH_EFETIVA_POUSO > '20080101'

SELECT	*
  FROM [IEOP].[dbo].[IEOP_EMBARQUE] 
 WHERE COD_STATUS = 172594  
   AND DTH_EFETIVA_DECOLAGEM > '20080101'

SELECT	*
  FROM [IEOP].[dbo].[IEOP_EMBARQUE]
 WHERE DTH_EFETIVA_DECOLAGEM IS NULL
 
SELECT  *
  FROM  [S-RJBN135\PRDSBGL01].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW]
 WHERE  DH_PAR_EFE IS NULL 
 
SELECT	*
  FROM [IEOP].[dbo].[IEOP_MOVIMENTACAO]
 WHERE COD_STATUS = 172594 
   AND DTH_MOVIMENTO > '20110801'



*/