SELECT  EMP_NUMERO_CPF AS NUM_CPF
     ,  TO_CHAR(EMP_DATA_NASCIMENTO, 'DD/MM/YYYY') AS DAT_NASCIMENTO
     ,  EMP_NU_CARTEIRA_IDENTIDADE AS NUM_CARTEIRA_IDENTIDADE
     ,  EMP_SIGLA_ORGAO_EMITENTE_CI || '/' ||  EMP_UFE_SIGLA_CI AS NOM_ORGAO_EXPEDICAO_CI
     ,  '6133123848' AS NUM_TELEFONE  --ALTERAR (DA TABELA DE TELEFONE - RAMAL)
     ,  EMP_NOME AS NME_CADASTRO
     ,  EMP_ENDERECO_ELETRONICO_MAIL AS DSC_ENDERECO_ELETRONICO
     ,  (SELECT DEP_SIGLA FROM DEPENDENCIAS WHERE DEP_CODIGO = EMP_DEP_CODIGO_LOTACAO) AS SIG_DEP_LOTACAO
     ,  (SELECT DEP_NOME FROM DEPENDENCIAS WHERE DEP_CODIGO = EMP_DEP_CODIGO_LOTACAO) AS NME_DEP_LOTACAO
     ,  (SELECT DEP_SIGLA FROM DEPENDENCIAS WHERE DEP_CODIGO = EMP_DEP_CODIGO_FISICO) AS SIG_DEP_FISICAO
     ,  (SELECT DEP_NOME FROM DEPENDENCIAS WHERE DEP_CODIGO = EMP_DEP_CODIGO_FISICO) AS NME_DEP_FISICA
     ,  (SELECT UOR_SIGLA FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EMP_UOR_CODIGO_LOTACAO) AS SIG_UOR_LOTACAO
     ,  (SELECT UOR_NOME FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EMP_UOR_CODIGO_LOTACAO) AS NME_UOR_LOTACAO
     ,  (SELECT UOR_SIGLA FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EMP_UOR_CODIGO_FISICO) AS SIG_UOR_FISICAO
     ,  (SELECT UOR_NOME FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = EMP_UOR_CODIGO_FISICO) AS NME_UOR_FISICA
     ,  '209552' AS NUM_MAT_SUPERIOR_IMEDIATO --ALTERAR  (PEGA O CHEFE IMADIATO)
     ,  '21386463191' AS NUM_CPF_SUPERIOR_IMEDIATO --ALTERAR (PEGA O CHEFE IMADIATO)
     ,  'A' AS DSC_SITUACAO_FUNCIONAL  --ALTERAR (Por exemplo: A – ativo; I – Inativo; L – licença -> EMP_STATUS E OCORRENCIAS_EMPREGADOS)
     ,  'EMPREGADO' AS TIP_USUARIO  --ALTERAR (TAMBÉM PARA ESTAGIARIO E TERCEIROS)
     ,  'FALSE' AS STA_GERENTE  --ALTERAR (COLOCAR TRUE SOMENTE PARA A FUNÇÃO DE GERENTE DA AREA)
     ,  EMP_NUMERO_MATRICULA AS NUM_MATRICULA
     ,  TO_CHAR(EMP_DATA_ADMISSAO, 'DD/MM/YYYY') AS DAT_ADMISSAO
     ,  'COORDENADOR SEDE' AS NME_CARGO  --ALTERAR (PEGAR DA TABELAS DE FUNÇÃO OU CARGO)
/*     ,  EMP_STATUS
     ,  EMP_QLP_CAR_CODIGO
     ,  EMP_QLP_CAR_CODIGO_NIVEL
     ,  EMP_QLP_CAR_OCC_CODIGO
     ,  EMP_QFU_FUN_CODIGO
     ,  EMP_QFU_HFL_UOR_CODIGO
     */     
  FROM  CADASTROS
 WHERE  EMP_NUMERO_MATRICULA = 1190738
