---********************************************************************************************

SELECT * 
INTO TAB_CIA_AEREA
FROM (
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA
FROM	dbo.BIOGER_RPE_DES
WHERE	GRUPO_VOO = 1 AND SIGLA_IATA_CIA_AEREA NOT IN ('AVG', 'MIL')
UNION
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA
FROM	dbo.BIOGER_RPE_EMB
WHERE	GRUPO_VOO = 1 AND SIGLA_IATA_CIA_AEREA NOT IN ('AVG', 'MIL')
ORDER BY 1
) A


INSERT INTO TAB_CIA_AEREA
SELECT * 
FROM (
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA,1 AS A
FROM	dbo.BIOGER_RPE_DES
WHERE	GRUPO_VOO = 1 AND SIGLA_IATA_CIA_AEREA NOT IN ('AVG', 'MIL')
UNION
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA,1 AS A
FROM	dbo.BIOGER_RPE_EMB
WHERE	GRUPO_VOO = 1 AND SIGLA_IATA_CIA_AEREA NOT IN ('AVG', 'MIL')
UNION
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA,1 AS A
FROM	dbo.BIOGER_RPE_DES
WHERE	GRUPO_VOO = 2
UNION
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, NME_CIA_AEREA,1 AS A
FROM	dbo.BIOGER_RPE_EMB
WHERE	GRUPO_VOO = 2
) A

---********************************************************************************************

SELECT * 
INTO TAB_EQUIPAMENTO
FROM (
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_DES
UNION
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_EMB
) A


INSERT INTO TAB_EQUIPAMENTO
SELECT * 
FROM (
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_DES
UNION
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_EMB
) A

/*
SELECT	COUNT(1) 
FROM	BIOGER_RPE_DES
--UPDATE BIOGER_RPE_DES SET SIGLA_IATA_CIA_AEREA = 'AVG'
WHERE	SIGLA_IATA_CIA_AEREA IS NULL


SELECT	COUNT(1) 
FROM	BIOGER_RPE_EMB
--UPDATE BIOGER_RPE_EMB SET SIGLA_IATA_CIA_AEREA = 'AVG'
WHERE	SIGLA_IATA_CIA_AEREA IS NULL


SELECT	COUNT(1) 
FROM	BIOGER_RPE_DES
--UPDATE BIOGER_RPE_DES SET SIGLA_IATA_CIA_AEREA = 'AVG'
WHERE	SIGLA_IATA_CIA_AEREA = ''


SELECT	COUNT(1) 
FROM	BIOGER_RPE_EMB
--UPDATE BIOGER_RPE_EMB SET SIGLA_IATA_CIA_AEREA = 'AVG'
WHERE	SIGLA_IATA_CIA_AEREA = ''

*/

---********************************************************************************************

SELECT SIGLA_IATA_CIA_AEREA, COUNT(1)
FROM TAB_CIA_AEREA
GROUP BY SIGLA_IATA_CIA_AEREA
HAVING COUNT(1) > 1


SELECT * FROM TAB_CIA_AEREA

SELECT	*--COUNT(1)
FROM	dbo.BIOGER_RPE_EMB
WHERE	SIGLA_IATA_CIA_AEREA NOT IN (SELECT SIGLA_IATA_CIA_AEREA FROM TAB_CIA_AEREA)

UPDATE BIOGER_RPE_EMB SET SIGLA_IATA_CIA_AEREA = 'MIL' WHERE SIGLA_IATA_CIA_AEREA IN ('MAR')


SELECT	*--COUNT(1)
FROM	dbo.BIOGER_RPE_DES
WHERE	SIGLA_IATA_CIA_AEREA NOT IN (SELECT SIGLA_IATA_CIA_AEREA FROM TAB_CIA_AEREA)

UPDATE BIOGER_RPE_DES SET SIGLA_IATA_CIA_AEREA = 'AVG' WHERE SIGLA_IATA_CIA_AEREA IN ('EPA')

---********************************************************************************************

SELECT	*--COUNT(1)
FROM	dbo.BIOGER_RPE_EMB
WHERE	SIGLA_EQUIPAMENTO NOT IN (SELECT SIGLA_EQUIPAMENTO FROM TAB_EQUIPAMENTO)

SELECT	*--COUNT(1)
FROM	dbo.BIOGER_RPE_DES
WHERE	SIGLA_EQUIPAMENTO NOT IN (SELECT SIGLA_EQUIPAMENTO FROM TAB_EQUIPAMENTO)


---********************************************************************************************

DECLARE		@SIGLA_EQUIPAMENTO			VARCHAR(10)
,			@SIGLA_EQUIPAMENTO_ATU		VARCHAR(10)
,			@NME_EQUIPAMENTO			VARCHAR(20)

CREATE TABLE #TEMP_EQUIPAMENTO (
		SIGLA_EQUIPAMENTO	VARCHAR(10)
,		NME_EQUIPAMENTO	VARCHAR(20)
)

DECLARE C_EQUIPAMENTO CURSOR FOR
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_DES
UNION
SELECT	DISTINCT SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_EMB
ORDER BY 1

OPEN C_EQUIPAMENTO
FETCH NEXT FROM C_EQUIPAMENTO 
INTO @SIGLA_EQUIPAMENTO
,    @NME_EQUIPAMENTO

SET @SIGLA_EQUIPAMENTO_ATU = ''

WHILE @@FETCH_STATUS = 0
BEGIN

	IF (@SIGLA_EQUIPAMENTO_ATU != @SIGLA_EQUIPAMENTO) BEGIN
		INSERT INTO #TEMP_EQUIPAMENTO VALUES (@SIGLA_EQUIPAMENTO,@NME_EQUIPAMENTO)
	END

	SET @SIGLA_EQUIPAMENTO_ATU = @SIGLA_EQUIPAMENTO

	FETCH NEXT FROM C_EQUIPAMENTO 
	INTO @SIGLA_EQUIPAMENTO
	,    @NME_EQUIPAMENTO

END

CLOSE C_EQUIPAMENTO
DEALLOCATE C_EQUIPAMENTO

INSERT INTO dbo.TAB_EQUIPAMENTO
SELECT * FROM #TEMP_EQUIPAMENTO
DROP TABLE #TEMP_EQUIPAMENTO

--TRUNCATE TABLE dbo.TAB_EQUIPAMENTO

SELECT  SIGLA_EQUIPAMENTO, COUNT(1)
FROM	TAB_EQUIPAMENTO
GROUP BY SIGLA_EQUIPAMENTO
HAVING COUNT(1) > 1

--APOS UMA NOVA CARGA. TEM QUE SER REFEITO DATETIME, AERONAVES, EQUIPAMENTOS

--DATETIME
INSERT INTO dbo.TAB_DATETIME
SELECT	DISTINCT
		YEAR(DATA_HORA_EFETIVA_POUSO) AS ANO
,		MONTH(DATA_HORA_EFETIVA_POUSO) AS MES
,		DAY(DATA_HORA_EFETIVA_POUSO) AS DIA
,		CONVERT(INT, SUBSTRING(CONVERT(VARCHAR(8),DATA_HORA_EFETIVA_POUSO,108),1,2)) AS HORA
,		CONVERT(INT, SUBSTRING(CONVERT(VARCHAR(8),DATA_HORA_EFETIVA_POUSO,108),4,2)) AS MINUTO
FROM	dbo.BIOGER_RPE_DES_MIG
UNION
SELECT	DISTINCT
		YEAR(DATA_HORA_EFETIVA_DECOLAGEM) AS ANO
,		MONTH(DATA_HORA_EFETIVA_DECOLAGEM) AS MES
,		DAY(DATA_HORA_EFETIVA_DECOLAGEM) AS DIA
,		CONVERT(INT, SUBSTRING(CONVERT(VARCHAR(8),DATA_HORA_EFETIVA_DECOLAGEM,108),1,2)) AS HORA
,		CONVERT(INT, SUBSTRING(CONVERT(VARCHAR(8),DATA_HORA_EFETIVA_DECOLAGEM,108),4,2)) AS MINUTO
FROM	dbo.BIOGER_RPE_EMB_MIG

--MATRICULA AERONAVE
INSERT INTO TAB_MATRICULA_AERONAVE
SELECT	DISTINCT
		MATRICULA_AERONAVE
FROM	dbo.BIOGER_RPE_DES_MIG
WHERE	MATRICULA_AERONAVE NOT IN (SELECT MATRICULA_AERONAVE FROM TAB_MATRICULA_AERONAVE)

INSERT INTO TAB_MATRICULA_AERONAVE
SELECT	DISTINCT
		MATRICULA_AERONAVE
FROM	dbo.BIOGER_RPE_EMB_MIG
WHERE	MATRICULA_AERONAVE NOT IN (SELECT MATRICULA_AERONAVE FROM TAB_MATRICULA_AERONAVE)

--EQUIPAMENTO
INSERT INTO TAB_EQUIPAMENTO
SELECT	SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_EMB_MIG
WHERE	SIGLA_EQUIPAMENTO NOT IN (SELECT SIGLA_EQUIPAMENTO FROM TAB_EQUIPAMENTO)
UNION
SELECT	SIGLA_EQUIPAMENTO, NME_EQUIPAMENTO
FROM	dbo.BIOGER_RPE_DES_MIG
WHERE	SIGLA_EQUIPAMENTO NOT IN (SELECT SIGLA_EQUIPAMENTO FROM TAB_EQUIPAMENTO)


--SELECT * FROM TAB_EQUIPAMENTO

SELECT	*
FROM	BIOGER_RPE_DES
WHERE	MATRICULA_AERONAVE = 'GUARÁ'

--UPDATE BIOGER_RPE_DES SET MATRICULA_AERONAVE = 'GUARÁ' WHERE MATRICULA_AERONAVE = 'GUARÁ'



----
--truncate table TAB_DATETIME
----

SET NOCOUNT ON

DECLARE		@DATA			DATETIME
,			@ANO			INT
,			@MES			INT
,			@DIA			INT
,			@HORA			INT
,			@MINUTO			INT

CREATE TABLE #TEMP_DATETIME (
			ANO			INT
,			MES			INT
,			DIA			INT
,			HORA			INT
,			MINUTO			INT
)

SET	@DATA = '19960101'
SET	@HORA = 0
SET	@MINUTO	= 0

WHILE @DATA < '20110101'
BEGIN
	
	SELECT		@ANO	=	YEAR(@DATA)
	,			@MES	=	MONTH(@DATA)
	,			@DIA	=	DAY(@DATA)

	WHILE @HORA < 24
	BEGIN
		WHILE @MINUTO < 60
		BEGIN		
			INSERT INTO #TEMP_DATETIME VALUES(@ANO,@MES,@DIA,@HORA,@MINUTO)
			SET @MINUTO = @MINUTO + 1
		END
		SET @HORA = @HORA + 1
		SET @MINUTO = 0
	END

	SET @DATA = DATEADD(DD,1,@DATA)
	SET	@HORA = 0
	SET	@MINUTO	= 0
END

INSERT INTO dbo.TAB_DATETIME
SELECT * FROM #TEMP_DATETIME
DROP TABLE #TEMP_DATETIME


--SELECT COUNT(1) FROM TAB_DATETIME WHERE MINUTO = 60
--UPDATE TAB_DATETIME SET MINUTO = 0 WHERE MINUTO = 60




SELECT	COUNT(1) AS TOTAL
FROM	BIOGER_RPE_DES
WHERE	YEAR(DATA_HORA_EFETIVA_POUSO) = 2008
AND		CD_STA NOT IN (SELECT CD_STA FROM BIOGER_RPE_EMB WHERE	YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = 2008)


SELECT	COUNT(1) AS TOTAL
FROM	BIOGER_RPE_EMB
WHERE	YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = 2008
AND		CD_STA NOT IN (SELECT CD_STA FROM BIOGER_RPE_DES WHERE	YEAR(DATA_HORA_EFETIVA_POUSO) = 2008)

SELECT	COUNT(1) AS TOTAL
FROM	BIOGER_RPE_EMB E
,		BIOGER_RPE_DES D
WHERE	E.CD_STA = D.CD_STA
AND		E.SIGLA_AEROPORTO = D.SIGLA_AEROPORTO
AND		YEAR(D.DATA_HORA_EFETIVA_POUSO) = 2008
AND		YEAR(E.DATA_HORA_EFETIVA_DECOLAGEM) = 2008
AND		E.CD_STA NOT IN (SELECT CD_STA FROM BIOGER_RPE_MOV WHERE	YEAR(DATA_HORA_MOV) = 2008)



---
--**********************
---
SELECT	SIGLA_IATA_CIA_AEREA + CONVERT(VARCHAR(5),NUMERO_VOO) AS NUM_VOO
,		SIGLA_EQUIPAMENTO
,		SIGLA_AEROPORTO_PRO
,		RIGHT('00' + CONVERT(VARCHAR(2), DIA_DES), 2) + '/' + RIGHT('00' + CONVERT(VARCHAR(2), MES_DES), 2) + '/' + CONVERT(CHAR(4), ANO_DES) + ' ' + RIGHT('00' + CONVERT(VARCHAR(2), HORA_DES), 2) + ':' + RIGHT('00' + CONVERT(VARCHAR(2), MINUTO_DES), 2) AS DATA_HORA_DES
,		SIGLA_AEROPORTO
,		RIGHT('00' + CONVERT(VARCHAR(2), DIA_EMB), 2) + '/' + RIGHT('00' + CONVERT(VARCHAR(2), MES_EMB), 2) + '/' + CONVERT(CHAR(4), ANO_EMB) + ' ' + RIGHT('00' + CONVERT(VARCHAR(2), HORA_EMB), 2) + ':' + RIGHT('00' + CONVERT(VARCHAR(2), MINUTO_EMB), 2) AS DATA_HORA_EMB		
,		SIGLA_AEROPORTO_DES
FROM	VIW_DADOS_BIOGER2
WHERE	ANO_EMB = 2008
AND		MES_EMB = 8
AND		DIA_EMB	= 17
AND		MATRICULA_AERONAVE = 'PTMZW'
ORDER BY
		HORA_EMB
,		MINUTO_EMB


/*
SELECT	DISTINCT SIGLA_IATA_CIA_AEREA, MATRICULA_AERONAVE
FROM	VIW_DADOS_BIOGER2
WHERE	ANO_EMB = 2008
AND		MES_EMB = 8
AND		DIA_EMB	= 15
*/

---------------
--**********************************
----------------------

SELECT	DISTINCT NR_BOX
INTO TAB_BOX
FROM	dbo.BIOGER_RPE_DES


SELECT	*
FROM	dbo.BIOGER_RPE_DES
--UPDATE BIOGER_RPE_DES SET NR_BOX = 'NONE'
WHERE	NR_BOX IS NULL

SELECT	*
FROM	dbo.BIOGER_RPE_DES
--UPDATE BIOGER_RPE_DES SET NR_BOX = 'NONE'
WHERE	NR_BOX = ''

SELECT	*
FROM	dbo.BIOGER_RPE_EMB
--UPDATE BIOGER_RPE_EMB SET NR_BOX = 'NONE'
WHERE	NR_BOX IS NULL

SELECT	*
FROM	dbo.BIOGER_RPE_EMB
--UPDATE BIOGER_RPE_EMB SET NR_BOX = 'NONE'
WHERE	NR_BOX = ''



INSERT INTO TAB_BOX
SELECT	DISTINCT
		NR_BOX
FROM	dbo.BIOGER_RPE_DES
WHERE	NR_BOX NOT IN (SELECT NR_BOX FROM TAB_BOX)

INSERT INTO TAB_BOX
SELECT	DISTINCT
		NR_BOX
FROM	dbo.BIOGER_RPE_EMB
WHERE	NR_BOX NOT IN (SELECT NR_BOX FROM TAB_BOX)


SELECT * FROM TAB_BOX
GRANT SELECT ON TAB_BOX TO RL_BIOGER_GERAL