USE [IFRSIVNET]
GO

/****** Object:  Index [HST_VOO_OPERACAO_STATUS_03]    Script Date: 05/17/2012 16:52:44 ******/
CREATE NONCLUSTERED INDEX [HST_VOO_OPERACAO_STATUS_03] ON [dbo].[HST_VOO_OPERACAO_STATUS] 
(
	[DAT_INSERCAO] ASC
)
INCLUDE ( [SEQ_HST_VOO_OPERACAO]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO

/****** Object:  Index [HST_VOO_OPERACAO_STATUS_IX]    Script Date: 05/17/2012 16:52:44 ******/
CREATE NONCLUSTERED INDEX [HST_VOO_OPERACAO_STATUS_IX] ON [dbo].[HST_VOO_OPERACAO_STATUS] 
(
	[SEQ_HST_VOO_OPERACAO] ASC,
	[DAT_PREV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO

/****** Object:  Index [HST_VOO_OPERACAO_STATUS_IX2]    Script Date: 05/17/2012 16:52:44 ******/
CREATE NONCLUSTERED INDEX [HST_VOO_OPERACAO_STATUS_IX2] ON [dbo].[HST_VOO_OPERACAO_STATUS] 
(
	[DAT_PREV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF, FILLFACTOR = 70) ON [PRIMARY]
GO

/****** Object:  Index [IDX_HST_VOO_OPERACAO_STATUS_01]    Script Date: 05/17/2012 16:52:44 ******/
CREATE NONCLUSTERED INDEX [IDX_HST_VOO_OPERACAO_STATUS_01] ON [dbo].[HST_VOO_OPERACAO_STATUS] 
(
	[SEQ_HST_VOO_OPERACAO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO

