
USE IEOP

--DES
SELECT	DISTINCT
	    D.SIG_AEROPORTO AS SIGLA_AEROPORTO
,		D.NUM_VOO NUMERO_VOO
,       D.DTH_NORMAL_POUSO DATA_HORA_NORMAL_POUSO
,		D.DTH_EFETIVA_POUSO DATA_HORA_EFETIVA_POUSO
,		D.COD_CIA_AEREA CD_COM
,		D.SIG_CIA_AEREA_IATA SIGLA_IATA_CIA_AEREA
,       D.NME_CIA_AEREA
,		D.COD_MATRICULA_AERONAVE MATRICULA_AERONAVE
,		D.NUM_GRUPO_VOO_DESEMB GRUPO_VOO
,		D.NUM_NATUREZA_VOO_DESEMB NATUREZA_VOO
,		D.NUM_CLASSE_VOO_DESEMB CLASSE_VOO
,		D.NUM_CATEGORIA_VOO_DESEMB CATEGORIA_VOO
,       D.NUM_CATEGORIA_VOO_DESEMB_VINCULADO CATEGORIA_VOO_VINCULADO
,		D.SIG_EQUIPAMENTO SIGLA_EQUIPAMENTO
,       D.NME_EQUIPAMENTO
,		D.QTD_PAX_DESEMB_DOM DESEMB_PASSAGEIRO_DOM
,		D.QTD_PAX_DESEMB_INT DESEMB_PASSAGEIRO_INT
,		D.QTD_BAG_DESEMB_DOM DESEMB_BAGAGEM_DOM
,		D.QTD_BAG_DESEMB_INT DESEMB_BAGAGEM_INT
,		D.QTD_CAR_DESEMB_DOM DESEMB_CARGA_DOM
,		D.QTD_CAR_DESEMB_INT DESEMB_CARGA_INT
,		D.QTD_COR_DESEMB_DOM DESEMB_CORREIO_DOM
,		D.QTD_COR_DESEMB_INT DESEMB_CORREIO_INT
,		D.QTD_BAG_TRANSITO_DOM TRANSITO_BAGAGEM_DOM
,		D.QTD_BAG_TRANSITO_INT TRANSITO_BAGAGEM_INT
,		D.QTD_CAR_TRANSITO_DOM TRANSITO_CARGA_DOM
,		D.QTD_CAR_TRANSITO_INT TRANSITO_CARGA_INT
,		D.QTD_COR_TRANSITO_DOM TRANSITO_CORREIO_DOM
,		D.QTD_COR_TRANSITO_INT TRANSITO_CORREIO_INT
,		D.QTD_CON_TRANSITO_DOM TRANSITO_CONEXAO_DOM
,		D.QTD_CON_TRANSITO_INT TRANSITO_CONEXAO_INT
,       D.COD_VOO_CHEGADA COD_CHG_VOO
,       D.COD_DESEMB_VINCULADO DES_VIN
,		D.NUM_BOX NR_BOX_DES
,       D.TIP_BOX TP_BOX
,       D.SIG_AEROPORTO_PROCEDENCIA SIGLA_AEROPORTO_PRO
,       D.FLG_TAXI_AEREO FL_AEN_TAX
,       D.FLG_EQUIP_HELICOP FL_EQP_HLC
,       D.COD_STATUS CD_STA
,       D.DSC_PISTA_POUSO DSC_PISTA_POU
,       D.DSC_PISTA_DECOLAGEM DSC_PISTA_DEC
FROM	IEOP.dbo.IEOP_DESEMBARQUE AS D
WHERE	D.FLG_MIGRADO != 2


--EMB
SELECT	DISTINCT
    	E.SIG_AEROPORTO AS SIGLA_AEROPORTO
,		E.NUM_VOO NUMERO_VOO
,       E.DTH_NORMAL_DECOLAGEM DATA_HORA_NORMAL_DECOLAGEM
,		E.DTH_EFETIVA_DECOLAGEM DATA_HORA_EFETIVA_DECOLAGEM
,		E.COD_CIA_AEREA CD_COM
,		E.SIG_CIA_AEREA_IATA SIGLA_IATA_CIA_AEREA
,       E.NME_CIA_AEREA 
,		E.COD_MATRICULA_AERONAVE MATRICULA_AERONAVE
,		E.NUM_GRUPO_VOO_EMB GRUPO_VOO
,		E.NUM_NATUREZA_VOO_EMB NATUREZA_VOO
,		E.NUM_CLASSE_VOO_EMB CLASSE_VOO
,		E.NUM_CATEGORIA_VOO_EMB CATEGORIA_VOO
,       E.NUM_CATEGORIA_VOO_EMB_VINCULADO CATEGORIA_VOO_VINCULADO
,		E.SIG_EQUIPAMENTO SIGLA_EQUIPAMENTO
,       E.NME_EQUIPAMENTO
,		E.QTD_TARIFA_PAGA_BILHETE_DOM_EMB EMB_TARIFA_PAGA_BILHETE_DOM
,		E.QTD_TARIFA_PAGA_BILHETE_INT_EMB EMB_TARIFA_PAGA_BILHETE_INT
,		E.QTD_TARIFA_PAGA_CHECKIN_DOM_EMB EMB_TARIFA_PAGA_CHECKIN_DOM
,		E.QTD_TARIFA_PAGA_CHECKIN_INT_EMB EMB_TARIFA_PAGA_CHECKIN_INT
,		E.QTD_ISENTA_COLO_EMB EMB_ISENTA_COLO
,		E.QTD_ISENTA_TRANSITO_EMB EMB_ISENTA_TRANSITO
,		E.QTD_ISENTA_CONEXAO_EMB_DOM EMB_ISENTA_CONEXAO_DOM
,		E.QTD_ISENTA_CONEXAO_EMB_INT EMB_ISENTA_CONEXAO_INT
,		E.QTD_ISENTA_OUTRAS_EMB EMB_ISENTA_OUTRAS
,		E.QTD_BAG_EMB_DOM EMB_BAGAGEM_DOM
,		E.QTD_BAG_EMB_INT EMB_BAGAGEM_INT
,		E.QTD_CAR_EMB_DOM EMB_CARGA_DOM
,		E.QTD_CAR_EMB_INT EMB_CARGA_INT
,		E.QTD_COR_EMB_DOM EMB_CORREIO_DOM
,		E.QTD_COR_EMB_INT EMB_CORREIO_INT
,		E.QTD_TARIFA_PAG_BILHETE_EMB_DOM_ANT EMB_TARIFA_PAG_BILHETE_DOM_ANT
,		E.QTD_TARIFA_PAG_BILHETE_EMB_INT_ANT EMB_TARIFA_PAG_BILHETE_INT_ANT
,		E.QTD_TARIFA_PAG_CHECKIN_EMB_DOM_ANT EMB_TARIFA_PAG_CHECKIN_DOM_ANT
,		E.QTD_TARIFA_PAG_CHECKIN_EMB_INT_ANT EMB_TARIFA_PAG_CHECKIN_INT_ANT
,       E.COD_VOO_CHEGADA_ANT COD_CHG_VOO_ANT
,       E.COD_EMB_VINCULADO EMB_VIN
,       E.NUM_BOX NR_BOX
,       E.TIP_BOX TP_BOX
,       E.SIG_AEROPORTO_DESTINO SIGLA_AEROPORTO_DES
,       E.FLG_TAXI_AEREA FL_AEN_TAX
,       E.FLG_EQUIP_HELICOP FL_EQP_HLC
,       E.COD_STATUS CD_STA
,       E.DSC_PISTA_DECOLAGEM DSC_PISTA_DEC
,		E.DSC_PISTA_POUSO DSC_PISTA_POU
FROM	IEOP.dbo.IEOP_EMBARQUE AS E
WHERE	E.FLG_MIGRADO != 2

/*
CREATE ROLE RPE_CONSULTA
GRANT SELECT ON IEOP_DESEMBARQUE TO RPE_CONSULTA
GRANT SELECT ON IEOP_EMBARQUE TO RPE_CONSULTA
GRANT SELECT ON IEOP_MOVIMENTACAO TO RPE_CONSULTA




/****** Object:  LinkedServer [SEDE - RPE_CONSULTA]    Script Date: 05/10/2012 09:03:03 ******/
EXEC master.dbo.sp_addlinkedserver @server = N'SEDE - RPE_CONSULTA', @srvproduct=N'SQLSERVER', @provider=N'SQLNCLI', @datasrc=N'S-SEBN111', @catalog=N'IEOP'
 /* For security reasons the linked server remote logins password is changed with ######## */
EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname=N'SEDE - RPE_CONSULTA',@useself=N'False',@locallogin=NULL,@rmtuser=N'usr_rpe_consulta',@rmtpassword='Infr@123'

GO
*/