USE BIOGER
--**********************************************************************************************
--DADOS DUPLICADOS DE DESEMBARQUE
--**********************************************************************************************

SELECT	*
INTO	BIOGER_RPE_DES_TEMP
FROM (
SELECT ISNULL(SIGLA_AEROPORTO, 0) AS SIGLA_AEROPORTO
      ,ISNULL(NUMERO_VOO, 0) AS NUMERO_VOO
      ,ISNULL(DATA_HORA_NORMAL_POUSO, 0) AS DATA_HORA_NORMAL_POUSO
      ,ISNULL(DATA_HORA_EFETIVA_POUSO, 0) AS DATA_HORA_EFETIVA_POUSO
      ,ISNULL(CD_COM, 0) AS CD_COM
      ,ISNULL(SIGLA_IATA_CIA_AEREA, 0) AS SIGLA_IATA_CIA_AEREA
      ,ISNULL(MATRICULA_AERONAVE, 0) AS MATRICULA_AERONAVE
      ,ISNULL(GRUPO_VOO, 0) AS GRUPO_VOO
      ,ISNULL(NATUREZA_VOO, 0) AS NATUREZA_VOO
      ,ISNULL(CLASSE_VOO, 0) AS CLASSE_VOO
      ,ISNULL(CATEGORIA_VOO, 0) AS CATEGORIA_VOO
      ,ISNULL(CATEGORIA_VOO_VINCULADO, 0) AS CATEGORIA_VOO_VINCULADO
      ,ISNULL(SIGLA_EQUIPAMENTO, 0) AS SIGLA_EQUIPAMENTO
      ,ISNULL(DESEMB_PASSAGEIRO_DOM, 0) AS DESEMB_PASSAGEIRO_DOM
      ,ISNULL(DESEMB_PASSAGEIRO_INT, 0) AS DESEMB_PASSAGEIRO_INT
      ,ISNULL(DESEMB_BAGAGEM_DOM, 0) AS DESEMB_BAGAGEM_DOM
      ,ISNULL(DESEMB_BAGAGEM_INT, 0) AS DESEMB_BAGAGEM_INT
      ,ISNULL(DESEMB_CARGA_DOM, 0) AS DESEMB_CARGA_DOM
      ,ISNULL(DESEMB_CARGA_INT, 0) AS DESEMB_CARGA_INT
      ,ISNULL(DESEMB_CORREIO_DOM, 0) AS DESEMB_CORREIO_DOM
      ,ISNULL(DESEMB_CORREIO_INT, 0) AS DESEMB_CORREIO_INT
      ,ISNULL(TRANSITO_BAGAGEM_DOM, 0) AS TRANSITO_BAGAGEM_DOM
      ,ISNULL(TRANSITO_BAGAGEM_INT, 0) AS TRANSITO_BAGAGEM_INT
      ,ISNULL(TRANSITO_CARGA_DOM, 0) AS TRANSITO_CARGA_DOM
      ,ISNULL(TRANSITO_CARGA_INT, 0) AS TRANSITO_CARGA_INT
      ,ISNULL(TRANSITO_CORREIO_DOM, 0) AS TRANSITO_CORREIO_DOM
      ,ISNULL(TRANSITO_CORREIO_INT, 0) AS TRANSITO_CORREIO_INT
      ,ISNULL(TRANSITO_CONEXAO_DOM, 0) AS TRANSITO_CONEXAO_DOM
      ,ISNULL(TRANSITO_CONEXAO_INT, 0) AS TRANSITO_CONEXAO_INT
      ,ISNULL(COD_CHG_VOO, 0) AS COD_CHG_VOO
      ,ISNULL(DES_VIN, 0) AS DES_VIN
      ,ISNULL(NR_BOX, 0) AS NR_BOX
      ,ISNULL(TP_BOX, 0) AS TP_BOX
      ,ISNULL(SIGLA_AEROPORTO_PRO, 0) AS SIGLA_AEROPORTO_PRO
      ,ISNULL(FL_AEN_TAX, 0) AS FL_AEN_TAX
      ,ISNULL(FL_EQP_HLC, 0) AS FL_EQP_HLC
      ,ISNULL(CD_STA, 0) AS CD_STA
      ,ISNULL(NME_CIA_AEREA, 0) AS NME_CIA_AEREA 
      ,ISNULL(NME_EQUIPAMENTO, 0) AS NME_EQUIPAMENTO
      ,ISNULL(DSC_PISTA_POU, 0) AS DSC_PISTA_POU
      ,ISNULL(DSC_PISTA_DEC, 0) AS DSC_PISTA_DEC
	  ,COUNT(1) TOTAL_REPETICAO
  FROM BIOGER_RPE_DES
 GROUP
    BY ISNULL(SIGLA_AEROPORTO, 0)
      ,ISNULL(NUMERO_VOO, 0)
      ,ISNULL(DATA_HORA_NORMAL_POUSO, 0)
      ,ISNULL(DATA_HORA_EFETIVA_POUSO, 0)
      ,ISNULL(CD_COM, 0)
      ,ISNULL(SIGLA_IATA_CIA_AEREA, 0)
      ,ISNULL(MATRICULA_AERONAVE, 0)
      ,ISNULL(GRUPO_VOO, 0)
      ,ISNULL(NATUREZA_VOO, 0)
      ,ISNULL(CLASSE_VOO, 0)
      ,ISNULL(CATEGORIA_VOO, 0)
      ,ISNULL(CATEGORIA_VOO_VINCULADO, 0)
      ,ISNULL(SIGLA_EQUIPAMENTO, 0)
      ,ISNULL(DESEMB_PASSAGEIRO_DOM, 0)
      ,ISNULL(DESEMB_PASSAGEIRO_INT, 0)
      ,ISNULL(DESEMB_BAGAGEM_DOM, 0)
      ,ISNULL(DESEMB_BAGAGEM_INT, 0)
      ,ISNULL(DESEMB_CARGA_DOM, 0)
      ,ISNULL(DESEMB_CARGA_INT, 0)
      ,ISNULL(DESEMB_CORREIO_DOM, 0)
      ,ISNULL(DESEMB_CORREIO_INT, 0)
      ,ISNULL(TRANSITO_BAGAGEM_DOM, 0)
      ,ISNULL(TRANSITO_BAGAGEM_INT, 0)
      ,ISNULL(TRANSITO_CARGA_DOM, 0)
      ,ISNULL(TRANSITO_CARGA_INT, 0)
      ,ISNULL(TRANSITO_CORREIO_DOM, 0)
      ,ISNULL(TRANSITO_CORREIO_INT, 0)
      ,ISNULL(TRANSITO_CONEXAO_DOM, 0)
      ,ISNULL(TRANSITO_CONEXAO_INT, 0)
      ,ISNULL(COD_CHG_VOO, 0)
      ,ISNULL(DES_VIN, 0)
      ,ISNULL(NR_BOX, 0)
      ,ISNULL(TP_BOX, 0)
      ,ISNULL(SIGLA_AEROPORTO_PRO, 0)
      ,ISNULL(FL_AEN_TAX, 0)
      ,ISNULL(FL_EQP_HLC, 0)
      ,ISNULL(CD_STA, 0)
      ,ISNULL(NME_CIA_AEREA, 0)
      ,ISNULL(NME_EQUIPAMENTO, 0)
      ,ISNULL(DSC_PISTA_POU, 0)
      ,ISNULL(DSC_PISTA_DEC, 0)
HAVING
		COUNT(1) > 1
) DES_TEMP

SELECT  *
-- SELECT SUM(TOTAL_REPETICAO) 
FROM	BIOGER_RPE_DES_TEMP

SELECT	B.* 
--BEGIN TRAN DELETE B
FROM	BIOGER_RPE_DES_TEMP A
,		BIOGER_RPE_DES B
WHERE	A.SIGLA_AEROPORTO = B.SIGLA_AEROPORTO
AND		A.NUMERO_VOO = B.NUMERO_VOO
AND		A.DATA_HORA_EFETIVA_POUSO = B.DATA_HORA_EFETIVA_POUSO
AND		A.DATA_HORA_NORMAL_POUSO = B.DATA_HORA_NORMAL_POUSO
AND		A.CD_COM = B.CD_COM
AND		A.MATRICULA_AERONAVE = B.MATRICULA_AERONAVE
AND		A.GRUPO_VOO = B.GRUPO_VOO
AND		A.NATUREZA_VOO = B.NATUREZA_VOO
AND		A.CLASSE_VOO = B.CLASSE_VOO
AND		A.CATEGORIA_VOO = B.CATEGORIA_VOO

COMMIT TRAN

INSERT INTO [BIOGER_RPE_DES]
SELECT [SIGLA_AEROPORTO]
      ,[NUMERO_VOO]
      ,[DATA_HORA_NORMAL_POUSO]
      ,[DATA_HORA_EFETIVA_POUSO]
      ,[CD_COM]
      ,[SIGLA_IATA_CIA_AEREA]
      ,[MATRICULA_AERONAVE]
      ,[GRUPO_VOO]
      ,[NATUREZA_VOO]
      ,[CLASSE_VOO]
      ,[CATEGORIA_VOO]
      ,[CATEGORIA_VOO_VINCULADO]
      ,[SIGLA_EQUIPAMENTO]
      ,[DESEMB_PASSAGEIRO_DOM]
      ,[DESEMB_PASSAGEIRO_INT]
      ,[DESEMB_BAGAGEM_DOM]
      ,[DESEMB_BAGAGEM_INT]
      ,[DESEMB_CARGA_DOM]
      ,[DESEMB_CARGA_INT]
      ,[DESEMB_CORREIO_DOM]
      ,[DESEMB_CORREIO_INT]
      ,[TRANSITO_BAGAGEM_DOM]
      ,[TRANSITO_BAGAGEM_INT]
      ,[TRANSITO_CARGA_DOM]
      ,[TRANSITO_CARGA_INT]
      ,[TRANSITO_CORREIO_DOM]
      ,[TRANSITO_CORREIO_INT]
      ,[TRANSITO_CONEXAO_DOM]
      ,[TRANSITO_CONEXAO_INT]
      ,[COD_CHG_VOO]
      ,[DES_VIN]
      ,[NR_BOX]
      ,[TP_BOX]
      ,[SIGLA_AEROPORTO_PRO]
      ,[FL_AEN_TAX]
      ,[FL_EQP_HLC]
      ,[CD_STA]
      ,[NME_CIA_AEREA]
      ,[NME_EQUIPAMENTO]
      ,[DSC_PISTA_POU]
      ,[DSC_PISTA_DEC]
      ,3
      ,GETDATE()
  FROM [BIOGER].[dbo].[BIOGER_RPE_DES_TEMP]

DROP TABLE BIOGER_RPE_DES_TEMP



--**********************************************************************************************
--DADOS DUPLICADOS DE EMBARQUE
--**********************************************************************************************

SELECT	*
INTO	BIOGER_RPE_EMB_TEMP
FROM (
SELECT [SIGLA_AEROPORTO]
      ,[NUMERO_VOO]
      ,[DATA_HORA_NORMAL_DECOLAGEM]
      ,[DATA_HORA_EFETIVA_DECOLAGEM]
      ,[CD_COM]
      ,[SIGLA_IATA_CIA_AEREA]
      ,[MATRICULA_AERONAVE]
      ,[GRUPO_VOO]
      ,[NATUREZA_VOO]
      ,[CLASSE_VOO]
      ,[CATEGORIA_VOO]
      ,[CATEGORIA_VOO_VINCULADO]
      ,[SIGLA_EQUIPAMENTO]
      ,[EMB_TARIFA_PAGA_BILHETE_DOM]
      ,[EMB_TARIFA_PAGA_BILHETE_INT]
      ,[EMB_TARIFA_PAGA_CHECKIN_DOM]
      ,[EMB_TARIFA_PAGA_CHECKIN_INT]
      ,[EMB_ISENTA_COLO]
      ,[EMB_ISENTA_TRANSITO]
      ,[EMB_ISENTA_CONEXAO_DOM]
      ,[EMB_ISENTA_CONEXAO_INT]
      ,[EMB_ISENTA_OUTRAS]
      ,[EMB_BAGAGEM_DOM]
      ,[EMB_BAGAGEM_INT]
      ,[EMB_CARGA_DOM]
      ,[EMB_CARGA_INT]
      ,[EMB_CORREIO_DOM]
      ,[EMB_CORREIO_INT]
      ,[EMB_TARIFA_PAG_BILHETE_DOM_ANT]
      ,[EMB_TARIFA_PAG_BILHETE_INT_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_DOM_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_INT_ANT]
      ,[COD_CHG_VOO_ANT]
      ,[EMB_VIN]
      ,[NR_BOX]
      ,[TP_BOX]
      ,[SIGLA_AEROPORTO_DES]
      ,[FL_AEN_TAX]
      ,[FL_EQP_HLC]
      ,[CD_STA]
      ,[NME_CIA_AEREA]
      ,[NME_EQUIPAMENTO]
      ,[DSC_PISTA_POU]
      ,[DSC_PISTA_DEC]
	  ,COUNT(1) TOTAL_REPETICAO
  FROM [BIOGER].[dbo].[BIOGER_RPE_EMB]
 GROUP
    BY [SIGLA_AEROPORTO]
      ,[NUMERO_VOO]
      ,[DATA_HORA_NORMAL_DECOLAGEM]
      ,[DATA_HORA_EFETIVA_DECOLAGEM]
      ,[CD_COM]
      ,[SIGLA_IATA_CIA_AEREA]
      ,[MATRICULA_AERONAVE]
      ,[GRUPO_VOO]
      ,[NATUREZA_VOO]
      ,[CLASSE_VOO]
      ,[CATEGORIA_VOO]
      ,[CATEGORIA_VOO_VINCULADO]
      ,[SIGLA_EQUIPAMENTO]
      ,[EMB_TARIFA_PAGA_BILHETE_DOM]
      ,[EMB_TARIFA_PAGA_BILHETE_INT]
      ,[EMB_TARIFA_PAGA_CHECKIN_DOM]
      ,[EMB_TARIFA_PAGA_CHECKIN_INT]
      ,[EMB_ISENTA_COLO]
      ,[EMB_ISENTA_TRANSITO]
      ,[EMB_ISENTA_CONEXAO_DOM]
      ,[EMB_ISENTA_CONEXAO_INT]
      ,[EMB_ISENTA_OUTRAS]
      ,[EMB_BAGAGEM_DOM]
      ,[EMB_BAGAGEM_INT]
      ,[EMB_CARGA_DOM]
      ,[EMB_CARGA_INT]
      ,[EMB_CORREIO_DOM]
      ,[EMB_CORREIO_INT]
      ,[EMB_TARIFA_PAG_BILHETE_DOM_ANT]
      ,[EMB_TARIFA_PAG_BILHETE_INT_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_DOM_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_INT_ANT]
      ,[COD_CHG_VOO_ANT]
      ,[EMB_VIN]
      ,[NR_BOX]
      ,[TP_BOX]
      ,[SIGLA_AEROPORTO_DES]
      ,[FL_AEN_TAX]
      ,[FL_EQP_HLC]
      ,[CD_STA]
      ,[NME_CIA_AEREA]
      ,[NME_EQUIPAMENTO]
      ,[DSC_PISTA_POU]
      ,[DSC_PISTA_DEC]
HAVING
		COUNT(1) > 1
) EMB_TEMP


SELECT  *
-- SELECT SUM(TOTAL_REPETICAO) 
FROM	BIOGER_RPE_EMB_TEMP

SELECT	B.* 
--BEGIN TRAN DELETE B
FROM	BIOGER_RPE_EMB_TEMP A
,		BIOGER_RPE_EMB B
WHERE	A.SIGLA_AEROPORTO = B.SIGLA_AEROPORTO
AND		A.NUMERO_VOO = B.NUMERO_VOO
AND		A.DATA_HORA_NORMAL_DECOLAGEM = B.DATA_HORA_NORMAL_DECOLAGEM
AND		A.DATA_HORA_EFETIVA_DECOLAGEM = B.DATA_HORA_EFETIVA_DECOLAGEM
AND		A.CD_COM = B.CD_COM
AND		A.MATRICULA_AERONAVE = B.MATRICULA_AERONAVE
AND		A.GRUPO_VOO = B.GRUPO_VOO
AND		A.NATUREZA_VOO = B.NATUREZA_VOO
AND		A.CLASSE_VOO = B.CLASSE_VOO
AND		A.CATEGORIA_VOO = B.CATEGORIA_VOO

COMMIT TRAN

INSERT INTO [BIOGER_RPE_EMB]
SELECT [SIGLA_AEROPORTO]
      ,[NUMERO_VOO]
      ,[DATA_HORA_NORMAL_DECOLAGEM]
      ,[DATA_HORA_EFETIVA_DECOLAGEM]
      ,[CD_COM]
      ,[SIGLA_IATA_CIA_AEREA]
      ,[MATRICULA_AERONAVE]
      ,[GRUPO_VOO]
      ,[NATUREZA_VOO]
      ,[CLASSE_VOO]
      ,[CATEGORIA_VOO]
      ,[CATEGORIA_VOO_VINCULADO]
      ,[SIGLA_EQUIPAMENTO]
      ,[EMB_TARIFA_PAGA_BILHETE_DOM]
      ,[EMB_TARIFA_PAGA_BILHETE_INT]
      ,[EMB_TARIFA_PAGA_CHECKIN_DOM]
      ,[EMB_TARIFA_PAGA_CHECKIN_INT]
      ,[EMB_ISENTA_COLO]
      ,[EMB_ISENTA_TRANSITO]
      ,[EMB_ISENTA_CONEXAO_DOM]
      ,[EMB_ISENTA_CONEXAO_INT]
      ,[EMB_ISENTA_OUTRAS]
      ,[EMB_BAGAGEM_DOM]
      ,[EMB_BAGAGEM_INT]
      ,[EMB_CARGA_DOM]
      ,[EMB_CARGA_INT]
      ,[EMB_CORREIO_DOM]
      ,[EMB_CORREIO_INT]
      ,[EMB_TARIFA_PAG_BILHETE_DOM_ANT]
      ,[EMB_TARIFA_PAG_BILHETE_INT_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_DOM_ANT]
      ,[EMB_TARIFA_PAG_CHECKIN_INT_ANT]
      ,[COD_CHG_VOO_ANT]
      ,[EMB_VIN]
      ,[NR_BOX]
      ,[TP_BOX]
      ,[SIGLA_AEROPORTO_DES]
      ,[FL_AEN_TAX]
      ,[FL_EQP_HLC]
      ,[CD_STA]
      ,[NME_CIA_AEREA]
      ,[NME_EQUIPAMENTO]
      ,[DSC_PISTA_POU]
      ,[DSC_PISTA_DEC]
      ,3
      ,GETDATE()
FROM [BIOGER].[dbo].BIOGER_RPE_EMB_TEMP

DROP TABLE BIOGER_RPE_EMB_TEMP


--**********************************************************************************************
--DADOS DUPLICADOS DE MOVIMENTAÇÃO
--**********************************************************************************************

SELECT	*
INTO	BIOGER_RPE_MOV_TEMP
FROM (
SELECT ISNULL([SIGLA_AEROPORTO], 0) AS [SIGLA_AEROPORTO]
      ,ISNULL([CD_STA], 0) AS [CD_STA]
      ,ISNULL([CD_MOV], 0) AS [CD_MOV]
      ,ISNULL([TIPO_MOV], 0) AS [TIPO_MOV]
      ,ISNULL([DATA_HORA_MOV], 0) AS [DATA_HORA_MOV]
      ,ISNULL([NR_BOX], 0) AS [NR_BOX]
      ,ISNULL([TP_BOX], 0) AS [TP_BOX]
      ,ISNULL([NR_TPS], 0) AS [NR_TPS]
      ,COUNT(1) TOTAL_REPETICAO
  FROM [BIOGER].[dbo].[BIOGER_RPE_MOV]
 GROUP
    BY ISNULL([SIGLA_AEROPORTO], 0)
      ,ISNULL([CD_STA], 0) 
      ,ISNULL([CD_MOV], 0)
      ,ISNULL([TIPO_MOV], 0)
      ,ISNULL([DATA_HORA_MOV], 0) 
      ,ISNULL([NR_BOX], 0)
      ,ISNULL([TP_BOX], 0)
      ,ISNULL([NR_TPS], 0)
HAVING
		COUNT(1) > 1
) MOV_TEMP


SELECT  *
-- SELECT SUM(TOTAL_REPETICAO) 
FROM	BIOGER_RPE_MOV_TEMP

SELECT	B.* 
--BEGIN TRAN DELETE B
FROM	BIOGER_RPE_MOV_TEMP A
,		BIOGER_RPE_MOV B
WHERE	A.SIGLA_AEROPORTO = B.SIGLA_AEROPORTO
AND		A.CD_STA = B.CD_STA
AND		A.CD_MOV = B.CD_MOV
AND		A.TIPO_MOV = B.TIPO_MOV
AND		A.DATA_HORA_MOV = B.DATA_HORA_MOV
AND		A.TP_BOX = B.TP_BOX


COMMIT TRAN

INSERT INTO [BIOGER_RPE_MOV]
SELECT [SIGLA_AEROPORTO]
      ,[CD_STA]
      ,[CD_MOV]
      ,[TIPO_MOV]
      ,[DATA_HORA_MOV]
      ,[NR_BOX]
      ,[TP_BOX]
      ,[NR_TPS]
      ,3
      ,GETDATE()
FROM [BIOGER].[dbo].BIOGER_RPE_MOV_TEMP

DROP TABLE BIOGER_RPE_MOV_TEMP
