SELECT R.RUB_CODIGO, R.RUB_DENOMINACAO, A.MOV_VALOR
FROM MOVIMENTACAO A,
RUBRICAS R
WHERE A.MOV_ANO_REFERENCIA = 2011
AND A.MOV_MES_REFERENCIA = 11
AND A.MOV_VERSAO_PAGAMENTO = 1
AND A.MOV_EMP_NUMERO_MATRICULA = 159047
AND A.MOV_RUB_CODIGO = R.RUB_CODIGO
/


SELECT DISTINCT A.MOV_EMP_NUMERO_MATRICULA
, (SELECT EMP_NOME FROM CADASTROS WHERE EMP_NUMERO_MATRICULA = A.MOV_EMP_NUMERO_MATRICULA) NOME
FROM MOVIMENTACAO A,
RUBRICAS R
WHERE A.MOV_ANO_REFERENCIA = 2011
AND A.MOV_MES_REFERENCIA = 11
AND A.MOV_VERSAO_PAGAMENTO = 1
--AND A.MOV_EMP_NUMERO_MATRICULA = 1028845
AND R.RUB_CODIGO = 1014
AND A.MOV_RUB_CODIGO = R.RUB_CODIGO
/