SELECT	SIG_AEROPORTO
     --,	COD_STATUS
     ,	COD_VOO_CHEGADA
     ,  DTH_EFETIVA_POUSO
     ,  COUNT(1)
  FROM	dbo.IEOP_DESEMBARQUE
 WHERE  COD_VOO_CHEGADA > 0
   AND  DTH_EFETIVA_POUSO IS NOT NULL
 GROUP
    BY	SIG_AEROPORTO
     --,	COD_STATUS
     ,	COD_VOO_CHEGADA
     ,  DTH_EFETIVA_POUSO
HAVING	COUNT(1) > 1
  ORDER
     BY	3


SELECT	*
  FROM	dbo.IEOP_DESEMBARQUE
 WHERE	SIG_AEROPORTO = 'SBRF'
   AND	COD_VOO_CHEGADA = 498671
   AND  DTH_EFETIVA_POUSO = '2013-03-03 23:49:00.000'