insert into documentos_cobranca (
       doc_numero, doc_cbe_ben_sigla,
       doc_cbe_cre_sequencial, doc_data, doc_data_pagamento,
       doc_tipo, doc_especificacao, doc_modalidade,
       doc_emb_emp_numero_matricula, doc_pvi_sequencial,
       doc_cct_codigo, doc_dep_codigo, doc_emb_ben_sigla,
       doc_especificacao_deducao, doc_mes_pagamento,
       doc_ano_pagamento, doc_especificacao_diferenca,
       doc_mes_vale, doc_ano_vale, doc_processo_encerrado,
       doc_guias_emp, doc_nr_doc_fiscal,
       doc_pvi_emp_numero_matricula, doc_dep_resp_incl,
       doc_tipo_pedido, doc_ind_imposto, doc_numero_imp_acumul,
       doc_mov_participacao, doc_qtd_depend_irrf,
       doc_data_criacao, doc_data_geracao_participacao,
       doc_interface_ps_mes, doc_interface_ps_ano,
       doc_interface_ps_seq, doc_data_inss_autonomo,
       data_processo_encerrado, doc_ri_cod_receita,
       doc_ri_dat_inicio, doc_tipo_servico, doc_tdc_seq_cobranca,
       doc_val_tax_adm, doc_val_tax_iss,
       doc_tot_glosado_excedente, doc_dat_venc_doc_fiscal,
       doc_valor, doc_deducao, doc_tot_faturamento,
       doc_tot_glosa, doc_tot_irrf, doc_tot_iss,
       doc_valor_liquido, doc_valor_participacao,
       doc_valor_diferenca, doc_valor_autorizado, doc_valor_taxa,
       doc_capital_seguro, doc_valor_inss, doc_vl_base_inss,
       doc_valor_ajuste, doc_inss_autonomo, doc_valor_irmp153,
       doc_valor_csll, doc_valor_pispasep, doc_valor_cofins)
SELECT	TRIM (a.doc_numero), TRIM (a.doc_cbe_ben_sigla),
			TRIM (a.doc_cbe_cre_sequencial), to_date(TRIM (a.doc_data), 'DD/MM/YYYY'),
			to_date(TRIM (a.doc_data_pagamento), 'DD/MM/YYYY'), TRIM (a.doc_tipo),
			TRIM (a.doc_especificacao), TRIM (a.doc_modalidade),
			TRIM (a.doc_emb_emp_numero_matricula), TRIM (a.doc_pvi_sequencial),
			TRIM (a.doc_cct_codigo), TRIM (a.doc_dep_codigo),
			TRIM (a.doc_emb_ben_sigla), TRIM (a.doc_especificacao_deducao),
			TRIM (a.doc_mes_pagamento), TRIM (a.doc_ano_pagamento),
			TRIM (a.doc_especificacao_diferenca), TRIM (a.doc_mes_vale),
			TRIM (a.doc_ano_vale), TRIM (a.doc_processo_encerrado),
			TRIM (a.doc_guias_emp), TRIM (a.doc_nr_doc_fiscal),
			TRIM (a.doc_pvi_emp_numero_matricula), TRIM (a.doc_dep_resp_incl),
			TRIM (a.doc_tipo_pedido), TRIM (a.doc_ind_imposto),
			TRIM (a.doc_numero_imp_acumul), TRIM (a.doc_mov_participacao),
			TRIM (a.doc_qtd_depend_irrf), to_date(TRIM (a.doc_data_criacao), 'DD/MM/YYYY'),
			to_date(TRIM (a.doc_data_geracao_participacao), 'DD/MM/YYYY'),
			TRIM (a.doc_interface_ps_mes), TRIM (a.doc_interface_ps_ano),
			TRIM (a.doc_interface_ps_seq), to_date(TRIM (a.doc_data_inss_autonomo), 'DD/MM/YYYY'),
			to_date(TRIM (a.data_processo_encerrado), 'DD/MM/YYYY'), TRIM (a.doc_ri_cod_receita),
			TRIM (a.doc_ri_dat_inicio), TRIM (a.doc_tipo_servico),
			TRIM (a.doc_tdc_seq_cobranca), TRIM (a.doc_val_tax_adm),
			TRIM (a.doc_val_tax_iss), TRIM (a.doc_tot_glosado_excedente),
			TRIM (a.doc_dat_venc_doc_fiscal), trunc (a.doc_valor,2),
			trunc (a.doc_deducao,2), trunc (a.doc_tot_faturamento,2),
			trunc (a.doc_tot_glosa,2), trunc (a.doc_tot_irrf,2), trunc (a.doc_tot_iss,2),
			trunc (a.doc_valor_liquido,2), trunc (a.doc_valor_participacao,2),
			trunc (a.doc_valor_diferenca,2), trunc (a.doc_valor_autorizado,2),
			trunc (a.doc_valor_taxa,2), trunc (a.doc_capital_seguro,2),
			trunc (a.doc_valor_inss,2), trunc (a.doc_vl_base_inss,2),
			trunc (a.doc_valor_ajuste,2), trunc (a.doc_inss_autonomo,2),
			trunc (a.doc_valor_irmp153,2), trunc (a.doc_valor_csll,2),
			trunc (a.doc_valor_pispasep,2), trunc (a.doc_valor_cofins,2)
  FROM	inss_122010 a
/* Formatted on 23-dez-2010 16:56:39 (QP5 v5.120.811.25008) */
