SELECT      A.EMP_NOME
,           (SELECT DEP_SIGLA FROM DEPENDENCIAS WHERE DEP_CODIGO = A.emp_dep_codigo_fisico) DEPENDENCIA
,           (SELECT UOR_SIGLA FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = A.EMP_UOR_CODIGO_FISICO) UOR
,           CARGOS_CONFIANCA.FUN_NOME AS EMP_QFU_FUNCAO
,           A.EMP_DATA_ADMISSAO
FROM        CADASTROS A
,           CARGOS_CONFIANCA
WHERE       A.EMP_STATUS <> 2
AND         A.EMP_SFU_CODIGO = 2
--AND         A.EMP_UOR_CODIGO_FISICO IN (SELECT UOR_CODIGO FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_SIGLA NOT LIKE '%NA%')
AND         CARGOS_CONFIANCA.FUN_CODIGO (+)= A.EMP_QFU_FUN_CODIGO
ORDER BY 5 desc, 2, 3, 1
/

SELECT      A.EMP_NOME
,           (SELECT DEP_SIGLA FROM DEPENDENCIAS WHERE DEP_CODIGO = A.emp_dep_codigo_fisico) DEPENDENCIA
,           (SELECT UOR_SIGLA FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_CODIGO = A.EMP_UOR_CODIGO_FISICO) UOR
,           CARGOS_CONFIANCA.FUN_NOME AS EMP_QFU_FUNCAO
,           (SELECT DISTINCT oem_data_inclusao FROM OCORRENCIAS_EMPREGADOS WHERE oem_data_inclusao  >= TO_DATE('01/02/2011','DD/MM/YYYY') AND oem_ofu_codigo = 264 AND oem_emp_numero_matricula = a.EMP_NUMERO_MATRICULA) AS DATA_DEMISSAO
FROM        CADASTROS A
,           CARGOS_CONFIANCA
WHERE       A.EMP_UOR_CODIGO_FISICO IN (SELECT UOR_CODIGO FROM UNIDADES_ORGANIZACIONAIS WHERE UOR_SIGLA NOT LIKE '%NA%')
AND         CARGOS_CONFIANCA.FUN_CODIGO (+)= A.EMP_QFU_FUN_CODIGO
AND         emp_numero_matricula iN (
            SELECT  emp_numero_matricula
            FROM CADASTROS
            WHERE EMP_NUMERO_MATRICULA IN (
                SELECT   DISTINCT oem_emp_numero_matricula
                FROM    OCORRENCIAS_EMPREGADOS
                WHERE   oem_data_inclusao  >= TO_DATE('01/02/2011','DD/MM/YYYY')
                AND     oem_ofu_codigo = 264
            )
            AND EMP_SFU_CODIGO = 2)
ORDER BY 5 desc,2, 3, 1
/
