SELECT	SIGLA_IATA_CIA_AEREA AS CIA_AEREA
	 ,	YEAR(DATA_HORA_EFETIVA_POUSO) AS ANO
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO) AS MES
	 ,	SUM(DESEMB_PASSAGEIRO_DOM + DESEMB_PASSAGEIRO_INT + TRANSITO_CONEXAO_DOM + TRANSITO_CONEXAO_INT) AS TOTAL_PAX_DESEMB
  FROM	BIOGER.dbo.BIOGER_RPE_DES D
 WHERE	DATA_HORA_EFETIVA_POUSO  > '20091001'
   AND  SIGLA_IATA_CIA_AEREA IN ('GLO', 'TAM')
 GROUP
    BY	SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_POUSO)
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO)
 ORDER
    BY  SIGLA_IATA_CIA_AEREA
     ,  YEAR(DATA_HORA_EFETIVA_POUSO)
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO)
	 
	 

SELECT	SIGLA_IATA_CIA_AEREA AS CIA_AEREA
	 ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM) AS ANO
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM) AS MES
	 ,	SUM(EMB_ISENTA_COLO + EMB_ISENTA_CONEXAO_DOM + EMB_ISENTA_CONEXAO_INT + EMB_ISENTA_OUTRAS + EMB_ISENTA_TRANSITO + EMB_TARIFA_PAGA_BILHETE_DOM + EMB_TARIFA_PAGA_BILHETE_INT + EMB_TARIFA_PAGA_CHECKIN_DOM + EMB_TARIFA_PAGA_CHECKIN_INT) AS TOTAL_PAX_EMB
  FROM	BIOGER.dbo.BIOGER_RPE_EMB D
 WHERE	DATA_HORA_EFETIVA_DECOLAGEM  > '20091001'
   AND  SIGLA_IATA_CIA_AEREA IN ('GLO', 'TAM')
 GROUP
    BY	SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM)
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM)
 ORDER
    BY  SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM)
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM)
	 
	 
	 

SELECT	SIGLA_IATA_CIA_AEREA AS CIA_AEREA
	 ,	YEAR(DATA_HORA_EFETIVA_POUSO) AS ANO
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO) AS MES
	 ,	SUM(DESEMB_PASSAGEIRO_DOM + DESEMB_PASSAGEIRO_INT + TRANSITO_CONEXAO_DOM + TRANSITO_CONEXAO_INT) AS TOTAL_PAX_DESEMB
  FROM	BIOGER.dbo.BIOGER_RPE_DES D
 WHERE	DATA_HORA_EFETIVA_POUSO  > '20081001'
   AND	DATA_HORA_EFETIVA_POUSO  < '20090101'
   AND  SIGLA_IATA_CIA_AEREA IN ('GLO', 'TAM')
   AND  SIGLA_AEROPORTO  NOT IN ('SBCT','SBTT')
 GROUP
    BY	SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_POUSO)
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO)
 ORDER
    BY  SIGLA_IATA_CIA_AEREA
     ,  YEAR(DATA_HORA_EFETIVA_POUSO)
	 ,	MONTH(DATA_HORA_EFETIVA_POUSO)
	 
	 

SELECT	SIGLA_IATA_CIA_AEREA AS CIA_AEREA
	 ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM) AS ANO
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM) AS MES
	 ,	SUM(EMB_ISENTA_COLO + EMB_ISENTA_CONEXAO_DOM + EMB_ISENTA_CONEXAO_INT + EMB_ISENTA_OUTRAS + EMB_ISENTA_TRANSITO + EMB_TARIFA_PAGA_BILHETE_DOM + EMB_TARIFA_PAGA_BILHETE_INT + EMB_TARIFA_PAGA_CHECKIN_DOM + EMB_TARIFA_PAGA_CHECKIN_INT) AS TOTAL_PAX_EMB
  FROM	BIOGER.dbo.BIOGER_RPE_EMB D
 WHERE	DATA_HORA_EFETIVA_DECOLAGEM  > '20081001'
   AND	DATA_HORA_EFETIVA_DECOLAGEM  < '20090101'
   AND  SIGLA_IATA_CIA_AEREA IN ('GLO', 'TAM')
   AND  SIGLA_AEROPORTO  NOT IN ('SBCT','SBTT')
 GROUP
    BY	SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM)
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM)
 ORDER
    BY  SIGLA_IATA_CIA_AEREA
     ,	YEAR(DATA_HORA_EFETIVA_DECOLAGEM)
	 ,	MONTH(DATA_HORA_EFETIVA_DECOLAGEM)
	 