DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_ACR_RET_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_ACR_RET_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(3, 0) NOT NULL,
    SEQ_RED_ACRES varchar2(4) NOT NULL,
    CODIGO_RED_ACRES varchar2(4) NOT NULL,
    TRANS_AMT number(12, 2) NOT NULL,
    DESCP varchar2(40) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    VAL_BRT number(12, 2) NOT NULL,
    PER_RET_ACRE number(6, 3) NOT NULL,
    LDR_ENTITY_ID varchar2(5) NOT NULL,
    DEPENDENCIA varchar2(3) NOT NULL,
    CONTA varchar2(9) NOT NULL,
    PROGRAMA varchar2(2) NOT NULL,
    PROJETO varchar2(4) NOT NULL,
    CUSTO varchar2(6) NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    CHGSTAMP number(3, 0) NOT NULL,
    STATUS varchar2(1) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_ACR_RET_U TO USR_CORP_SQLSERVER
/

DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_HEAD_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_HEAD_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(3, 0) NOT NULL,
    TIPO_SP varchar2(1) NOT NULL,
    VENDOR_ID_ORIGEM varchar2(10) NOT NULL,
    VENDOR_LOC_CODE_ORIGEM varchar2(3) NOT NULL,
    PMT_RQST_NBR_ORIGEM varchar2(22) NOT NULL,
    PMT_RQST_DATE_ORIGEM date NOT NULL,
    SCHLD_PMT_NBR_ORIGEM number(3, 0) NOT NULL,
    PRIM_AMT number(12, 2) NOT NULL,
    SECDY_AMT number(12, 2) NOT NULL,
    ENCARGOS_ATRASO varchar2(1) NOT NULL,
    SP_STATUS_CODE varchar2(2) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    TYPE_OF_PMT varchar2(4) NOT NULL,
    SEQ_NBR varchar2(3) NOT NULL,
    PMT_METH_ID varchar2(5) NOT NULL,
    FINAL_DUE_DATE date NOT NULL,
    TERMS_OF_PMT_ID varchar2(17) NOT NULL,
    PAYABLE_ENTITY_ID_OPER varchar2(5) NOT NULL,
    CHGSTAMP number(3, 0) NOT NULL,
    STATUS varchar2(1) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_HEAD_U TO USR_CORP_SQLSERVER
/

DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_OUTROS_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_OUTROS_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(3, 0) NOT NULL,
    DESC_GLOSA varchar2(93) NOT NULL,
    DESC_APLICACAO varchar2(141) NOT NULL,
    USER_FLD_1 varchar2(20) NOT NULL,
    USER_FLD_2 varchar2(15) NOT NULL,
    USER_FLD_3 varchar2(15) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    CHGSTAMP number(3, 0) NOT NULL,
    STATUS varchar2(1) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_OUTROS_U TO USR_CORP_SQLSERVER
/

DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_RATEIO_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_RATEIO_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(3, 0) NOT NULL,
    SEQ_ITEM varchar2(4) NOT NULL,
    CODIGO_RESUMO_VALOR varchar2(3) NOT NULL,
    TIPO_CRONOGRAMA varchar2(1) NOT NULL,
    NUMERO_PARCELA varchar2(4) NOT NULL,
    JRNL_LINE_NBR_varchar2 varchar2(10) NOT NULL,
    LDR_ENTITY_ID varchar2(5) NOT NULL,
    DEPENDENCIA varchar2(3) NOT NULL,
    CONTA varchar2(9) NOT NULL,
    PROGRAMA varchar2(2) NOT NULL,
    PROJETO varchar2(4) NOT NULL,
    CUSTO varchar2(6) NOT NULL,
    PER_RATEIO number(19, 4) NOT NULL,
    PRIM_AMT number(12, 2) NOT NULL,
    SECDY_AMT number(12, 2) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    CHGSTAMP number(3, 0) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_RATEIO_U TO USR_CORP_SQLSERVER
/

DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_RA_RATEIO_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_RA_RATEIO_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(5, 0) NOT NULL,
    SEQ_RED_ACRES varchar2(4) NOT NULL,
    JRNL_LINE_NBR_CHAR varchar2(10) NOT NULL,
    LDR_ENTITY_ID varchar2(5) NOT NULL,
    DEPENDENCIA varchar2(3) NOT NULL,
    CONTA varchar2(9) NOT NULL,
    PROGRAMA varchar2(2) NOT NULL,
    PROJETO varchar2(4) NOT NULL,
    CUSTO varchar2(6) NOT NULL,
    PER_RATEIO number(19, 4) NOT NULL,
    PRIM_AMT number(19, 4) NOT NULL,
    SECDY_AMT number(19, 4) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    CHGSTAMP number(5, 0) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_RA_RATEIO_U TO USR_CORP_SQLSERVER
/

DROP TABLE IFRCORP.TEMP_CONF_SOL_PAG_VAL_U PURGE
/

CREATE TABLE IFRCORP.TEMP_CONF_SOL_PAG_VAL_U(
    PAYABLE_ENTITY_ID varchar2(5) NOT NULL,
    CONTRACT_ID varchar2(30) NOT NULL,
    CONTRACT_VERSAO varchar2(2) NOT NULL,
    VENDOR_ID varchar2(10) NOT NULL,
    VENDOR_LOC_CODE varchar2(3) NOT NULL,
    PMT_RQST_NBR varchar2(22) NOT NULL,
    PMT_RQST_DATE date NOT NULL,
    SCHLD_PMT_NBR number(3, 0) NOT NULL,
    SEQ_ITEM varchar2(4) NOT NULL,
    CODIGO_RESUMO_VALOR varchar2(3) NOT NULL,
    TIPO_CRONOGRAMA varchar2(1) NOT NULL,
    NUMERO_PARCELA varchar2(4) NOT NULL,
    PRIM_AMT number(12, 2) NOT NULL,
    SECDY_AMT number(12, 2) NOT NULL,
    SISTEMA_ORIGEM_CODE varchar2(2) NOT NULL,
    CONTRACT_VERSAO_ORIGEM varchar2(2) NOT NULL,
    DATA_VENCTO date NOT NULL,
    DATE_CREATED date NOT NULL,
    USER_ID_CREATED varchar2(30) NOT NULL,
    DATE_CHANGED date NOT NULL,
    USER_ID_CHANGED varchar2(30) NOT NULL,
    INACTIVE_IND varchar2(1) NOT NULL,
    ACTIVE_DATE date NOT NULL,
    CHGSTAMP number(3, 0) NOT NULL,
    STATUS varchar2(1) NOT NULL,
    MIGRATION_DATE date NULL
) 
/

GRANT SELECT, UPDATE(MIGRATION_DATE) ON ifrcorp.TEMP_CONF_SOL_PAG_VAL_U TO USR_CORP_SQLSERVER
/


CREATE TABLE ifrcorp.gvw_consulta_fornecedor
    (vendor_id                     VARCHAR2(10) NOT NULL,
    vendor_loc_code                VARCHAR2(3) NOT NULL,
    tipo_pessoa                    VARCHAR2(3) NOT NULL,
    cnpj_cpf                       VARCHAR2(25) NOT NULL,
    nome_fornecedor                VARCHAR2(45) NOT NULL,
    sequencia                      VARCHAR2(3) NOT NULL,
    banco                          VARCHAR2(17) NOT NULL,
    nome_banco                     VARCHAR2(70) NOT NULL,
    agencia                        VARCHAR2(70) NOT NULL,
    conta                          VARCHAR2(17) NOT NULL,
    endereco_1                     VARCHAR2(35) NOT NULL,
    endereco_2                     VARCHAR2(35) NOT NULL,
    cidade                         VARCHAR2(35) NOT NULL,
    estado                         VARCHAR2(9) NOT NULL,
    cep                            VARCHAR2(9) NOT NULL,
    pais                           VARCHAR2(2) NOT NULL,
    status                         VARCHAR2(1) NOT NULL)
 /
 
GRANT SELECT, INSERT, DELETE ON ifrcorp.gvw_consulta_fornecedor TO USR_CORP_SQLSERVER
/


--***********************************************************************************
GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_ACR_RET_U TO IFRBENNER
/

GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_HEAD_U TO IFRBENNER
/

GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_OUTROS_U TO IFRBENNER
/

GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_RATEIO_U TO IFRBENNER
/

GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_RA_RATEIO_U TO IFRBENNER
/

GRANT SELECT, INSERT ON ifrcorp.TEMP_CONF_SOL_PAG_VAL_U TO IFRBENNER
/
 
GRANT SELECT ON ifrcorp.gvw_consulta_fornecedor TO IFRBENNER
/

--***********************************************************************************
--EXECUTAR COMO IFRBENNER
--

CREATE SYNONYM TEMP_CONF_SOL_PAG_ACR_RET_U FOR ifrcorp.TEMP_CONF_SOL_PAG_ACR_RET_U
/

CREATE SYNONYM TEMP_CONF_SOL_PAG_HEAD_U FOR ifrcorp.TEMP_CONF_SOL_PAG_HEAD_U
/

CREATE SYNONYM TEMP_CONF_SOL_PAG_OUTROS_U FOR ifrcorp.TEMP_CONF_SOL_PAG_OUTROS_U
/

CREATE SYNONYM TEMP_CONF_SOL_PAG_RATEIO_U FOR  ifrcorp.TEMP_CONF_SOL_PAG_RATEIO_U
/

CREATE SYNONYM TEMP_CONF_SOL_PAG_RA_RATEIO_U FOR  ifrcorp.TEMP_CONF_SOL_PAG_RA_RATEIO_U
/

CREATE SYNONYM TEMP_CONF_SOL_PAG_VAL_U FOR  ifrcorp.TEMP_CONF_SOL_PAG_VAL_U
/
 
CREATE SYNONYM gvw_consulta_fornecedor FOR  ifrcorp.gvw_consulta_fornecedor
/





