--*******************************************************************
-->>>>>>> DELETAR OS REGISTROS CONSTANTES DAS 3 CONSULTAS ABAIXO
--*******************************************************************
SELECT * 
FROM CONTROLE_USUARIO_DEPENDENCIA
  INNER JOIN CADASTROS ON 'I' || TO_CHAR(CADASTROS.EMP_NUMERO_MATRICULA) = CONTROLE_USUARIO_DEPENDENCIA.SGU_ID_USUARIO
WHERE CADASTROS.EMP_UOR_CODIGO_LOTACAO = 9219
  AND CONTROLE_USUARIO_DEPENDENCIA.SSI_CD_SISTEMA <> 13
  AND EMP_STATUS <> 2

SELECT * 
FROM SEG_USUARIO_CENTRO_CUSTO
  INNER JOIN CADASTROS ON 'I' || TO_CHAR(CADASTROS.EMP_NUMERO_MATRICULA) = SEG_USUARIO_CENTRO_CUSTO.SU_ID_USUARIO
WHERE CADASTROS.EMP_UOR_CODIGO_LOTACAO = 9219
  AND SEG_USUARIO_CENTRO_CUSTO.SS_CD_SISTEMA <> 13
  AND EMP_STATUS <> 2
  
SELECT *
FROM SEG_USUARIO_SISTEMA
  INNER JOIN CADASTROS ON 'I' || TO_CHAR(CADASTROS.EMP_NUMERO_MATRICULA) = SEG_USUARIO_SISTEMA.SU_ID_USUARIO
WHERE CADASTROS.EMP_UOR_CODIGO_LOTACAO = 9219
  AND SEG_USUARIO_SISTEMA.SS_CD_SISTEMA <> 13
  AND EMP_STATUS <> 2

--*******************************************************************
-->>>>>>> ATRIBUIR AS ROLES NO BANCO INDICADA PELA CONSULTA ABAIXO
--*******************************************************************
SELECT DISTINCT USUARIO.SU_ID_USUARIO, CADASTROS.EMP_NOME, GRUPO.ROLE, 'GRANT ' || GRUPO.ROLE || ' TO ' || USUARIO.SU_ID_USUARIO || ';'
FROM SEG_GRUPO_USUARIO GRUPO
  INNER JOIN SEG_USUARIO_SISTEMA USUARIO
    ON USUARIO.SGU_CD_GRUPO = GRUPO.CD_GRUPO
    AND USUARIO.SS_CD_SISTEMA = GRUPO.SS_CD_SISTEMA
  INNER JOIN CONTROLE_USUARIO_DEPENDENCIA CONTROLE
    ON CONTROLE.SGU_ID_USUARIO = USUARIO.SU_ID_USUARIO
    AND CONTROLE.SSI_CD_SISTEMA = USUARIO.SS_CD_SISTEMA
  INNER JOIN CADASTROS 
    ON 'I' || TO_CHAR(CADASTROS.EMP_NUMERO_MATRICULA) = USUARIO.SU_ID_USUARIO
  LEFT JOIN VIW_ROLES_USUARIOS BANCO
    ON BANCO.USUARIO = USUARIO.SU_ID_USUARIO
    AND BANCO.ROLE = GRUPO.ROLE
WHERE CADASTROS.EMP_STATUS <> 2    
  AND USUARIO.SS_CD_SISTEMA IN (27,32,31,3,5,8,7,10,11,12,13,18,22,23,28,29,30,34,36,33,35)
  AND BANCO.USUARIO IS NULL
ORDER BY 2, 3




