use IFRSIVNET

--PASSO INICIAL - DESABILITAR O AUTO IDENTITY
--alter trigger TRG_HST_VOO_OPERACAO_I disable

--SET IDENTITY_INSERT [HST_VOO_OPERACAO] ON

MERGE [IFRSIVNET].[dbo].[HST_VOO_OPERACAO] des
USING (
SELECT [SEQ_HST_VOO_OPERACAO]
      ,[NUM_VOO]
      ,[SEQ_AEROPORTO]
      ,[SEQ_CIA]
      ,[SEQ_AEROPORTO_ENVIA_ARQUIVO]
      ,[SEQ_NATUREZA]
      ,[SEQ_SENTIDO]
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[HST_VOO_OPERACAO]
  where SEQ_HST_VOO_OPERACAO in (
SELECT TOP 100000 [SEQ_HST_VOO_OPERACAO]
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[HST_VOO_OPERACAO_STATUS]
  where DAT_INSERCAO > dateadd(hh, -1, getdate())) ori
 ON des.SEQ_HST_VOO_OPERACAO = ori.SEQ_HST_VOO_OPERACAO
 WHEN NOT MATCHED THEN
INSERT values ([SEQ_HST_VOO_OPERACAO]
      ,[NUM_VOO]
      ,[SEQ_AEROPORTO]
      ,[SEQ_CIA]
      ,[SEQ_AEROPORTO_ENVIA_ARQUIVO]
      ,[SEQ_NATUREZA]
      ,[SEQ_SENTIDO]);


MERGE [IFRSIVNET].[dbo].[TAB_EQUIPAMENTO] des
USING (
SELECT [SEQ_EQUIPAMENTO]
      ,[NOM_EQUIPAMENTO]
      ,[COD_EQUIPAMENTO]
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[TAB_EQUIPAMENTO]) ori
 ON des.[SEQ_EQUIPAMENTO] = ori.[SEQ_EQUIPAMENTO]
 WHEN NOT MATCHED THEN
INSERT values ([SEQ_EQUIPAMENTO]
      ,[NOM_EQUIPAMENTO]
      ,[COD_EQUIPAMENTO]);

SELECT  MAX([SEQ_HST_VOO_OPERACAO]) VOO_OPERACAO_146
FROM	[S-SEBN146\PROD].[IFRSIVNET].[dbo].[HST_VOO_OPERACAO]

SELECT  MAX([SEQ_HST_VOO_OPERACAO]) VOO_OPERACAO_177
FROM	[IFRSIVNET].[dbo].[HST_VOO_OPERACAO]

SELECT  COUNT(1) VOO_OPERACAO_STATUS_146
FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[HST_VOO_OPERACAO_STATUS] SEDE
  where SEDE.DAT_INSERCAO > dateadd(hh, -1, getdate())
  
SELECT COUNT(1) VOO_OPERACAO_STATUS_177
FROM [IFRSIVNET].[dbo].[HST_VOO_OPERACAO_STATUS] SEDE
  where SEDE.DAT_INSERCAO > dateadd(hh, -1, getdate())
  
SELECT COUNT(1)
FROM  [S-SEBN146\PROD].[IFRSIVNET].[dbo].[TAB_VOO_OPERACAO]

SELECT COUNT(1)
 FROM [IFRSIVNET].[dbo].[TAB_VOO_OPERACAO]


MERGE [IFRSIVNET].[dbo].[HST_VOO_OPERACAO_STATUS] des
USING (SELECT TOP 100000 SEDE.[SEQ_HST_VOO_OPERACAO]
      ,SEDE.[DAT_INSERCAO]
      ,SEDE.[DAT_PREV]
      ,SEDE.[DAT_CONF]
      ,SEDE.[SEQ_STATUS]
      ,SEDE.[TXT_OBS]
      ,SEDE.[TIP_VOO_OPERACAO]
      ,SEDE.[DSC_HORARIO_SAIDA_CALCO]
      ,SEDE.[DSC_HORARIO_POUSO_DECOLAGEM]
      ,SEDE.[TIP_CATEGORIA_VOO]
      ,SEDE.[SEQ_EQUIPAMENTO]
      ,SEDE.[NUM_TPS]
      ,SEDE.[NUM_CHECKIN]
      ,SEDE.[NUM_GATE]
      ,SEDE.[NUM_BOX]
      ,SEDE.[DAT_CANCELAMENTO]
      ,SEDE.[NUM_MATRICULA] 
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[HST_VOO_OPERACAO_STATUS] SEDE
  where SEDE.DAT_INSERCAO > dateadd(hh, -1, getdate())) ori
ON des.SEQ_HST_VOO_OPERACAO = ori.SEQ_HST_VOO_OPERACAO
    AND des.[DAT_INSERCAO] = ori.[DAT_INSERCAO]
WHEN NOT MATCHED THEN
INSERT values ([SEQ_HST_VOO_OPERACAO]
      ,[DAT_INSERCAO]
      ,[DAT_PREV]
      ,[DAT_CONF]
      ,[SEQ_STATUS]
      ,[TXT_OBS]
      ,[TIP_VOO_OPERACAO]
      ,[DSC_HORARIO_SAIDA_CALCO]
      ,[DSC_HORARIO_POUSO_DECOLAGEM]
      ,[TIP_CATEGORIA_VOO]
      ,[SEQ_EQUIPAMENTO]
      ,[NUM_TPS]
      ,[NUM_CHECKIN]
      ,[NUM_GATE]
      ,[NUM_BOX]
      ,[DAT_CANCELAMENTO]
      ,[NUM_MATRICULA]);
     

MERGE [IFRSIVNET].[dbo].[TAB_CONTROLE_CARGA] des
USING (SELECT TOP 100000 [SEQ_AEROPORTO]
      ,[DAT_CARGA]
      ,[TXT_OBS]
      ,[QTD_REG_MIGRADO]
      ,[DAT_GERACAO_XML]
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[TAB_CONTROLE_CARGA]) ori
ON des.[SEQ_AEROPORTO] = ori.[SEQ_AEROPORTO]
WHEN NOT MATCHED THEN
INSERT values ([SEQ_AEROPORTO]
      ,[DAT_CARGA]
      ,[TXT_OBS]
      ,[QTD_REG_MIGRADO]
      ,[DAT_GERACAO_XML]);
      
      
MERGE [IFRSIVNET].[dbo].[TAB_CONTROLE_ERRO] des
USING (SELECT TOP 100000 [SEQ_ERRO]
      ,[SEQ_AEROPORTO]
      ,[DSC_ERRO]
      ,[NUM_VOO]
      ,[TIP_ERRO]
      ,[SIG_STATUS]
      ,[SIG_SENTIDO]
      ,[DSC_STATUS]
  FROM [IFRSIVNET].[dbo].[TAB_CONTROLE_ERRO]) ori
ON des.[SEQ_ERRO] = ori.[SEQ_ERRO]
WHEN NOT MATCHED THEN
INSERT values ([SEQ_ERRO]
      ,[SEQ_AEROPORTO]
      ,[DSC_ERRO]
      ,[NUM_VOO]
      ,[TIP_ERRO]
      ,[SIG_STATUS]
      ,[SIG_SENTIDO]
      ,[DSC_STATUS]);
     


--PASSO FINAL - DESABILITAR O AUTO IDENTITY
--alter trigger TRG_HST_VOO_OPERACAO_I disable
--DBCC checkident([HST_VOO_OPERACAO])
--DBCC checkident([HST_VOO_OPERACAO], reseed, 175046)
--alter trigger TRG_HST_VOO_OPERACAO_I enable


/*
MERGE [IFRSIVNET].[dbo].[TAB_VOO_OPERACAO] des
USING (SELECT TOP 100000 [SEQ_VOO_OPERACAO]
      ,[SEQ_STATUS]
      ,[SEQ_CIA]
      ,[SEQ_NATUREZA]
      ,[SEQ_SENTIDO]
      ,[SEQ_AEROPORTO]
      ,[SEQ_EQUIPAMENTO]
      ,[DAT_VOO]
      ,[NUM_VOO]
      ,[HOR_PREV]
      ,[HOR_CONF]
      ,[NUM_TPS]
      ,[NUM_CHECKIN]
      ,[NUM_GATE]
      ,[NUM_BOX]
      ,[TXT_OBS]
      ,[SEQ_AEROPORTO_ENVIA_ARQUIVO]
      ,[TIP_VOO_OPERACAO]
      ,[DSC_HORARIO_SAIDA_CALCO]
      ,[DSC_HORARIO_POUSO_DECOLAGEM]
      ,[TIP_CATEGORIA_VOO]
  FROM [S-SEBN146\PROD].[IFRSIVNET].[dbo].[TAB_VOO_OPERACAO]) ori
ON des.SEQ_VOO_OPERACAO = ori.SEQ_VOO_OPERACAO
WHEN NOT MATCHED THEN
INSERT values ([SEQ_VOO_OPERACAO]
      ,[SEQ_STATUS]
      ,[SEQ_CIA]
      ,[SEQ_NATUREZA]
      ,[SEQ_SENTIDO]
      ,[SEQ_AEROPORTO]
      ,[SEQ_EQUIPAMENTO]
      ,[DAT_VOO]
      ,[NUM_VOO]
      ,[HOR_PREV]
      ,[HOR_CONF]
      ,[NUM_TPS]
      ,[NUM_CHECKIN]
      ,[NUM_GATE]
      ,[NUM_BOX]
      ,[TXT_OBS]
      ,[SEQ_AEROPORTO_ENVIA_ARQUIVO]
      ,[TIP_VOO_OPERACAO]
      ,[DSC_HORARIO_SAIDA_CALCO]
      ,[DSC_HORARIO_POUSO_DECOLAGEM]
      ,[TIP_CATEGORIA_VOO]);
      
*/