ALTER USER USR_TREINAMENTO_SAT ACCOUNT LOCK;

SELECT * FROM DBA_USERS WHERE USERNAME = 'USR_TREINAMENTO_SAT'

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'USR_TREINAMENTO_SAT'

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'USR_TREINAMENTO_SAT'

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ROL_SAT_ADMIN'

SELECT * FROM DBA_ROLES WHERE ROLE = 'ROL_SAT_ADMIN'


GRANT SELECT ON IFRCORP.TAB_COLABORADOR TO ROL_SAT_ADMIN;
GRANT SELECT ON IFRCORP.VIW_COLABORADOR TO ROL_SAT_ADMIN;
GRANT SELECT ON VIW_COLABORADOR_SISEG TO ROL_SAT_ADMIN;

REVOKE SELECT ON IFRCORP.TAB_COLABORADOR FROM USR_TREINAMENTO_SAT;
REVOKE SELECT ON IFRCORP.VIW_COLABORADOR FROM USR_TREINAMENTO_SAT;
REVOKE SELECT ON VIW_COLABORADOR_SISEG FROM USR_TREINAMENTO_SAT;
