USE [bdo]
GO

CREATE TABLE [dbo].[P_T_HES](
	[DH_HES_CHG_ALO] [datetime] NULL,
	[CD_CHG] [int] NOT NULL,
	[CD_EST] [int] NULL,
	[DH_HES] [smalldatetime] NULL,
	[CD_USR] [int] NULL,
	[NM_HES_USR] [varchar](30) NULL,
	[DH_HES_CHG_DES] [datetime] NULL,
	[CD_AER] [int] NULL,
	[ADB_SUBJECT] [varchar](255) NULL,
	[ADB_SEQUENCE] [int] IDENTITY(1,1) NOT NULL,
	[ADB_SET_SEQUENCE] [int] NULL,
	[ADB_TIMESTAMP] [datetime] NULL,
	[ADB_OPCODE] [int] NOT NULL,
	[ADB_UPDATE_ALL] [int] NULL,
	[ADB_REF_OBJECT] [varchar](64) NULL,
	[ADB_L_DELIVERY_STATUS] [char](1) NULL,
	[ADB_L_CMSEQUENCE] [decimal](28, 0) NULL,
	[ADB_TRACKINGID] [varchar](40) NULL,
	[IDB_STATUS] [char](1) NULL
) ON [PRIMARY]

GO

GRANT SELECT, UPDATE, DELETE, INSERT ON [P_T_HES] TO siso_carga;

CREATE TRIGGER [dbo].[TR1_P_T_HES] ON [dbo].[T_HES]
FOR INSERT AS BEGIN
SET NOCOUNT ON
INSERT INTO dbo.P_T_HES(
	 DH_HES_CHG_ALO
    ,CD_CHG
    ,CD_EST
    ,DH_HES
    ,CD_USR
    ,NM_HES_USR
    ,DH_HES_CHG_DES
    ,CD_AER
	,ADB_SUBJECT
	,ADB_TIMESTAMP
	,ADB_OPCODE
	,ADB_REF_OBJECT
	,ADB_L_DELIVERY_STATUS)
	SELECT DH_HES_CHG_ALO,CD_CHG,CD_EST,DH_HES,CD_USR,NM_HES_USR,DH_HES_CHG_DES,CD_AER, NULL, getdate(), 1, NULL, 'N'
	FROM inserted
END

GO

CREATE TRIGGER [dbo].[TR2_P_T_HES] ON [dbo].[T_HES]
FOR UPDATE AS BEGIN
SET NOCOUNT ON
BEGIN
DECLARE @CD_EST_OLD INT
      , @CD_EST_NEW INT
      , @DH_HES_OLD DATETIME
      , @DH_HES_NEW DATETIME


SELECT	@CD_EST_OLD = deleted.CD_EST
      , @DH_HES_OLD = deleted.DH_HES
   FROM deleted
      
SELECT	@CD_EST_NEW = inserted.CD_EST
      , @DH_HES_NEW = inserted.DH_HES
  FROM inserted

IF ((@CD_EST_OLD <> @CD_EST_NEW) OR (@DH_HES_OLD <> @DH_HES_NEW)) BEGIN
	INSERT INTO dbo.P_T_HES(
	 DH_HES_CHG_ALO
    ,CD_CHG
    ,CD_EST
    ,DH_HES
    ,CD_USR
    ,NM_HES_USR
    ,DH_HES_CHG_DES
    ,CD_AER
	,ADB_SUBJECT
	,ADB_TIMESTAMP
	,ADB_OPCODE
	,ADB_REF_OBJECT
	,ADB_L_DELIVERY_STATUS)
	SELECT DH_HES_CHG_ALO,CD_CHG,CD_EST,DH_HES,CD_USR,NM_HES_USR,DH_HES_CHG_DES,CD_AER, NULL, getdate(), 2, NULL, 'N'
	FROM inserted
END
END
END




GO

GRANT SELECT ON T_SAL TO SISO_CARGA
