use stms

CREATE TABLE [dbo].[P_Strips_Torre] (
	[RowId] [varchar] (36) NULL ,
	[RowId_Strip] [varchar] (36) NULL ,
	[IdRow] [nvarchar] (255) NULL ,
	[DataHora] [datetime] NULL ,
	[TabOrigem] [varchar] (1) NULL ,
	[PosicaoOperacional] [char] (1) NULL ,
	[Indicativo] [varchar] (7) NULL ,
	[Matricula] [varchar] (7) NULL ,
	[Status] [smallint] NULL ,
	[Ordem] [smallint] NULL ,
	[Origem] [varchar] (4) NULL ,
	[Destino] [varchar] (4) NULL ,
	[HorarioPrevisto] [varchar] (4) NULL ,
	[DataPrevista] [datetime] NULL ,
	[DataHoraPrevista] [datetime] NULL ,
	[DataHoraPrevLocal] [datetime] NULL ,
	[HorarioReal] [varchar] (4) NULL ,
	[DataReal] [datetime] NULL ,
	[DataHoraReal] [datetime] NULL ,
	[DataHoraLocal] [datetime] NULL ,
	[DataLocal] [datetime] NULL ,
	[Tipo] [varchar] (4) NULL ,
	[Categoria] [varchar] (1) NULL ,
	[Transponder] [varchar] (4) NULL ,
	[Classe] [varchar] (2) NULL ,
	[Fonte] [varchar] (3) NULL ,
	[Pob] [smallint] NULL ,
	[Alternativa] [varchar] (4) NULL ,
	[Alternativa2] [varchar] (4) NULL ,
	[Autonomia] [varchar] (4) NULL ,
	[Rota] [varchar] (30) NULL ,
	[Nivel] [varchar] (4) NULL ,
	[Velocidade] [varchar] (5) NULL ,
	[Rwy] [varchar] (5) NULL ,
	[PreRwy] [varchar] (5) NULL ,
	[Rv] [varchar] (2) NULL ,
	[Pre_Rv] [varchar] (1) NULL ,
	[Tqa] [smallint] NULL ,
	[TqaLigado] [smallint] NULL ,
	[Qaf] [smallint] NULL ,
	[TipoQaf] [char] (1) NULL ,
	[Anexo] [varchar] (512) NULL ,
	[Estacionamento] [varchar] (10) NULL ,
	[Est_Ocupado] [smallint] NULL ,
	[TimerHora] [datetime] NULL ,
	[TimerExibir] [smallint] NULL ,
	[Rmk1] [varchar] (30) NULL ,
	[Rmk2] [varchar] (35) NULL ,
	[RmkApp] [varchar] (180) NULL ,
	[Setor] [varchar] (4) NULL ,
	[Condicao] [varchar] (3) NULL ,
	[Operador] [varchar] (4) NULL ,
	[Procedimento] [varchar] (4) NULL ,
	[Afis] [smallint] NULL ,
	[Envio_Insert] [datetime] NULL ,
	[Area] [varchar] (3) NULL ,
	[DHFixoEntrada] [datetime] NULL ,
	[FixoEntrada] [varchar] (5) NULL ,
	[DHFixoSaida] [datetime] NULL ,
	[FixoSaida] [varchar] (5) NULL ,
	[Equipamento1] [varchar] (25) NULL ,
	[Equipamento2] [varchar] (1) NULL ,
	[NumAeronaves] [smallint] NULL ,
	[EET] [varchar] (4) NULL ,
	[OutrosDados] [varchar] (150) NULL ,
	[ADB_SUBJECT] [varchar] (255) NULL ,
	[ADB_SEQUENCE] [int] IDENTITY (1, 1) NOT NULL ,
	[ADB_SET_SEQUENCE] [int] NULL ,
	[ADB_TIMESTAMP] [datetime] NULL ,
	[ADB_OPCODE] [int] NOT NULL ,
	[ADB_UPDATE_ALL] [int] NULL ,
	[ADB_REF_OBJECT] [varchar] (64) NULL ,
	[ADB_L_DELIVERY_STATUS] [char] (1) NULL ,
	[ADB_L_CMSEQUENCE] [decimal](28, 0) NULL ,
	[ADB_TRACKINGID] [varchar] (40) NULL ,
	[IDB_STATUS] [char] (1) NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[P_Strips_Torre] ADD  DEFAULT ('N') FOR [IDB_STATUS]
GO




CREATE TRIGGER [dbo].[TR1_P_Strips_Torre] ON [dbo].[Strips_Torre]
FOR INSERT AS BEGIN
SET NOCOUNT ON
INSERT INTO dbo.P_Strips_Torre(
	RowId,
	RowId_Strip,
	IdRow,
	DataHora,
	TabOrigem,
	PosicaoOperacional,
	Indicativo,
	Matricula,
	Status,
	Ordem,
	Origem,
	Destino,
	HorarioPrevisto,
	DataPrevista,
	DataHoraPrevista,
	DataHoraPrevLocal,
	HorarioReal,
	DataReal,
	DataHoraReal,
	DataHoraLocal,
	DataLocal,
	Tipo,
	Categoria,
	Transponder,
	Classe,
	Fonte,
	Pob,
	Alternativa,
	Alternativa2,
	Autonomia,
	Rota,
	Nivel,
	Velocidade,
	Rwy,
	PreRwy,
	Rv,
	Pre_Rv,
	Tqa,
	TqaLigado,
	Qaf,
	TipoQaf,
	Anexo,
	Estacionamento,
	Est_Ocupado,
	TimerHora,
	TimerExibir,
	Rmk1,
	Rmk2,
	RmkApp,
	Setor,
	Condicao,
	Operador,
	Procedimento,
	Afis,
	Envio_Insert,
	Area,
	DHFixoEntrada,
	FixoEntrada,
	DHFixoSaida,
	FixoSaida,
	Equipamento1,
	Equipamento2,
	NumAeronaves,
	EET,
	OutrosDados,
	ADB_SUBJECT,
	ADB_TIMESTAMP,
	ADB_OPCODE,
	ADB_REF_OBJECT,
	ADB_L_DELIVERY_STATUS)
	SELECT RowId, RowId_Strip, IdRow, DataHora, TabOrigem, PosicaoOperacional, Indicativo, Matricula, Status, Ordem, Origem, Destino, HorarioPrevisto, DataPrevista, DataHoraPrevista, DataHoraPrevLocal, HorarioReal, DataReal, DataHoraReal, DataHoraLocal, DataLocal, Tipo, Categoria, Transponder, Classe, Fonte, Pob, Alternativa, Alternativa2, Autonomia, Rota, Nivel, Velocidade, Rwy, PreRwy, Rv, Pre_Rv, Tqa, TqaLigado, Qaf, TipoQaf, Anexo, Estacionamento, Est_Ocupado, TimerHora, TimerExibir, Rmk1, Rmk2, RmkApp, Setor, Condicao, Operador, Procedimento, Afis, Envio_Insert, Area, DHFixoEntrada, FixoEntrada, DHFixoSaida, FixoSaida, Equipamento1, Equipamento2, NumAeronaves, EET, OutrosDados, NULL, getdate(), 1, NULL, 'N'
	FROM inserted
END


GO


CREATE TRIGGER [dbo].[TR2_P_Strips_Torre] ON [dbo].[Strips_Torre]
FOR UPDATE AS BEGIN
SET NOCOUNT ON
IF UPDATE(Status)
BEGIN
INSERT INTO dbo.P_Strips_Torre(
	RowId,
	RowId_Strip,
	IdRow,
	DataHora,
	TabOrigem,
	PosicaoOperacional,
	Indicativo,
	Matricula,
	Status,
	Ordem,
	Origem,
	Destino,
	HorarioPrevisto,
	DataPrevista,
	DataHoraPrevista,
	DataHoraPrevLocal,
	HorarioReal,
	DataReal,
	DataHoraReal,
	DataHoraLocal,
	DataLocal,
	Tipo,
	Categoria,
	Transponder,
	Classe,
	Fonte,
	Pob,
	Alternativa,
	Alternativa2,
	Autonomia,
	Rota,
	Nivel,
	Velocidade,
	Rwy,
	PreRwy,
	Rv,
	Pre_Rv,
	Tqa,
	TqaLigado,
	Qaf,
	TipoQaf,
	Anexo,
	Estacionamento,
	Est_Ocupado,
	TimerHora,
	TimerExibir,
	Rmk1,
	Rmk2,
	RmkApp,
	Setor,
	Condicao,
	Operador,
	Procedimento,
	Afis,
	Envio_Insert,
	Area,
	DHFixoEntrada,
	FixoEntrada,
	DHFixoSaida,
	FixoSaida,
	Equipamento1,
	Equipamento2,
	NumAeronaves,
	EET,
	OutrosDados,
	ADB_SUBJECT,
	ADB_TIMESTAMP,
	ADB_OPCODE,
	ADB_REF_OBJECT,
	ADB_L_DELIVERY_STATUS)
	SELECT RowId, RowId_Strip, IdRow, DataHora, TabOrigem, PosicaoOperacional, Indicativo, Matricula, Status, Ordem, Origem, Destino, HorarioPrevisto, DataPrevista, DataHoraPrevista, DataHoraPrevLocal, HorarioReal, DataReal, DataHoraReal, DataHoraLocal, DataLocal, Tipo, Categoria, Transponder, Classe, Fonte, Pob, Alternativa, Alternativa2, Autonomia, Rota, Nivel, Velocidade, Rwy, PreRwy, Rv, Pre_Rv, Tqa, TqaLigado, Qaf, TipoQaf, Anexo, Estacionamento, Est_Ocupado, TimerHora, TimerExibir, Rmk1, Rmk2, RmkApp, Setor, Condicao, Operador, Procedimento, Afis, Envio_Insert, Area, DHFixoEntrada, FixoEntrada, DHFixoSaida, FixoSaida, Equipamento1, Equipamento2, NumAeronaves, EET, OutrosDados, NULL, getdate(), 2, NULL, 'N'
	FROM inserted
	WHERE EXISTS
		(SELECT * 
		FROM deleted
		WHERE inserted.RowId = deleted.RowId AND inserted.TabOrigem = deleted.TabOrigem AND inserted.Indicativo = deleted.Indicativo)
END
END


