SELECT * FROM (
SELECT 
  SIG_ITEM_CONFIGURACAO AS SIGLA_SISTEMA,
  NOM_ITEM_CONFIGURACAO AS NOME_SISTEMA,
  C.NOM_CRITICIDADE AS CRITICIDADE,
  TD.NOM_TIPO_DISPONIBILIDADE AS DISPONIBILIDADE,
  NULL AS "PERÍODO DE CRITICIDADE",
  (SELECT UOR.UOR_SIGLA FROM UOR WHERE UOR.UOR_CODIGO = COD_UOR_AREA_GESTORA) AS UOR_GESTORA
FROM IFRGESTAO_TI.ITEM_CONFIGURACAO IC
   , IFRGESTAO_TI.CRITICIDADE C
   , IFRGESTAO_TI.TIPO_DISPONIBILIDADE TD
   , IFRGESTAO_TI.PRIORIDADE P
WHERE  IC.SEQ_CRITICIDADE = C.SEQ_CRITICIDADE
  AND  TD.SEQ_TIPO_DISPONIBILIDADE = IC.SEQ_TIPO_DISPONIBILIDADE
  AND  P.SEQ_PRIORIDADE = IC.SEQ_PRIORIDADE
  AND  SEQ_TIPO_ITEM_CONFIGURACAO = 2 --SISTEMAS
  ) SISTEMAS
  WHERE (UOR_GESTORA LIKE 'DC%' OR UOR_GESTORA LIKE 'DF%')
  ORDER BY UOR_GESTORA, NOME_SISTEMA;