SELECT	*
--DELETE
  FROM	CGA..ColetasCGA
 WHERE  DtaColeta > '20120703'
   and  SigAeroporto IN ('SBBR','SBSV','SBRF','SBCF', 'SBFZ','SBGL') --= 'SBGL' 

SELECT COUNT(1)
  FROM	dbo.P_T_CHG_SEDE_TMP
  --UPDATE dbo.P_T_CHG_SEDE_TMP SET ADB_L_DELIVERY_STATUS = 'N'
 WHERE  IDB_SIG_AEROPORTO IN ('SBBR','SBSV','SBRF','SBCF', 'SBFZ','SBGL')
   AND  ADB_TIMESTAMP >= '20120703'
  
SELECT COUNT(1)
  FROM	dbo.P_T_PAR_SEDE_TMP
  --UPDATE dbo.P_T_PAR_SEDE_TMP SET ADB_L_DELIVERY_STATUS = 'N'
 WHERE  IDB_SIG_AEROPORTO IN ('SBBR','SBSV','SBRF','SBCF', 'SBFZ','SBGL')
   AND  ADB_TIMESTAMP >= '20120703'
   
SELECT COUNT(1)
  FROM	dbo.P_T_STA_SEDE_TMP
    --UPDATE dbo.P_T_STA_SEDE_TMP SET ADB_L_DELIVERY_STATUS_PAR = 'N', ADB_L_DELIVERY_STATUS_CHG = 'N'
 WHERE  IDB_SIG_AEROPORTO IN ('SBBR','SBSV','SBRF','SBCF', 'SBFZ','SBGL')
   AND  ADB_TIMESTAMP >= '20120703'
   
SELECT COUNT(1)
  FROM	dbo.P_T_MOV_SEDE_TMP
    --UPDATE dbo.P_T_MOV_SEDE_TMP SET ADB_L_DELIVERY_STATUS = 'N'
 WHERE  IDB_SIG_AEROPORTO IN ('SBBR','SBSV','SBRF','SBCF', 'SBFZ','SBGL')
   AND  ADB_TIMESTAMP >= '20120703'
   
   
--executar as procedures
/*
use CGA

EXEC dbo.PRC_01_CARGA_POUSOS 'SBGL'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBGL'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBGL'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBGL'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBGL'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBGL'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBGL'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBGL'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBGL'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBGL'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBGL'


EXEC dbo.PRC_01_CARGA_POUSOS 'SBCF'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBCF'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBCF'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBCF'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBCF'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBCF'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBCF'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBCF'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBCF'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBCF'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBCF'


EXEC dbo.PRC_01_CARGA_POUSOS 'SBBR'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBBR'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBBR'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBBR'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBBR'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBBR'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBBR'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBBR'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBBR'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBBR'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBBR'


EXEC dbo.PRC_01_CARGA_POUSOS 'SBSV'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBSV'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBSV'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBSV'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBSV'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBSV'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBSV'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBSV'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBSV'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBSV'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBSV'


EXEC dbo.PRC_01_CARGA_POUSOS 'SBFZ'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBFZ'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBFZ'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBFZ'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBFZ'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBFZ'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBFZ'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBFZ'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBFZ'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBFZ'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBFZ'



EXEC dbo.PRC_01_CARGA_POUSOS 'SBRF'
EXEC dbo.PRC_02_CARGA_ENTRADA_CALCO 'SBRF'
EXEC dbo.PRC_03_CARGA_VOO_CONFIRMADO 'SBRF'
EXEC dbo.PRC_04_CARGA_VOO_EMB_PROXIMO 'SBRF'
EXEC dbo.PRC_05_CARGA_EMB_IMEDIATO 'SBRF'
EXEC dbo.PRC_06_CARGA_ULT_CHAMADA 'SBRF'
EXEC dbo.PRC_07_CARGA_VOO_ENCERRADO 'SBRF'
EXEC dbo.PRC_08_CARGA_SAIDA_CALCO 'SBRF'
EXEC dbo.PRC_09_CARGA_DECOLAGEM 'SBRF'
EXEC dbo.PRC_10_ATU_DADOS_PROC_DECOLAGEM 'SBRF'
EXEC dbo.PRC_11_ATU_OUTROS_DADOS 'SBRF'

*/