DECLARE @REL TABLE (
	SIGLA_AEROPORTO VARCHAR(4)
,	ANO INT
,	MES_INI INT
,	MES_FIM INT
,	TOTAL_PAX_DOM NUMERIC(12,2)
,	TOTAL_COR_DOM NUMERIC(12,2)
,	TOTAL_CAR_DOM NUMERIC(12,2)
,	TOTAL_PAX_DOM_ANT NUMERIC(12,2)
,	TOTAL_COR_DOM_ANT NUMERIC(12,2)
,	TOTAL_CAR_DOM_ANT NUMERIC(12,2)
,	TOTAL_PAX_INT NUMERIC(12,2)
,	TOTAL_COR_INT NUMERIC(12,2)
,	TOTAL_CAR_INT NUMERIC(12,2)
,	TOTAL_PAX_INT_ANT NUMERIC(12,2)
,	TOTAL_COR_INT_ANT NUMERIC(12,2)
,	TOTAL_CAR_INT_ANT NUMERIC(12,2)
,	TOTAL_PAX_DOM_ANO_ANT NUMERIC(12,2)
,	TOTAL_COR_DOM_ANO_ANT NUMERIC(12,2)
,	TOTAL_CAR_DOM_ANO_ANT NUMERIC(12,2)
,	TOTAL_PAX_INT_ANO_ANT NUMERIC(12,2)
,	TOTAL_COR_INT_ANO_ANT NUMERIC(12,2)
,	TOTAL_CAR_INT_ANO_ANT NUMERIC(12,2)
)

DECLARE		@AEROPORTO VARCHAR(4)
,			@ANO INT
,			@ANO_ANT INT
,			@MES_INI INT
,			@MES_FIM INT
,			@TOTAL_PAX_DOM_DES NUMERIC(12,2)
,			@TOTAL_COR_DOM_DES NUMERIC(12,2)
,			@TOTAL_CAR_DOM_DES NUMERIC(12,2)
,			@TOTAL_PAX_DOM_DES_ANT NUMERIC(12,2)
,			@TOTAL_COR_DOM_DES_ANT NUMERIC(12,2)
,			@TOTAL_CAR_DOM_DES_ANT NUMERIC(12,2)
,			@TOTAL_PAX_DOM_EMB NUMERIC(12,2)
,			@TOTAL_COR_DOM_EMB NUMERIC(12,2)
,			@TOTAL_CAR_DOM_EMB NUMERIC(12,2)
,			@TOTAL_PAX_DOM_EMB_ANT NUMERIC(12,2)
,			@TOTAL_COR_DOM_EMB_ANT NUMERIC(12,2)
,			@TOTAL_CAR_DOM_EMB_ANT NUMERIC(12,2)
,			@TOTAL_PAX_INT_DES NUMERIC(12,2)
,			@TOTAL_COR_INT_DES NUMERIC(12,2)
,			@TOTAL_CAR_INT_DES NUMERIC(12,2)
,			@TOTAL_PAX_INT_DES_ANT NUMERIC(12,2)
,			@TOTAL_COR_INT_DES_ANT NUMERIC(12,2)
,			@TOTAL_CAR_INT_DES_ANT NUMERIC(12,2)
,			@TOTAL_PAX_INT_EMB NUMERIC(12,2)
,			@TOTAL_COR_INT_EMB NUMERIC(12,2)
,			@TOTAL_CAR_INT_EMB NUMERIC(12,2)
,			@TOTAL_PAX_INT_EMB_ANT NUMERIC(12,2)
,			@TOTAL_COR_INT_EMB_ANT NUMERIC(12,2)
,			@TOTAL_CAR_INT_EMB_ANT NUMERIC(12,2)
,			@TOTAL_PAX_DOM_ANO_ANT NUMERIC(12,2)
,			@TOTAL_COR_DOM_ANO_ANT NUMERIC(12,2)
,			@TOTAL_CAR_DOM_ANO_ANT NUMERIC(12,2)
,			@TOTAL_PAX_INT_ANO_ANT NUMERIC(12,2)
,			@TOTAL_COR_INT_ANO_ANT NUMERIC(12,2)
,			@TOTAL_CAR_INT_ANO_ANT NUMERIC(12,2)

SELECT		@AEROPORTO = 'SBGR'
,			@ANO = 2009
,			@ANO_ANT = 2008
,			@MES_INI = 1
,			@MES_FIM = 7	

---
SELECT		@TOTAL_PAX_DOM_DES = SUM(DESEMB_PASSAGEIRO_DOM+TRANSITO_CONEXAO_DOM)
,			@TOTAL_PAX_INT_DES = SUM(DESEMB_PASSAGEIRO_INT+TRANSITO_CONEXAO_INT)
,			@TOTAL_COR_DOM_DES = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
,			@TOTAL_CAR_DOM_DES = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)
FROM		BIOGER.dbo.BIOGER_RPE_DES
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_POUSO) = @ANO
AND			MONTH(DATA_HORA_EFETIVA_POUSO) BETWEEN @MES_INI AND @MES_FIM
AND			GRUPO_VOO = 1

SELECT		@TOTAL_PAX_DOM_DES_ANT = SUM(DESEMB_PASSAGEIRO_DOM+TRANSITO_CONEXAO_DOM)
,			@TOTAL_PAX_INT_DES_ANT = SUM(DESEMB_PASSAGEIRO_INT+TRANSITO_CONEXAO_INT)
,			@TOTAL_COR_DOM_DES_ANT = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
,			@TOTAL_CAR_DOM_DES_ANT = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)
FROM		BIOGER.dbo.BIOGER_RPE_DES
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_POUSO) = @ANO_ANT
AND			MONTH(DATA_HORA_EFETIVA_POUSO) BETWEEN @MES_INI AND @MES_FIM
AND			GRUPO_VOO = 1


SELECT		@TOTAL_PAX_DOM_ANO_ANT = SUM(DESEMB_PASSAGEIRO_DOM+TRANSITO_CONEXAO_DOM)
,			@TOTAL_PAX_INT_ANO_ANT = SUM(DESEMB_PASSAGEIRO_INT+TRANSITO_CONEXAO_INT)
/*,			@TOTAL_COR_DOM_DES_ANT = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
,			@TOTAL_CAR_DOM_DES_ANT = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)*/
FROM		BIOGER.dbo.BIOGER_RPE_DES
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_POUSO) = @ANO_ANT
AND			GRUPO_VOO = 1

---

SELECT		@TOTAL_PAX_DOM_EMB = SUM(EMB_TARIFA_PAGA_BILHETE_DOM+EMB_TARIFA_PAGA_CHECKIN_DOM+EMB_ISENTA_COLO+EMB_ISENTA_TRANSITO+EMB_ISENTA_CONEXAO_DOM+EMB_ISENTA_OUTRAS+EMB_TARIFA_PAG_BILHETE_DOM_ANT+EMB_TARIFA_PAG_CHECKIN_DOM_ANT)
,			@TOTAL_PAX_INT_EMB = SUM(EMB_TARIFA_PAGA_BILHETE_INT+EMB_TARIFA_PAGA_CHECKIN_INT+EMB_ISENTA_CONEXAO_INT+EMB_TARIFA_PAG_BILHETE_INT_ANT+EMB_TARIFA_PAG_CHECKIN_INT_ANT)
--,			@TOTAL_COR_DOM_DES = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
--,			@TOTAL_CAR_DOM_DES = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)
FROM		BIOGER.dbo.BIOGER_RPE_EMB
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = @ANO
AND			MONTH(DATA_HORA_EFETIVA_DECOLAGEM) BETWEEN @MES_INI AND @MES_FIM
AND			GRUPO_VOO = 1

SELECT		@TOTAL_PAX_DOM_EMB_ANT = SUM(EMB_TARIFA_PAGA_BILHETE_DOM+EMB_TARIFA_PAGA_CHECKIN_DOM+EMB_ISENTA_COLO+EMB_ISENTA_TRANSITO+EMB_ISENTA_CONEXAO_DOM+EMB_ISENTA_OUTRAS+EMB_TARIFA_PAG_BILHETE_DOM_ANT+EMB_TARIFA_PAG_CHECKIN_DOM_ANT)
,			@TOTAL_PAX_INT_EMB_ANT = SUM(EMB_TARIFA_PAGA_BILHETE_INT+EMB_TARIFA_PAGA_CHECKIN_INT+EMB_ISENTA_CONEXAO_INT+EMB_TARIFA_PAG_BILHETE_INT_ANT+EMB_TARIFA_PAG_CHECKIN_INT_ANT)
--,			@TOTAL_COR_DOM_DES_ANT = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
--,			@TOTAL_CAR_DOM_DES_ANT = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)
FROM		BIOGER.dbo.BIOGER_RPE_EMB
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = @ANO_ANT
AND			MONTH(DATA_HORA_EFETIVA_DECOLAGEM) BETWEEN @MES_INI AND @MES_FIM
AND			GRUPO_VOO = 1

SELECT		@TOTAL_PAX_DOM_ANO_ANT = @TOTAL_PAX_DOM_ANO_ANT + SUM(EMB_TARIFA_PAGA_BILHETE_DOM+EMB_TARIFA_PAGA_CHECKIN_DOM+EMB_ISENTA_COLO+EMB_ISENTA_TRANSITO+EMB_ISENTA_CONEXAO_DOM+EMB_ISENTA_OUTRAS+EMB_TARIFA_PAG_BILHETE_DOM_ANT+EMB_TARIFA_PAG_CHECKIN_DOM_ANT)
,			@TOTAL_PAX_INT_ANO_ANT = @TOTAL_PAX_INT_ANO_ANT + SUM(EMB_TARIFA_PAGA_BILHETE_INT+EMB_TARIFA_PAGA_CHECKIN_INT+EMB_ISENTA_CONEXAO_INT+EMB_TARIFA_PAG_BILHETE_INT_ANT+EMB_TARIFA_PAG_CHECKIN_INT_ANT)
--,			@TOTAL_COR_DOM_DES_ANT = SUM(DESEMB_CORREIO_DOM+TRANSITO_CORREIO_DOM)
--,			@TOTAL_CAR_DOM_DES_ANT = SUM(DESEMB_CARGA_DOM+TRANSITO_CARGA_DOM)
FROM		BIOGER.dbo.BIOGER_RPE_EMB
WHERE		SIGLA_AEROPORTO = @AEROPORTO
AND			YEAR(DATA_HORA_EFETIVA_DECOLAGEM) = @ANO_ANT
AND			GRUPO_VOO = 1

---

INSERT INTO @REL VALUES (@AEROPORTO, @ANO, @MES_INI, @MES_FIM, @TOTAL_PAX_DOM_DES+@TOTAL_PAX_DOM_EMB, @TOTAL_COR_DOM_DES, @TOTAL_CAR_DOM_DES, @TOTAL_PAX_DOM_DES_ANT+@TOTAL_PAX_DOM_EMB_ANT, @TOTAL_COR_DOM_DES_ANT, @TOTAL_CAR_DOM_DES_ANT, @TOTAL_PAX_INT_DES+@TOTAL_PAX_INT_EMB, @TOTAL_COR_INT_DES, @TOTAL_CAR_INT_DES, @TOTAL_PAX_INT_DES_ANT+@TOTAL_PAX_INT_EMB_ANT, @TOTAL_COR_INT_DES_ANT, @TOTAL_CAR_INT_DES_ANT, @TOTAL_PAX_DOM_ANO_ANT, @TOTAL_COR_DOM_ANO_ANT, @TOTAL_CAR_DOM_ANO_ANT, @TOTAL_PAX_INT_ANO_ANT, @TOTAL_COR_INT_ANO_ANT, @TOTAL_CAR_INT_ANO_ANT)



SELECT	SIGLA_AEROPORTO
,		ANO 
,		MES_INI 
,		MES_FIM 
,		CONVERT(INT,TOTAL_PAX_DOM) AS TOTAL_PAX_DOM
,		CONVERT(INT,TOTAL_PAX_INT) AS TOTAL_PAX_INT
,       CONVERT(INT,TOTAL_PAX_DOM)+ CONVERT(INT,TOTAL_PAX_INT) AS TOTAL_PAX
,		100 - (((TOTAL_PAX_DOM_ANT+TOTAL_PAX_INT_ANT)*100)/(TOTAL_PAX_DOM+TOTAL_PAX_INT)) AS VARIACAO_PAX
,		CONVERT(INT,(CONVERT(INT,@TOTAL_PAX_DOM_ANO_ANT) + CONVERT(INT,@TOTAL_PAX_INT_ANO_ANT)) * (((100 -(((TOTAL_PAX_DOM_ANT+TOTAL_PAX_INT_ANT)*100)/(TOTAL_PAX_DOM+TOTAL_PAX_INT)))/100)+1) ) AS ESTIMATIVA_PAX
/*,		CONVERT(INT,TOTAL_COR_DOM) AS TOTAL_COR_DOM
,		100 - ((TOTAL_COR_DOM*100)/TOTAL_COR_DOM_ANT) VAR_COR_DOM
,		CONVERT(INT,TOTAL_BAG_DOM) AS TOTAL_BAG_DOM
,		100-((TOTAL_BAG_DOM*100)/TOTAL_BAG_DOM_ANT) VAR_BAG_DOM
,		CONVERT(INT,TOTAL_CAR_DOM) AS TOTAL_CAR_DOM 
,		100 - ((TOTAL_CAR_DOM*100)/TOTAL_CAR_DOM_ANT) VAR_CAR_DOM */
FROM	@REL