CREATE SEQUENCE SEQ_CRONOGRAMA
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
 NOCACHE
/

PROMPT Creating Table 'OBRAS_USUARIOS'
CREATE TABLE OBRAS_USUARIOS
 (OBUS_OBR_SEQUENCIAL VARCHAR2(15) NOT NULL
 ,OBUS_USU_CPF VARCHAR2(15) NOT NULL
 ,OBUS_USU_AER VARCHAR2(4) NOT NULL
 ,OBUS_FISCAL VARCHAR2(1)
 ,OBUS_OBR_AER VARCHAR2(3)
 )
/

COMMENT ON COLUMN OBRAS_USUARIOS.OBUS_OBR_SEQUENCIAL IS 'Sequencial formecido para identificacao unica da obra,e o mesmo para todos os sistemas de obras da INFRAERO'
/

COMMENT ON COLUMN OBRAS_USUARIOS.OBUS_USU_CPF IS 'CPF do usuario que pode ter acesso a obra'
/

COMMENT ON COLUMN OBRAS_USUARIOS.OBUS_USU_AER IS 'Aeroporto do usuario que pode ter acesso a obra'
/

COMMENT ON COLUMN OBRAS_USUARIOS.OBUS_FISCAL IS 'Indicacao se o usuario e fiscal da obra'
/


CREATE TABLE CAD_CRONOGRAMAS
 (CRO_OBR_SEQUENCIAL VARCHAR2(15) NOT NULL
 ,CRO_OBR_AER VARCHAR2(3)
 ,CRO_ATIVIDADE VARCHAR2(3) NOT NULL
 ,CRO_MESANO_INICIO DATE
 ,CRO_MESANO_FIM DATE
 ,CRO_TIPO VARCHAR2(1)
 ,CRO_OBR_AER_PAI VARCHAR2(3)
 ,CRO_VALOR_PREVISTO NUMBER
 )
/

COMMENT ON COLUMN CAD_CRONOGRAMAS.CRO_OBR_SEQUENCIAL IS 'Sequencial formecido para identificacao unica da obra,e o mesmo para todos os sistemas de obras da INFRAERO'
/

COMMENT ON COLUMN CAD_CRONOGRAMAS.CRO_OBR_AER IS 'Codigo da dependencia na Infraero'
/

COMMENT ON COLUMN CAD_CRONOGRAMAS.CRO_ATIVIDADE IS 'Atividade do cronograma'
/


PROMPT Creating Table 'CAD_FATURAMENTOS'
CREATE TABLE CAD_FATURAMENTOS
 (CNT_COD VARCHAR2(30)
 ,FAT_OBR_SEQUENCIAL VARCHAR2(15) NOT NULL
 ,FAT_MEDICAO NUMBER NOT NULL
 ,FAT_PERIODO DATE
 ,FAT_VALOR NUMBER
 ,FAT_VALOR_REAJUSTE NUMBER
 ,FAT_SALDO NUMBER
 ,FAT_PERCENTUAL NUMBER
 )
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_OBR_SEQUENCIAL IS 'Sequencial formecido para identificacao unica da obra,e o mesmo para todos os sistemas de obras da INFRAERO'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_MEDICAO IS 'Ordem da medicao'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_PERIODO IS 'Periodo a que se refere a medicao, mes/ano'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_VALOR IS 'Valor pago'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_VALOR_REAJUSTE IS 'Valor pago'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_SALDO IS 'Saldo do restante'
/

COMMENT ON COLUMN CAD_FATURAMENTOS.FAT_PERCENTUAL IS 'Percentual gasto'
/


PROMPT Creating Table 'FOTOS'
CREATE TABLE FOTOS
 (FOTO_OBR_SEQUENCIAL VARCHAR2(15) NOT NULL
 ,FOTO_NUMERO NUMBER NOT NULL
 ,FOTO_OBR_AER VARCHAR2(4)
 ,FOTO_NOMEIMAGEM VARCHAR2(15)
 )
/


PROMPT Creating Table 'DESPACHOS'
CREATE TABLE DESPACHOS
 (DES_OBR_SEQUENCIAL VARCHAR2(15) NOT NULL
 ,DES_OBR_AER VARCHAR2(4) NOT NULL
 ,DES_ASSUNTO VARCHAR2(240)
 ,DES_ORIGEM VARCHAR2(10)
 ,DES_ENCAMINHAMENTO DATE
 ,DES_DESTINO VARCHAR2(10)
 ,DES_RECEBIMENTO DATE
 ,DES_USU_CPFENCAMIN VARCHAR2(15)
 ,DES_USU_AEREMCAMIN VARCHAR2(4)
 ,DES_USU_CPFRECEBIM VARCHAR2(15)
 ,DES_USU_AERRECEBIM VARCHAR2(4)
 ,DES_CODIGO NUMBER NOT NULL
 )
/

COMMENT ON COLUMN DESPACHOS.DES_OBR_SEQUENCIAL IS 'Sequencial formecido para identificacao unica da obra,e o mesmo para todos os sistemas de obras da INFRAERO'
/

COMMENT ON COLUMN DESPACHOS.DES_OBR_AER IS 'Aeroporto onde sera realizada a obra'
/

COMMENT ON COLUMN DESPACHOS.DES_ASSUNTO IS 'Assunto do despacho'
/

COMMENT ON COLUMN DESPACHOS.DES_ORIGEM IS 'Origem do despacho'
/

COMMENT ON COLUMN DESPACHOS.DES_ENCAMINHAMENTO IS 'Data do encaminhamento'
/

COMMENT ON COLUMN DESPACHOS.DES_DESTINO IS 'Destino do despacho'
/

COMMENT ON COLUMN DESPACHOS.DES_RECEBIMENTO IS 'Data de recebimento'
/

COMMENT ON COLUMN DESPACHOS.DES_USU_CPFENCAMIN IS 'CPF do responsavel pelo encaminhamento'
/

COMMENT ON COLUMN DESPACHOS.DES_USU_AEREMCAMIN IS 'Aeroporto do responsavel pelo encaminhamento'
/

COMMENT ON COLUMN DESPACHOS.DES_USU_CPFRECEBIM IS 'CPF do responsavel pelo recebimento'
/

COMMENT ON COLUMN DESPACHOS.DES_USU_AERRECEBIM IS 'Aeroporto do responsavel pelo recebimento'
/

COMMENT ON COLUMN DESPACHOS.DES_CODIGO IS 'Codigo do despacho'
/

PROMPT Creating Primary Key on 'OBRAS_USUARIOS'
ALTER TABLE OBRAS_USUARIOS
 ADD CONSTRAINT PK_OBRAS_USUARIOS PRIMARY KEY 
  (OBUS_USU_CPF
  ,OBUS_OBR_SEQUENCIAL)
/

PROMPT Creating Primary Key on 'FOTOS'
ALTER TABLE FOTOS
 ADD CONSTRAINT PK_FOTOS PRIMARY KEY 
  (FOTO_OBR_SEQUENCIAL
  ,FOTO_NUMERO)
/

PROMPT Creating Primary Key on 'DESPACHOS'
ALTER TABLE DESPACHOS
 ADD CONSTRAINT DESPACHOS_PK PRIMARY KEY 
  (DES_OBR_SEQUENCIAL
  ,DES_CODIGO)
/
               
PROMPT Creating Foreign Keys on 'OBRAS_USUARIOS'
ALTER TABLE OBRAS_USUARIOS ADD CONSTRAINT
 OBRAS_USUARIO_TAB_CARENCIA_FK FOREIGN KEY 
  (OBUS_OBR_SEQUENCIAL) REFERENCES TAB_CARENCIA
  (CRE_COD)
/

PROMPT Creating Foreign Keys on 'CAD_CRONOGRAMAS'
ALTER TABLE CAD_CRONOGRAMAS ADD CONSTRAINT
 CAD_CRONOGRAMAS_02_FK FOREIGN KEY 
  (CRO_OBR_SEQUENCIAL) REFERENCES TAB_CARENCIA
  (CRE_COD) ADD CONSTRAINT
 CAD_CRONOGRAMAS_01_FK FOREIGN KEY 
  (CRO_ATIVIDADE) REFERENCES TAB_ETAPA_OBRA
  (ETO_COD)  
/

PROMPT Creating Foreign Keys on 'CAD_FATURAMENTOS'
ALTER TABLE CAD_FATURAMENTOS ADD CONSTRAINT
 FATURAMENTOS_TAB_CONTRATO_FK1 FOREIGN KEY 
  (FAT_OBR_SEQUENCIAL
  ,CNT_COD) REFERENCES TAB_CONTRATO
  (CNT_CRE_COD
  ,CNT_COD)  
/


PROMPT Creating Foreign Keys on 'FOTOS'
ALTER TABLE FOTOS ADD CONSTRAINT
 TAB_CARENCIA_TAB_FOTOS_FK FOREIGN KEY 
  (FOTO_OBR_SEQUENCIAL) REFERENCES TAB_CARENCIA
  (CRE_COD)
/

PROMPT Creating Foreign Keys on 'DESPACHOS'
ALTER TABLE DESPACHOS ADD CONSTRAINT
 TAB_CARENCIA_TAB_DESPACHOS_FK FOREIGN KEY 
  (DES_OBR_SEQUENCIAL) REFERENCES TAB_CARENCIA
  (CRE_COD)
/

PROMPT Creating View 'VW_CRO_ATRASADO'
CREATE OR REPLACE FORCE VIEW VW_CRO_ATRASADO
 (CRO_OBR_SEQUENCIAL
 ,CRO_OBR_AER
 ,CRO_MESANO_INICIO
 ,CRO_MESANO_FIM
 ,CRO_ATIVIDADE
 ,CRO_TIPO
 ,TIPO_ATRASO)
 AS SELECT CRO_OBR_SEQUENCIAL,CRO_OBR_AER,CRO_MESANO_INICIO,CRO_MESANO_FIM 
,CRO_ATIVIDADE,CRO_TIPO,'NI' AS TIPO_ATRASO
FROM CAD_CRONOGRAMAS
  WHERE (CRO_OBR_SEQUENCIAL,CRO_ATIVIDADE) NOT IN (select 
CRO_OBR_SEQUENCIAL,CRO_ATIVIDADE
                                                 FROM CAD_CRONOGRAMAS
                                                 WHERE CRO_TIPO='R')
AND CRO_MESANO_INICIO < TRUNC(SYSDATE,'MONTH')
UNION
select 
R.CRO_OBR_SEQUENCIAL,R.CRO_OBR_AER,R.CRO_MESANO_INICIO,
R.CRO_MESANO_FIM ,R.CRO_ATIVIDADE,R.CRO_TIPO,'IA' AS TIPO_ATRASO
from cad_cronogramas P,cad_cronogramas R
WHERE  P.CRO_OBR_SEQUENCIAL=R.CRO_OBR_SEQUENCIAL
and p.CRO_OBR_AER  = r.CRO_OBR_AER
and P.CRO_ATIVIDADE=R.CRO_ATIVIDADE
and P.CRO_TIPO='P'
and R.CRO_TIPO='R'
AND P.CRO_MESANO_INICIO < R.CRO_MESANO_INICIO
UNION
select 
R.CRO_OBR_SEQUENCIAL,R.CRO_OBR_AER,R.CRO_MESANO_INICIO,
R.CRO_MESANO_FIM ,R.CRO_ATIVIDADE,R.CRO_TIPO ,'FA' AS TIPO_ATRASO

from cad_cronogramas P,cad_cronogramas R
WHERE  P.CRO_OBR_SEQUENCIAL=R.CRO_OBR_SEQUENCIAL
and p.CRO_OBR_AER  = r.CRO_OBR_AER
and P.CRO_ATIVIDADE=R.CRO_ATIVIDADE
and P.CRO_TIPO='P'
AND P.CRO_TIPO<>R.CRO_TIPO
AND P.CRO_MESANO_FIM<R.CRO_MESANO_FIM
/

