comment on table ifrsrh.ADICIONAL_13_FERIAS is 'Tabela que grava os valores calculados dos adicionais de 13º e férias dos empregados';
comment on table ifrsrh.ARQUIVO_CREDITO_BANCARIO is 'Tabela que grava os registros que serão encaminhados para os bancos com os valores a serem pagos aos empregados no mês';
comment on table ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS is 'Tabela que grava os registros que serão encaminhados para os bancos com os valores a serem pagos aos pensionistas no mês';
comment on table ifrsrh.ASSINFRA_MOVIMENTACAO is 'Tabela que grava a movimentação (valores) das Assinfras registradas';
comment on table ifrsrh.CRONOGRAMAS_PAGAMENTOS is 'Tabela que grava o cronograma de pagamento mensal da folha';
comment on table ifrsrh.EMPREGADOS_PAGAMENTOS is 'Tabela que grava os valores consolidados das movimentação que serão pagos aos empregados mensalmente';
comment on table ifrsrh.EMPRESTIMOS_INFRAPREV is 'Tabela que grava e controla as parcelas dos empregados que possuem empréstimos pela INFRAPREV';
comment on table ifrsrh.FORMULAS is 'Tabela que grava as fórmulas das rubricas utilizadas na folha de pagamento';
comment on table ifrsrh.FORMULAS_RUBRICAS is 'Tabela que faz o relacionamento da rubrica com a fórmula da rubrica';
comment on table ifrsrh.GRH_HST_DIRF is 'Tabela que grava os dados enviados para a DIRF anualmente';
comment on table ifrsrh.GRUPOS_RUBRICAS is 'Tabela que grava os grupos/classificações das rubricas';
comment on table ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS is 'Log da tabela de cronograma de pagamento da folha';
comment on table ifrsrh.LOG_EMPREGADOS_PAGAMENTOS is 'Log da tabela de pagamentos consolidados dos empregados';
comment on table ifrsrh.LOG_ERRO_FOLHA_FECHADA is 'Tabela que grava dados dos usuários que tentam alterar alguma informação na folha que já se encontra encerrada/fechada';
comment on table ifrsrh.LOG_MOVIMENTACAO is 'Log da tabela de movimentação de pagamento dos empregados';
comment on table ifrsrh.MENSAGENS_CONTRACHEQUES is 'Tabela para gravar mensagens que são exibidas no contracheque do empregado';
comment on table ifrsrh.MOVIMENTACAO is 'Tabela que grava a movimentação individual financeira do empregado mensalmente';
comment on table ifrsrh.OPERANDOS is 'Tabela que grava os operandos que são utilzados nas fórmulas das rubricas';
comment on table ifrsrh.PREVISAO_PAGAMENTO is 'Tabela que grava a previsão de pagamento da folha';
comment on table ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB is 'Tabela criada para gravar os erros apresentados no momento da migração da base RDB para a base Oracle';
comment on table ifrsrh.RUBRICAS is 'Tabela que grava as rubricas utilizadas na folha de pagamento para cálculo do pagamento do empregado';
comment on table ifrsrh.TAB_MSG_CONTRACHEQUE_EMPREGADO is 'Tabela com as mensagens que devem aparecer no contracheque dos empregados';
comment on table ifrsrh.TMP_CONTRACHEQUE_EMP is 'Tabela temporária para gravar e organizar os dados do empregado antes de gerar o contracheque';

-- colunas
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EGT_CRP_ANO_PAGAMENTO is 'Ano de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EGT_CRP_MES_PAGAMENTO is 'Mês de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EGT_CRP_SEQUENCIAL is 'Versão de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_SEQUENCIAL is 'Tipo de pagamento: 1 - Normal;2 - Complementar';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_ABA_BAN_CODIGO is 'Banco do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_REMUNERACAO_LIQUIDO is 'Valor líquido a ser creditado para o empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_ABA_CODIGO is 'Agência bancária do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EMP_CONTA_CORRENTE is 'Conta corrente do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO.ACB_EMP_TIPO_CONTA is 'Tipo de conta do empregado (CC, Poupança, etc)';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.EGT_CRP_ANO_PAGAMENTO is 'Ano de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.EGT_CRP_MES_PAGAMENTO is 'Mês de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.EGT_CRP_SEQUENCIAL is 'Versão de pagamento do salário';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.ACP_SEQUENCIAL is 'Tipo de pagamento: 1 - Normal;2 - Complementar';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.ACP_PEN_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.ACP_PEN_CODIGO is 'Código do pensionista';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.DEP_CODIGO is 'Dependência do empregado';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.ABA_BAN_CODIGO is 'Agência bancária do pensionista';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.ABA_CODIGO is 'Banco do pensionista';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.EMP_CONTA_CORRENTE is 'Conta corrente do pensionista';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.REMUNERACAO_LIQUIDO is 'Valor líquido a ser creditado para o pensionista';
comment on column ifrsrh.ARQUIVO_CREDITO_BANCARIO_PENS.TIPO_CREDITO is 'Tipo de crédito do pensionista';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_ADE_CAS_CNPJ is 'CNPJ da Assinfra';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_ADE_DEP_CODIGO is 'Dependência da Assinfra';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_VERSAO is 'Versão da movimentação';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_MES_REFERENCIA is 'Mês de referência da movimentação';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_ANO_REFERENCIA is 'Ano de referência da movimentação';
comment on column ifrsrh.ASSINFRA_MOVIMENTACAO.AMO_VALOR is 'Valor da movimentação';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_DEP_CODIGO is 'Dependência';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_EPG_CODIGO is 'Evento de Pagamento';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_ANO_PAGAMENTO is 'Ano de pagamento';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_MES_PAGAMENTO is 'Mês de pagamento';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_SEQUENCIAL is 'Versão de pagamento';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_DATA_PREVISTA is 'Data prevista da execução do evento';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_PERCENTUAL_FOLHA is 'Percentual da folha do mês';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_IND_13 is 'Indicador de cronograma de 13º';
comment on column ifrsrh.CRONOGRAMAS_PAGAMENTOS.CRP_DATA_REALIZACAO is 'Data de realização do evento';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_NUMERO_MATRICULA is 'Mátricula do empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_CRP_ANO_PAGAMENTO is 'Ano de pagamento';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_CRP_MES_PAGAMENTO is 'Mês de pagamento';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_CRP_SEQUENCIAL is 'Versão de pagamento';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_DEP_CODIGO is 'Dependência do empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_UOR_CODIGO is 'Unidade organizacional do empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_VALOR_FG is 'Valor da Função Gratificada do empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_VALOR_RG is 'Valor da Remuneração Global do empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_DEPENDENTES_IR is 'Quantidade de Dependentes para cálculo de Imposto de Renda';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_DEPENDENTES_SAL_FAM is 'Quantidade de Dependentes para cálculo de Salário Família';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_NUMERO_MES_13 is 'Proporcionalidade de meses para cálculo do 13º';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_NUMERO_ANUENIOS is 'Quantidade de anuênios';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_CARGA_HORARIA_MES is 'Carga horário de trabalho no mês';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_BASE_FGTS is 'Valor da Base de FGTS para cálculo do FGTS';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_BASE_INSS is 'Valor da Base de INSS para cálculo do INSS';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_BASE_IRRF is 'Valor da Base do IRRF para cálculo do IRRF';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_PERCENTUAL_ARSAPREV is 'Percentual utilizado para cálculo do INFRAPREV';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_PLANO_ARSAPREV is 'Número do plano INFRAPREV aderido pelo empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_BASE_ARSAPREV is 'Valor da Base de INFRAPREV para cálculo do plano';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_QLP_CAR_CODIGO is 'Código do Cargo do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_QLP_CAR_CODIGO_NIVEL is 'Nível do Cargo do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_QLP_CAR_OCC_CODIGO is 'Ocupação do Cargo do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_NSA_CODIGO_NIVEL is 'Nível de salário do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_NSA_CODIGO_PADRAO is 'Padrão de salário do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_NSA_IN_NIVEL_ESCOLARID is 'Nível de Escolaridade de salário do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_EMP_QFU_FUN_CODIGO is 'Código da Função exercida pelo Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_REMUNERACAO_LIQUIDO is 'Remuneração líquida do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_HCC_CCT_CODIGO is 'Centro de Custo do Empregado na mês/ano pagamento';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_FAIXA_INSS is 'Faixa de INSS para desconto';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_VALOR_MARGEM_CONSIGNAVEL is 'Valor da margem consignável';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.EGT_DEP_CODIGO_FISICO is 'Código da dependência física do Empregado';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.COD_USUARIO is 'Código do Usuário responsável pela inclusão do registro';
comment on column ifrsrh.EMPREGADOS_PAGAMENTOS.DTA_OPERACAO is 'Data da operação (inclusão) do registro';
comment on column ifrsrh.EMPRESTIMOS_INFRAPREV.ANO_REFERENCIA is 'Ano de pagamento';
comment on column ifrsrh.EMPRESTIMOS_INFRAPREV.MES_REFERENCIA is 'Mês de pagamento';
comment on column ifrsrh.EMPRESTIMOS_INFRAPREV.NUM_MATRICULA_EMPREGADO is 'Matrícula do empregado';
comment on column ifrsrh.FORMULAS.FOR_CODIGO is 'Código da fórmula';
comment on column ifrsrh.FORMULAS.FOR_FORMULA is 'Fórmula de cálculo da rubrica';
comment on column ifrsrh.FORMULAS.FOR_FORMULA_INVERTIDA is 'Fórmula de cálculo da rubrica invertida';
comment on column ifrsrh.FORMULAS.FOR_DESCRICAO is 'Descrição da fórmula';
comment on column ifrsrh.FORMULAS.FOR_TIPO_PARAMETRO is 'Tipo de parâmetro de cálculo da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_ANO_INICIO is 'Ano de início de vigência da fórmula para a rubrica';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_MES_INICIO is 'Mês de início de vigência da fórmula para a rubrica';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_ANO_TERMINO is 'Ano de término de vigência da fórmula para a rubrica';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_MES_TERMINO is 'Mês de término de vigência da fórmula para a rubrica';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_FOR_CODIGO is 'Código da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_VALOR_INFERIOR is 'Valor inferior limítrofe da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_VALOR_SUPERIOR is 'Valor superior limítrofe da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_FREQUENCIA_INFERIOR is 'Freqüência inferior limítrofe da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_FREQUENCIA_SUPERIOR is 'Freqüência superior limítrofe da fórmula';
comment on column ifrsrh.FORMULAS_RUBRICAS.FRU_COMENTARIO is 'Comentário da fórmula';
comment on column ifrsrh.GRH_HST_DIRF.GHD_DAT_ANO is 'Ano de execução da DIRF';
comment on column ifrsrh.GRH_HST_DIRF.GHD_NUM_CPF is 'CPF do empregado';
comment on column ifrsrh.GRH_HST_DIRF.GHD_NUM_SEQUENCIAL is 'Sequencial';
comment on column ifrsrh.GRH_HST_DIRF.GHD_TIP_REGISTRO is 'Tipo de registro gerado';
comment on column ifrsrh.GRH_HST_DIRF.GHD_NUM_CNPJ is 'CNPJ da empresa';
comment on column ifrsrh.GRH_HST_DIRF.GHD_COD_RETENCAO is 'Código de retenção';
comment on column ifrsrh.GRH_HST_DIRF.GHD_COD_IDENT_ESP_BEN is 'Código identificador';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_JAN is 'Valor do Rendimento de Janeiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_JAN is 'Valor da Dedução de Janeiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_JAN is 'Valor do Imposto Retido de Janeiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_FEV is 'Valor do Rendimento de Fevereiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_FEV is 'Valor da Dedução de Fevereiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_FEV is 'Valor do Imposto Retido de Fevereiro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_MAR is 'Valor do Rendimento de Março';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_MAR is 'Valor da Dedução de Março';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_MAR is 'Valor do Imposto Retido de Março';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_ABR is 'Valor do Rendimento de Abril';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_ABR is 'Valor da Dedução de Abril';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_ABR is 'Valor do Imposto Retido de Abril';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_MAI is 'Valor do Rendimento de Maio';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_MAI is 'Valor da Dedução de Maio';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_MAI is 'Valor do Imposto Retido de Maio';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_JUN is 'Valor do Rendimento de Junho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_JUN is 'Valor da Dedução de Junho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_JUN is 'Valor do Imposto Retido de Junho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_JUL is 'Valor do Rendimento de Julho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_JUL is 'Valor da Dedução de Julho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_JUL is 'Valor do Imposto Retido de Julho';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_AGO is 'Valor do Rendimento de Agosto';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_AGO is 'Valor da Dedução de Agosto';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_AGO is 'Valor do Imposto Retido de Agosto';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_SET is 'Valor do Rendimento de Setembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_SET is 'Valor da Dedução de Setembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_SET is 'Valor do Imposto Retido de Setembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_OUT is 'Valor do Rendimento de Outubro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_OUT is 'Valor da Dedução de Outubro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_OUT is 'Valor do Imposto Retido de Outubro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_NOV is 'Valor do Rendimento de Novembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_NOV is 'Valor da Dedução de Novembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_NOV is 'Valor do Imposto Retido de Novembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_DEZ is 'Valor do Rendimento de Dezembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_DEZ is 'Valor da Dedução de Dezembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_DEZ is 'Valor do Imposto Retido de Dezembro';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_REND_13 is 'Valor do Rendimento do 13º';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_DED_13 is 'Valor da Dedução do 13º';
comment on column ifrsrh.GRH_HST_DIRF.GHD_VAL_IR_13 is 'Valor do Imposto Retido do 13º';
comment on column ifrsrh.GRH_HST_DIRF.GHD_NOM_BENEFICIARIO is 'Nome do empregado/beneficiário';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.COD_USUARIO is 'Código do Usuário responsável pela inclusão do registro';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.DTA_OPERACAO is 'Data da operação (inclusão) do registro';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.TIP_OPERACAO is 'Tipo da operação (I-INSERT;U-UPDATE;D-DELETE)';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_DEP_CODIGO is 'Código da dependência';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_EPG_CODIGO is 'Código do evento de pagamento';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_ANO_PAGAMENTO is 'Ano de pagamento';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_MES_PAGAMENTO is 'Mês de pagamento';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_SEQUENCIAL is 'Sequencial/versão de pagamento';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_DATA_PREVISTA is 'Data prevista para execução do evento';
comment on column ifrsrh.LOG_CRONOGRAMAS_PAGAMENTOS.CRP_DATA_REALIZACAO is 'Data de realização do evento';
comment on column ifrsrh.LOG_EMPREGADOS_PAGAMENTOS.EGT_VALOR_MARGEM_CONSIGNAVEL is 'Valor da margem consignável';
comment on column ifrsrh.LOG_EMPREGADOS_PAGAMENTOS.EGT_DEP_CODIGO_FISICO is 'Código da dependência física do Empregado';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.LEF_CODIGO is 'Código do erro';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.DATA is 'Data do erro';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.USUARIO is 'Código do Usuário responsável pela inclusão do registro';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.OPERACAO is 'Tipo da operação (I-INSERT;U-UPDATE;D-DELETE)';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_ANO_REFERENCIA is 'Ano de pagamento';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_MES_REFERENCIA is 'Mês de pagamento';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_VERSAO_PAGAMENTO is 'Versão de pagamento';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_SEQUENCIAL is 'Sequencial do registro';
comment on column ifrsrh.LOG_ERRO_FOLHA_FECHADA.MOV_TIP_RUBRICA is 'Tipo da rubrica';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_CODIGO is 'Código da mensagem';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_MES is 'Mês para aparecer a mensagem no contracheque';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_ANO is 'Ano para aparecer a mensagem no contracheque';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_DESCRICAO is 'Descrição da mensagem';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_DEP_CODIGO is 'Código da dependência da mensagem';
comment on column ifrsrh.MENSAGENS_CONTRACHEQUES.MEC_MENSAGEM_GERAL is 'Descrição da mensagem caso seja mensagem geral';
comment on column ifrsrh.MOVIMENTACAO.MOV_ANO_REFERENCIA is 'Ano de referência da movimentação';
comment on column ifrsrh.MOVIMENTACAO.MOV_MES_REFERENCIA is 'Mês de referência da movimentação';
comment on column ifrsrh.MOVIMENTACAO.MOV_VERSAO_PAGAMENTO is 'Versão de pagamento';
comment on column ifrsrh.MOVIMENTACAO.MOV_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_SEQUENCIAL is 'Sequencial do registro';
comment on column ifrsrh.MOVIMENTACAO.MOV_PARCELA is 'Número da parcela a ser creditada/descontada';
comment on column ifrsrh.MOVIMENTACAO.MOV_PARCELA_ATUAL is 'Total de parcelas a ser creditada/descontada';
comment on column ifrsrh.MOVIMENTACAO.MOV_RUB_SEQ_PAGAMENTO is 'Sequencia de pagamento da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_EMP_DEP_CODIGO_PAGTO is 'Dependência de pagamento do empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_TIP_RUBRICA is 'Tipo de rubrica(N-NORMAL;D-DIFERENÇA;E-ESTORNO)';
comment on column ifrsrh.MOVIMENTACAO.MOV_IND_CALCULO is 'Indicador de cálculo (S-CALCULADO;N-NÃO CALCULADO)';
comment on column ifrsrh.MOVIMENTACAO.MOV_IND_EXCLUSIVO is 'Indicador de rubrica exclusiva do Sistema(S-SIM;N-NÃO)';
comment on column ifrsrh.MOVIMENTACAO.MOV_FOR_CODIGO is 'Código da fórmula da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_PARAMETRO is 'Parâmetro para cálculo da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_VALOR is 'Valor da rubrica calculada';
comment on column ifrsrh.MOVIMENTACAO.MOV_ANO_REF_DIFERENCA is 'Ano de diferença da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_MES_REF_DIFERENCA is 'Mês de diferença da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_PEN_CODIGO is 'Código do pensionista';
comment on column ifrsrh.MOVIMENTACAO.MOV_PKT_CODIGO_PEDIDO is 'Código do pedido de tíquete';
comment on column ifrsrh.MOVIMENTACAO.MOV_VALOR_INTEGRAL is 'Valor integral da rubrica calculada';
comment on column ifrsrh.MOVIMENTACAO.MOV_FUN_CODIGO is 'Código da Função exercida pelo Empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_DIAS_PROPORCIONALIDADE is 'Dias de proporcionalidade da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_NSA_CODIGO_NIVEL is 'Nível de salário do Empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_OEM_EMP_NUMERO_MATRICULA is 'Matrícula da ocorrência geradora da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_OEM_OFU_CODIGO is 'Código da ocorrência geradora da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_OEM_DATA_INICIO is 'Data de início da ocorrência geradora da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_DATA_CALCULO is 'Data de cálculo da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_PEM_BEN_SIGLA is 'Sigla do benefício gerador da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_TIPO_FUNCAO is 'Tipo de função exercida pelo empregado(RG;FG;DI)';
comment on column ifrsrh.MOVIMENTACAO.MOV_TIPO_PARAMETRO is 'Tipo de parâmetro de cálculo da rubrica';
comment on column ifrsrh.MOVIMENTACAO.MOV_IND_13 is 'Indicador de rubrica de 13º';
comment on column ifrsrh.MOVIMENTACAO.MOV_IND_ARSAPREV is 'Indicador de rubrica INFRAPREV';
comment on column ifrsrh.MOVIMENTACAO.MOV_IND_LANCAMENTO_LIQ_NEGAT is 'Indicador de rubrica candidata a líquido negativo';
comment on column ifrsrh.MOVIMENTACAO.MOV_NSA_CODIGO_PADRAO is 'Padrão de salário do Empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_NSA_INDICADOR_NIVEL_ESCOLA is 'Escolaridade de salário do empregado';
comment on column ifrsrh.MOVIMENTACAO.MOV_FLG_FREQUENCIA is 'Indicador de rubrica proviniente de frequencia';
comment on column ifrsrh.MOVIMENTACAO.COD_USUARIO is 'Código do Usuário responsável pela inclusão do registro';
comment on column ifrsrh.MOVIMENTACAO.DTA_OPERACAO is 'Data da operação (inclusão) do registro';
comment on column ifrsrh.MOV_SOMA_MENSAL.MOV_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.MOV_SOMA_MENSAL.MOV_MES_REFERENCIA is 'Mês de referência da movimentação';
comment on column ifrsrh.MOV_SOMA_MENSAL.MOV_ANO_REFERENCIA is 'Ano de referência da movimentação';
comment on column ifrsrh.MOV_SOMA_MENSAL.MOV_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.MOV_SOMA_MENSAL.MOV_TIP_RUBRICA is 'Tipo de rubrica(N-NORMAL;D-DIFERENÇA;E-ESTORNO)';
comment on column ifrsrh.MOV_SOMA_MENSAL.SOMA is 'Soma dos valores das rubricas';
comment on column ifrsrh.OPERANDOS.OPE_SIGLA is 'Sigla do operando';
comment on column ifrsrh.OPERANDOS.OPE_DESCRICAO is 'Descrição do operando';
comment on column ifrsrh.OPERANDOS.OPE_COMENTARIO is 'Comentário do operando';
comment on column ifrsrh.PREVISAO_PAGAMENTO.PPA_ANO_PAGAMENTO is 'Ano de previsão do pagamento da folha';
comment on column ifrsrh.PREVISAO_PAGAMENTO.PPA_MES_PAGAMENTO is 'Mês de previsão do pagamento da folha';
comment on column ifrsrh.PREVISAO_PAGAMENTO.PPA_DATA_PREVISTA is 'Data prevista para execução do evento';
comment on column ifrsrh.PREVISAO_PAGAMENTO.PPA_DATA_PAGAMENTO is 'Data efetiva de pagamento da folha';
comment on column ifrsrh.PREVISAO_PAGAMENTO.PPA_DIAS_UTEIS is 'Dias úteis do mês da folha';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_ANO_REFERENCIA is 'Ano de referência';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_MES_REFERENCIA is 'Mês de referência';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_VERSAO_PAGAMENTO is 'Versão de pagamento';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_MENSAGEM is 'Mensagem do erro apresentado';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_TIPO_AUDITORIA is 'Tipo de erro apresentado';
comment on column ifrsrh.REG_ERRO_MIGRACAO_FOLHA_RDB.REM_DATA_ERRO is 'Data de inclusão do erro';
comment on column ifrsrh.RUBRICAS.RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_DENOMINACAO is 'Descrição da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_EXCLU_RUBRICA is 'Indicador de rubrica de exclusão (S-SIM;N-NÃO)';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_RUBR_ATIVA is 'Indicador de rubrica ativa para o sistema';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_EXCLUSIVA is 'Indicador de rubrica exclusiva do Sistema(S-SIM;N-NÃO)';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_FORMULA is 'Indicador de rubrica com fórmula(S-SIM;N-NÃO)';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_FORMULA_VALOR is 'Indicador de rubrica com valor na fórmula';
comment on column ifrsrh.RUBRICAS.RUB_TIPO_RUBRICA is 'Tipo de rubrica (D-DESCONTO;R-RENDIMENTO)';
comment on column ifrsrh.RUBRICAS.RUB_SEQ_PAGAMENTO is 'Sequencia de pagamento da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_SEQ_EXCLU_RUBRICA is 'Sequencia de exclusão da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_CCO_CODIGO is 'Conta contábil da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_OBSERVACAO is 'Observação referente a rubrica';
comment on column ifrsrh.RUBRICAS.RUB_MES_CRIACAO is 'Mês de criação da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_ANO_CRIACAO is 'Ano de criação da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_MES_EXTINCAO is 'Mês de extinção da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_ANO_EXTINCAO is 'Ano de extinção da rubrica';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_PROPORCIONAL is 'Indicador de rubrica com proporcionalidade para a folha de pagamento';
comment on column ifrsrh.RUBRICAS.RUB_TIPO_PARAMETRO is 'Tipo de parâmetro da rubrica (D - Dias; H - Hora; P - Percentual; V - Valor)';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_BENEFICIO is 'Indicador de rubrica proviniente do Sistema de Benefício';
comment on column ifrsrh.RUBRICAS.COD_USUARIO is 'Código do Usuário responsável pela inclusão do registro';
comment on column ifrsrh.RUBRICAS.DTA_OPERACAO is 'Data da operação (inclusão) do registro';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_FIXO_VARIAVEL is 'Indicador de tipo da rubrica a ser considerada para cálculo do adicional proporcional (C - Cheio; F - Fixo; V - Variável; - N - Normal)';
comment on column ifrsrh.RUBRICAS.RUB_INDIC_RUB_ADICIONAL is 'Indicador de grupo em que a rubrica participa para cálculo do adicional proporcional (1 - Diária de Viagem; 2 - Gratificação de Instrutoria; 3 - Outros; 4 - Frequencia)';
comment on column ifrsrh.RUBRICAS_ANTERIORES.RUA_RUB_CODIGO is 'Código da rubrica';
comment on column ifrsrh.RUBRICAS_ANTERIORES.RUA_CODIGO_ANTERIOR is 'Código da rubrica anterior a nova';
comment on column ifrsrh.RUBRICA_TEMP.NUM_SEQUENCIA is 'Sequencial da tabela temporária';
comment on column ifrsrh.RUBRICA_TEMP.COD_RUBRICA is 'Código da rubrica';
comment on column ifrsrh.RUBRICA_TEMP.RUB_DENOMINACAO is 'Descrição da rubrica';
comment on column ifrsrh.RUBRICA_TEMP.RUB_CCO_CODIGO is 'Conta contábil da rubrica';
comment on column ifrsrh.TMP_CONTRACHEQUE_EMP.SEQUENCIA is 'Sequencial da tabela temporária';
comment on column ifrsrh.TMP_CONTRACHEQUE_EMP.EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.TMP_CONTRACHEQUE_EMP.CONTADOR is 'Contador para controle';
comment on column ifrsrh.TMP_FOLHA_EMPREGADOS.SEQUENCIA is 'Sequencial da tabela temporária';
comment on column ifrsrh.TMP_FOLHA_EMPREGADOS.EMP_NUMERO_MATRICULA is 'Matrícula do empregado';
comment on column ifrsrh.TMP_FOLHA_EMPREGADOS.CONTADOR is 'Contador para controle';
comment on column ifrsrh.TMP_FOLHA_EMPREGADOS.DATA_FREQUENCIA is 'Data de frequencia';


