COMMENT ON COLUMN LOG_ATUALIZA_UOR.ID IS 'Identificacao do log_atualiza_uor'
/
COMMENT ON COLUMN LOG_ATUALIZA_UOR.UOR_CODIGO IS 'Codigo da unidade organizacional'
/
COMMENT ON COLUMN LOG_ATUALIZA_UOR.UOR_NOME IS 'Nome da unidade organizacional'
/
COMMENT ON COLUMN LOG_ATUALIZA_UOR.DATA_ERRO IS 'Data do erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_UOR.DESCRICAO_ERRO IS 'Descricao do erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_UOR.ACAO IS 'Acao tomada'
/
