COMMENT ON COLUMN HISTORICO_FORNECEDOR.ID IS 'Identificacao do historico do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.ID_FORNECEDOR IS 'Identificacao do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.DT_ALTERACAO IS 'Data de alteracao do historico do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.ID_USUARIO IS 'Identificacao do usuario'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.NOME_USUARIO IS 'Nome do usuario'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.EMAIL_USUARIO IS 'Email do usuario'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.RAZAO_SOCIAL IS 'Nome da empresa fornecedora'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.CNPJ IS 'Cnpj do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.ENDERECO IS 'Endereco do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.CEP IS 'Cep do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.CIDADE IS 'Cidade do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.TELEFONE IS 'Telefone do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.FAX IS 'Fax do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.CONTATO IS 'Pessoa de contato com o fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.TEL_CONTATO IS 'Telefone de contado do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.FAX_CONTATO IS 'Fax de contado do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.EMAIL IS 'Email do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.SIGLA_UF IS 'Sigla da unidade da federacao'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.NOME_PAIS IS 'Nome do pais de origem do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.ESTADO_ESTRANGEIRO IS 'Nome do estado de origem do fornecedor se estrangeiro'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.CODIGO_ESTRANGEIRO IS 'Codigo estrangeiro do fornecedor'
/
COMMENT ON COLUMN HISTORICO_FORNECEDOR.OPERACAO IS 'Historico de alteracao e insercao da tabela fornecedor'
/
