COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.ID IS 'Identificacao do LOG_ATUALIZA_DEPENDENCIAS'
/
COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.DEP_CODIGO IS 'Codigo do departamento'
/
COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.DEP_NOME IS 'Nome do departamento'
/
COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.DATA_ERRO IS 'Data em que ocorreu o erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.DESCRICAO_ERRO IS 'Descricao do erro'
/
COMMENT ON COLUMN LOG_ATUALIZA_DEPENDENCIAS.ACAO IS 'Acao tomada'
/
