GRANT SELECT ON RESUMO_ENCARGOS_INSS TO SRH_SFP_04;
GRANT SELECT ON RESUMO_ENCARGOS_SAL_EDUCACAO TO SRH_SFP_04;
GRANT SELECT ON RESUMO_ENCARGOS_INFRAPREV TO SRH_SFP_04;
GRANT SELECT ON CRONOGRAMAS_PAGAMENTOS  TO SRH_SFP_04;
GRANT SELECT ON DEPENDENCIAS TO SRH_SFP_04;
GRANT SELECT ON EMPREGADOS_PAGAMENTOS TO SRH_SFP_04;
GRANT SELECT ON CADASTROS TO SRH_SFP_04;
GRANT SELECT ON OCORRENCIAS_EMPREGADOS TO SRH_SFP_04;
GRANT SELECT ON MOVIMENTACAO TO SRH_SFP_04;
GRANT SELECT ON RUBRICAS TO SRH_SFP_04;
GRANT SELECT ON INCIDENCIAS_RUBRICAS TO SRH_SFP_04;

GRANT INSERT, DELETE, UPDATE, SELECT ON PAGAMENTO_TEMP  TO SRH_SFP_04;
GRANT INSERT, DELETE, UPDATE, SELECT ON TMP_CONTABILIDADE_RELATORIOS TO SRH_SFP_04;

