CREATE TABLE OCORRENCIAS_PIS_PASEP (
    NOME_ARQUIVO                VARCHAR2(20)
,   CODIDO_OCORRENCIA           NUMBER(3)
,   TIPO_OCORRENCIA             CHAR(1)
,   DESCRICAO_OCORRENCIA        VARCHAR2(200)
)
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP.NOME_ARQUIVO IS 'Nome do arquivo fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP.CODIDO_OCORRENCIA IS 'Código da ocorrência fornecido pelo Banco do Brasil.'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP.TIPO_OCORRENCIA IS 'Tipo da ocorrência fornecido pelo Banco do Brasil. Ex: Se ocorrência de header, detalhe, trailler, etc'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP.DESCRICAO_OCORRENCIA IS 'Descrição da ocorrência fornecido pelo Banco do Brasil.'
/

ALTER TABLE OCORRENCIAS_PIS_PASEP
ADD CONSTRAINT OPP_PK PRIMARY KEY (NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
USING INDEX
TABLESPACE TS_INDICE
/ 

CREATE TABLE OCORRENCIAS_PIS_PASEP_ARQUIVO (
    DATA_PROCESSAMENTO                      DATE
,   SEQUENCIAL_ARQUIVO                      NUMBER(6)
,   NOME_ARQUIVO                            VARCHAR2(20)
,   CODIDO_OCORRENCIA                       NUMBER(3)
,   TIPO_OCORRENCIA                         CHAR(1)
,   INDICADOR_PROCESSAMENTO                 NUMBER(1)   
,   NR_ULTIMA_REMESSA                       NUMBER(6)   
,   NR_REMESSA                              NUMBER(6)   
,   FORMA_REPASSE                           NUMBER(1)   
,   DATA_LANCAMENTO_CREDITO                 DATE        
,   DATA_LANCAMENTO_DEBITO                  DATE        
,   AGENCIA_LANCAMENTO                      NUMBER(4)   
,   CONTA_CORRENTE_LANCAMENTO               NUMBER(11)  
,   CODIGO_CONTA_TESOURO_NACIONAL           NUMBER(14)  
,   DATA_CADASTRO                           DATE        
,   QTDADE_REG_VERIFICADOS                  NUMBER(6)   
,   QTDADE_REG_VALIDOS                      NUMBER(6)   
,   QTDADE_PARTICIPANTES_ARQ900             NUMBER(6)   
,   QTDADE_PARTIC_PAGOS                     NUMBER(6)   
,   QTDADE_PARTIC_REJEITADOS                NUMBER(6)   
,   VALOR_LANCAMENTO                        NUMBER(11,2)
,   QTDADE_REG_VERIFICADA_ARQ900            NUMBER(6)   
,   QTDADE_CANCEL_ACEITOS                   NUMBER(6)   
,   QTDADE_CANCEL_REJEITADOS                NUMBER(6)   
,   QTDADE_REG_TIPO2                        NUMBER(6)   
)
/
   
COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.DATA_PROCESSAMENTO IS 'Data do processamento fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.SEQUENCIAL_ARQUIVO IS 'Sequencial do arquivo fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.NOME_ARQUIVO IS 'Nome do arquivo fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.CODIDO_OCORRENCIA IS 'Código da ocorrência fornecido pelo Banco do Brasil'
/   

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.TIPO_OCORRENCIA IS 'Tipo da ocorrência fornecido pelo Banco do Brasil.Ex: Se ocorrência de header, detalhe, trailler, etc'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.INDICADOR_PROCESSAMENTO IS 'Campo que indica se o arquivo foi recusado ou processado com sucesso'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.NR_ULTIMA_REMESSA IS 'Indica o número da última remessa processada com sucesso'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.NR_REMESSA IS 'Número da remessa do arquivo 900'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.FORMA_REPASSE IS 'Código da forma escolhida para repasse do crédito'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.DATA_LANCAMENTO_CREDITO IS 'Data do lançamento do crédito'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.DATA_LANCAMENTO_DEBITO IS 'Data do lançamento do débito'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.AGENCIA_LANCAMENTO IS 'Agência de lançamento do débito'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.CONTA_CORRENTE_LANCAMENTO IS 'Conta corrente do lançamento do débito'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.CODIGO_CONTA_TESOURO_NACIONAL IS 'Código da conta única no Tesouro Nacional'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.DATA_CADASTRO IS 'Data do cadastro do arquivo na base Gestorh'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_REG_VERIFICADOS IS 'Quantidade de verificados de registros'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_REG_VALIDOS IS 'Quantidade de registros(tipo 2) válidos no arquivo'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_PARTICIPANTES_ARQ900 IS 'Quantidade de participantes do arquivo900 '
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_PARTIC_PAGOS IS 'Quantidade de registros(tipo 2) válidos no arquivo'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.CODIGO_CONTA_TESOURO_NACIONAL IS 'Soma dos registros rejeitados nos dois processamentos (prévio e definitivo)'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.DATA_CADASTRO IS 'Soma dos valores individuais dos registros'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_REG_VERIFICADOS IS 'Quantidade de participantes enviados para processamento'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_REG_VALIDOS IS 'Quantidade de registros aceitos no processamento definitivo'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_PARTICIPANTES_ARQ900 IS 'Soma dos registros rejeitados nos dois processamentos (prévio e definitivo)'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_ARQUIVO.QTDADE_PARTIC_PAGOS IS 'Quantidade de registros tipo2 válidos'
/

ALTER TABLE OCORRENCIAS_PIS_PASEP_ARQUIVO
ADD CONSTRAINT OPPA_PK PRIMARY KEY (DATA_PROCESSAMENTO,SEQUENCIAL_ARQUIVO,NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
USING INDEX
TABLESPACE TS_INDICE
/    
   
ALTER TABLE OCORRENCIAS_PIS_PASEP_ARQUIVO
ADD CONSTRAINT OPPA_OPP_FK FOREIGN KEY (NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
      REFERENCES OCORRENCIAS_PIS_PASEP (NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
/


CREATE TABLE OCORRENCIAS_PIS_PASEP_EMP (
    MATRICULA                                NUMBER(7)
,   DATA_PROCESAMENTO                        DATE  
,   SEQUENCIAL_ARQUIVO                       NUMBER(6)      NOT NULL
,   NOME_ARQUIVO                             VARCHAR2(20)
,   CODIDO_OCORRENCIA                        NUMBER(3)
,   TIPO_OCORRENCIA                          CHAR(1)
,   SEQUENCIAL_PARTICIPANTE                  NUMBER(6)      NOT NULL
,   NR_PIS_ATIVA                             NUMBER(11)   
,   NR_ORIGINAL_REMANESCENTE                 NUMBER(11)   
,   NOME_EMPREGADO_PASEP                     VARCHAR2(100)
,   INDICADOR_PROCESSAMENTO                  NUMBER(1)    
,   VALOR                                    NUMBER(9,2)  
,   CNPJ_ENT_PAGADORA                        NUMBER(14)   
,   DATA_PAGAMENTO                           DATE
,   DATA_CADASTRO                            DATE
)
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.MATRICULA IS 'Matricula do empregado'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.DATA_PROCESAMENTO IS 'Data do processamento fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.SEQUENCIAL_ARQUIVO IS 'Sequencial do arquivo fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.NOME_ARQUIVO IS 'Data do processamento fornecido pelo Banco do Brasil'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.CODIDO_OCORRENCIA IS 'Código da ocorrência fornecido pelo Banco do Brasil.'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.TIPO_OCORRENCIA IS 'Tipo da ocorrência fornecido pelo Banco do Brasil.Ex: Se ocorrência de header, detalhe, trailler, etc'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.SEQUENCIAL_PARTICIPANTE IS 'Sequencial do empregado no arquivo fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.NR_PIS_ATIVA IS 'Número do PIS ativo'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.NR_ORIGINAL_REMANESCENTE IS 'Número do PIS original ou remanescente'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.NOME_EMPREGADO_PASEP IS 'Nome do empregado cadastrado no PASEP'
/   

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.INDICADOR_PROCESSAMENTO IS 'Indicador de processamento fornecido pelo Banco do Brasil'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.VALOR IS 'Valor que o empregado faz jus'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.CNPJ_ENT_PAGADORA IS 'CNPJ da entidade que fez o pagamento do PIS, no caso do empregado já tenha sido pago'
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.DATA_PAGAMENTO IS 'Data em que o pagamento foi efetuado, caso o empregado já tenha sido pago por outra entidade'
/     

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP_EMP.DATA_CADASTRO IS 'Data do cadastro do arquivo na base Gestorh'
/   

ALTER TABLE OCORRENCIAS_PIS_PASEP_EMP
ADD CONSTRAINT OPPE_PK PRIMARY KEY (MATRICULA,DATA_PROCESAMENTO,NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
USING INDEX
TABLESPACE TS_INDICE
/    
   
ALTER TABLE OCORRENCIAS_PIS_PASEP_EMP
ADD CONSTRAINT OPPE_OPP_FK FOREIGN KEY (NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
      REFERENCES OCORRENCIAS_PIS_PASEP (NOME_ARQUIVO,CODIDO_OCORRENCIA,TIPO_OCORRENCIA)
/
 
GRANT SELECT ON OCORRENCIAS_PIS_PASEP TO SRH_SFP_03, SRH_SFP_04
/

GRANT SELECT,DELETE,INSERT, UPDATE ON OCORRENCIAS_PIS_PASEP TO RH_PERFIL_99, SRH_SFP_01
/

GRANT SELECT ON OCORRENCIAS_PIS_PASEP_ARQUIVO TO SRH_SFP_03, SRH_SFP_04
/

GRANT SELECT,DELETE,INSERT, UPDATE ON OCORRENCIAS_PIS_PASEP_ARQUIVO TO RH_PERFIL_99, SRH_SFP_01
/

GRANT SELECT ON OCORRENCIAS_PIS_PASEP_EMP TO SRH_SFP_03, SRH_SFP_04
/

GRANT SELECT,DELETE,INSERT, UPDATE ON OCORRENCIAS_PIS_PASEP_EMP TO RH_PERFIL_99, SRH_SFP_01
/

CREATE PUBLIC SYNONYM OCORRENCIAS_PIS_PASEP FOR IFRSRH.OCORRENCIAS_PIS_PASEP
/

CREATE PUBLIC SYNONYM OCORRENCIAS_PIS_PASEP_ARQUIVO FOR IFRSRH.OCORRENCIAS_PIS_PASEP_ARQUIVO
/

CREATE PUBLIC SYNONYM OCORRENCIAS_PIS_PASEP_EMP FOR IFRSRH.OCORRENCIAS_PIS_PASEP_EMP
/

INSERT INTO TABELAS VALUES ('SRHSFP', 'OCORRENCIAS_PIS_PASEP', 'IFRSRH', 'TABELA')
/

INSERT INTO TABELAS VALUES ('SRHSFP', 'OCORRENCIAS_PIS_PASEP_ARQUIVO', 'IFRSRH', 'TABELA')
/

INSERT INTO TABELAS VALUES ('SRHSFP', 'OCORRENCIAS_PIS_PASEP_EMP', 'IFRSRH', 'TABELA')
/       

--****************************************************************************************

ALTER TABLE OCORRENCIAS_PIS_PASEP
ADD POSICAO_OCORRENCIA NUMBER(3)  NULL
/

COMMENT ON COLUMN OCORRENCIAS_PIS_PASEP.POSICAO_OCORRENCIA IS 'Posição do código da ocorrência no arquivo enviado pelo BB.'
/   

ALTER TABLE OCORRENCIAS_PIS_PASEP
MODIFY POSICAO_OCORRENCIA NUMBER(3) NOT NULL
/
