CREATE TABLE PESSOAL_SEM_VINCULO (
    	PSV_SEQUENCIAL                	NUMBER(7) 
,	PSV_NOME_USUARIO           	VARCHAR2(60)  NOT NULL 
,	PSV_VIP_COD_VINCULO       	NUMBER(2)   
,	PSV_LOA_CODIGO                 	NUMBER(3)
,	PSV_NOME_PAI                    VARCHAR2(60)
,	PSV_NOME_MAE                  	VARCHAR2(60)
,	PSV_DATA_NASCIMENTO           	DATE
,	PSV_ESTADO_CIVIL                VARCHAR2(1)
,	PSV_PLA_COD_PLANO           	NUMBER(3)
,	PSV_SEXO       			VARCHAR2(1)
,	PSV_CRE_SEQUENCIAL         	NUMBER(5)
,	PSV_TIPO_PAGAMENTO      	VARCHAR2(1)
,	PSV_NUMERO_CPF        		NUMBER(11)
,	PSV_NUMERO_IDENTIDADE     	VARCHAR2(15)
,	PSV_ORGAO_EXPEDIDOR_CI     	VARCHAR2(10)
,	PSV_DATA_EXPEDICAO            	DATE
,	PSV_UFE_SIGLA_CI          	VARCHAR2(2)
)
/


ALTER TABLE PESSOAL_SEM_VINCULO
ADD CONSTRAINT PSV_PK PRIMARY KEY (PSV_SEQUENCIAL)
USING INDEX
TABLESPACE TS_INDICE
/ 

GRANT SELECT,DELETE,INSERT, UPDATE ON PESSOAL_SEM_VINCULO TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM PESSOAL_SEM_VINCULO FOR IFRSRH.PESSOAL_SEM_VINCULO
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'PESSOAL_SEM_VINCULO', 'IFRSRH', 'TABELA')
/


--****************************************************************************************

CREATE TABLE COBRANCA_PSV(
	CSV_PSV_SEQUENCIAL              NUMBER(7) 
,	CSV_ANO_REFERENCIA              NUMBER(4)
,	CSV_MES_REFERENCIA              NUMBER(2)
,	CSV_CRE_SEQUENCIAL        	NUMBER(5)
,	CSV_NUMERO      		NUMBER(10)  NOT NULL 
,	CSV_PSV_VALOR             	NUMBER(12,2)
,	CSV_PSV_COD_PLANO     		NUMBER(3)
,	CSV_EMP_DEP_FISICO      	NUMBER(4) NOT NULL
,	CSV_EMP_DEP_LOTACAO      	NUMBER(4) NOT NULL
,	CSV_EMP_ATI_CT_CUSTOS   	NUMBER(10)
,	CSV_ANO_PAGAMENTO               NUMBER(4)
,	CSV_MES_PAGAMENTO               NUMBER(2)
,	CSV_DESCONTO_FOLHA      	VARCHAR2(1) CONSTRAINT CK_CSV_1 CHECK (CSV_DESCONTO_FOLHA IN ('S', 'N'))
,	CSV_PSV_TIPO_PAGAMENTO   	VARCHAR2(1) 
,	CSV_OBSERVACAO                  VARCHAR2(200)
)
/

ALTER TABLE COBRANCA_PSV
ADD CONSTRAINT CSV_PK PRIMARY KEY (CSV_PSV_SEQUENCIAL, CSV_ANO_REFERENCIA, CSV_MES_REFERENCIA)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE COBRANCA_PSV
ADD CONSTRAINT CSV_PSV_FK FOREIGN KEY (CSV_PSV_SEQUENCIAL)
      REFERENCES PESSOAL_SEM_VINCULO (PSV_SEQUENCIAL)
/

ALTER TABLE COBRANCA_PSV
ADD CONSTRAINT CSV_CRE_FK FOREIGN KEY (CSV_CRE_SEQUENCIAL)
      REFERENCES CREDENCIADOS (CRE_SEQUENCIAL)
/ 

GRANT SELECT,DELETE,INSERT, UPDATE ON COBRANCA_PSV TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM COBRANCA_PSV FOR IFRSRH.COBRANCA_PSV
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'COBRANCA_PSV', 'IFRSRH', 'TABELA')
/


--****************************************************************************************

CREATE TABLE RESPONSAVEL_FINANCEIRO(
	RFI_SEQUENCIAL                	NUMBER(7) 
,	RFI_NUMERO_CPF        		NUMBER(11)
,	RFI_NUMERO_IDENTIDADE     	VARCHAR2(15)
,	RFI_ORGAO_EXPEDIDOR_CI     	VARCHAR2(10)
,	RFI_DATA_EXPEDICAO 		DATE
,	RFI_UFE_SIGLA_CI 		VARCHAR2(2)
,	RFI_NOME     			VARCHAR2(60)
,	RFI_ENDERECO    		VARCHAR2(50)
,	RFI_BAIRRO     			VARCHAR2(20)
,	RFI_CEP    			NUMBER(8)
,	RFI_CIDADE    			NUMBER(5)
,	RFI_UFE_SIGLA          		VARCHAR2(2)
,	RFI_FONE_COMERCIAL    		NUMBER(12)
,	RFI_FONE_RESIDENCIA          	NUMBER(12)
,	RFI_FONE_CELULAR      		NUMBER(12)
)
/

ALTER TABLE RESPONSAVEL_FINANCEIRO
ADD CONSTRAINT RFI_PK PRIMARY KEY (RFI_SEQUENCIAL)
USING INDEX
TABLESPACE TS_INDICE
/ 

GRANT SELECT,DELETE,INSERT, UPDATE ON RESPONSAVEL_FINANCEIRO TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM RESPONSAVEL_FINANCEIRO FOR IFRSRH.RESPONSAVEL_FINANCEIRO
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'RESPONSAVEL_FINANCEIRO', 'IFRSRH', 'TABELA')
/


--****************************************************************************************

CREATE TABLE EMPREGADOS_PESSOAL_SEM_VINCULO(
	EPV_EMP_NUMERO_MATRICULA        NUMBER(7)
,	EPV_PSV_SEQUENCIAL          	NUMBER(5)
,	EPV_DATA_INICIO      		DATE
,	EPV_DATA_TERMINO      		DATE
)
/

ALTER TABLE EMPREGADOS_PESSOAL_SEM_VINCULO
ADD CONSTRAINT EPV_PK PRIMARY KEY (EPV_EMP_NUMERO_MATRICULA,EPV_PSV_SEQUENCIAL,EPV_DATA_INICIO)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE EMPREGADOS_PESSOAL_SEM_VINCULO
ADD CONSTRAINT EPV_EMP_FK FOREIGN KEY (EPV_EMP_NUMERO_MATRICULA)
      REFERENCES CADASTROS (EMP_NUMERO_MATRICULA)
/
ALTER TABLE EMPREGADOS_PESSOAL_SEM_VINCULO
ADD CONSTRAINT EPV_PSV_FK FOREIGN KEY (EPV_PSV_SEQUENCIAL)
      REFERENCES PESSOAL_SEM_VINCULO (PSV_SEQUENCIAL)
/

GRANT SELECT,DELETE,INSERT, UPDATE ON EMPREGADOS_PESSOAL_SEM_VINCULO TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM EMPREGADOS_PESSOAL_SEM_VINCULO FOR IFRSRH.EMPREGADOS_PESSOAL_SEM_VINCULO
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'EMPREGADOS_PESSOAL_SEM_VINCULO', 'IFRSRH', 'TABELA')
/


--****************************************************************************************
CREATE TABLE RESP_FINANCEIRO_PSV(
	RFP_ANO_REFERENCIA       	NUMBER(4)
,	RFP_MÊS_REFERENCIA        	NUMBER(2)
,	RFP_PSV_SEQUENCIAL        	NUMBER(7)
,	RFP_RFI_SEQUENCIAL              NUMBER(7)
)
/

ALTER TABLE RESP_FINANCEIRO_PSV
ADD CONSTRAINT RFP_PK PRIMARY KEY (RFP_ANO_REFERENCIA,RFP_MÊS_REFERENCIA,RFP_PSV_SEQUENCIAL,RFP_RFI_SEQUENCIAL)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE RESP_FINANCEIRO_PSV
ADD CONSTRAINT RFP_PSV_FK FOREIGN KEY (RFP_PSV_SEQUENCIAL)
      REFERENCES PESSOAL_SEM_VINCULO (PSV_SEQUENCIAL)
/
ALTER TABLE RESP_FINANCEIRO_PSV
ADD CONSTRAINT RFP_RFI_FK FOREIGN KEY (RFP_RFI_SEQUENCIAL)
      REFERENCES RESPONSAVEL_FINANCEIRO (RFI_SEQUENCIAL)
/

GRANT SELECT,DELETE,INSERT, UPDATE ON RESP_FINANCEIRO_PSV TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM RESP_FINANCEIRO_PSV FOR IFRSRH.RESP_FINANCEIRO_PSV
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'RESP_FINANCEIRO_PSV', 'IFRSRH', 'TABELA')
/


--****************************************************************************************
CREATE TABLE PLANOS_MEDICOS(
	PLA_CRE_SEQUENCIAL              NUMBER(5)
,	PLA_COD_PLANO        		NUMBER(4)
,	PLA_DATA_INICIO       		DATE     
,	PLA_DESCRICAO       		VARCHAR2(60)
,	PLA_VALOR_MENSALIDADE    	NUMBER(10,2)
,	PLA_REAJUSTE      		NUMBER(6,2)
,	PLA_DATA_REAJUSTE     		DATE
,	PLA_DESCONTO     		NUMBER(3)
,	PLA_OBSERVAÇÃO    		VARCHAR2(200)
,	PLA_FAIXA_ETARIA_INICIAL    	NUMBER(2)
,	PLA_FAIXA_ETARIA_FINAL        	NUMBER(2)
,	PLA_DATA_TERMINO       		DATE
)
/

ALTER TABLE PLANOS_MEDICOS
ADD CONSTRAINT PLA_PK PRIMARY KEY (PLA_CRE_SEQUENCIAL,PLA_COD_PLANO,PLA_DATA_INICIO)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE PLANOS_MEDICOS
ADD CONSTRAINT PLA_CRE_FK FOREIGN KEY (PLA_CRE_SEQUENCIAL)
      REFERENCES CREDENCIADOS (CRE_SEQUENCIAL)
/

GRANT SELECT,DELETE,INSERT, UPDATE ON PLANOS_MEDICOS TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM PLANOS_MEDICOS FOR IFRSRH.PLANOS_MEDICOS
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'PLANOS_MEDICOS', 'IFRSRH', 'TABELA')
/


--****************************************************************************************

CREATE TABLE VINCULO_PRESTADORA(
	VIP_CRE_SEQUENCIAL             	NUMBER(5)
,	VIP_COD_VINCULO        		NUMBER(2)
,	VIP_COD_DESCRICAO   		VARCHAR2(60)
)
/

ALTER TABLE VINCULO_PRESTADORA
ADD CONSTRAINT VIP_PK PRIMARY KEY (VIP_CRE_SEQUENCIAL,VIP_COD_VINCULO)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE VINCULO_PRESTADORA
ADD CONSTRAINT VIP_CRE_FK FOREIGN KEY (VIP_CRE_SEQUENCIAL)
      REFERENCES CREDENCIADOS (CRE_SEQUENCIAL)
/

GRANT SELECT,DELETE,INSERT, UPDATE ON VINCULO_PRESTADORA TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM VINCULO_PRESTADORA FOR IFRSRH.VINCULO_PRESTADORA
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'VINCULO_PRESTADORA', 'IFRSRH', 'TABELA')
/


--****************************************************************************************
CREATE TABLE LOCAL_ATENDIMENTO(
	LOA_CRE_SEQUENCIAL        	NUMBER(5)
,	LOA_CODIGO        		NUMBER(3)
,	LOA_CIDADE       		VARCHAR2(50)
,	LOA_UFE    	 		VARCHAR2(2)
,	LOA_DEP_CODIGO    		NUMBER(4)
)
/

ALTER TABLE LOCAL_ATENDIMENTO
ADD CONSTRAINT LOA_PK PRIMARY KEY (LOA_CRE_SEQUENCIAL,LOA_CODIGO)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE LOCAL_ATENDIMENTO
ADD CONSTRAINT LOA_CRE_FK FOREIGN KEY (LOA_CRE_SEQUENCIAL)
      REFERENCES CREDENCIADOS (CRE_SEQUENCIAL)
/

GRANT SELECT,DELETE,INSERT, UPDATE ON LOCAL_ATENDIMENTO TO RH_PERFIL_99
/


CREATE PUBLIC SYNONYM LOCAL_ATENDIMENTO FOR IFRSRH.LOCAL_ATENDIMENTO
/


INSERT INTO TABELAS VALUES ('SRHBEN', 'LOCAL_ATENDIMENTO', 'IFRSRH', 'TABELA')
/


--****************************************************************************************