alter table PLANOS_MEDICOS
modify PLA_FAIXA_ETARIA_INICIAL number(3);

alter table PLANOS_MEDICOS
modify PLA_FAIXA_ETARIA_FINAL  number(3);

alter table local_atendimento
drop constraint LOA_PK;

ALTER TABLE local_atendimento
ADD CONSTRAINT LOA_PK PRIMARY KEY (LOA_CRE_SEQUENCIAL, LOA_CODIGO, LOA_DEP_CODIGO)
USING INDEX
TABLESPACE TS_INDICE
/ 

ALTER TABLE local_atendimento
ADD CONSTRAINT LOA_DEP_FK FOREIGN KEY (LOA_DEP_CODIGO)
      REFERENCES DEPENDENCIAS (DEP_CODIGO)
/ 
