CREATE TABLE AGRUPAMENTO_RECEITA (
	COD_AGRUPAMENTO		NUMBER(4)
,	DSC_AGRUPAMENTO		VARCHAR2(50)	NOT NULL	
,	IND_TIPO		NUMBER(1)	NOT NULL
,	COD_AGRUP_RELAC		NUMBER(4)
)
/

ALTER TABLE AGRUPAMENTO_RECEITA
 ADD CONSTRAINT PK_AGRUP_REC PRIMARY KEY (COD_AGRUPAMENTO)
/

ALTER TABLE AGRUPAMENTO_RECEITA
  ADD CONSTRAINT CK_AGRUP_REC CHECK (IND_TIPO IN (1, 2, 3))
/

ALTER TABLE AGRUPAMENTO_RECEITA
      ADD CONSTRAINT FK_AGR_R_2_AGR_R FOREIGN KEY (COD_AGRUP_RELAC) REFERENCES AGRUPAMENTO_RECEITA(COD_AGRUPAMENTO)
/

CREATE TABLE ESTRUTURA_RECEITA(
	NRO_CONTA_CONTABIL	VARCHAR2(20)
,	COD_AGRUPAMENTO		NUMBER(4)
)
/

ALTER TABLE ESTRUTURA_RECEITA
 ADD CONSTRAINT PK_ESTRUT_REC PRIMARY KEY (NRO_CONTA_CONTABIL, COD_AGRUPAMENTO)
/

ALTER TABLE ESTRUTURA_RECEITA
      ADD CONSTRAINT FK_AGR_R_2_CNT_C FOREIGN KEY (NRO_CONTA_CONTABIL) REFERENCES CONTA_CONTABIL(NR_CONTA)
/

ALTER TABLE ESTRUTURA_RECEITA
      ADD CONSTRAINT FK_AGR_R_2_EST_R FOREIGN KEY (COD_AGRUPAMENTO) REFERENCES AGRUPAMENTO_RECEITA(COD_AGRUPAMENTO)
/

INSERT INTO TABELAS VALUES(
'SICOF', 'ESTRUTURA_RECEITA', 'IFRDBA2', 'TABELA');

INSERT INTO TABELAS VALUES(
'SICOF', 'AGRUPAMENTO_RECEITA', 'IFRDBA2', 'TABELA');

CREATE PUBLIC SYNONYM ESTRUTURA_RECEITA FOR IFRDBA2.ESTRUTURA_RECEITA;

CREATE PUBLIC SYNONYM AGRUPAMENTO_RECEITA FOR IFRDBA2.AGRUPAMENTO_RECEITA;


GRANT SELECT, INSERT, DELETE, UPDATE ON ESTRUTURA_RECEITA TO ORC_GER_ORC;
GRANT SELECT, INSERT, DELETE, UPDATE ON ESTRUTURA_RECEITA TO ORC_GER_ORC_SEDE;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_AUDITOR;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_DFOT2;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_EMP_DFOT1;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_EMP_DFOT12;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_EMP_DFOT2;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_GER_GERAL;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_GER_USR;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_RESP_DEP;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_SUP;
GRANT SELECT ON ESTRUTURA_RECEITA TO ORC_USR;

GRANT SELECT, INSERT, DELETE, UPDATE ON AGRUPAMENTO_RECEITA TO ORC_GER_ORC;
GRANT SELECT, INSERT, DELETE, UPDATE ON AGRUPAMENTO_RECEITA TO ORC_GER_ORC_SEDE;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_AUDITOR;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_DFOT2;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_EMP_DFOT1;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_EMP_DFOT12;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_EMP_DFOT2;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_GER_GERAL;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_GER_USR;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_RESP_DEP;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_SUP;
GRANT SELECT ON AGRUPAMENTO_RECEITA TO ORC_USR;
