CREATE TABLE TIPOS_CREDENCIADOS (
    TPC_CODIGO                  NUMBER(02)
,   TPC_DESCRICAO_TIPO          VARCHAR2(40)  NOT NULL
)
/

COMMENT ON table TIPOS_CREDENCIADOS IS 'Tabela para receber os tipos de credenciados '
/

COMMENT ON COLUMN TIPOS_CREDENCIADOS.TPC_CODIGO IS 'Código do tipo'
/

COMMENT ON COLUMN TIPOS_CREDENCIADOS.TPC_DESCRICAO_TIPO IS 'Nome da descrição do tipo'
/


ALTER TABLE TIPOS_CREDENCIADOS
ADD CONSTRAINT TPC_PK PRIMARY KEY (TPC_CODIGO)
USING INDEX
TABLESPACE TS_INDICE
/ 

grant SELECT,DELETE,INSERT, UPDATE ON TIPOS_CREDENCIADOS TO RH_PERFIL_994;

CREATE PUBLIC SYNONYMTIPOS_CREDENCIADOSS FOR IFRSRHTIPOS_CREDENCIADOSS
/

INSERT INTO TABELAS VALUES ('SRHSFP', TIPOS_CREDENCIADOS', 'IFRSRH', 'TABELA')
/