SET SCAN OFF
CREATE OR REPLACE PACKAGE PCK_CONSULTA_NAO_INERENTES AS 
   TYPE TNAO_INERENTES IS RECORD (
        DEP_SIGLA DEPENDENCIAS.DEP_SIGLA%TYPE,
        UOR_SIGLA UNIDADES_ORGANIZACIONAIS.UOR_SIGLA%TYPE,
	EMP_NUMERO_MATRICULA CADASTROS.EMP_NUMERO_MATRICULA%TYPE,
        EMP_NOME_ABREVIADO CADASTROS.EMP_NOME_ABREVIADO%TYPE,
	CAR_NOME CARGOS.CAR_NOME%TYPE,
	OCC_DESCRICAO OCUPACOES_CARGO.OCC_DESCRICAO%TYPE,
	EMP_DEP_CODIGO_LOTACAO CADASTROS.EMP_DEP_CODIGO_LOTACAO%TYPE, 
	DEP_DEP_CODIGO DEPENDENCIAS.DEP_DEP_CODIGO%TYPE,
	EMP_QLP_CAR_CODIGO CADASTROS.EMP_QLP_CAR_CODIGO%TYPE,
        EMP_QLP_CAR_OCC_CODIGO CADASTROS.EMP_QLP_CAR_OCC_CODIGO%TYPE,
        TOTAL NUMBER);
    
   TYPE TDADOS IS REF CURSOR RETURN TNAO_INERENTES;

   PROCEDURE PRC_NAO_INERENTES(TAB IN OUT TDADOS, IDEP_DEP_CODIGO IN NUMBER := NULL, 
                                            IDEP_CODIGO IN NUMBER := NULL, 
                                            IUOR_CODIGO IN NUMBER := NULL,
					    IMATRICULA  IN NUMBER := NULL);
END;
/
CREATE OR REPLACE PACKAGE BODY PCK_CONSULTA_NAO_INERENTES AS 
   
   PROCEDURE PRC_NAO_INERENTES(TAB IN OUT TDADOS, IDEP_DEP_CODIGO IN NUMBER := NULL, 
                                            IDEP_CODIGO IN NUMBER := NULL, 
                                            IUOR_CODIGO IN NUMBER := NULL,					    
					    IMATRICULA  IN NUMBER := NULL) IS 
   BEGIN
     IF IMATRICULA IS NOT NULL THEN           
        OPEN TAB FOR
           SELECT S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NUMERO_MATRICULA, S.EMP_NOME_ABREVIADO,
	          S.CAR_NOME, S.OCC_DESCRICAO, S.EMP_DEP_CODIGO_LOTACAO, S.DEP_DEP_CODIGO,
		  S.EMP_QLP_CAR_CODIGO, S.EMP_QLP_CAR_OCC_CODIGO,
                  (
                    SELECT COUNT(AEM_ATI_CODIGO) 
                    FROM ATIVIDADES_EMPREGADOS
                    WHERE AEM_EMP_NUMERO_MATRICULA = S.EMP_NUMERO_MATRICULA AND
                          AEM_DATA_CONFIRMA_NAO_INERENTE IS NOT NULL AND
			  AEM_IND_ATI_INERENTE = 'N'
                  ) AS TOTAL
           FROM EMPREGADOS_SUBORDINADOS S
           WHERE EXISTS
		(SELECT DISTINCT (A.AEM_EMP_NUMERO_MATRICULA)
		FROM ATIVIDADES_EMPREGADOS A
		WHERE  A.AEM_IND_ATI_INERENTE = 'N' AND
		       A.AEM_DATA_CONFIRMA_NAO_INERENTE IS NULL AND
		       S.EMP_NUMERO_MATRICULA = A.AEM_EMP_NUMERO_MATRICULA) AND
		S.EMP_NUMERO_MATRICULA = IMATRICULA				
           ORDER BY S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NOME_ABREVIADO; 
	   
     ELSIF (IDEP_DEP_CODIGO IS NOT NULL AND IDEP_CODIGO IS NULL AND IUOR_CODIGO IS NULL) THEN	 	  	 	        
        OPEN TAB FOR
           SELECT S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NUMERO_MATRICULA, S.EMP_NOME_ABREVIADO,
	          S.CAR_NOME, S.OCC_DESCRICAO, S.EMP_DEP_CODIGO_LOTACAO, S.DEP_DEP_CODIGO,
		  S.EMP_QLP_CAR_CODIGO, S.EMP_QLP_CAR_OCC_CODIGO,
                  (
                    SELECT COUNT(AEM_ATI_CODIGO) 
                    FROM ATIVIDADES_EMPREGADOS
                    WHERE AEM_EMP_NUMERO_MATRICULA = S.EMP_NUMERO_MATRICULA AND
                          AEM_DATA_CONFIRMA_NAO_INERENTE IS NOT NULL AND
			  AEM_IND_ATI_INERENTE = 'N'
                  ) AS TOTAL
           FROM EMPREGADOS_SUBORDINADOS S
           WHERE EXISTS
		(SELECT DISTINCT (A.AEM_EMP_NUMERO_MATRICULA)
		FROM ATIVIDADES_EMPREGADOS A
		WHERE  A.AEM_IND_ATI_INERENTE = 'N' AND
		       A.AEM_DATA_CONFIRMA_NAO_INERENTE IS NULL AND
		       S.EMP_NUMERO_MATRICULA = A.AEM_EMP_NUMERO_MATRICULA) AND
		       ((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
		         (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO)) AND
		       EXISTS
                           (SELECT DEP_CODIGO
	 	            FROM DEPENDENCIAS
	 	            WHERE DEP_DATA_EXTINCAO IS NULL AND
	 	                  S.EMP_DEP_CODIGO_LOTACAO = DEP_CODIGO
	 	            CONNECT BY PRIOR DEP_CODIGO = DEP_DEP_CODIGO
	 	            START WITH DEP_CODIGO = IDEP_DEP_CODIGO
                           ) 
           ORDER BY S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NOME_ABREVIADO;     

     ELSIF IDEP_DEP_CODIGO IS NOT NULL AND IDEP_CODIGO IS NOT NULL AND IUOR_CODIGO IS NULL THEN
        OPEN TAB FOR
           SELECT S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NUMERO_MATRICULA, S.EMP_NOME_ABREVIADO,
	          S.CAR_NOME, S.OCC_DESCRICAO, S.EMP_DEP_CODIGO_LOTACAO, S.DEP_DEP_CODIGO,
		  S.EMP_QLP_CAR_CODIGO, S.EMP_QLP_CAR_OCC_CODIGO,
                  (
                    SELECT COUNT(AEM_ATI_CODIGO) 
                    FROM ATIVIDADES_EMPREGADOS
                    WHERE AEM_EMP_NUMERO_MATRICULA = S.EMP_NUMERO_MATRICULA AND
                          AEM_DATA_CONFIRMA_NAO_INERENTE IS NOT NULL AND
			  AEM_IND_ATI_INERENTE = 'N'
                  ) AS TOTAL
           FROM EMPREGADOS_SUBORDINADOS S
           WHERE EXISTS
		(SELECT DISTINCT (A.AEM_EMP_NUMERO_MATRICULA)
		FROM ATIVIDADES_EMPREGADOS A
		WHERE  A.AEM_IND_ATI_INERENTE = 'N' AND
		       A.AEM_DATA_CONFIRMA_NAO_INERENTE IS NULL AND
		       S.EMP_NUMERO_MATRICULA = A.AEM_EMP_NUMERO_MATRICULA) AND
                S.EMP_DEP_CODIGO_LOTACAO = IDEP_CODIGO AND
		((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
		 (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO))
           ORDER BY S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NOME_ABREVIADO;     

     ELSIF IDEP_DEP_CODIGO IS NOT NULL AND (IDEP_CODIGO IS NOT NULL OR IDEP_CODIGO IS NULL) AND IUOR_CODIGO IS NOT NULL THEN
        OPEN TAB FOR
           SELECT S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NUMERO_MATRICULA, S.EMP_NOME_ABREVIADO,
	          S.CAR_NOME, S.OCC_DESCRICAO, S.EMP_DEP_CODIGO_LOTACAO, S.DEP_DEP_CODIGO,
		  S.EMP_QLP_CAR_CODIGO, S.EMP_QLP_CAR_OCC_CODIGO,
                  (
                    SELECT COUNT(AEM_ATI_CODIGO) 
                    FROM ATIVIDADES_EMPREGADOS
                    WHERE AEM_EMP_NUMERO_MATRICULA = S.EMP_NUMERO_MATRICULA AND
                          AEM_DATA_CONFIRMA_NAO_INERENTE IS NOT NULL AND
			  AEM_IND_ATI_INERENTE = 'N'
                  ) AS TOTAL
           FROM EMPREGADOS_SUBORDINADOS S
           WHERE EXISTS
		(SELECT DISTINCT (A.AEM_EMP_NUMERO_MATRICULA)
		FROM ATIVIDADES_EMPREGADOS A
		WHERE  A.AEM_IND_ATI_INERENTE = 'N' AND
		       A.AEM_DATA_CONFIRMA_NAO_INERENTE IS NULL AND
		       S.EMP_NUMERO_MATRICULA = A.AEM_EMP_NUMERO_MATRICULA) AND
		       ((S.EMP_UOR_CODIGO_LOTACAO = S.EMP_UOR_CODIGO_FISICO)AND
		         (S.EMP_DEP_CODIGO_LOTACAO = S.EMP_DEP_CODIGO_FISICO)) AND
                       EXISTS
                           (SELECT UOR_CODIGO FROM UNIDADES_ORGANIZACIONAIS
	 	  	    WHERE UOR_DATA_EXTINCAO IS NULL AND
			          (UOR_CODIGO = IUOR_CODIGO OR UOR_UOR_CODIGO = IUOR_CODIGO) AND
	 	  	          S.EMP_UOR_CODIGO_LOTACAO = UOR_CODIGO
	 	  	    /*CONNECT BY PRIOR UOR_CODIGO = UOR_UOR_CODIGO
	 	  	    START WITH UOR_CODIGO = IUOR_CODIGO*/
                           ) 
           ORDER BY S.DEP_SIGLA, S.UOR_SIGLA, S.EMP_NOME_ABREVIADO;      
     END IF;
   END;
END;
/
SHOW ERROR