spo roles_sgp.log

PROMPT 'CONECTAR SYSMAN'

CONN SYSMAN@HOMOLOG

CREATE ROLE SGP_GERENTE;
CREATE ROLE SGP_DEMA;
CREATE ROLE SGP_ENGenharia;
CREATE ROLE SGP_MANUTENCAO;
CREATE ROLE SGP_GESTORH;

PROMPT 'CONECTAR IFRDBA2'

CONN IFRDBA2@HOMOLOG

PROMPT 'GRANTS PARA ROLE SGP_GESTORH'

GRANT SELECT ON DEPENDENCIAS TO SGP_GESTORH;

PROMPT 'CONECTAR IFRSGP'

CONN IFRSGP@HOMOLOG

PROMPT 'GRANTS PARA ROLE SGP_GERENTE'

GRANT SELECT, INSERT, UPDATE, DELETE ON T_FORNECEDORES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_MATERIAIS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_REGIOES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ESTRUTURAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_TIPOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SERVICOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_INDS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CONCEITOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PRESSAO_PNEUS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_RESISTENCIAS  TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CLIMA_DEPENDENCIA TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_MATERIAIS_DE_AEROPORTOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SERVICOS_DE_AEROPORTOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PISTAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ATRITOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SECOES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CAMADAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CONDICOES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HISTORICOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CUSTOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_MODELOS_PCI TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_POLITICAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PESOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ANALISE TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ENTRADAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SAIDAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_RES_CONDICOES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ORCAMENTOS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_AVALIADORES TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_UAS TO SGP_GERENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_INSPECOES TO SGP_GERENTE;

PROMPT 'GRANTS PARA ROLE SGP_DEMA'

GRANT SELECT, INSERT, UPDATE, DELETE ON T_FORNECEDORES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_MATERIAIS TO SGP_DEMA;
GRANT SELECT ON T_REGIOES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ESTRUTURAS TO SGP_DEMA;
GRANT SELECT ON T_TIPOS TO SGP_DEMA;
GRANT SELECT ON T_SERVICOS TO SGP_DEMA;
GRANT SELECT ON T_INDS TO SGP_DEMA;
GRANT SELECT ON T_CONCEITOS TO SGP_DEMA;
GRANT SELECT ON T_PRESSAO_PNEUS TO SGP_DEMA;
GRANT SELECT ON T_RESISTENCIAS  TO SGP_DEMA;
GRANT SELECT ON T_CLIMA_DEPENDENCIA TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_MATERIAIS_DE_AEROPORTOS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SERVICOS_DE_AEROPORTOS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PISTAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ATRITOS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SECOES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CAMADAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_CONDICOES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_HISTORICOS TO SGP_DEMA;
GRANT SELECT ON T_CUSTOS TO SGP_DEMA;
GRANT SELECT ON T_MODELOS_PCI TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE ON T_POLITICAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE ON T_PESOS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ANALISE TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ENTRADAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SAIDAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_RES_CONDICOES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ORCAMENTOS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_AVALIADORES TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_UAS TO SGP_DEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_INSPECOES TO SGP_DEMA;


PROMPT 'GRANTS PARA ROLE SGP_ENGENHARIA'

GRANT SELECT ON T_FORNECEDORES TO SGP_ENGENHARIA;
GRANT SELECT ON T_MATERIAIS TO SGP_ENGENHARIA;
GRANT SELECT ON T_REGIOES TO SGP_ENGENHARIA;
GRANT SELECT ON T_ESTRUTURAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_TIPOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_SERVICOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_INDS TO SGP_ENGENHARIA;
GRANT SELECT ON T_CONCEITOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_PRESSAO_PNEUS TO SGP_ENGENHARIA;
GRANT SELECT ON T_RESISTENCIAS  TO SGP_ENGENHARIA;
GRANT SELECT ON T_CLIMA_DEPENDENCIA TO SGP_ENGENHARIA;
GRANT SELECT ON T_MATERIAIS_DE_AEROPORTOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_SERVICOS_DE_AEROPORTOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_PISTAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_ATRITOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_SECOES TO SGP_ENGENHARIA;
GRANT SELECT ON T_CAMADAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_CONDICOES TO SGP_ENGENHARIA;
GRANT SELECT ON T_HISTORICOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_CUSTOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_MODELOS_PCI TO SGP_ENGENHARIA;
GRANT SELECT ON T_POLITICAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_PESOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_ANALISE TO SGP_ENGENHARIA;
GRANT SELECT ON T_ENTRADAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_SAIDAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_RES_CONDICOES TO SGP_ENGENHARIA;
GRANT SELECT ON T_ORCAMENTOS TO SGP_ENGENHARIA;
GRANT SELECT ON T_AVALIADORES TO SGP_ENGENHARIA;
GRANT SELECT ON T_UAS TO SGP_ENGENHARIA;
GRANT SELECT ON T_INSPECOES TO SGP_ENGENHARIA;

PROMPT 'GRANTS PARA ROLE SGP_MANUTENCAO'

GRANT SELECT ON T_FORNECEDORES TO SGP_MANUTENCAO;
GRANT SELECT ON T_MATERIAIS TO SGP_MANUTENCAO;
GRANT SELECT ON T_REGIOES TO SGP_MANUTENCAO;
GRANT SELECT ON T_ESTRUTURAS TO SGP_MANUTENCAO;
GRANT SELECT ON T_TIPOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_SERVICOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_INDS TO SGP_MANUTENCAO;
GRANT SELECT ON T_CONCEITOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_PRESSAO_PNEUS TO SGP_MANUTENCAO;
GRANT SELECT ON T_RESISTENCIAS  TO SGP_MANUTENCAO;
GRANT SELECT ON T_CLIMA_DEPENDENCIA TO SGP_MANUTENCAO;
GRANT SELECT ON T_MATERIAIS_DE_AEROPORTOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_SERVICOS_DE_AEROPORTOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_PISTAS TO SGP_MANUTENCAO;
GRANT SELECT ON T_ATRITOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_SECOES TO SGP_MANUTENCAO;
GRANT SELECT ON T_CAMADAS TO SGP_MANUTENCAO;
GRANT SELECT ON T_CONDICOES TO SGP_MANUTENCAO;
GRANT SELECT ON T_HISTORICOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_CUSTOS TO SGP_MANUTENCAO;
GRANT SELECT ON T_MODELOS_PCI TO SGP_MANUTENCAO;
GRANT SELECT ON T_POLITICAS TO SGP_MANUTENCAO;
GRANT SELECT ON T_PESOS TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ANALISE TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ENTRADAS TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_SAIDAS TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_RES_CONDICOES TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ORCAMENTOS TO SGP_MANUTENCAO;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_AVALIADORES TO SGP_MANUTENCAO;
GRANT SELECT ON T_UAS TO SGP_MANUTENCAO;
GRANT SELECT ON T_INSPECOES TO SGP_MANUTENCAO;

PROMPT 'CONECTAR SYSMAN'

CONN SYSMAN@HOMOLOG

GRANT SGP_GESTORH TO SGP_GERENTE;
GRANT SGP_GESTORH TO SGP_DEMA;
GRANT SGP_GESTORH TO SGP_ENGENHARIA;
GRANT SGP_GESTORH TO SGP_MANUTENCAO;

spo off
