CREATE TABLE INTEGRACAO.TAB_MODALIDADE_CONTR_U
  (
  CODIGO_MOD_CONTRATACAO CHAR (4) NOT NULL,
  DESCP CHAR (40) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  USER_ID_CREATED CHAR (30) NOT NULL,
  DATE_CHANGED DATE NOT NULL,
  USER_ID_CHANGED CHAR (30) NOT NULL,
  INACTIVE_ID CHAR (1) NOT NULL,
  ACTIVE_DATE DATE NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL,
  FLG_INCISO CHAR (1)
 )
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.CODIGO_MOD_CONTRATACAO IS 'SIGLA DA MODALIDADE'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.DESCP IS 'DESCRICAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.DATE_CREATED IS 'DATA DE CRIACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.USER_ID_CREATED IS 'USUARIO CRIADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.DATE_CHANGED IS 'DATA DE ALTERACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.USER_ID_CHANGED IS 'USUARIO ALTERADOR DO SMARTSTREAM'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.INACTIVE_ID IS 'FLAG DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.ACTIVE_DATE IS 'DATA DE ATIVACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.CHGSTAMP IS 'CONTROLE DE QTDE DE ALTERACOES DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_MODALIDADE_CONTR_U.FLG_INCISO IS 'FLAG DE INCISO OBRIGATORIO'
/
