CREATE TABLE INTEGRACAO.TAB_RED_ACRES_U
  (
  CODIGO_RED_ACRES CHAR (4) NOT NULL,
  DESCP CHAR (40) NOT NULL,
  IND_RED_ACRESC CHAR (1) NOT NULL,
  TIPO_RED_ACRES CHAR (1) NOT NULL,
  PER_RED_ACRES_DEFAULT FLOAT NOT NULL,
  PER_TIPO CHAR (1) NOT NULL,
  PER_TIPO_EDICAO CHAR (1) NOT NULL,
  IND_RESULTADO CHAR (1) NOT NULL,
  CODIGO_RED_ACRES_CONTRA CHAR (4) NOT NULL,
  LDR_ENTITY_ID CHAR (5) NOT NULL,
  DEPENDENCIA CHAR (3) NOT NULL,
  CONTA CHAR (9) NOT NULL,
  PROGRAMA CHAR (2) NOT NULL,
  PROJETO CHAR (4) NOT NULL,
  CUSTO CHAR (6) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  USER_ID_CREATED CHAR (30) NOT NULL,
  DATE_CHANGED DATE NOT NULL,
  USER_ID_CHANGED CHAR (30) NOT NULL,
  INACTIVE_IND CHAR (1) NOT NULL,
  ACTIVE_DATE DATE NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.CODIGO_RED_ACRES IS 'CODIGO DA REDUCAO/ACRESCIMO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.DESCP IS 'DESCRICAO DA REDUCAO/ACRESCIMO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.IND_RED_ACRESC IS 'REDUCAO (R) OU ACRESCIMO (A)'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.TIPO_RED_ACRES IS 'TIPO REDUCAO OU ACRESCIMO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.PER_RED_ACRES_DEFAULT IS 'PERCENTUAL DEFAULT'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.PER_TIPO IS 'TIPO VALOR REFERENCIA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.PER_TIPO_EDICAO IS 'FLAG PERMITE EDICAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.IND_RESULTADO IS 'AFETA RESULTADO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.CODIGO_RED_ACRES_CONTRA IS 'CODIGO RED/ACRES ASSOCIADO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.LDR_ENTITY_ID IS 'ENTIDADE'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.DEPENDENCIA IS 'DEPENDENCIA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.CONTA IS 'CONTA CONTABIL'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.PROGRAMA IS 'PROGRAMA'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.PROJETO IS 'PROJETO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.CUSTO IS 'CENTRO DE CUSTO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.DATE_CREATED IS 'DATA DE CRIACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.USER_ID_CREATED IS 'USUARIO CRIADOR'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.DATE_CHANGED IS 'DATA DE ALTERACAO DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.USER_ID_CHANGED IS 'USUARIO ALTERADOR'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.INACTIVE_IND IS 'INDICE DE INATIVACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.ACTIVE_DATE IS 'DATA DE ATIVACAO'
/
COMMENT ON COLUMN INTEGRACAO.TAB_RED_ACRES_U.CHGSTAMP IS 'CONTROLE DE ALTERACOES'
/
