CREATE TABLE INTEGRACAO.USER_MASTER_1
  (
  USER_ID CHAR (30) NOT NULL,
  LAST_NAME CHAR (20) NOT NULL,
  FIRST_NAME CHAR (20) NOT NULL,
  SEC_GROUP_UD CHAR (30) NOT NULL,
  NOTES VARCHAR2 (255) NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.USER_ID IS 'LOGON DO USUARIO'
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.LAST_NAME IS 'ULTIMO NOME'
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.FIRST_NAME IS 'PRIMEIRO NOME'
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.SEC_GROUP_UD IS 'GRUPO DE SEGURANCA'
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.NOTES IS 'OBSERVACOES'
/
COMMENT ON COLUMN INTEGRACAO.USER_MASTER_1.CHGSTAMP IS 'CONTROLE DE QTE DE ALTERACOES DO REGISTRO'
/
