CREATE TABLE INTEGRACAO.VENDOR_LOC_ADDR
  (
  VENDOR_ID CHAR (10) NOT NULL,
  VENDOR_LOC_CODE CHAR (3) NOT NULL,
  ADDR_TYPE CHAR (1) NOT NULL,
  ADDR_LINE_1 CHAR (35) NOT NULL,
  STREET_OR_POST_OFFICE_BOX_1 CHAR (35) NOT NULL,
  STREET_OR_POST_OFFICE_BOX_2 CHAR (35) NOT NULL,
  CITY_NAME CHAR (35) NOT NULL,
  COUNTRY_SUB_ENTITY_CODE CHAR (9) NOT NULL,
  POSTAL_CODE CHAR (9) NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL,
  PHONE_FORMAT_CODE CHAR (6) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.VENDOR_ID IS 'ID DO FORNECEDOR'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.VENDOR_LOC_CODE IS 'LOCALIZACAO DO FORNECEDOR'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.ADDR_TYPE IS 'TIPO DE ENDERECO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.ADDR_LINE_1 IS 'ENDERECO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.STREET_OR_POST_OFFICE_BOX_1 IS 'COMPLEMENTO DE QTDE DE ALTERACOES DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.STREET_OR_POST_OFFICE_BOX_2 IS 'BAIRRO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.CITY_NAME IS 'CIDADE'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.COUNTRY_SUB_ENTITY_CODE IS 'PAIS'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.POSTAL_CODE IS 'CEP'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.CHGSTAMP IS 'CONTROLE DE QTDE DE ALTERACOES DO REGISTRO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_ADDR.PHONE_FORMAT_CODE IS 'TELEFONE'
/
