CREATE TABLE INTEGRACAO.VENDOR_LOC_BANK_ACCT_U
  (
  VENDOR_ID CHAR (10) NOT NULL,
  VENDOR_LOC_CODE CHAR (3) NOT NULL,
  TYPE_OF_PMT CHAR (4) NOT NULL,
  SEQ_NBR CHAR (3) NOT NULL,
  DEFAULT_FLAG CHAR (1) NOT NULL,
  BANK_ACCT_NBR CHAR (17) NOT NULL,
  BANK_NAME CHAR (70) NOT NULL,
  BANK_NBR CHAR (17) NOT NULL,
  BRANCH_NAME CHAR (70) NOT NULL,
  ADDR_LINE CHAR (35) NOT NULL,
  STREET_OR_POST_OFFICE_BOX_1 CHAR (35) NOT NULL,
  STREET_OR_POST_OFFICE_BOX_2 CHAR (35) NOT NULL,
  CITY_NAME CHAR (35) NOT NULL,
  COUNTRY_SUB_ENTITY_CODE CHAR (9) NOT NULL,
  POSTAL_CODE CHAR (9) NOT NULL,
  NAME_ON_ACCT CHAR (45) NOT NULL,
  BANK_ACCT_TYPE_CODE CHAR (1) NOT NULL,
  PMT_CHANNEL_CODE CHAR (3) NOT NULL,
  CHGSTAMP NUMBER (2) NOT NULL
 )
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.VENDOR_ID IS 'ID DO FORNECEDOR'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.VENDOR_LOC_CODE IS 'LOCALIZACAO DO FORNECEDOR'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.TYPE_OF_PMT IS 'TIPO DO PAGAMENTO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.SEQ_NBR IS 'SEQUENCIA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.DEFAULT_FLAG IS 'FLAG DE CONTA ATIVA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.BANK_ACCT_NBR IS 'NUMERO DA CONTA BANCARIA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.BANK_NAME IS 'NOME DO BANCO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.BANK_NBR IS 'NUMERO DO BANCO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.BRANCH_NAME IS 'CODIGO DA AGENCIA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.ADDR_LINE IS 'CONTATO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.STREET_OR_POST_OFFICE_BOX_1 IS 'ENDERECO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.STREET_OR_POST_OFFICE_BOX_2 IS 'COMPLEMENTO ENDERECO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.CITY_NAME IS 'CIDADE'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.COUNTRY_SUB_ENTITY_CODE IS 'UF'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.POSTAL_CODE IS 'CEP'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.NAME_ON_ACCT IS 'DESCRICAO DA CONTA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.BANK_ACCT_TYPE_CODE IS 'TIPO DA CONTA BANCARIA'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.PMT_CHANNEL_CODE IS 'METODO DE PAGAMENTO'
/
COMMENT ON COLUMN INTEGRACAO.VENDOR_LOC_BANK_ACCT_U.CHGSTAMP IS 'CONTROLE DE QTDE DE ALTERACOES DO REGISTRO'
/
