/* Formatted on 2004/01/22 07:45 (Formatter Plus v4.7.0) */
CREATE OR REPLACE FORCE VIEW viw_dependencias (dep_codigo,
                                                          dep_tel_secretaria,
                                                          dep_nome_secretaria,
                                                          dep_tel_superintendente,
                                                          dep_grupos_dependencia,
                                                          dep_dependencia,
                                                          dep_nome_superintendente,
                                                          dep_feriados_locais,
                                                          dep_tipo,
                                                          dep_tipo_codigo,
                                                          dep_nome,
                                                          dep_sigla,
                                                          dep_endereco_logradouro,
                                                          dep_endereco_bairro,
                                                          dep_municipio,
                                                          dep_ufe_sigla,
                                                          dep_endereco_cep,
                                                          dep_numero_telefone_1,
                                                          dep_numero_telefone_2,
                                                          dep_numero_fax,
                                                          dep_numero_cgc,
                                                          dep_dep_codigo,
                                                          dep_data_criacao,
                                                          dep_data_extincao,
                                                          dep_grupos_dependencias,
                                                          dep_comar,
                                                          dep_denominacao_completa,
                                                          dep_ie,
                                                          dep_horario_administrativo,
                                                          dep_fuso_horario_bsb,
                                                          dep_dt_absorcao_infraero,
                                                          dep_tel_achados_perdidos,
                                                          dep_tel_balcao_informacao,
                                                          dep_tel_comunicacao_social,
                                                          dep_dep_sigla
                                                         )
AS
   (SELECT d.dep_codigo, '' AS dep_tel_secretaria, '' AS dep_nome_secretaria,
           '' AS dep_tel_superintendente, '' AS dep_grupos_dependencia,
           '' AS dep_dependencia, '' AS dep_nome_superintendente,
           '' AS dep_feriados_locais,
           DECODE (d.dep_tipo,
                   1, 'SEDE',
                   2, 'SUPERINTENDÊNCIA',
                   3, 'AEROPORTO',
--4,'GTA',
--5,'COORDENAÇÃO DE NEGÓCIO',
                   6, 'GNA',
                   7, 'UNA'
       --,
--8,'CONVÊNIOS COM RESSARCIMENTO',
--9,'CONVÊNIOS SEM RESSARCIMENTO',
--10,'DEPENDÊNCIA GNA',
--11,'DEPENDÊNCIA UNA',
--12,'DEPENDÊNCIA DE DEPENDÊNCIA',DEP_TIPO)
                  ) AS dep_tipo,
           d.dep_tipo AS dep_tipo_codigo, d.dep_nome, d.dep_sigla,
           d.dep_endereco_logradouro, d.dep_endereco_bairro,
           m.mun_descricao AS dep_municipio, d.dep_ufe_sigla,
           d.dep_endereco_cep, d.dep_numero_telefone_1,
           d.dep_numero_telefone_2, d.dep_numero_fax, d.dep_numero_cgc,
           d.dep_dep_codigo,
           TO_CHAR (d.dep_data_criacao, 'DD/MM/YYYY') AS dep_data_criacao,
           TO_CHAR (d.dep_data_extincao, 'DD/MM/YYYY') AS dep_data_extincao,
           d.dep_grupos_dependencias, d.dep_comar, d.dep_denominacao_completa,
           '' AS dep_ie, '' AS dep_horario_administrativo,
           '' AS dep_fuso_horario_bsb,
           TO_CHAR ('') AS dep_dt_absorcao_infraero,
           '' AS dep_tel_achados_perdidos, '' AS dep_tel_balcao_informacao,
           '' AS dep_tel_comunicacao_social,
           DECODE (d2.dep_sigla, 'SEDE', '', d2.dep_sigla) AS dep_dep_sigla
      FROM dependencias d, dependencias d2, municipios m
     WHERE d.dep_tipo IN (1, 2, 3, 6, 7)
       AND m.mun_codigo(+) = d.dep_mun_codigo
       AND m.mun_ufe_sigla(+) = d.dep_ufe_sigla
       AND d2.dep_codigo(+) = d.dep_dep_codigo
       AND d.dep_data_extincao IS NULL);

