-- Start of DDL Script for View IFRTECA.TKP_MOV_FINANCEIRO
-- Generated 11-fev-2004 16:56:21 from IFRTECA@SEBN07.WORLD

CREATE OR REPLACE VIEW TKP_MOV_FINANCEIRO (
   id_tempo,
   id_modulo,
   tipo_cob,
   cod_tab,
   cod_enq,
   aer_cod,
   timestamp,
   idt_alteracao,
   qtd_doc,
   tarifa,
   ataero,
   retencao,
   valor_carga )
AS
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPTBL_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPRJ_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPRF_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPMN_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPBR_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPPA_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPSP_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPKP_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPFI_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPCT_MOV_FINANCEIRO
UNION ALL
SELECT ID_TEMPO, ID_MODULO, TIPO_COB, COD_TAB, COD_ENQ, AER_COD, TIMESTAMP, IDT_ALTERACAO, QTD_DOC, TARIFA, ATAERO,
RETENCAO, VALOR_CARGA
FROM IFRTECA.TKPSANPBE_MOV_FINANCEIRO
/

-- Grants for View
GRANT SELECT ON tkp_mov_financeiro TO role_dclc
/

-- End of DDL Script for View IFRTECA.TKP_MOV_FINANCEIRO

