-- Start of DDL Script for View IFRHUMANUS.VIW_REL_HOR_INSTUTOR
-- Generated 29/08/2006 08:30 from IFRHUMANUS@PRODSEDE

CREATE OR REPLACE VIEW VIW_REL_HOR_INSTUTOR 
AS
SELECT
    TRN_PESSOA.PESNOMEEXTENSO || TRN_CADASTROS.EMP_NOME AS NOME,
    TRN_CURSO_DEP_ANO.CDA_DEP_CODIGO, 
    TRN_INSTRUTOR.ITR_PESCODPESSOA,  
    TRN_INSTRUTOR.ITR_EMP_NUMERO_MATRICULA, 
    TRN_EVENTO_INSTRUTOR.IEVVALORHORAAULA, 
    TRN_EVENTO_INSTRUTOR.IEVQTDHORASAULAS,
    TRN_EVENTO_INSTRUTOR.IEVINSTRUTORIAVALOR, 
    TRN_CURSO_DEP_ANO.CDA_CRS_SEQ ||'.'|| TRN_EVENTO.EVE_SEQ as GrdID,  
    TRN_EVENTO.EVE_DAT_INICIO AS DTMX, 
    TRN_INSTRUTOR.ITR_SEQ
FROM
    IFRHUMANUS.TRN_CURSO_DEP_ANO TRN_CURSO_DEP_ANO,
    IFRHUMANUS.TRN_EVENTO TRN_EVENTO,
    IFRHUMANUS.TRN_EVENTO_INSTRUTOR TRN_EVENTO_INSTRUTOR,
    IFRHUMANUS.TRN_INSTRUTOR  TRN_INSTRUTOR,
    IFRHUMANUS.TRN_PESSOA TRN_PESSOA,
    IFRHUMANUS.TRN_CADASTROS TRN_CADASTROS
WHERE
    TRN_CURSO_DEP_ANO.cda_dep_codigo LIKE '%'
AND TRN_CURSO_DEP_ANO.CDA_SEQ = TRN_EVENTO.EVE_CDA_SEQ 
AND TRN_EVENTO.EVE_DAT_INICIO >= TO_DATE(TRN_EVENTO.EVE_DAT_INICIO) 
AND TRN_EVENTO.EVE_DAT_INICIO <= TO_DATE(TRN_EVENTO.EVE_DAT_INICIO) 
AND TRN_EVENTO.EVE_SEQ = TRN_EVENTO_INSTRUTOR.IEV_EVE_SEQ 
AND TRN_EVENTO_INSTRUTOR.IEV_ITR_SEQ = TRN_INSTRUTOR.ITR_SEQ 
AND TRN_INSTRUTOR.ITR_PESCODPESSOA = TRN_PESSOA.PESCODPESSOA (+)
AND TRN_INSTRUTOR.ITR_PES_TPP_SEQ = TRN_PESSOA.PES_TPP_SEQ (+)
AND TRN_INSTRUTOR.ITR_EMP_NUMERO_MATRICULA = TRN_CADASTROS.EMP_NUMERO_MATRICULA(+) 
ORDER BY NOME 
/

-- Grants for View
GRANT SELECT ON VIW_REL_HOR_INSTUTOR TO srh_trn_01
/
GRANT SELECT ON VIW_REL_HOR_INSTUTOR TO srh_trn_02
/
GRANT SELECT ON VIW_REL_HOR_INSTUTOR TO srh_trn_03
/

-- End of DDL Script for View IFRHUMANUS.VIW_REL_HOR_INSTUTOR
