--CREATE UNIQUE INDEX "MEDICAO_PK" ON "MEDICAO" ("ID_ESTACAO" , "CD_ATRIBUTO" , "NO_PISTA" 
--, "DT_MEDICAO" , "HR_MEDICAO" , "VL_ALTITUDE" )  
--TABLESPACE "TSI_BDCLIM" LOGGING
--/

spo _indices_ifrclim.log

ALTER TABLE "MEDICAO" ADD  CONSTRAINT "MEDICAO_PK" PRIMARY KEY ("ID_ESTACAO", 
"CD_ATRIBUTO", "NO_PISTA", "DT_MEDICAO", "HR_MEDICAO", "VL_ALTITUDE") 
USING INDEX TABLESPACE "TSI_BDCLIM" ENABLE
/

CREATE INDEX "MEDICAONX4" ON "MEDICAO" ("ID_ESTACAO" , "CD_ATRIBUTO" , "DT_MEDICAO" )
TABLESPACE "TSI_BDCLIM" LOGGING
/

CREATE INDEX "MEDICAONX2" ON "MEDICAO" ("DT_MEDICAO" , "CD_ATRIBUTO" , "ID_ESTACAO" )  
TABLESPACE "TSI_BDCLIM" LOGGING
/

CREATE INDEX "MEDICAONX6" ON "MEDICAO" ("CD_ATRIBUTO" , "DT_MEDICAO" , "HR_MEDICAO" )
TABLESPACE "TSI_BDCLIM" LOGGING
/

spo off

