select 'revoke '||privilege||' on '||owner||'.'||table_name||' from '||grantee||';'
from dba_tab_privs
where table_name in ('SEG_USUARIO','CONTROLE_USUARIO_DEPENDENCIA',
                     'SEG_USUARIO_SISTEMA','SEG_GRUPO_USUARIO',
                     'SEG_USUARIO_CENTRO_CUSTO','SEG_SISTEMA')    AND
PRIVILEGE NOT IN ('SELECT','REFERENCES') AND
GRANTEE<>'SEG_GERAL'
ORDER BY OWNER;

revoke DELETE on IFRDBA2.SEG_USUARIO from SEG_CAD_USR;
revoke INSERT on IFRDBA2.SEG_USUARIO from SEG_CAD_USR;
revoke UPDATE on IFRDBA2.SEG_USUARIO from SEG_CAD_USR;
revoke DELETE on IFRDBA2.SEG_USUARIO_SISTEMA from SEG_CAD_USR;
revoke INSERT on IFRDBA2.SEG_USUARIO_SISTEMA from SEG_CAD_USR;
revoke UPDATE on IFRDBA2.SEG_USUARIO_SISTEMA from SEG_CAD_USR;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from IFRDBA2;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from RH_PERFIL_99;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from RH_PERFIL_99;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from RH_PERFIL_99;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_18;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_18;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_18;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_17;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_17;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_17;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_BEN_01;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_BEN_01;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_BEN_01;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_02;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_02;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_02;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_04;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_04;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_04;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_06;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_06;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_06;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_07;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_07;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_07;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_08;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_08;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_08;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_09;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_09;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_09;
revoke DELETE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_99;
revoke INSERT on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_99;
revoke UPDATE on IFRSRH.CONTROLE_USUARIO_DEPENDENCIA from SRH_CAD_99;
