set heading off
SET FEEDBACK OFF
set verify off

SPOOL C:\Sistemas\Sql\Infraero\Oracle\Scripts\script_ronei\OBJETOS_NAO_CADASTRADOS.LOG

SELECT 'TABELA '||A.OWNER||'.'||A.TABLE_NAME
FROM DBA_TABLES A
WHERE 	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.TABLE_NAME NOT IN (SELECT B.OWNER||B.TABELA
				    FROM TABELAS B
				    WHERE B.OWNER=A.OWNER AND
					  B.TABELA=A.TABLE_NAME AND
 					  B.TIPO='TABELA')
ORDER BY A.OWNER,A.TABLE_NAME;

SELECT 'VIEW '||A.OWNER||'.'||A.VIEW_NAME
FROM DBA_VIEWS A
WHERE 	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.VIEW_NAME NOT IN (SELECT B.OWNER||B.TABELA
				    FROM TABELAS B
				    WHERE B.OWNER=A.OWNER AND
					  B.TABELA=A.VIEW_NAME AND
 					  B.TIPO='VIEW')
ORDER BY A.OWNER,A.VIEW_NAME;

SELECT 'SEQUENCE '||A.SEQUENCE_OWNER||'.'||A.SEQUENCE_NAME
FROM DBA_SEQUENCES A
WHERE 	A.SEQUENCE_OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.SEQUENCE_OWNER||A.SEQUENCE_NAME NOT IN (SELECT B.OWNER||B.TABELA
				    FROM TABELAS B
				    WHERE B.OWNER=A.SEQUENCE_OWNER AND
					  B.TABELA=A.SEQUENCE_NAME AND
 					  B.TIPO='SEQUENCE')
ORDER BY A.SEQUENCE_OWNER,A.SEQUENCE_NAME;

SELECT 'FUNCTION '||A.OWNER||'.'||A.NAME
FROM DBA_SOURCE A
WHERE 	A.TYPE = 'FUNCTION' AND
	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.NAME NOT IN (SELECT B.OWNER||B.TABELA
				FROM TABELAS B
				WHERE B.OWNER=A.OWNER AND
				      B.TABELA=A.NAME AND
 				      B.TIPO='FUNCTION')
GROUP BY A.OWNER,A.NAME
ORDER BY A.OWNER,A.NAME;

SELECT 'PROCEDURE '||A.OWNER||'.'||A.NAME
FROM DBA_SOURCE A
WHERE 	A.TYPE = 'PROCEDURE' AND
	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.NAME NOT IN (SELECT B.OWNER||B.TABELA
				FROM TABELAS B
				WHERE B.OWNER=A.OWNER AND
				      B.TABELA=A.NAME AND
 				      B.TIPO='PROCEDURE')
GROUP BY A.OWNER,A.NAME
ORDER BY A.OWNER,A.NAME;

SELECT 'PACKAGE '||A.OWNER||'.'||A.NAME
FROM DBA_SOURCE A
WHERE 	A.TYPE = 'PACKAGE' AND
	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.NAME NOT IN (SELECT B.OWNER||B.TABELA
				FROM TABELAS B
				WHERE B.OWNER=A.OWNER AND
				      B.TABELA=A.NAME AND
 				      B.TIPO='PACKAGE')
GROUP BY A.OWNER,A.NAME
ORDER BY A.OWNER,A.NAME;

SELECT 'PACKAGE BODY '||A.OWNER||'.'||A.NAME
FROM DBA_SOURCE A
WHERE 	A.TYPE = 'PACKAGE BODY' AND
	A.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','DONOREP','DISCOVERER') AND
	A.OWNER||A.NAME NOT IN (SELECT B.OWNER||B.TABELA
				FROM TABELAS B
				WHERE B.OWNER=A.OWNER AND
				      B.TABELA=A.NAME AND
 				      B.TIPO='PACKAGE BODY')
GROUP BY A.OWNER,A.NAME
ORDER BY A.OWNER,A.NAME;

SPOOL OFF