USE [IEOP]
GO

/****** Object:  StoredProcedure [dbo].[PRC_CARGA_EMB_AEROPORTOS]    Script Date: 27/08/2013 09:11:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[PRC_CARGA_EMB_AEROPORTOS](@SIG_AEROPORTO varchar(4))
AS
declare @QUERY VARCHAR(2000);
BEGIN
	set @QUERY='';
	--TRUNCATE TABLE IEOP.dbo.IEOP_EMBARQUE_TEMP
	set @QUERY='UPDATE ['+@SIG_AEROPORTO+' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] 
	   SET FL_STATUS= 1 --TEMPORARIO
	 WHERE FL_STATUS IS NULL --NÃO MIGRADO';
	exec(@QUERY);

	set @QUERY='INSERT INTO IEOP.dbo.IEOP_EMBARQUE_TEMP
	SELECT  
			 LTRIM(RTRIM(SIGLA_AEROPORTO)) SIGLA_AEROPORTO 
			,LTRIM(RTRIM(NR_PAR_VOO)) NR_PAR_VOO
			,DH_PAR_NRM
			,DH_PAR_EFE
			,CD_COM
			,LTRIM(RTRIM(SG_COM_IAT_003)) SG_COM_IAT_003
			,LTRIM(RTRIM(NOME_CIA)) NOME_CIA
			,LTRIM(RTRIM(NR_AEN)) NR_AEN
			,TP_PAR_GRU
			,TP_PAR_NAT
			,TP_PAR
			,TP_PAR_CTG
			,TP_PAR_CTG_VIN
			,LTRIM(RTRIM(SG_EQP)) SG_EQP
			,LTRIM(RTRIM(NM_EQP)) NM_EQP
			,QT_DEP_TFB_DOM,QT_DEP_TFB_INT,QT_DEP_TFC_DOM
			,QT_DEP_TFC_INT,QT_DEP_ISE_COL,QT_DEP_ISE_TRA
			,QT_DEP_ISE_CON_DOM,QT_DEP_ISE_CON_INT,QT_DEP_ISE_OUT
			,QT_DEP_EMB_BAG_DOM,QT_DEP_EMB_BAG_INT,QT_DEP_EMB_CAR_DOM
			,QT_DEP_EMB_CAR_INT,QT_DEP_EMB_COR_DOM,QT_DEP_EMB_COR_INT
			,QT_DEP_TFB_DOM_ANT,QT_DEP_TFB_INT_ANT,QT_DEP_TFC_DOM_ANT,QT_DEP_TFC_INT_ANT
			,LTRIM(RTRIM(CD_CHG_AEN_ANT)) CD_CHG_AEN_ANT
			,LTRIM(RTRIM(CD_PAR_VIN)) CD_PAR_VIN
			,LTRIM(RTRIM(SIGLA_AEROPORTO_DES)) SIGLA_AEROPORTO_DES
			,LTRIM(RTRIM(NR_BOX)) NR_BOX
			,LTRIM(RTRIM(TP_BOX)) TP_BOX
			,LTRIM(RTRIM(NM_PON)) NM_PON
			,LTRIM(RTRIM(NR_POR)) NR_POR
			,LTRIM(RTRIM(PIS_PO)) PIS_PO
			,LTRIM(RTRIM(PIS_DE)) PIS_DE
			,CD_STA
			,CD_STA_ANT
			,CD_STA_POS
			,TP_STA
			,FL_STATUS
			,FL_AEN_TAX
			,FL_EQP_HLC
			,HR_MOV_PRI
			,HR_MOV_ULT
			,HR_MOV_ULT_SAI
			,ISNULL(CD_PAR,0) CD_PAR
			,DTH_ATUALIZACAO
			,0 QTD_ATUALIZACAO
			,1 FLG_MIGRADO
			,GETDATE() DTH_MIGRACAO			
		FROM ['+@SIG_AEROPORTO+' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] WITH (NOLOCK)
	   WHERE FL_STATUS = 1 --TEMPORARIO';
	exec(@QUERY);

	set @QUERY='UPDATE ['+@SIG_AEROPORTO+' - INTEGRACAO].[integracao].[dbo].[INTEGRACAO_SISO_BIOGER_EMB_NEW] 
	   SET FL_STATUS = 2 --MIGRADO
	 WHERE FL_STATUS = 1 --TEMPORARIO';
	exec(@QUERY);
END;
GO


