COL MEMBER FORMAT A50
COL DATAFILE FORMAT A50
COL FILE_NAME FORMAT A50
COL INSTANCE# FORMAT A10

SELECT TABLESPACE_NAME, FILE_NAME, STATUS
FROM DBA_DATA_FILES;
SELECT T.TS#, T.NAME TABLESPACE, D.FILE#, D.NAME DATAFILE, STATUS
FROM V$DATAFILE D, V$TABLESPACE T
WHERE T.TS# = D.TS#
/
SELECT * FROM V$BACKUP
/
SELECT GROUP#,THREAD#,SEQUENCE#,BYTES,MEMBERS,ARCHIVED,STATUS         
FROM V$LOG
/
SELECT *
FROM V$LOGFILE
/
SELECT SEGMENT_ID, SEGMENT_NAME, TABLESPACE_NAME, INSTANCE_NUM INSTANCE#, STATUS
FROM DBA_ROLLBACK_SEGS
ORDER BY INSTANCE#, SEGMENT_NAME
/
@err
@t
